
@MSG_CNF503B_001
<bup 0 8 5>
Dr. Kasal was able to contain
the vapor that escaped.
<wait>
Thank goodness it only infected one
other person...
<wait>
This operation will be another mutated
Triti, like before.
<wait>
No... It's too strong... This must be Triti's
true form...
<wait>
There aren't many doctors who could treat
something like this.
<wait>
<bup 0 8 3>
We have to stop it now, before it causes
any more damage.
<wait>

@MSG_CNF503B_START
<bup 0 2 10>
We can do this...
Just focus.
<vplay 1 5>
<wait>
<bup_cls>
