
@MSG_CNF103_001
<bup 0 10 1>
Yesterday's procedure went very smoothly.
<wait>
I want you to handle Mr. Spence's
operation today.
<wait>
It's another tumor excision.
<wait>
Just be careful. There's more than one
this time--make sure you don't miss any.
<wait>

@MSG_CNF103_002
<bup 0 11 1>
This is the last time I'll be assisting you,
Dr. Stiles.
<wait>
If you can handle this operation,
I'll feel much better about leaving.
<wait>

@MSG_CNF103_003
<bup 0 1 4>
.........
<wait>

@MSG_CNF103_004
<bup 0 11 1>
Oh... I didn't mean to upset you.
<wait>
<bup 0 11 3>
...but wake up, Dr. Stiles!
<wait>
The only person you should be thinking
about during an operation is the patient!
<wait>
Do you understand?
<wait>

@MSG_CNF103_005
<bup 0 1 5>
Y-Yes, ma'am!
<wait>

@MSG_CNF103_006
<bup 0 11 1>
Let's review the main objective
of today's operation:
<wait>
・ Excise and remove all tumors
from the patient's pancreas.
<wait>
Now, think back to yesterday's procedure,
and begin.
<wait>

@MSG_CNF103_START
<bup 0 1 10>
Here goes...
Let's begin the operation!
<vplay 1 8>
<wait>
<bup_cls>
