
@MSG_CNF106_001
<bup 0 7 5>
Since Dr. Kasal is at a conference,
I'll be briefing you today.
<wait>

@MSG_CNF106_002
<bup 0 1 4>
(...I think you'd be briefing me even if
he was here.)
<wait>

@MSG_CNF106_003
<bup 0 7 5>
We're extracting a stage 1 tumor from
the patient's small intestine.
<wait>

@MSG_CNF106_004
<bup 0 1 1>
So... If we take it out, he should fully
recover.
<wait>

@MSG_CNF106_005
<bup 0 7 5>
However, his blood test results were...unusual.
<wait>

@MSG_CNF106_006
<bup 0 1 1>
We can ask Dr. Kasal about that once
he gets back.
<wait>
As long as I extract the tumor, the patient
should be fine.
<wait>

@MSG_CNF106_007
<bup 0 7 5>
That's technically correct, but--
<wait>

@MSG_CNF106_008
<bup 0 1 1>
I'm pretty confident about this. I've extracted
tumors several times already.
<wait>
This'll be a snap.
<wait>

@MSG_CNF106_009
<bup 0 7 5>
...Okay. Keep the two operation
objectives in mind, then:
<wait>
・ Treat the inflamed epithelium in his small
intestine.
<wait>
・ Excise and remove all tumors in the area.
<wait>
If you're ready, let's begin.
<wait>

@MSG_CNF106_START
<bup 0 1 10>
Let's begin the operation!
<vplay 1 8>
<wait>
<bup_cls>
