
@MSG_CNF105_001
<bup 0 7 5>
We should start the briefing.
<wait>
Let's review today's patient,
Mr. Cox.
<wait>
He started feeling pain in his throat
about a month ago...
<wait>
He's been coughing up blood since then,
and now has trouble breathing.
<wait>
Since Mr. Cox is a rock singer, it's likely
that a polyp has developed due to strained
<wait>
bronchial tubes.
Obviously, it has started to hemorrhage.
<wait>
We attempted to treat it with a nebulizer,
but his condition is getting worse.
<wait>
It's nothing life threatening, but
considering the patient's career...
<wait>
it's serious enough to warrant
surgical intervention.
<wait>
It's still possible for him to fully recover.
<wait>
What's your opinion, Dr. Kasal?
<wait>

@MSG_CNF105_002
<bup 0 10 1>
That sounds like a good plan.
<wait>

@MSG_CNF105_003
<bup 0 7 5>
Are you ready, Dr. Stiles?
<wait>
This operation has three objectives:
<wait>
・ Drain the overflowing blood.
<wait>
・ Locate the source of the patient's distress.
・ Use the laser to remove it.
<wait>
This is a delicate operation, so we'll
need to use the magnification tool.
<wait>
Remember, this is the patient's livelihood,
so tread carefully.
<wait>

@MSG_CNF105_004
<bup 0 10 1>
...Nice work, Angie.
Derek, good luck.
<wait>

@MSG_CNF105_START
<bup 0 1 10>
...Okay.
Let's begin the operation!
<vplay 1 8>
<wait>
<bup_cls>
