
@MSG_CNF108_001
<bup 0 1 5>
What's the situation?
<wait>

@MSG_CNF108_002
<bup 0 7 4>
...The ambulance brought him here as soon
as they could...
<wait>
...his heart isn't beating...
I tried reviving him, but--
<wait>

@MSG_CNF108_003
<bup 0 1 5>
Angie!
<wait>

@MSG_CNF108_004
<bup 0 7 4>
What do I do...!?
I need help! I... I...
<wait>

@MSG_CNF108_005
<bup 0 1 3>
Angie!
<wait>

@MSG_CNF108_006
<bup 0 7 4>
...D-Dr. Stiles...
<wait>

@MSG_CNF108_007
<bup 0 1 3>
The only person here who needs
help is the patient.
<wait>
...And we're the ones who are going
to help him.
<wait>
It's up to us, and only us.
We're going to save him.
<wait>
I can't do this without you, Angie.
I want to save his life.
<wait>
Pretend this is a normal procedure.
Calm down; think things through.
<wait>

@MSG_CNF108_008
<bup 0 7 4>
...F-First we need a pulse...
We have to get a pulse.
<wait>

@MSG_CNF108_009
<bup 0 1 5>
Understood!
<wait>

@MSG_CNF108_START
<bup 0 1 10>
Let's begin the operation!
<vplay 1 6>
<wait>
<bup_cls>
