
@MSG_CNF102_001
<bup 0 10 1>
Today, we need to excise a tumor
in the patient's distal stomach.
<wait>
Two years ago, tests indicated that it
was small and benign.
<wait>
However, it's grown rapidly and started
to hemorrhage.
<wait>
At this rate, it might become malignant.
<wait>
After talking with Mr. Laurie, we've
decided to remove it.
<wait>
There is one objective in this operation:
<wait>
・ Excise and remove the tumor in
the patient's distal stomach.
<wait>
That is all.
<wait>
But, you'll need to remove the tumor using
the Powell Procedure.
<wait>
First, drain the tumor's cytoplasm
to decrease its size.
<wait>
Then, once you excise it, the cells can't
metastasize, resulting in a smaller incision.
<wait>
There seems to be a trend toward this
type of removal.
<wait>
It's a good idea for you to learn it.
<wait>
<bup 0 10 3>
Now, begin the operation!
Stay calm and keep it steady.
<wait>

@MSG_CNF102_START
<bup 0 1 10>
Understood!
Let's begin the operation!
<vplay 1 8>
<wait>
<bup_cls>
