
@MSG_CNF101_001
<bup 0 11 1>
Let's begin the briefing.
<wait>
Our patient, Kevin Turk, just arrived
in an ambulance.
<wait>
He lost control of his motorcycle and crashed
through a glass door.
<wait>
He received a number of lacerations, which
have begun to hemorrhage.
<wait>
There are glass fragments lodged here,
in his right forearm.
<wait>
Our cosmetic surgeon is out at a
Medical Society meeting...
<wait>
But, you should be able to handle the
stitching--it's fairly straightforward.
<wait>
There are two main objectives
in this operation:
<wait>
・ Suture any lacerations.
<wait>
・ Extract fragments of glass from underneath
the patient's skin.
<wait>
Be thorough, and try your best not
to leave any scars.
<wait>

@MSG_CNF101_START
<bup 0 1 10>
Okay...
Let's begin the operation!
<vplay 1 8>
<wait>
<bup_cls>
