
@MSG_CNF211_001
<bup 0 10 1>
Today, you will be operating on Elisa Chalke,
who's been in our pediatric ward.
<wait>

@MSG_CNF211_002
<bup 0 1 5>
She's a very young child with
valvular heart disease...
<wait>

@MSG_CNF211_003
<bup 0 10 1>
It was a tough decision, but her parents finally
decided to go ahead with the procedure.
<wait>
There's only one main objective
for this operation:
<wait>
・ Replace a valve in her heart with
a synthetic one.
<wait>
You'll use a triple incision to excise
the valve--cut three times.
<wait>
You'll need to be as cautious as possible,
understand?
<wait>
Technology has made a lot of situations
much easier for us...
<wait>
...but heart surgery will always rely
on a skillful doctor.
<wait>
Angie, keep an eye on the oscillograph
to aid Dr. Stiles.
<wait>

@MSG_CNF211_004
<bup 0 7 5>
I understand.
<wait>

@MSG_CNF211_005
<bup 0 10 1>
Don't let the gravity of this
operation intimidate you.
<wait>
The conference is over.
She's in your hands now, Derek.
<wait>

@MSG_CNF211_START
<bup 0 1 10>
Let's begin the operation!
<vplay 1 5>
<wait>
<bup_cls>
