
@MSG_CNF209_001
<bup 0 10 5>
Her blood pressure is decreasing
at a frightening rate...
<wait>
We suspect hemorrhaging in her
lungs again...
<wait>
There has to be some explanation for
why these lacerations are occuring.
<wait>
Until we figure out what that is,
there's not a lot we can do.
<wait>
You should have two objectives
during this operation:
<wait>
・ Treat any bleeding injuries within
the thoracic cavity.
<wait>
・ Discover the source of the lacerations.
<wait>
I'll be working as your assistant.
Stay calm, Derek.
<wait>

@MSG_CNF209_START
<bup 0 1 10>
No... She wants to live!
...I have to save her!
<vplay 1 6>
<wait>
<bup_cls>
