
@MSG_CNF204_001
<bup 0 10 5>
Today's patient is Mr. Kovac, who was
carried in this morning...
<wait>
He's currently not doing very well.
<wait>
Tests showed a number of aneurysms near
his large intestine.
<wait>
Some of them have ruptured, and there is
risk of anemia.
<wait>
We need to perform a laparotomy and get
those aneurysms under control.
<wait>
The objective of this operation is:
<wait>
・ Treat the aneurysms on the outer membrane
of the patient's large intestine.
<wait>
That should be all.
<wait>
First, inject a sedative into the swollen
vessel to reduce its size.
<wait>
Excise the problem area, and suture
the vessel closed.
<wait>
You'll need to use magnification again,
to ensure your accuracy.
<wait>
Derek, concentrate on the patient.
Don't worry about anything else.
<wait>

@MSG_CNF204_002
<bup 0 1 5>
...Okay!
<wait>

@MSG_CNF204_START
<bup 0 1 10>
Let's begin the operation!
<vplay 1 2>
<wait>
<bup_cls>
