
@MSG_CNF206_001
<bup 0 10 3>
The patient's a 17-year-old female.
Her case history is unknown.
<wait>
We've found massive bleeding in her
thoracic cavity.
<wait>
Derek, you need to perform a
lobectomy immediately!
<wait>
This operation has one objective:
<wait>
・ Treat all injuries within the thoracic cavity.
<wait>
We'll proceed from there.
<wait>
Drain the blood first, if it's a
large laceration.
<wait>
After that, use the forceps to close
the area, then suture it.
<wait>
Just be sure to drain any blood before
moving on with the operation.
<wait>
Hurry, Derek!
<wait>

@MSG_CNF206_START
<bup 0 1 10>
Let's begin the operation!
<vplay 1 9>
<wait>
<bup_cls>
