
@MSG_CNF201_001
<bup 0 10 1>
Let's go over the procedure for
Mr. Pratt's operation.
<wait>
He's been suffering from dizziness
and nausea recently.
<wait>
Tests show that wastes accumulated
in his spleen, and are now blocking
<wait>
blood vessels there.
<wait>
Today's objective is to remove
the buildup of thrombi.
<wait>
The contrast medium was administered
thirty minutes ago in IV.
<wait>
Because of that, you should be able to find
the waste material using ultrasound.
<wait>
Once it shows a shadow, try clipping
near that area with the forceps.
<wait>
It should stop moving. Make your
incision, then drain the area.
<wait>
This is a sensitive operation, so you'll need
to make proper use of magnification.
<wait>
Remember, the objective is:
<wait>
・ Remove all thrombi in the vessels.
<wait>
That is all.
<wait>
If further waste blockage occurs,
the patient's vitals will drop.
<wait>
<bup 0 10 3>
Remember to stay calm and
keep it steady.
<wait>

@MSG_CNF201_START
<bup 0 1 10>
Let's begin the operation!
<vplay 1 2>
<wait>
<bup_cls>
