
@MSG_CNF302_001
<bup 0 13 1>
I'll be briefing you on the procedures
for this operation.
<wait>
Today's patient is a GUILT victim who was
brought here three days ago.
<wait>
Derek, you've actually operated on
this exact strain already.
<wait>

@MSG_CNF302_002
<bup 0 2 1>
It was called...
Kyriaki, wasn't it?
<wait>

@MSG_CNF302_003
<bup 0 13 1>
Correct. This GUILT hides inside organs
while attacking their tissue.
<wait>
Removing it, however, should be just
like removing any parasite.
<wait>
We wanted a simple case to evaluate
your abilities.
<wait>
There's only one objective in this procedure:
<wait>
・ Remove the Kyriaki.
<wait>
I'll leave the exact details of the operation
to your discretion.
<wait>
Show us your talent, Dr. Stiles.
<wait>

@MSG_CNF302_004
<bup 0 2 5>
Yes sir.
<wait>

@MSG_CNF302_START
<bup 0 2 10>
Okay... Let's begin the operation.
<vplay 1 2>
<wait>
<bup_cls>
