
@MSG_CNF308_001
<bup 0 8 5>
It looks like respiratory failure...
<wait>
From what his wife explained, he'd been
suffering from edema of the lungs.
<wait>
He was prescribed medication, which
stabilized the condition. They were given
<wait>
permission to return home.
<wait>
But, stress from traveling may have
aggravated his symptoms.
<wait>
I'd recommend an immediate lobectomy
to drain the pleural fluids.
<wait>

@MSG_CNF308_002
<bup 0 2 1>
We're going to perform surgery in mid flight?
<wait>

@MSG_CNF308_003
<bup 0 8 5>
The captain has allowed us use of the crew's
cabin.
<wait>
Sterilized gowns and operation tools have
been prepared, as well.
<wait>

@MSG_CNF308_004
<bup 0 2 1>
...We really don't have a choice...
<wait>

@MSG_CNF308_005
<bup 0 8 5>
Once we land, he can receive more
permanent treatment...
<wait>
But for now, we have one objective:
<wait>
・ Drain pleural fluid from inside the patient's
lungs.
<wait>
Use ultrasound to find where fluid has
accumulated, and drain it.
<wait>

@MSG_CNF308_006
<bup 0 2 5>
Understood. Let's hurry.
<wait>

@MSG_CNF308_START
<bup 0 2 10>
Let's begin the emergency operation.
<vplay 1 8>
<wait>
<bup_cls>
