
@MSG_CNF304_001
<bup 0 17 5>
The Deftera's basically a tumor.
...A really gnarly one.
<wait>
It replicates its DNA while actively
moving throughout the body.
<wait>

@MSG_CNF304_002
<bup 0 2 5>
A tumor that...moves!?
That's impossible!
<wait>

@MSG_CNF304_003
<bup 0 17 5>
Well, to be fair, "moving" is kind of
a bad way to describe it.
<wait>
It copies itself to other locations.
So...it just looks like it's moving.
<wait>
Basically, it keeps on replicating its DNA
and creating new tumors.
<wait>

@MSG_CNF304_004
<bup 0 8 5>
...That's horrible.
<wait>

@MSG_CNF304_005
<bup 0 17 5>
Good news, though: we might just
know its weak point.
<wait>

@MSG_CNF304_006
<bup 0 2 5>
What is it?
<wait>

@MSG_CNF304_007
<bup 0 17 5>
Deftera comes in two flavors.
We'll call 'em Type A and Type B.
<wait>
Type A's and Type B's like to eat
each other when they meet up.
<wait>
But...they're both equally strong,
so they kinda just stall there.
<wait>
And, if they're not moving, they're
just like any old tumor, right?
<wait>

@MSG_CNF304_008
<bup 0 8 5>
So, after we drain the GUILT's tissue,
we can just excise it!
<wait>

@MSG_CNF304_009
<bup 0 17 5>
Hopefully.
I mean, this is all theoretical.
<wait>
One wrong move and they multiply, so
there's no room for trial and error.
<wait>
...It's not like we could safely
test the theory before trying it.
<wait>
...But, you have the Healing Touch.
<wait>
I've seen you use it, man...
it's amazing.
<wait>
If anyone can save Amy now,
I know it's you.
<wait>
I don't need to tell you the objective
of this operation, do I?
<wait>
・ Remove the GUILT from...the patient's
stomach and lungs.
<wait>
That's all.
<wait>
Just save her, man... All that stuff
I said before? Just forget it...
<wait>
...Please, Derek...
<wait>

@MSG_CNF304_START
<bup 0 2 10>
I understand, Tyler.
<vplay 1 7>
<wait>
<bup_cls>
