
@MSG_CNF310_001
<bup 0 19 1>
The boy's Chiral results just came back...
<wait>

@MSG_CNF310_002
<bup 0 8 5>
...He tested positive for GUILT.
<wait>
The spectral analysis indicates
this is a different strain...
<wait>

@MSG_CNF310_003
<bup 0 2 5>
An unknown GUILT...
<wait>

@MSG_CNF310_004
<bup 0 8 5>
We found an abnormality near his pancreas,
but...that's all.
<wait>

@MSG_CNF310_005
<bup 0 19 1>
His vitals are dropping quickly.
<wait>
If we tried to reach a hospital,
he would probably die on the way.
<wait>
...I think we should open him up
and do what we can, but...
<wait>
It's your call, Dr. Stiles.
<wait>

@MSG_CNF310_006
<bup 0 2 5>
I understand. We can't just stand
here and watch him die...
<wait>

@MSG_CNF310_START
<bup 0 2 10>
I'll do my best...!
<vplay 1 5>
<wait>
<bup_cls>
