
@MSG_CNF306_001
<bup 0 15 1>
I think everyone's clear...
...enough.
<wait>
Okay, you'll need to follow my
instructions carefully, got it?
<wait>

@MSG_CNF306_002
<bup 0 2 4>
...Aren't you scared?
<wait>

@MSG_CNF306_003
<bup 0 15 1>
Of course.
<wait>
But, why should a doctor be afraid?
<wait>
I'm sure you've been in worse situations
than this.
<wait>
We hold patients' lives in the palms
of our hands, you know...
<wait>
One mistake, and you have to watch them die.
<wait>
What could be more frightening than that?
<wait>

@MSG_CNF306_004
<bup 0 2 5>
Uh...I guess.
You're really brave, Dr. Myers...
<wait>

@MSG_CNF306_005
<bup 0 15 1>
Ha! They don't call me the Iron Vixen
for nothing!
<wait>

@MSG_CNF306_006
<bup 0 2 5>
That's what Tyler said. ...He comes up with
some weird nicknames.
<wait>

@MSG_CNF306_007
<bup 0 15 1>
Actually, that started back during my days
on the police force.
<wait>
I was in the crime lab, you know. Even
though I was just a novice investigator,
<wait>
I was still stronger than all the guys!
*chuckle*
<wait>

@MSG_CNF306_008
<bup 0 2 5>
So, you were really a police officer...?
<wait>

@MSG_CNF306_009
<bup 0 15 1>
That's right. And, I dated a guy
on the bomb squad...
<wait>
...So trust me on this one.
<wait>

@MSG_CNF306_START
<bup 0 2 5>
...Okay, then...L-Let's begin...
dismantling the...bomb. *gulp*
<vplay 1 3>
<wait>
<bup_cls>
