
@MSG_CNF404_001
<bup 0 14 1>
Okay, Dr. Stiles. I'll be explaining the details
of this operation.
<wait>
As you know, Tetarti is a very dangerous
strain of GUILT.
<wait>
They function in groups of three,
and produce a harmful pathogen.
<wait>
In other words, the Tetarti itself acts as one
poisonous mass.
<wait>
But, if we administer our antibody serum,
the GUILT should die...
<wait>
Victor just completed that serum,
as I'm sure you're aware.
<wait>
So, there's just one objective
in this operation:
<wait>
・ Kill the GUILT cells in his liver
by injecting the correct serums.
<wait>
As we discussed, the Tetarti will weaken
once you inject the serum.
<wait>
There's a different serum for each
one, so pay attention to colors.
<wait>
Remember, the Tetarti cells are
synchronized with each other.
<wait>
You have a limited window of time
to inject all three cells.
<wait>
You'll need to be accurate and fast.
Of course, every surgeon should be.
<wait>
...Dr. Kasal is a fine surgeon.
<wait>
You trained under him, and now you
have to save his life...
<wait>
...Do your best, Derek...
<wait>

@MSG_CNF404_002
<bup 0 2 5>
I plan on it.
<wait>

@MSG_CNF404_003
<bup 0 14 1>
Good luck...
Now, let's begin.
<wait>

@MSG_CNF404_START
<bup 0 2 10>
Okay, Dr. Kasal...
We're beginning the operation.
<vplay 1 6>
<wait>
<bup_cls>
