
@MSG_CNF410_001
<bup 0 16 1>
I developed a new type of laser for use
in this procedure.
<wait>
Last time, we found that a single core
unifies the cells.
<wait>
Even if most of the tissue is lost, the core
can just reboot everything.
<wait>
...But even when we destroyed the core,
it just restored itself.
<wait>
A meme for core regeneration must exist
in each individual cell.
<wait>
In other words, this GUILT has a wicked
contingency plan...
<wait>
...So, I thought up a little contingency
plan of my own:
<wait>
・ Use the nanomachine to lure out the core,
just like last time.
<wait>
・ Use our new laser to destroy the core
as it tries to regenerate tissue.
<wait>
Yeah, not that different from before.
It should be easy.
<wait>

@MSG_CNF410_002
<bup 0 13 1>
Victor... How sure are you that
this new laser will work?
<wait>

@MSG_CNF410_003
<bup 0 16 1>
It leaves less than 1% of the core
protein behind. ...A lot less.
<wait>
It's guaranteed to work, even against
this bastard.
<wait>
But...the laser will also cause serious damage
to any human tissue it comes in contact with.
<wait>
You're going to have to be really careful
about that...
<wait>

@MSG_CNF410_004
<bup 0 13 1>
Understood.
<wait>
There's not much time left...
You can do it, Derek.
<wait>

@MSG_CNF410_START
<bup 0 2 10>
I'm going to save him...
<vplay 1 7>
<wait>
<bup_cls>
