
@MSG_CNF408_001
<bup 0 16 1>
From the data we gathered during
the last operation...
<wait>
it's safe to assume this thing is impossible
to remove directly.
<wait>
But, the artificial DNA structure at its root
has a distinct weakness.
<wait>
It collapses when attacked from
a three-dimensional angle.
<wait>
So, I developed a nanomachine to exploit
that very weakness.
<wait>
By slightly altering its DNA, we can
instigate necrosis.
<wait>
Basically, we'll drive it to suicide.
<wait>
I tried it on a sample, and it took effect
immediately.
<wait>
Within four seconds, its mass had been
halved... Three seconds later, 91% of
<wait>
its mass was completely destroyed.
<wait>
See, this GUILT's rapid regeneration rate only
transfers the suicidal DNA that much faster.
<wait>
If we can shrink it down that way,
excision should be cake.
<wait>
So, our objectives are simple:
<wait>
・ Perform a lobectomy and inject
the nanomachine directly.
<wait>
・ Then, excise the GUILT and any
surrounding tissue.
<wait>
So, that's the plan, Chief.
Any objections?
<wait>

@MSG_CNF408_002
<bup 0 13 1>
It sounds like our best option.
Derek, prepare for surgery.
<wait>

@MSG_CNF408_START
<bup 0 2 10>
I understand.
<vplay 1 5>
<wait>
<bup_cls>
