
@MSG_CNF406_001
<bup 0 16 1>
There's a new GUILT called Pempti
inside the Secretary's chest.
<wait>
I've done enough tests to know how bad
this bastard can be...but I have no idea
<wait>
how to treat it.
Honestly? I think it's hopeless.
<wait>
But hey, every disease has to have
a cure, right?
<wait>
So it's up to us to find one.
That's how medicine advances.
<wait>
But, you know that.
That's why you joined Caduceus.
<wait>
Anderson said worst case, at least his illness
can be used to advance our understanding
<wait>
of GUILT.
<wait>
I assumed he was just some crusty
old bureaucrat...
<wait>
But, when you think about that, I guess he
really understands what we're about.
<wait>
So, we kind of owe it to the guy to make
sure this works out.
<wait>
I'd say you have one main objective:
<wait>
・ Do everything I tell you to do.
<wait>

@MSG_CNF406_002
<bup 0 2 5>
...What kind of objective is that!?
<wait>

@MSG_CNF406_003
<bup 0 16 1>
There's no known treatment yet.
Would YOU like to think one up?
<wait>
I'm the one who's done all the research,
so just listen to me.
<wait>

@MSG_CNF406_004
<bup 0 2 4>
(...We'll see about that...)
<wait>

@MSG_CNF406_005
<bup 0 16 1>
What's wrong?
<wait>

@MSG_CNF406_006
<bup 0 2 5>
...Nothing.
Let's just do our job.
<wait>

@MSG_CNF406_007
<bup 0 16 1>
That's a good attitude.
I hope you can handle this.
<wait>

@MSG_CNF406_START
<bup 0 2 10>
Okay...
Let's begin the operation!
<vplay 1 2>
<wait>
<bup_cls>
