
@MSG_CNF407_001
<bup 0 16 1>
All I need you to do today is help me
with a simple puzzle.
<wait>
It's pretty easy, but I need to see how
other people go about solving it.
<wait>
A genius like me would obviously settle on
the quickest solution immediately...
<wait>
But, I need someone like you, who's
...uh, you know, you're...
<wait>
...Someone who's not quite as adept at
maximizing his mental processes.
<wait>

@MSG_CNF407_002
<bup 0 2 4>
(If you think I'm an idiot, just say so.)
<wait>

@MSG_CNF407_003
<bup 0 16 1>
I'll be recording each one of your solutions.
Just relax...
<wait>
All you need to do is solve the puzzle.
Good luck!
<wait>

@MSG_CNF407_START
<bup 0 2 5>
Okay, let's give it a try...
<vplay 1 4>
<wait>
<bup_cls>
