
@MSG_CNF402A_001
<bup 0 8 5>
The patient has been transported.
...And our protective area is now sealed.
<wait>
I'll explain how Director Kasal requested
that we obtain the samples...
<wait>
These patients have tested positive for GUILT.
However, the specimens inside them are still
<wait>
in an immature state of development.
<wait>
In fact, this serum should be able to
completely incapacitate them.
<wait>
Doctor, first locate the GUILT.
Then use the serum to stop it.
<wait>
After that, place the GUILT specimen
onto the tray and slice it open.
<wait>

@MSG_CNF402A_002
<bup 0 2 5>
Slice it open!?
<wait>

@MSG_CNF402A_003
<bup 0 8 5>
Yes, we need the GUILT's internal fluids
to replicate its antigen.
<wait>
After we've drained the GUILT,
the procedure is complete.
<wait>
We only have one objective in this operation:
<wait>
・ Use the general serum to stop the GUILT
and obtain its fluids.
<wait>
That's all.
<wait>

@MSG_CNF402_START
<bup 0 2 10>
Understood.
Let's begin the operation.
<vplay 1 2>
<wait>
<bup_cls>
