
@MSG_CNF509_001
<bup 0 8 5>
...The Chiral reaction seems to be coming
from his abdomen.
<wait>
The spectral analysis indicates this is
the same GUILT as before.
<wait>

@MSG_CNF509_002
<bup 0 2 5>
Angie...
<wait>

@MSG_CNF509_003
<bup 0 8 5>
......
<wait>
...I saw a lot of my father's back.
<wait>
I can still see him sitting at his desk
in the study...
<wait>
If I tried to speak with him, he'd always say
that he was too busy.
<wait>
His own daughter... And, he wouldn't even
turn around to face me...
<wait>
And then, he left us...
<wait>
...He turned his back on us once and for all.
<wait>
<bup 0 8 4>
Was this what he left us for?
<wait>
...Was this worth abandoning his own family!?
<wait>

@MSG_CNF509_004
<bup 0 2 5>
......
<wait>

@MSG_CNF509_005
<bup 0 8 4>
He...abandoned us...
But...
<wait>
...He's still my father.
<wait>
Please save him...Doctor...
<wait>

@MSG_CNF509_006
<bup 0 2 5>
You have a lot to answer for,
Professor Blackwell.
<wait>
...Those are sins you'll have to deal with,
yourself.
<wait>
First, I'm going to make sure you survive this!
<wait>

@MSG_CNF509_START
<bup 0 2 10>
I won't let you die!
<vplay 1 20>
<wait>
<bup_cls>
