
@MSG_CNF503A_001
<bup 0 8 5>
Our tests indicate this is a mutated
Triti strain.
<wait>

@MSG_CNF503A_002
<bup 0 2 5>
The GUILT we saw in Africa!
<wait>

@MSG_CNF503A_003
<bup 0 8 5>
According to Dr. Niguel, this mutation
is far more contagious than before.
<wait>
The thorns become highly toxic
when vaporized.
<wait>

@MSG_CNF503A_004
<bup 0 2 5>
...So we'll need to drain the mist before
the infection can spread.
<wait>

@MSG_CNF503A_005
<bup 0 8 5>
Correct. ...Please be very careful,
Dr. Stiles.
<wait>

@MSG_CNF503A_START
<bup 0 2 10>
We can't afford any mistakes.
<vplay 1 2>
<wait>
<bup_cls>
