
@MSG_CNF508_001
<bup 0 8 5>
I contacted headquarters, but there
seems to be no matching data.
<wait>
<bup_cls>

@MSG_CNF508_002
<bup 0 2 5>
I see... Guess we'll be going in blind again...
<wait>
This almost seems like it was planned out.
<wait>

@MSG_CNF508_003
<bup 0 8 5>
What do you mean?
<wait>

@MSG_CNF508_004
<bup 0 2 5>
How could the researchers accidentally
release this GUILT?
<wait>
They know how dangerous it is--they're
the ones who created it!
<wait>

@MSG_CNF508_005
<bup 0 8 5>
Do you think they infected themselves as
a way to hide the evidence?
<wait>

@MSG_CNF508_006
<bup 0 2 5>
That doesn't sound right, either...
<wait>
Delphi definitely seems to have a weird
preoccupation with death, but...
<wait>
I don't think they'd encourage suicide as a
way to further their cause.
<wait>
...Sorry, nevermind. We need to concentrate
on the patient.
<wait>

@MSG_CNF508_START
<bup 0 2 10>
Let's begin the operation.
<vplay 1 2>
<wait>
<bup_cls>
