
@MSG_CNF506_001
<bup 0 16 1>
I checked the files, and it looks like
we've got a 97% match.
<wait>
This one's fibrous...which basically means
it's going to be a pain in the ass.
<wait>
You'll need to operate right away.
<wait>

@MSG_CNF506_002
<bup 0 2 5>
Huh? You haven't explained how to operate
on this fibrous thing...
<wait>

@MSG_CNF506_003
<bup 0 16 3>
I'll explain it after you open her up.
C'mon, hurry!
<wait>
As soon as that thing gets in the body,
it moves directly toward the heart.
<wait>
...And if it gets there, she's history.
<wait>

@MSG_CNF506_004
<bup 0 2 5>
......!
<wait>

@MSG_CNF506_005
<bup 0 16 1>
Find it yet?
<wait>

@MSG_CNF506_006
<bup 0 8 3>
Th-There's something in her stomach,
near the small intestine.
<wait>

@MSG_CNF506_007
<bup 0 16 1>
...Sounds about right.
It's quick, so we'll have to hurry.
<wait>

@MSG_CNF506_START
<bup 0 2 10>
Okay, then let's start!
<vplay 1 9>
<wait>
<bup_cls>
