
@MSG_CNF606_001
<bup 0 2 3>
...What's going on here!? GUILT shouldn't be
able to present this quickly...
<wait>

@MSG_CNF606_002
<bup 0 8 5>
Calm down, Doctor! We need to focus on
treating the patient...
<wait>

@MSG_CNF606_003
<bup 0 2 5>
...You're right, Angie.
<wait>
I just need to calm down... This one is going
to take serious concentration.
<wait>

@MSG_CNF606_004
<bup 0 8 5>
I'm worried about your condition...
<wait>
...but, here are the test results. They were
expedited, so the notes aren't complete.
<wait>

@MSG_CNF606_005
<bup 0 2 5>
But, they're sure it's GUILT?
<wait>

@MSG_CNF606_006
<bup 0 8 5>
That's what the report says.
...In his right lung.
<wait>
By the look of these Chiral reactions, I'd
say it's the Pempti strain.
<wait>
...Which gives us one objective:
<wait>
- Destroy the Pempti core.
<wait>
Once the core is gone, the fluids should go
away naturally, as always.
<wait>

@MSG_CNF606_START
<bup 0 2 10>
...Let's begin the emergency operation!
<vplay 1 5>
<wait>
<bup_cls>
