
@MSG_CNF603_001
<bup 0 2 1>
...Caduceus Europe's tests were correct.
<wait>
This is definitely Tetarti, though the symptoms
are a little unusual...
<wait>

@MSG_CNF603_002
<bup 0 8 1>
Let's treat it normally, but be prepared in case
anything unexpected happens.
<wait>
You can handle this, Doctor.
I believe in you.
<wait>

@MSG_CNF603_003
<bup 0 2 5>
...Yeah, you're right...
<wait>

@MSG_CNF603_004
<bup 0 8 5>
Are you feeling all right, Derek?
<wait>

@MSG_CNF603_005
<bup 0 2 5>
S-Sure, I'm fine...
<wait>

@MSG_CNF603_006
<bup 0 8 5>
Then, I'll keep you posted on anything unusual.
You just concentrate on the procedure.
<wait>
The only problem we can anticipate with Tetarti
is changes in its synchronicity.
<wait>

@MSG_CNF603_007
<bup 0 2 5>
Once we observe its movement pattern, that
shouldn't be too much of an issue.
<wait>

@MSG_CNF603_008
<bup 0 8 5>
That's true. Let's hope we don't need to worry
about anything beyond our objective:
<wait>
- Exterminate the Tetarti cells.
<wait>
I'm ready when you are.
<wait>

@MSG_CNF603_START
<bup 0 2 10>
Okay...
Let's begin the operation.
<vplay 1 2>
<wait>
<bup_cls>
