
@MSG_CNF607_001
<bup 0 8 5>
...There are a total of four patients who require
immediate treatment!
<wait>
You'll both alternate patients so that one of
you can keep an eye on the other three.
<wait>

@MSG_CNF607_002
<bup 0 2 5>
Got it.
<wait>

@MSG_CNF607_003
<bup 0 8 5>
While Dr. Stiles is operating, you'll need to
prep for your next procedure.
<wait>
Please adjust your routine accordingly,
Dr. Kimishima.
<wait>
Once Dr. Stiles closes his patient up, we'll
move on to yours immediately.
<wait>

@MSG_CNF607_004
<bup 0 6 1>
Understood.
<wait>

@MSG_CNF607_005
<bup 0 8 5>
Take time between operations to calm down
and refocus on the task at hand.
<wait>
Each of you will have two patients, meaning
we'll complete four procedures, total.
<wait>

@MSG_CNF607_006
<bup 0 2 5>
This is like the time we had ten minutes to
treat five GUILT patients... Remember, Angie?
<wait>

@MSG_CNF607_007
<bup 0 8 5>
This time there are only four, and we have
two doctors... So I'm going to be optimistic.
<wait>
However, judging by this GUILT data and
the patient information...
<wait>
<bup 0 8 3>
...this is an entirely different situation
than before.
<wait>

@MSG_CNF607_008
<bup 0 6 1>
Even with the two of us, we're going to have
our hands full.
<wait>

@MSG_CNF607_009
<bup 0 8 5>
...We're running out of time.
<wait>
Derek... Dr. Kimishima...
We have to save these people.
<wait>

@MSG_CNF607_START
<bup 0 2 10>
We won't let them die...!
<vplay 1 6>
<wait>
<bup_cls>
