
@MSG_CNF608_001
<bup 0 8 5>
The tests came back positive for Savato.
<wait>
However, there's a high probability that this
is a mutation of the strain.
<wait>
The points to focus on will be:
<wait>
- Use the scalpel to destroy Savato's nest.
<wait>
- Neutralize its defensive layer with the laser.
<wait>
- Once the Savato is vulnerable, attack it
with the scalpel.
<wait>
Let's just hope it's that simple.
<wait>
The Savato may travel to other areas during
the procedure.
<wait>
In order to counteract this, you'll both need to
be involved in the surgery.
<wait>
If you work together, I think we can save
Director Hoffman.
<wait>

@MSG_CNF608_002
<bup 0 2 5>
Understood!
<wait>

@MSG_CNF608_003
<bup 0 6 1>
I see. Having two Healing Touches should
even out the odds...
<wait>

@MSG_CNF608_004
<bup 0 8 5>
If you're both ready, we shouldn't waste
any more time...
<wait>

@MSG_CNF608_START
<bup 0 2 10>
Dr. Hoffman won't die on my watch!
<vplay 1 23>
<wait>
<bup_cls>
