
@MSG_CNF604_001
<bup 0 6 1>
Here are the test results...
<wait>

@MSG_CNF604_002
<bup 0 8 9>
...!? ...This Chiral reaction shows two
distinct patterns...
<wait>

@MSG_CNF604_003
<bup 0 6 1>
Yeah... He's been infected by two different
strains of GUILT at the same time.
<wait>

@MSG_CNF604_004
<bup 0 8 4>
Then, it's too late...
<wait>

@MSG_CNF604_005
<bup 0 6 1>
There's no reason to assume the worst.
<wait>

@MSG_CNF604_006
<bup 0 8 5>
...You're right, I'm sorry.
<wait>
What types... Er, do we know which strains
of GUILT are involved?
<wait>

@MSG_CNF604_007
<bup 0 6 1>
...The tests say Kyriaki and Paraskevi.
You already know the affected area is--
<wait>

@MSG_CNF604_008
<bup 0 8 5>
...Derek's heart.
<wait>
Kyriaki's lacerations are going to present
a serious danger to his vitals...
<wait>
...and if we give Paraskevi an opening, it will
burrow directly into his heart.
<wait>
We won't be allowed any mistakes, so we'll
both need...complete concentration.
<wait>

@MSG_CNF604_009
<bup 0 6 2>
...That's more like it.
Just hold it together, alright?
<wait>

@MSG_CNF604_010
<bup 0 8 5>
Saving Dr. Stiles will require two steps:
<wait>
- Exterminate the Kyriaki.
- Extract the Paraskevi.
<wait>

@MSG_CNF604_START
<bup 0 6 10>
OK, let's begin.
<vplay 4 2>
<wait>
<bup_cls>
