
@MSG_CNF702_001
<bup 0 5 1>
The anesthesia is proceeding well, so I should
be able to start on schedule.
<wait>
(Looks like I only have one objective:
<wait>
- Extract any tumors in the patient's
large intestine.
<wait>
Simple enough...)
<wait>
(Though, this can't be a normal tumor if
they needed to get me involved...)
<wait>
(I don't know what they've got inside him, so
I'll need to keep an eye on those vitals.)
<wait>
(...Of course, if anything goes wrong, I still
have that to fall back on.)
<wait>

@MSG_CNF702_START
<bup 0 5 10>
...Alright, I'm ready.
<vplay 4 4>
<wait>
<bup_cls>
