
@MSG_CNF701_001
<bup 0 4 1>
Let's see... 
Time of dictation: 3:48 PM.
<wait>
The patient's name is Alan Chambers. He has
a serious fracture in his right arm.
<wait>
As for the X-ray results...
<wait>
Fragments of the bone seem to be scattered,
and I see hemorrhaging.
<wait>
That said, I will be approaching this operation
with three objectives:
<wait>
- Collect fragments of his radius and ulna.
- Set the radius properly for healing.
<wait>
- Return the fragments to their original location
and rebuild the patient's radius and ulna.
<wait>
I anticipate a smooth procedure.
<wait>

@MSG_CNF701_START
<bup 0 4 10>
It's time to get started...
<vplay 4 3>
<wait>
<bup_cls>
