
@MSG_CNF703_001
<bup 0 5 1>
It's too dark to see... We'll need to get him
over in front of our headlights.
<wait>
Here, help me pull him out of the wreckage...
<wait>

@MSG_CNF703_002
<bup 0 25 1>
...No good! His leg is stuck.
<wait>

@MSG_CNF703_003
<bup 0 5 1>
...Guess I don't have a choice.
I'll have to treat him here.
<wait>

@MSG_CNF703_004
<bup 0 25 1>
Can you even do that!?
<wait>

@MSG_CNF703_005
<bup 0 5 1>
I wish he was in a better position, but that
shouldn't cause too many problems.
<wait>
...If you have any suggestions about getting
some light over here, I'm all ears.
<wait>

@MSG_CNF703_006
<bup 0 25 1>
I think we're in trouble. The crash shorted out
the tunnel's electrical system.
<wait>
With him on that side of the wreck, my
headlights won't be able to do much, either.
<wait>

@MSG_CNF703_007
<bup 0 5 1>
...Necessity is the mother of invention.
<wait>

@MSG_CNF703_008
<bup 0 25 1>
A penlight!? You've gotta be kidding.
<wait>

@MSG_CNF703_009
<bup 0 5 1>
Nope--and you're going to be holding it.
Just shine it where I tell you, okay?
<wait>
Most of the trauma is...here. I don't like the
looks of his abdomen, either.
<wait>
*sigh* Tonight's abdominal surgery will
have two objectives:
<wait>
- Extract any foreign objects.
- Suture any lacerations.
<wait>
Given the situation, that's about all we
can do for him.
<wait>

@MSG_CNF703_START
<bup 0 5 10>
May as well get started.
<vplay 4 6>
<wait>
<bup_cls>
