
@MSG_CNF704_001
<bup 0 5 1>
Well, since we're still waiting on that kidney...
<wait>
...I might as well get started on the tumor.
<wait>
I can't transplant the kidney until that tumor is
out of him, anyway.
<wait>
(The key to this transplant is going to be
anastomosing the opened veins.)
<wait>
Once I administer the vasoconstrictor, his
blood flow should slow down...
<wait>
I'll need to complete the anastomosis while
it's still in effect, or he could bleed out.
<wait>
In short, there are two parts to this:
<wait>
- Tumor excision.
- Transplanting the new kidney.
<wait>
...A pretty tall order, considering.
<wait>
We've got a real risk of blood loss here, so just
make sure I've got that kidney when I need it.
<wait>
(Depending on how this goes, I may need to
bring my Healing Touch into play...)
<wait>

@MSG_CNF704_START
<bup 0 5 10>
...I'm going to begin the procedure.
Keep me posted on the new kidney.
<vplay 4 6>
<wait>
<bup_cls>
