
@MSG_CNF705_001
<bup 0 25 1>
Professor Blackwell will be observing as well.
Don't let us down, Weaver.
<wait>

@MSG_CNF705_002
<bup 0 23 1>
We're in a critical situation here, but try to
concentrate on the patient.
<wait>

@MSG_CNF705_003
<bup 0 5 1>
Yes, Professor.
<wait>
I read the packet you provided. You believe
this patient has...Kyriaki?
<wait>

@MSG_CNF705_004
<bup 0 25 1>
The tests weren't conclusive, but everything
we've been told seems to indicate Kyriaki, yes.
<wait>
This is a weird case--make sure that you don't
get infected with it too.
<wait>

@MSG_CNF705_005
<bup 0 5 1>
Understood.
I think I can handle it...
<wait>
So, there's really only one thing I need to
do here...
<wait>
- Expel the Kyriaki.
<wait>
(What the hell is going on?)
<wait>

@MSG_CNF705_START
<bup 0 5 10>
Bring in the patient...
Let's begin the operation.
<vplay 4 5>
<wait>
<bup_cls>
