
@MSG_CNF803_001
<bup 0 22 1>
For decades, the world's governments have
financed the creation of biological weapons.
<wait>
Airborne viruses which calcify the organs
of their victims...developed for war.
<wait>
...Yet those same governments are surprised
when such weapons are used against them.
<wait>
Modern man is the very model of hypocrisy.
You glorify the discovery of medicine, yet
<wait>
hide the fact that the same knowledge
is used to create disease!
<wait>

@MSG_CNF803_START
<bup 0 2 10>
...And you'd rather create new ways for us
to die? That's insane!
<vplay 1 9>
<wait>
<bup_cls>
