
@MSG_CNF805_001
<bup 0 22 1>
Mankind's greed has no ending... You continue
to consume until even your host is laid waste.
<wait>
Is survival that important?
<wait>
...So important you would trade it for
the earth's destruction?
<wait>

@MSG_CNF805_START
<bup 0 2 10>
If people as a whole are consuming too much
then maybe that's another disease we
<vplay 1 9>
<wait>
need to cure...but we can cure it!
<wait>
<bup_cls>
