
@MSG_CNF806_001
<bup 0 22 1>
In young forests at the dawn of time, plants
were born with the ability to kill humans.
<wait>
...Such simple, perfect organisms.
<wait>
Do you understand the meaning of such
toxic flora?
<wait>
They demonstrate that all creation seeks
an end to mankind.
<wait>

@MSG_CNF806_START
<bup 0 2 10>
If humans are to be judged...it won't be
at the hands of other men!
<vplay 1 9>
<wait>
<bup_cls>
