
@MSG_CNF807_001
<bup 0 22 1>
My beautiful, perfect image of Death itself...
which I have deemed Savato.
<wait>
But... What if I told you this Death existed
inherently inside all human DNA?
<wait>
...I merely gave it the chance to take shape.
<wait>
This is the Death you have denied.
...Our guide to the truth.
<wait>

@MSG_CNF807_START
<bup 0 2 10>
Even if what you're saying is true,
Savato remained dormant.
<wait>
We found a way to overcome Death--that
was humanity's choice!
<vplay 1 9>
<wait>
<bup_cls>
