
@MSG_CNF906_001
<bup 0 22 1>
In young forests at the dawn of time, plants
were born with the ability to kill humans.
<wait>
...Such simple, perfect organisms.
<wait>
Do you understand the meaning of such
toxic flora?
<wait>
They demonstrate that all creation seeks
an end to mankind.
<wait>

@MSG_CNF906_START
<bup 0 6 10>
Your old world, steeped in death, perished
at the dawning of civilization!
<vplay 4 6>
<wait>
<bup_cls>
