
@MSG_CNF907_001
<bup 0 22 1>
My beautiful, perfect image of Death itself...
which I have deemed Savato.
<wait>
But... What if I told you this Death existed
inherently inside all human DNA?
<wait>
...I merely gave it the chance to take shape.
<wait>
This is the Death you have denied.
...Our guide to the truth.
<wait>

@MSG_CNF907_START
<bup 0 6 10>
...If it's Death you want, I'll be sure
to give it to you!
<vplay 4 6>
<wait>
<bup_cls>
