
@MSG_CNF903_001
<bup 0 22 1>
For decades, the world's governments have
financed the creation of biological weapons.
<wait>
Airborne viruses which calcify the organs
of their victims...developed for war.
<wait>
...Yet those same governments are surprised
when such weapons are used against them.
<wait>
Modern man is the very model of hypocrisy.
You glorify the discovery of medicine, yet
<wait>
hide the fact that the same knowledge
is used to create disease!
<wait>

@MSG_CNF903_START
<bup 0 6 10>
...Human history is one of mistakes, but there
are those of us who don't want to repeat them!
<vplay 4 6>
<wait>
<bup_cls>
