
@MSG_OPEDBG_GAME_OVER
<bup 0 10 3>
月森、何をもたもたしている！
あとは私が代わる！
<wait>

@MSG_OPEDBG_START_OPE
<bup 1 1 1>
それじゃを始めましょう。
まずは…出血の酷い裂傷の処理ね。
<wait>
<rubi 縫合 ナート>
するわよ。
針と糸をとって頂戴。

@MSG_OPEDBG_SELECT_STITCHES
<bup 1 1 1>
そう、それそれ。そのまま
裂傷をジグザグになぞってみて。

@MSG_OPEDBG_STEP_1stSLASH_END
<bup 1 1 1>
お見事！…なんてね。
基本よね、外科医なら。
<wait>
それじゃ、
もう１つの裂傷も縫合しましょう。

@MSG_OPEDBG_CAUTION_SLASH
<bup 1 1 1>
先生、どうしたの？
まずは裂傷の縫合をして頂戴。

@MSG_OPEDBG_STEP_2ndSLASH_END
<bup 1 1 1>
良く出来ました。
縫合処理はこれで終わりね。
<wait>
次はガラス片の摘出よ。
ピンセットをとって頂戴。

@MSG_OPEDBG_SELECT_FORCEPS
<bup 1 1 1>
ピンセットでガラス片を掴んで、
傷口から抜くようにスライドさせて。

@MSG_OPEDBG_STEP_1stFOREIGN_PULL
<bup 1 1 1>
抜いたガラス片は、
トレイまで持ってきて放してね。

@MSG_OPEDBG_MISS_FOREIGN_PULL
<bup 1 1 1>
先生、乱暴すぎるわよ。
傷口からまっすぐ抜くようにしないと。

@MSG_OPEDBG_MISS_FOREIGN_DROP
<bup 1 1 1>
トレイまでもってきて放して頂戴ね。
落としたら危ないわよ。

@MSG_OPEDBG_STEP_1stFOREIGN_END
<bup 1 1 1>
オーケーよ。
もう１つのほうも摘出して。

@MSG_OPEDBG_STEP_2ndFOREIGN_END
<bup 1 1 1>
見えるガラス片は
抜き終わったみたいね。
<wait>
小さな傷の処置もしちゃいましょうか。
ヒールゼリーをとって頂戴。

@MSG_OPEDBG_SELECT_GEL
<bup 1 1 1>
それそれ。
それを傷口に塗ってあげて。

@MSG_OPEDBG_STEP_1stSCAR_END
<bup 1 1 1>
いい感じよ？
なかなか手馴れてきたわね。

@MSG_OPEDBG_STEP_AllSCAR_END
<bup 1 1 1>
医学の進歩って凄いわよね。
小さな傷ならこれで一発ですもんね。
<wait>
万病に効く軟膏って
昔からニセモノばっかりだったけど、
<wait>
とうとう本物ができちゃったのね。
…って、おしゃべりしてちゃダメね。
<wait>
手術を続けるわよ。
さっき見た感じだと、腕の中にも
<wait>
いくつかガラス片が埋まってるみたい。
皮膚を切って摘出するしかないわね。
<wait>
上腕上皮を切開しましょう。
メス…の前に、消毒よ。
<wait>
ヒールゼリーをガイド線に塗って頂戴。

@MSG_OPEDBG_CAUTION_MARKER
<bup 1 1 1>
黄色の切開ガイドを全部緑にしないと
消毒は終わらないわよ。

@MSG_OPEDBG_STEP_OPENMARKER_END
<bup 1 1 1>
消毒完了…と。いよいよ切開ね。
メスをとって頂戴。

@MSG_OPEDBG_SELECT_SCALPEL
<bup 1 1 1>
緊張する？大丈夫よね。
ガイドに沿ってゆっくり線を引くのよ。

@MSG_OPEDBG_MISS_OPEN_OTHERPLACE
<bup 1 1 1>
何やってるのッ！
ちゃんとガイドに沿って切りなさい！

@MSG_OPEDBG_STEP_OPEN_END
<bup 1 1 1>
…あらあら、結構な数ね。
感染症を起こすといけないわね。
<wait>
手早く処置しちゃいましょう。
手順はさっきと同じよ。

@MSG_OPEDBG_MISS_OPEN_GUIDELINE
<bup 1 1 1>
あわてなくていいわ。
速い事と巧い事は別よ。
<wait>
ゆっくりでもいいから、
丁寧に確実にやる事を覚えなさい。

@MSG_OPEDBG_TALK_GOODJOB
<bup 1 1 1>
上出来よ、月森先生。
そのまま続けて。

@MSG_OPEDBG_CAUTION_FOREIGN
<bup 1 1 1>
まだガラス片が残っているわよ？
摘出をお願いね。

@MSG_OPEDBG_CAUTION_SCAR
<bup 1 1 1>
どうしたの？
ヒールゼリーで傷口を治療するのよ？

@MSG_OPEDBG_MISS_FOREIGN_INNER
<bup 1 1 1>
ちゃんと注意して！
慎重過ぎて過ぎる事はないのよ！

@MSG_OPEDBG_END_FLOW
<bup 1 1 1>
うん、もう大丈夫みたいね。
閉創しましょう。

@MSG_OPEDBG_STEP_CLOSE_STITCHES
<bup 1 1 1>
最初の裂傷と同じように、
ジグザグに縫って閉じて頂戴。
<wait>
縫い目は広すぎず狭すぎず、
しっかり丁寧にね。

@MSG_OPEDBG_STEP_CLOSE_END
<bup 1 1 1>
さて、ほとんど終わりだけど、
最後まで気をぬいちゃだめよ。
<wait>
今縫合した部分を、
ヒールゼリーで消毒して頂戴。

@MSG_OPEDBG_STEP_CLOSEMAKER_END
<bup 1 1 1>
綺麗になったわね。
最後に患部をテーピングしましょ。
<wait>
保護テープをとって頂戴。

@MSG_OPEDBG_SELECT_BANDAGE
<bup 1 1 1>
傷口の端から端まで
ビーッとテープを貼れば完了よ。

@MSG_OPEDBG_MISS_BANDAGE_OOR
<bup 1 1 1>
それじゃだめね。
傷口にできるだけピッタリあわせて。

@MSG_OPEDBG_END_OPE
<bup 1 1 1>
はい、手術終了よ。
お疲れ様でした、月森先生。
<wait>
ちゃんと復習しておいてね。
<wait>
