
@MSG_OPE402H_GAMEOVER
<bup 0 8 3>
It's too dangerous! We'll have to
transport him to Caduceus!
<wait>
<bup_cls>

@MSG_OPE402Ha_DEBUGMSG01
<bup 1 8 5>

@MSG_OPE402Ha_DEBUGMSG02
<bup 1 8 5>

@MSG_OPE402Ha_START_OPE
<bup 1 8 5>
<vplay 7 3>
We have two objectives: remove the GUILT
from the patient, and get a sample.
<wait>
Both require careful procedures.
So, let's begin...

@MSG_OPE402Ha_OPEN_BODY
<bup 1 8 5>
<vplay 7 113>
It's an immature GUILT cell, just like
Dr. Kasal's data theorized!
<wait>
Inject it with serum to slow its activity.

@MSG_OPE402Ha_POISON_GENERATE
<bup 1 8 5>
<vplay 7 41>
It's releasing toxic chemicals...
Neutralize them with antibiotic gel!

@MSG_OPE402Ha_STEP_TRITI_SYRINGE
<bup 1 8 5>
The serum was effective, but...
now it's hidden itself inside the organ.
<wait>
Try to locate it using ultrasound so that
you can excise it.

@MSG_OPE402Ha_STEP_TRITI_SYRINGE
<bup 1 8 5>
<vplay 7 55>
The serum seems to be working.
It should stop moving soon.

@MSG_OPE402Ha_STEP_TRITI_SYRINGE
<bup 1 8 5>
The GUILT has been incapacitated.
Move it onto the tray, carefully.

@MSG_OPE402Ha_STEP_TRITI_FORCEPS
<bup 1 8 5>
<vplay 7 64>
Carefully make an incision down
the center of the GUILT...

@MSG_OPE402Ha_STEP_TRITI_SCALPEL
<bup 1 8 5>
<vplay 7 67>
Now, use the drain to suck out the GUILT's
internal fluids.

@MSG_OPE402Ha_END_FLOW_NOTHING_L
<bup 1 8 5>
<vplay 7 58>
Fluid extraction complete...
Let's close him up.

@MSG_OPE402Ha_END_FLOW_REMAIN_LE
<bup 1 8 5>
<vplay 7 58>
Fluid extraction complete...
Let's finish the treatment.

@MSG_OPE402Ha_CLOSE_BODY
<bup 1 8 5>
A GUILT that releases toxic substances...
How could they create something like this!?
<wait>
<vplay 7 82>
I hope Dr. Kasal is all right...

@MSG_OPE402Ha_END_OPE
<bup 1 8 5>
<vplay 7 9>
Operation complete.
Good work, Doctor.
<wait>

@MSG_OPE402Hb_START_OPE
<bup 1 8 5>
<vplay 7 3>
Please remove the GUILT and obtain
its antigen just like before.

@MSG_OPE402Hb_OPEN_BODY
<bup 1 8 5>
<vplay 7 113>
Immature GUILT cell confirmed!
Inject the serum.

@MSG_OPE402Hb_STEP_TRITI_SYRINGE
<bup 1 8 5>
It escaped...
Use the ultrasound to find it!

@MSG_OPE402Hb_STEP_TRITI_SYRINGE
<bup 1 8 5>
<vplay 7 106>
Chiral reaction is faint... The next injection
should be enough to stop it!

@MSG_OPE402Hb_STEP_TRITI_SYRINGE
<bup 1 8 5>
The GUILT is incapacitated!
Move it carefully onto the tray.

@MSG_OPE402Hb_STEP_TRITI_FORCEPS
<bup 1 8 5>
<vplay 7 64>
Now, make an incision along its center
and extract the sample.

@MSG_OPE402Hb_END_FLOW_NOTHING_L
<bup 1 8 5>
<vplay 7 33>
Fluid extraction complete!
Let's close him up.

@MSG_OPE402Hb_END_FLOW_REMAIN_LE
<bup 1 8 5>
<vplay 7 33>
Fluid extraction complete!
Let's finish treating him.

@MSG_OPE402Hb_CLOSE_BODY
<bup 1 8 5>
Oh... I'm nervous.
I hope this is the right one...

@MSG_OPE402Hb_END_OPE
<bup 1 8 5>
<vplay 7 9>
Operation complete!
Good work, Doctor.
<wait>

@MSG_OPE402Hc_START_OPE
<bup 1 8 5>
<vplay 7 3>
Please excise the GUILT and obtain
the antigen sample like before.

@MSG_OPE402Hc_OPEN_BODY
<bup 1 8 5>
<vplay 7 113>
Immature GUILT confirmed!
Inject it with serum now.

@MSG_OPE402Hc_STEP_TRITI_SYRINGE
<bup 1 8 5>
It escaped...
Use the ultrasound to find it!

@MSG_OPE402Hc_STEP_TRITI_SYRINGE
<bup 1 8 5>
<vplay 7 106>
Chiral reaction is faint... The next injection
should stop it!

@MSG_OPE402Hc_CAUTION_TRITI_RAMP
<bup 1 8 3>
<vplay 7 50>
What the...!? Doctor! Use the gel to
neutralize it!

@MSG_OPE402Hc_STEP_TRITI_SYRINGE
<bup 1 8 5>
It...stopped moving. I have a really bad
feeling about this GUILT...

@MSG_OPE402Hc_STEP_TRITI_FORCEPS
<bup 1 8 5>
Make an incision along its center to extract
the antigen sample.

@MSG_OPE402Hc_END_FLOW_NOTHING_L
<bup 1 8 5>
<vplay 7 33>
Fluid extraction complete!
Let's close him up.

@MSG_OPE402Hc_END_FLOW_REMAIN_LE
<bup 1 8 5>
<vplay 7 33>
Fluid extraction complete!
Let's finish treating him.

@MSG_OPE402Hc_CLOSE_BODY
<bup 1 8 5>
I hope this is the last sample we'll need...!

@MSG_OPE402Hc_END_OPE
<bup 1 8 5>
<vplay 7 9>
Operation complete!
Good work, Dr. Stiles.
<wait>
