
@MSG_OPE503c_GAMEOVER
<bup 0 14 1>
This is too dangerous!
Dr. Stiles, let me handle it!
<wait>
<bup_cls>

@MSG_OPE503c_START_OPE
<bup 1 8 5>
This GUILT is highly infectious...
<wait>
We won't get a second chance if
it starts to spread.
<wait>
<vplay 7 5>
Let's get started...
Good luck.

@MSG_OPE503c_ENTER_BODY
<bup 1 8 5>
We'll proceed just like before--remove
the thorns and membranes.

@MSG_OPE503c_CAUTION_REMAIN_MEMB
<bup 1 8 3>
<vplay 7 24>
Be careful! If you isolate one membrane,
it can multiply!

@MSG_OPE503c_CAUTION_EVAPORATE_W
<bup 1 8 3>
<vplay 7 72>
It released a poison mist...
Drain it immediately!

@MSG_OPE503c_CAUTION_SMOKE_MAKE_
<bup 1 8 3>
That vapor could rebuild the membranes!
Be careful...

@MSG_OPE503c_TREATMENT_TETARTI_H
<bup 1 8 5>
<vplay 7 55>
Excision is going smoothly!
We're almost done, Doctor.

@MSG_OPE503c_STEP_MEMBRANE_FORCE
<bup 1 8 3>
Be careful with the thorns!
If you drop one...

@MSG_OPE503c_END_FLOW
<bup 1 8 1>
<vplay 7 45>
The Triti has been removed.
Is this getting easier for you?

@MSG_OPE503c_MISS_MEMBRANE_DROP
<bup 1 8 3>
<vplay 7 27>
Don't drop the membrane, Doctor!
It can still do serious damage.

@MSG_OPE503c_END_OPE
<bup 1 8 1>
If that strain had spread, it would
have been a disaster...
<wait>
<bup 1 8 2>
<vplay 7 9>
I'm glad we stopped it before
there was an outbreak.
<wait>
