
@MSG_OPE503b_GAMEOVER
<bup 0 14 1>
This is too dangerous!
Dr. Stiles, let me handle it!
<wait>
<bup_cls>

@MSG_OPE503b_START_OPE
<bup 1 8 5>
This GUILT is highly infectious...
<wait>
We won't get a second chance if
it starts to spread.
<wait>
Let's get started...
Good luck.

@MSG_OPE503b_ENTER_BODY
<bup 1 8 5>
We'll proceed just like before--remove
the thorns and membranes.

@MSG_OPE503b_CAUTION_REMAIN_MEMB
<bup 1 8 3>
<vplay 7 24>
Be careful! If you isolate one membrane,
it can multiply!

@MSG_OPE503b_CAUTION_EVAPORATE_W
<bup 1 8 3>
<vplay 7 72>
It released a poison mist...
Drain it immediately!

@MSG_OPE503b_CAUTION_SMOKE_MAKE_
<bup 1 8 3>
That vapor could rebuild the membranes!
Be careful...

@MSG_OPE503b_TREATMENT_TETARTI_H
<bup 1 8 5>
<vplay 7 55>
Excision is going smoothly!
We're almost done, Doctor.

@MSG_OPE503b_STEP_MEMBRANE_FORCE
<bup 1 8 3>
Be careful with the thorns!
If you drop one...

@MSG_OPE503b_END_FLOW
<bup 1 8 1>
<vplay 7 45>
The Triti has been removed.
Is this getting easier for you?

@MSG_OPE503b_MISS_MEMBRANE_DROP
<bup 1 8 3>
<vplay 7 27>
Don't drop the membrane, Doctor!
It can still do serious damage.

@MSG_OPE503b_END_OPE
<bup 1 8 1>
If that strain had spread, it would
have been a disaster...
<wait>
<bup 1 8 2>
<vplay 7 9>
I'm glad we stopped it before
there was an outbreak.
<wait>

@MSG_OPE503b_NEXT_OPE
<bup 0 8 3>
<vplay 7 43>
No... It's the poison mist!
<wait>
<bup 0 9 5>
I can tell you're struggling here...
<wait>
Leave this patient to me.
Move on to the next one...
<wait>
<bup 0 8 5>
We understand.
Let's go, Doctor!
<wait>
<bup_cls>
