
@MSG_OPE105_GAMEOVER
<bup 0 10 3>
Let me handle this, Derek!
<wait>
<bup_cls>

@MSG_OPE105_START_OPE
<vplay 7 2>
<bup 1 7 5>
Operating on the pharynx requires precision
movement and the utmost care.

@MSG_OPE105_ENTER_BODY
<vplay 7 40>
<bup 1 7 5>
The outer membrane of the trachea
has started to hemorrhage...
<wait>
That should be our focal point.
<wait>
It's hard to see the affected area,
so we'll need to magnify it.
<wait>
Take the magnification tool. I'll explain
how it's used.

@MSG_OPE105_MISS_SCALPEL_GUIDELI
<vplay 7 42>
<bup 1 7 5>
...What are you waiting for, Doctor?
We need to proceed with the surgery.

@MSG_OPE105_CAUTION_LASER_DONT_U
<bup 1 7 5>
Doctor, please stop taking actions
without advisement.

@MSG_OPE105_STEP_BLOOD_DRAIN_END
<vplay 7 64>
<bup 1 7 5>
The source of the bleeding seems to
be a small group of polyps.
<wait>
There's no way we can excise them;
they're far too small. Use the laser.
<wait>
Prepare the laser so we can burn off
the growths.

@MSG_OPE105_CAUTION_BLOOD_REPOP
<vplay 7 40>
<bup 1 7 5>
It's getting worse.
We have even more bleeding.
<wait>
Drain the blood before continuing,
or you won't be able to see.

@MSG_OPE105_CAUTION_BLOOD_USE_MA
<bup 1 7 5>
That's very dangerous.
We need to magnify it first.

@MSG_OPE105_CAUTION_BLOOD_USE_MA
<bup 1 7 5>
Magnify the affected area before starting
treatment!

@MSG_OPE105_SELECT_MAGNIFICATION
<vplay 7 54>
<bup 1 7 5>
Select the area you want to magnify and
press the A Button to activate it.
<wait>
You can then continue your procedure
in the magnified operating area.

@MSG_OPE105_CAUTION_MAGNIFICATIO
<vplay 7 52>
<bup 1 7 5>
You've magnified the wrong area.
Please try again.
<wait>
First, you'll need to cease magnification.

@MSG_OPE105_USE_MAGNIFICATION
<vplay 7 64>
<bup 1 7 5>
The magnification was successful.
That hemorrhaging is our problem.
<wait>
Once you're finished working in the
affected area...
<wait>
...simply return to the non-magnified
view.
<wait>
Keep these options in mind as you set up
the best angle for a given task.
<wait>
First, we need to drain the blood so those
polyps are exposed.

@MSG_OPE105_SELECT_LASER
<vplay 7 40>
<bup 1 7 5>
The laser will continue to burn tissue as
long as you have it activated.
<wait>
...Applying it for extended periods will
cause additional bleeding.
<wait>
Please be careful and only apply the laser
precisely where necessary.
<wait>
Let's begin. Slowly burn away the polyps.

@MSG_OPE105_MISS_LASER
<vplay 7 23>
<bup 1 7 5>
Shoot... I think the laser burned away
a little too much tissue.
<wait>
See? That's what caused those tiny wounds.
<wait>
Please treat those areas with antibiotic gel
immediately.

@MSG_OPE105_STEP_1stPOLYP_HALFEN
<vplay 7 40>
<bup 1 7 5>
Hmm... I don't think its possible to burn
away polyps without damaging nearby tissue.
<wait>
The capillaries in the trachea's outer
membrane are damaged and have caused
<wait>
further bleeding.
<wait>
...You're going to need to adjust
the procedure accordingly.
<wait>
We need to apply antibiotic gel immediately
after using the laser.
<wait>
If blood starts to collect, drain it quickly
to maintain visibility.
<wait>
Stay calm, Dr. Stiles. If you're careful,
everything should be fine.

@MSG_OPE105_STEP_1stPOLYP_END
<vplay 7 57>
<bup 1 7 5>
All the polyps have been removed.
<wait>
It...could have gone better, but I guess
it's not too bad, for you.

@MSG_OPE105_FLOW_TURNING_POINT
<vplay 7 55>
<bup 1 7 5>
Everything is going well.
Please continue the treatment.

@MSG_OPE105_POLYP_SPAWN_BEFORE_M
<vplay 7 40>
<bup 1 7 5>
Another section of the membrane
is starting to hemorrhage!
<wait>
You'll need to cease magnification.

@MSG_OPE105_POLYP_SPAWN_BEFORE_M
<vplay 7 64>
<bup 1 7 5>
It looks like there are several other
polyp-affected areas.
<wait>
We'll need to treat all of them.

@MSG_OPE105_POLYP_SPAWN_AFTER_MA
<vplay 7 64>
<bup 1 7 5>
It looks like there are several other
polyp-affected areas.
<wait>
We'll need to treat all of them.

@MSG_OPE105_END_FLOW
<vplay 7 56>
<bup 1 7 5>
...That seems to be all of them.
Let's close the patient up.

@MSG_OPE105_CLOSE_BODY
<vplay 7 79>
<bup 1 7 5>
Let's close the patient up.
Suture the incision.

@MSG_OPE105_END_OPE
<vplay 7 7>
<bup 1 7 5>
(...So I've really been assigned to this
inexperienced slacker...?)
<wait>
Er, that is... Good job, Dr. Stiles.
<wait>
