
@MSG_OPE108_GAMEOVER
<bup 0 10 3>
...I made it just in time!
Derek, you need to get out of my way!
<wait>
<bup_cls>

@MSG_OPE108_START_OPE
<vplay 7 21>
<bup 1 7 4>
He's flatlining! We have to
do something...!
<wait>
...W-We need to recover his pulse.
<wait>
<vplay 7 23>
Let me explain how to use
the defibrillator.
<wait>
First, move the paddles toward the patient
and place them on his chest.

@MSG_OPE108_STEP_1ST_DEFIBRILLAT
<vplay 7 43>
<bup 1 7 4>
Let me explain how to use
the defibrillator.
<wait>
First, move the paddles toward the patient
and place them on his chest.

@MSG_OPE108_STEP_1ST_DEFIBRILLAT
<vplay 7 23>
<bup 1 7 4>
Now, I'll explain how to release the
shock...hold the paddles in position.
<wait>
Keep an eye on the meter displaying
the level of electric charge.
<wait>
Do you see the green area on
the voltage gauge?
<func5 504 131 240>
<wait>
Activate the shock when the meter
reaches that area on the gauge.
<wait>
The closer to this reading you get, the
more effective the shock will be.
<wait>
Now, you need to know how to activate
the defibrillator...
<wait>
Once it's moved toward the patient, press
the B Button and Z Button simultaneously.
<wait>
Do you understand?
<wait>
You apply the shock by pressing both buttons
when the paddles are placed on the patient.
<func6 0>

@MSG_OPE108_CAUTION_PADDLE_RELEA
<bup 1 7 4>
Don't lift the paddles yet! If they're not
making contact, this won't work!

@MSG_OPE108_CAUTION_PADDLE_RELEA
<bup 1 7 4>
Keep the paddles pressed against the
patient's chest.

@MSG_OPE108_STEP_1ST_DEFIBRILLAT
<bup 1 7 4>
...Still no pulse.
Keep trying--you have the timing down.

@MSG_OPE108_STEP_1ST_DEFIBRILLAT
<bup 1 7 4>
You need to time it more carefully...

@MSG_OPE108_STEP_1ST_DEFIBRILLAT
<bup 1 7 4>
Watch the gauge, Doctor! We need
to get a pulse!

@MSG_OPE108_STEP_1ST_DEFIBRILLAT
<bup 1 7 4>
Your timing is good...
Try one last time!

@MSG_OPE108_STEP_1ST_DEFIBRILLAT
<bup 1 7 4>
You're doing well--just keep trying!

@MSG_OPE108_STEP_1ST_DEFIBRILLAT
<bup 1 7 4>
Watch the gauge, Dr. Stiles! Timing is
crucial if we're going to revive him!

@MSG_OPE108_STEP_1ST_DEFIBRILLAT
<vplay 7 61>
<bup 1 7 4>
Th-There's a pulse...
...We did it!
<wait>
<bup 1 7 5>
......!
<wait>
Vitals are still below 30!
...He's not in the clear yet.
<wait>
<bup 1 1 11>
...That sounds more like the Angie
I know.
<wait>
<bup 1 7 5>
Dr. Stiles... Are we going
to save him?
<wait>
<bup 1 1 11>
Of course we are.
<wait>
<bup 1 7 5>
...Understood!
<wait>
First, take care of those lacerations
so we can continue the procedure.

@MSG_OPE108_CONTINUE_TREATMENT_L
<vplay 7 55>
<bup 1 7 5>
Treatment's going well, please
continue.

@MSG_OPE108_TREATMENT_LESION_END
<bup 1 7 5>
External wounds have been healed.
<wait>
Bleeding seems to have stopped,
but his vitals are dropping fast!
<wait>
He suffered a lot of damage to his
chest. ...What else could it be?
<wait>
<vplay 7 62>
Perform a lobectomy! I think there
might be something in his chest!

@MSG_OPE108_ENTER_BODY
<vplay 7 48>
<bup 1 7 5>
...No...
You can't--!
<wait>
Don't take this the wrong way...
<wait>
I don't think you have the skill
to treat it like this...
<wait>
...We recovered his pulse, so maybe
we should wait for Dr. Kasal's help.
<wait>
...No, the longer we wait, the lower
his chances at survival...
<wait>
I don't know what to do!
<wait>
Either way, I won't blame you.
...This is your decision...

@MSG_OPE108_CONTINUE_OPERATION
<vplay 7 63>
<bup 1 7 5>
I understand.
...I'll trust you.

@MSG_OPE108_STEP_FOREIGN_FORCEPS
<bup 1 7 3>
Be careful around the pericardium...
We're fighting against blood loss!

@MSG_OPE108_MISS_FOREIGN_DROP
<vplay 7 24>
<bup 1 7 3>
Careful! The smallest mistake could
cost the patient his life!

@MSG_OPE108_STEP_SLASH_SUTURE
<bup 1 7 5>
No problems...
Continue treatment.

@MSG_OPE108_2ND_DEFIBRILLATOR_1
<bup 1 7 3>
He's suffering cardiac arrest again!
...We need to revive him!

@MSG_OPE108_2ND_DEFIBRILLATOR_EN
<bup 1 7 5>
We have a pulse!
...What!?

@MSG_OPE108_STEP_HUGEFOREIGN_1
<vplay 7 50>
<bup 1 7 5>
H-How could something like that
be lodged in the pericardium!?
<wait>
Please extract it, b-but...
be careful...

@MSG_OPE108_STEP_HUGEFOREIGN_END
<bup 1 7 1>
*sigh*...
I think he's going to make it.

@MSG_OPE108_BROKEN_HEART
<vplay 7 51>
<bup 1 7 5>
This...can't be happening...

@MSG_OPE108_AUTOACTIVE_HEALINGTO
<vplay 1 17>
Dammit!
Don't die on me!

@MSG_OPE108_AUTOACTIVE_HEALINGTO
<vplay 1 11>
<bup 1 1 11>
This is bad...

@MSG_OPE108_STEP_HUGESLASH_SUTUR
<vplay 1 20>
(...C'mon, concentrate! All I have
to do is suture this wound...)

@MSG_OPE108_END_FLOW
<bup 1 7 5>
(...What!?)
<wait>
<vplay 7 49>
(H-He sutured the myocardium
in a split second!)
<wait>
I...I think we're finished.
Let's close him up.

@MSG_OPE108_END_OPE
<bup 1 7 5>
I could feel him slipping away...
I was so scared, Doctor.
<wait>
...I froze, and all I could think
about was running away...
<wait>
But, you didn't worry at all.
<wait>
You stood your ground, and did
what had to be done.
<wait>
You... You are a real doctor.
<wait>
<vplay 7 8>
<bup 1 7 2>
Thank you... Doctor Stiles.
<wait>
