
@MSG_OPE102_GAMEOVER
<bup 0 10 3>
Out of the way, Stiles...
I'll take over from here!
<wait>
<bup_cls>

@MSG_OPE102_START_OPE
<vplay 11 2>
<bup 1 11 1>
This will be a laparotomy.
You'll need to open up his abdomen.
<wait>
You've done this before, so there's no
reason to be anxious.
<wait>
Let's begin. Disinfect the area and make
your incision.

@MSG_OPE102_MISS_OPEN_OTHERPLACE
<vplay 11 12>
<bup 1 11 3>
Stop that, Derek, or I'll report you to
the Board!

@MSG_OPE102_MISS_OPEN_GUIDELINE
<vplay 11 12>
<bup 1 11 1>
There's no need to rush.
Remember, slow and steady.

@MSG_OPE102_ENTER_BODY
<vplay 11 19>
<bup 1 11 1>
We're going to treat a tumor, but...
<wait>
Hmm...
His vitals are dropping.
<wait>
You'll need to use a syringe.
Let's stabilize his condition.
<func5 111 376 45>

@MSG_OPE102_SELECT_SYRINGE
<func6 0>
<bup 1 11 1>
Insert it into the vial first, to fill it with
medicine.

@MSG_OPE102_USE_SYRINGE_FULLMEDI
<vplay 11 14>
<bup 1 11 1>
Now inject it into the infected area, making
sure to hold it steady.

@MSG_OPE102_CAUTION_SYRINGE
<vplay 11 19>
<bup 1 11 1>
We should probably administer
a little bit more.
<wait>
Fill the syringe completely and inject
a full dosage.

@MSG_OPE102_USE_SYINGE
<vplay 11 19>
<bup 1 11 1>
Vitals are... stabilized.
<wait>
Now we can begin. At first glance,
it appears that nothing is wrong.
<wait>
However, yesterday's test revealed 
something in the patient's lower stomach.
<wait>
We'll need to use the ultrasound
in order to find the problem area.
<func5 88 396 225>

@MSG_OPE102_SELECT_ULTRASOUND
<func6 0>
<bup 1 11 1>
You can activate the ultrasound by pressing
the B Button.
<wait>
You will notice that infected areas show
up as shadows when sonar is activated.

@MSG_OPE102_STEP_TUMOR_FINDSHADO
<vplay 11 23>
<bup 1 11 2>
Wha--You found it on your first try!
Is that talent or beginner's luck?
<wait>
Now we'll expose the tumor...
Incise down the center.

@MSG_OPE102_RETRY_ULTRASOUND
<vplay 11 21>
<bup 1 11 1>
Oh, almost! We lost sight of it because
the ultrasound was too far away.
<wait>
If you scan directly over the tumor, it
should remain visible for much longer.
<wait>
Expert doctors can perform this operation
without the benefit of visual aid, but
<wait>
you should take a moment to confirm the
shadow before moving forward.

@MSG_OPE102_RETRY_ULTRASOUND_AGA
<bup 1 11 1>
Very close...
You almost had it.

@MSG_OPE102_STEP_TUMOR_FINDSHADO
<vplay 11 15>
<bup 1 11 1>
Okay, that's right. Hm...
This is definitely the problem.
<wait>
Now we'll expose the tumor...
Incise down the center.

@MSG_OPE102_CAUTION_TUMOR_LOSTSH
<bup 1 11 1>
It will fade away over time, but if that 
happens, just stay calm and start again.

@MSG_OPE102_STEP_TUMOR_FINDSHADO
<bup 1 11 1>
There's the tumor. Incise down the center
of the shadow, quickly.

@MSG_OPE102_MISS_SCALPEL_OTHERPL
<vplay 11 20>
<bup 1 11 3>
What are you doing!? I asked you to cut
across the shadow!
<wait>
You'd better suture that wound you opened
up. Understand?

@MSG_OPE102_RECOVER_AllSLASH
<vplay 11 25>
<bup 1 11 1>
*sigh* Don't scare me like that.
This time, be a little more careful.
<wait>
Incise down the center of the shadow
and take care not to cut too far.

@MSG_OPE102_CAUTION_SLASH_notSUT
<vplay 11 21>
<bup 1 11 3>
What are you doing!? Hurry--suture
his wounds!

@MSG_OPE102_MISS_SCALPEL_OTHERPL
<vplay 11 12>
<bup 1 11 3>
You're being too careless!
Suture those up, now!

@MSG_OPE102_CAUTION_SLASH_notSUT
<bup 1 11 3>
Doctor Stiles! You must suture
his lacerations immediately!

@MSG_OPE102_RECOVER_AllSLASH_AGA
<vplay 11 25>
<bup 1 11 1>
...Getting back to business...
Incise down the shadow's center.

@MSG_OPE102_STEP_AllTUMOR_APPEAR
<vplay 11 19>
<bup 1 11 1>
Hmmm... It's pretty big. Looks like
we did this just in time.
<wait>
As Dr. Kasal explained earlier, we'll be
using the Powell Procedure.
<wait>
We'll use the drain first.
Pick it up.
<func5 111 396 135>

@MSG_OPE102_SELECT_DRAIN
<func6 0>
<bup 1 11 1>
Next, insert the drain into the tumor.
<func5 415 280 270>

@MSG_OPE102_STEP_TUMOR_DRAIN
<vplay 11 29>
<func6 0>
<bup 1 11 1>
Now, while keeping the drain steady,
begin extracting the cytoplasm.

@MSG_OPE102_CAUTION_DRAIN_OUT
<bup 1 11 1>
Oh no, don't remove it...
<wait>
Now try again. Aim for the tumor.

@MSG_OPE102_STEP_TUMOR_DRAIN_AGA
<bup 1 11 1>
Keep the drain in place.

@MSG_OPE102_CAUTION_DRAIN_OUT_AG
<bup 1 11 3>
Doctor! Don't remove it from the tumor!

@MSG_OPE102_STEP_TUMOR_DRAIN_END
<vplay 11 14>
<bup 1 11 1>
We've completed the first step:
draining the cytoplasm.
<wait>
But, cytoplasm will continue to ooze out
if we don't do anything.
<wait>
Excise it with the scalpel before that
happens.

@MSG_OPE102_SELECT_SCALPEL
<bup 1 11 1>
Follow the guide line and cut with care.

@MSG_OPE102_RETRY_TUMOR_DRAIN
<bup 1 11 1>
There's more cytoplasm.
You need to drain it again.

@MSG_OPE102_RETRY_TUMOR_DRAIN_EN
<bup 1 11 1>
You drained the cytoplasm--now excise
the tumor.

@MSG_OPE102_STEP_TUMOR_SCALPEL_E
<vplay 11 22>
<bup 1 11 1>
Good job excising the tumor.
Now, just extract it.
<func5 89 375 315>

@MSG_OPE102_MISS_SCALPEL_GUIDELI
<vplay 11 20>
<bup 1 11 3>
What are you doing!? I asked you to cut
along the guide line!
<wait>
You'd better suture that wound you opened up.
Understand?

@MSG_OPE102_RECOVER_AllSLASH_B
<bup 1 11 1>
*sigh* Don't scare me like that.
This time, be a little more careful.
<wait>
There's more cytoplasm.
You'll need to drain it again.

@MSG_OPE102_CAUTION_SLASH_notSUT
<vplay 11 21>
<bup 1 11 3>
What are you doing!? Hurry up
and suture his wounds!

@MSG_OPE102_MISS_SCALPEL_GUIDELI
<bup 1 11 3>
You're being too careless!
Suture those up, now!

@MSG_OPE102_CAUTION_SLASH_notSUT
<vplay 11 21>
<bup 1 11 3>
Doctor Stiles! You must suture these
lacerations immediately!

@MSG_OPE102_RETRY_TUMOR_DRAIN_AG
<bup 1 11 1>
There's too much cytoplasm.
You need to drain it again.

@MSG_OPE102_STEP_TUMOR_FORCEPS_E
<vplay 11 14>
<func6 0>
<bup 1 11 1>
Well done.
You're doing well so far.
<wait>
But, removing the tumor is only
the beginning.
<wait>
You need to apply a synthetic membrane
to stop the bleeding.
<wait>
Grab a membrane with the forceps
and place it over the incision.

@MSG_OPE102_MISS_TUMOR_DROP
<vplay 11 11>
<bup 1 11 3>
Don't let go until its over the tray!
We're dealing with human life here!

@MSG_OPE102_STEP_TUMOR_MEMBRANE
<vplay 11 19>
<bup 1 11 1>
That's good. Now let's affix the synthetic
membrane.
<wait>
First, apply antibiotic gel over the membrane
to disinfect it.

@MSG_OPE102_MISS_MEMBRANE_DROP_N
<bup 1 11 1>
You need to be more accurate.
Apply it over the excised area.

@MSG_OPE102_MISS_MEMBRANE_DROP_F
<bup 1 11 1>
Doctor, what are you doing!?
Place it over the area of excision!

@MSG_OPE102_STEP_TUMOR_GEL_END
<vplay 11 18>
<bup 1 11 1>
That's enough gel. The membrane is
beginning to meld with the tissue.
<wait>
It's made of protein, so there's no chance
of tissue rejection.
<wait>
I think it's blended in nicely.
It should heal up perfectly.

@MSG_OPE102_END_FLOW
<bup 1 11 1>
Now, finish the operation by suturing
your incision.

@MSG_OPE102_END_OPE
<vplay 11 4>
<bup 1 11 1>
You can relax now, Dr. Stiles.
The operation is complete.
<wait>
