
@MSG_OPE103_GAMEOVER
<bup 0 10 3>
What are you doing...!?
*sigh* Leave the rest to me...
<wait>
<bup 0 11 1>
I guess you needed more guidance...
<wait>
I really didn't think I'd have to hold your
hand this time.
<wait>
<bup_cls>

@MSG_OPE103_START_OPE
<vplay 11 2>
<bup 1 11 1>
Let's begin the operation, Dr. Stiles.

@MSG_OPE103_ENTER_BODY
<vplay 11 3>
<bup 1 11 1>
The pancreatic membrane is inflamed,
so we'll need an anti-inflammatory.

@MSG_OPE103_SELECT_SYRINGE
<bup 1 11 1>
It's kept in a blue vial. Inject that
into the inflamed area.
<func5 318 340 90>

@MSG_OPE103_STEP_1stINFLAM_END
<func6 0>
<bup 1 11 1>
It's reacting normally. Now inject
it into the other inflammation.

@MSG_OPE103_STEP_2ndINFLAM_END
<vplay 11 15>
<bup 1 11 1>
Good, the swelling's gone down...
Let's move on to the tumors.
<wait>
Three tumors have been identified
in the patient's pancreas.
<wait>
Perform ultrasound carefully to locate them.

@MSG_OPE103_STEP_1stTUMOR_FINDSH
<bup 1 11 1>
...You found one!
Proceed the same way as before.

@MSG_OPE103_CAUTION_TUMOR_LOSTSH
<bup 1 11 1>
I think we've lost it.
Try the ultrasound again.

@MSG_OPE103_STEP_1stTUMOR_DRAIN_
<bup 1 11 1>
Drainage complete...
Move on to the next step.

@MSG_OPE103_STEP_1stTUMOR_SCALPE
<vplay 11 16>
<bup 1 11 1>
Excision complete.
Keep up the good work.

@MSG_OPE103_STEP_2ndTUMOR_SCALPE
<bup 1 11 1>
<vplay 11 17>
You're pretty good with a scalpel!
That's two down...

@MSG_OPE103_STEP_2ndTUMOR_FORCEP
<bup 1 11 1>
Good work, Derek! You didn't even
have to ask me what to do.

@MSG_OPE103_STEP_AllTUMOR_FORCEP
<vplay 11 22>
<bup 1 11 1>
All three tumors have been excised.
<wait>
Don't forget to care for
the affected areas.

@MSG_OPE103_MISS_TUMOR_DROP
<vplay 11 11>
<bup 1 11 3>
Doctor! Please be careful when moving
the tumor.

@MSG_OPE103_MISS_MEMBRANE_DROP
<vplay 11 10>
<bup 1 11 1>
Don't get frustrated, Derek.
Just try it again, okay?

@MSG_OPE103_STEP_TUMOR_GEL_END
<vplay 11 19>
<bup 1 11 1>
The membrane is in place.
We're done with this area.

@MSG_OPE103_END_FLOW_NOTHING_LES
<vplay 11 23>
<bup 1 11 1>
That takes care of the tumors we
found in our test.
<wait>
You're really improving--can you tell?
<wait>
You seemed really focused today...
I guess my work here is done!

@MSG_OPE103_END_FLOW_REMAIN_LESI
<vplay 11 23>
<bup 1 11 1>
That takes care of the tumors we
found in our test.
<wait>
You're really improving--can you tell?
<wait>
You seemed really focused today...
I guess my work here is done!
<wait>
Well, let's finish up by taking care
of this incision, Doctor.

@MSG_OPE103_CLOSE_BODY
<bup 1 11 2>
Perfect work, Dr. Stiles.
Let's close up the incision.

@MSG_OPE103_END_OPE
<vplay 11 5>
<bup 1 11 1>
I think we can both relax, Derek.
You're doing great!
<wait>
