
@MSG_OPE101_GAMEOVER
<bup 0 10 3>
Why are you wasting time, Derek?
I'll take over from here!
<wait>
<bup_cls>

@MSG_OPE101_START_OPE
<se_play 0 8 0>
<vplay 11 2>
<bup 1 11 1>
Let's begin the operation. We should
start with those lacerations.
<wait>
Take the stitching needle to suture
those wounds.
<func5 117 386 90>

@MSG_OPE101_SELECT_STITCHES
<func6 0>
<vplay 11 28>
<bup 1 11 1>
Just follow along the laceration
in a zig-zag pattern.
<func5 440 200 270>

@MSG_OPE101_STEP_1stSLASH_END
<se_play 0 8 10>
<func6 0>
<bup 1 11 2>
Good work!
Of course, this is only a basic surgery skill.
<wait>
<bup 1 11 1>
Now do the same thing with the other
laceration.

@MSG_OPE101_CAUTION_SLASH
<vplay 11 21>
<bup 1 11 1>
Doctor, is something wrong?
Please suture the wound.

@MSG_OPE101_STEP_2ndSLASH_END
<se_play 0 8 10>
<vplay 11 22>
<bup 1 11 1>
Well done. The lacerations have been
taken care of.
<wait>
Next, take your forceps.
We need to remove that glass.
<func5 88 376 315>

@MSG_OPE101_SELECT_FORCEPS
<func6 0>
<vplay 11 24>
<bup 1 11 1>
Grip the glass fragments by pressing with
both fingers (A and B Buttons).
<wait>
Once you have a hold on one, slide it out.
<func5 370 170 270>

@MSG_OPE101_STEP_1stFOREIGN_PULL
<func6 0>
<bup 1 11 1>
Place the extracted fragments in the tray.

@MSG_OPE101_MISS_FOREIGN_PULL
<vplay 11 20>
<bup 1 11 3>
Doctor, please be more careful.
Slide against the direction of entry.

@MSG_OPE101_MISS_FOREIGN_DROP
<vplay 11 13>
<bup 1 11 1>
Please drop it into the tray, not back into
the patient.
<wait>
Try extracting it again, but be more careful
this time.

@MSG_OPE101_STEP_1stFOREIGN_END
<bup 1 11 1>
Good job.
Now extract the other one.

@MSG_OPE101_STEP_2ndFOREIGN_END
<vplay 11 14>
<bup 1 11 1>
All the visible glass has now been extracted.
<wait>
We need to take care of those
smaller wounds now.
<wait>
Take the antibiotic gel.
<func5 99 369 0>

@MSG_OPE101_SELECT_GEL
<func6 0>
<bup 1 11 1>
That's the one.
Gently apply over the wounds.
<func5 390 210 270>

@MSG_OPE101_STEP_1stSCAR_END
<func6 0>
<bup 1 11 1>
That's good. It looks like you're starting
to get the hang of it.

@MSG_OPE101_STEP_AllSCAR_END
<se_play 0 8 10>
<vplay 11 26>
<bup 1 11 2>
Medicine has come a long way. This gel can
actually cure small injuries immediately.
<wait>
In the past, cure-all ointments were
just gimmicks and scams...
<wait>
...but somebody finally created a real one.
<wait>
<bup 1 11 1>
Oops, I shouldn't be talking so much.
Let's continue...
<wait>
Some glass shards are embedded in
the patient's arm, as well.
<wait>
We'll need to extract those--make an 
incision in his upper epithelium.
<wait>
Don't forget to disinfect the area 
beforehand. Use antibiotic gel.
<func5 150 215 90>

@MSG_OPE101_CAUTION_MARKER
<vplay 11 19>
<bup 1 11 1>
When the guide line turns blue, the area
has been disinfected.

@MSG_OPE101_STEP_OPENMARKER_END
<func6 0>
<vplay 11 15>
<bup 1 11 1>
Now we'll make an incision.
Pick up the scalpel.
<func5 82 386 270>

@MSG_OPE101_SELECT_SCALPEL
<func6 0>
<vplay 11 27>
<bup 1 11 1>
There's no reason to be nervous, just follow
the guide line carefully.

@MSG_OPE101_MISS_OPEN_OTHERPLACE
<vplay 11 12>
<bup 1 11 3>
What are you doing!?
Cut along the guide line! It's easy!

@MSG_OPE101_STEP_OPEN_END
<vplay 11 19>
<bup 1 11 1>
Hm... This is serious.
We can't let them get infected.
<wait>
We'll need to work quickly, using
the same procedure as before.

@MSG_OPE101_MISS_OPEN_GUIDELINE
<vplay 11 10>
<bup 1 11 1>
Don't rush it! Being accurate is far more
important than finishing quickly.
<wait>
Slow down... Stay careful and be precise.

@MSG_OPE101_TALK_GOODJOB
<bup 1 11 1>
Well done, Dr. Stiles.
Please continue.

@MSG_OPE101_CAUTION_FOREIGN
<vplay 11 21>
<bup 1 11 1>
There are still fragments left.
Please continue.

@MSG_OPE101_CAUTION_SCAR
<vplay 11 21>
<bup 1 11 1>
What are you waiting for? Treat
those wounds with antibiotic gel.

@MSG_OPE101_MISS_FOREIGN_INNER
<vplay 11 20>
<bup 1 11 3>
Watch out! You can never be too cautious.

@MSG_OPE101_END_FLOW
<vplay 11 18>
<bup 1 11 1>
Alright, everything looks good.
Let's close it up.
<wait>

@MSG_OPE101_STEP_CLOSE_STITCHES
<vplay 11 19>
<bup 1 11 1>
<func5 150 215 90>
Suture the wound the same way
you have before.
<wait>
Make sure the stitches aren't too
wide or too narrow.
<func6 0>

@MSG_OPE101_STEP_CLOSE_END
<vplay 11 15>
<bup 1 11 1>
We're just about done, but you shouldn't
relax just yet.
<wait>
Disinfect the sutured area with antibiotic gel.
<func5 150 215 90>

@MSG_OPE101_STEP_CLOSEMAKER_END
<func6 0>
<vplay 11 14>
<bup 1 11 1>
That should heal up nicely.
Now we just apply the bandage.
<wait>
There are some tools you only need to
use in specific instances.
<wait>
You can pick them up once I
have placed them on the tray.
<wait>
So, take the bandages now, okay?
<func5 155 290 270>

@MSG_OPE101_SELECT_BANDAGE
<func6 0>
<bup 1 11 1>
Bandage along the entire length of
the incision.

@MSG_OPE101_MISS_BANDAGE_OOR
<bup 1 11 1>
That's unacceptable. You need to
bandage the entire incision.

@MSG_OPE101_END_OPE
<func6 0>
<vplay 11 4>
<bup 1 11 1>
...And, we're done.
Good job, Dr. Stiles.
<wait>
Make sure you review what we went over
today when you have the chance.
<wait>
