
@MSG_OPE106_GAMEOVER
<bup 0 7 3>
It's too dangerous! Stop!
We'll just wait for Dr. Kasal!
<wait>
<bup_cls>

@MSG_OPE106_START_OPE
<vplay 7 2>
<bup 1 7 5>
Well, Dr. Stiles, let's begin the operation.

@MSG_OPE106_ENTER_BODY
<vplay 7 47>
<bup 1 7 5>
What's going on!? The entire intestinal
membrane is inflamed.
<wait>
What's going on? Only the small intestine
should be affected...
<wait>
Doctor, I think we need to close up
the patient for re-examination.
<wait>
<bup 1 1 11>
Let's continue operating, Angie.
Those symptoms aren't uncommon.
<wait>
<bup 1 7 5>
...I understand...
<wait>
In that case, proceed with
tumor excision.
<wait>
I know you've done this before, so I'll try
to stay out of your way.

@MSG_OPE106_STEP_INFLAM_TURNING_
<vplay 7 55>
<bup 1 7 5>
Treatment is going well. Please inject
the anti-inflammatory.

@MSG_OPE106_STEP_INFLAM_END
<bup 1 7 5>
Treatment of the visibly inflamed areas
is complete, but...

@MSG_OPE106_STEP_TUMOR_DRAIN_END
<bup 1 7 5>
The Powell Method, huh? You must be
studying the latest techniques.

@MSG_OPE106_STEP_TUMOR_SCALPEL_E
<vplay 7 55>
<bup 1 7 5>
The second tumor's been excised, but
...something's not right.

@MSG_OPE106_RETRY_DRAIN
<vplay 7 40>
<bup 1 7 5>
You let it re-permeate?
...Hmph, rookie mistake.

@MSG_OPE106_STEP_TUMOR_FORCEPS_E
<bup 1 7 5>
The first tumor's been excised.
At least we're making progress.

@MSG_OPE106_STEP_AllTUMOR_FORCEP
<vplay 7 40>
<bup 1 7 5>
We've removed all the tumors.
Please treat the incision.

@MSG_OPE106_MISS_TUMOR_DROP
<bup 1 7 5>
...Try to avoid making stupid mistakes, 
Doctor.

@MSG_OPE106_MISS_MEMBRANE_DROP
<bup 1 7 5>
...Try to avoid making stupid mistakes,
Doctor.

@MSG_OPE106_END_FLOW
<vplay 7 58>
<bup 1 7 5>
We treated the patient as planned,
but he's not improving.
<wait>
His vitals aren't stabilizing.
There must be something else--
<wait>
<bup 1 1 11>
The patient's vitals don't usually
stabilize right after the operation.
<wait>
<bup 1 7 5>
...But...we need to at least check
his blood test results!
<wait>
<bup 1 1 11>
......
<wait>
Hm, okay...
What would you suggest?
<wait>
<bup 1 7 5>
Try using the ultrasound again...
Just to be safe.

@MSG_OPE106_RETRY_ULTRASOUND_1
<vplay 7 41>
<bup 1 7 5>
Check the entire area carefully.

@MSG_OPE106_RETRY_ULTRASOUND_2
<bup 1 7 5>
......

@MSG_OPE106_RETRY_ULTRASOUND_END
<bup 1 1 11>
I don't see anything, Angie.
<wait>
<bup 1 7 5>
But I was certain... Sorry about
second-guessing you, Doctor.
<wait>
<bup 1 1 11>
Don't worry. We're both still learning from
experience, right?
<wait>
<bup 1 7 5>
...I guess.

@MSG_OPE106_CLOSE_BODY
<vplay 7 64>
<bup 1 7 5>
You should finish up by suturing the incision.

@MSG_OPE106_END_OPE
<vplay 7 7>
<bup 1 7 5>
We're finished, Dr. Stiles.
<wait>
