
@MSG_OPE211_GAMEOVER
<bup 0 10 3>
I won't let her die!
I can still save her...
<wait>
<bup_cls>

@MSG_OPE211_START_OPE
<bup 1 7 5>
Her report details frequent occurences
of light arrhythmia.
<wait>
...Be ready for the unexpected, 
just in case...
<wait>
<vplay 7 3>
Let's get started with the operation.

@MSG_OPE211_OPEN_BODY
<bup 1 7 5>
Disinfection complete.
Please make your incision.

@MSG_OPE211_CAUTION_EVENT_VF_SIG
<bup 1 7 5>
...What? The electrocardiogram is
showing an abnormality!

@MSG_OPE211_CAUTION_EVENT_VF_INC
<bup 1 7 3>
She's suffering ventrical fibrillation!
<wait>
I'll attempt to stop the convulsions...
3, 2, 1... Clear!
<wait>

@MSG_OPE211_CAUTION_EVENT_FLATLI
<bup 1 7 3>
She's flatlining! We need a pulse, quickly!

@MSG_OPE211_STEP_DEFIBRILLATOR_E
<bup 1 7 5>
<vplay 7 41>
Doctor, the patient was born with
a highly irregular heart beat.
<wait>
There's a good chance her heart will
continue to go into convulsions.
<wait>
I'll stand by with the defibrillator
in case we need to use it again.
<wait>
If that happens, you'll need to recover
her pulse as quickly as possible!
<wait>
The defibrillator may have a high success
rate, but allowing the heart to
<wait>
flatline repeatedly is obviously
very dangerous for the patient.
<wait>
Make sure you revive her right away
if that happens.
<wait>
...Now, continue the operation.
Please open the atrium.

@MSG_OPE211_CAUTION_VF_INC
<bup 1 7 3>
Stand by for defibrillation...
...3, 2, 1... Clear!

@MSG_OPE211_STEP_DEFIBRILLATOR_E
<bup 1 7 5>
Pulse is back to normal. Keep an eye
out for any more abnormalities.

@MSG_OPE211_CAUTION_DEFIBRILLATO
<bup 1 7 5>
<vplay 7 19>
Doctor! We need a pulse! Hurry!

@MSG_OPE211_OPEN_HEART
<bup 1 7 5>
<vplay 7 41>
This is a delicate procedure.

@MSG_OPE211_STEP_1stBLOOD_DRAIN_
<bup 1 7 5>
Visibility is clear. First, excise
the left side of the valve.

@MSG_OPE211_STEP_MITRALVALVE_SCA
<bup 1 7 5>
Next, excise the right side.

@MSG_OPE211_STEP_MITRALVALVE_SCA
<bup 1 7 5>
<vplay 7 55>
Finally, excise the valve tissue itself.

@MSG_OPE211_MISS_SCALPEL_OPEN_HE
<bup 1 7 5>
<vplay 7 43>
This is heart surgery, Dr. Stiles!
Please be more careful!

@MSG_OPE211_STEP_MITRALVALVE_MAG
<bup 1 7 5>
Let's begin the valve procedure.
We will excise it in 3 stages.
<wait>
...But before that, we'll need to drain
this blood.
<wait>

@MSG_OPE211_STEP_MITRALVALVE_SCA
<bup 1 7 5>
<vplay 7 56>
Valve excised. Please place it on the tray.

@MSG_OPE211_STEP_MITRALVALVE_FOR
<bup 1 7 5>
Now place the artificial valve in
its proper location.

@MSG_OPE211_STEP_ARTIFICIALVALVE
<bup 1 7 5>
The artificial valve has been set.
You may now suture it in place.

@MSG_OPE211_MISS_ARTIFICIALVALVE
<bup 1 7 5>
<vplay 7 41>
Please place the valve more closely.
We don't have much margin for error.

@MSG_OPE211_MISS_ARTIFICIALVALVE
<bup 1 7 3>
<vplay 7 43>
What are you doing!? Place it where
the patient's valve was removed!

@MSG_OPE211_STEP_MITRALVALVE_STI
<bup 1 7 1>
<vplay 7 45>
Good work.
You're getting better at suturing.
<wait>
The valve transplant is complete.
Let's finish up here.
<wait>

@MSG_OPE211_CAUTION_MAGNIFICATIO
<bup 1 7 1>
Is something wrong? You should be able
to suture the incision, now.

@MSG_OPE211_CAUTION_BLOOD
<bup 1 7 3>
<vplay 7 43>
Doctor! You have to drain the blood
before proceeding with treatment!

@MSG_OPE211_CLOSE_HEART
<bup 1 7 1>
*sigh* What a relief...
The operation was a success.
<wait>
Now she can play outside with
all of her friends.

@MSG_OPE211_CLOSE_BODY
<bup 1 7 1>
Please close the incision.

@MSG_OPE211_END_OPE
<bup 1 7 1>
Poor girl...she's too young to go through
something like this.
<wait>
...Having someone cut open your
chest is so unnatural.
<wait>
But something in that little heart
refused to give up...
<wait>
Maybe it sounds silly, but I keep
thinking about it.
<wait>
<vplay 7 9>
...The human body is truly amazing.
<wait>

@MSG_OPE211_CAUTION_REMAIN_BLOOD
<bup 1 7 1>
Let's drain that blood, first.
