
@MSG_OPE204_GAMEOVER
<bup 0 10 3>
You're done here, I'll have to finish it!
<wait>
<bup_cls>

@MSG_OPE204_START_OPE
<bup 1 7 5>
<vplay 7 3>
The antihypertensive is in effect,
but the aneurysm could still burst.
<wait>
We need to hurry, Dr. Stiles.

@MSG_OPE204_OPEN_BODY
<bup 1 7 5>
The area's disinfected.
Please make your incision.

@MSG_OPE204_ENTER_BODY
<bup 1 7 5>
<vplay 7 41>
The lump on that vessel is the aneurysm.
<wait>
Try magnifying that area. We're treating
an artery, so be careful.

@MSG_OPE204_CAUTION_MAGNIFICATIO
<bup 1 7 5>
...We can't see it from this angle.
Cancel magnification.

@MSG_OPE204_USE_MAGNIFICATION_EN
<bup 1 7 5>
<vplay 7 23>
Let's try to avoid a rupture.
Inject sedative into the aneurysm.

@MSG_OPE204_STEP_HEMATOMA_SYRING
<bup 1 7 5>
<vplay 7 28>
That should decrease the risk of it
rupturing. Now you can excise it.

@MSG_OPE204_CAUTION_HEMATOMA_EXP
<bup 1 7 3>
<vplay 7 43>
...The aneurysm has ruptured!
We need to stop the bleeding...
<wait>
First, drain the blood.

@MSG_OPE204_CAUTION_HEMATOMA_EXP
<bup 1 7 3>
<vplay 7 43>
...The aneurysm has ruptured! Change views
to find it so you can stop that bleeding!

@MSG_OPE204_CAUTION_HEMATOMA_EXP
<bup 1 7 3>
<vplay 7 43>
...The aneurysm has ruptured! Magnify the
area quickly so we can stop the bleeding!

@MSG_OPE204_CAUTION_HEMATOMA_EXP
<bup 1 7 3>
<vplay 7 43>
It's bleeding again! Drain the blood
so we can stop it.

@MSG_OPE204_STEP_EXPLOSIONBLOOD_
<bup 1 7 5>
<vplay 7 66>
The vessel area is clear.
Now, perform anastomosis.
<wait>
You'll need to manually connect
one side to the other.

@MSG_OPE204_STEP_HEMATOMA_DRAIN_
<bup 1 7 5>
<vplay 7 66>
Next, perform anastomosis. Use the
forceps to reconnect the vessel.

@MSG_OPE204_CAUTION_BLOOD_REPOP
<bup 1 7 3>
<vplay 7 43>
It's bleeding! We'll need to drain
the blood again.

@MSG_OPE204_CAUTION_EXIST_BLOOD
<bup 1 7 3>
<vplay 7 27>
No, that's dangerous! You need to drain
the blood first!

@MSG_OPE204_STEP_HEMATOMA_SCALPE
<bup 1 7 5>
<vplay 7 71>
Excision complete.
Now place it on the tray.

@MSG_OPE204_RETRY_SYRINGE
<bup 1 7 5>
<vplay 7 43>
The sedative's worn off.
Please inject more right away!

@MSG_OPE204_STEP_HEMATOMA_FORCEP
<bup 1 7 5>
<vplay 7 41>
We have to re-connect the vessels
that were cut, but...
<wait>
There's a lot of blood in the way.
Drain the blood, first.

@MSG_OPE204_FLOW_TURNING_POINT
<bup 1 7 5>
<vplay 7 28>
*sigh* This doesn't end...
Keep up the good work, Doctor.

@MSG_OPE204_STEP_VESSEL_FORCEPS_
<bup 1 7 5>
The vessel's connected. Now,
suture it quickly.

@MSG_OPE204_MISS_VESSEL_FORCEPS
<bup 1 7 3>
<vplay 7 27>
Doctor! You need to be more careful!

@MSG_OPE204_STEP_HEMATOMA_STITCH
<bup 1 7 2>
<vplay 7 29>
The aneurysm's been treated...
We can finally relax.
<wait>
Let's close him up, now.
Cease magnification.

@MSG_OPE204_1st_HEMATOMA_END_REM
<bup 1 7 5>
Let's drain that blood, first.

@MSG_OPE204_USE_MAGNIFICATION_RE
<bup 1 7 3>
<vplay 7 73>
What? Again...!?
<wait>
Every vessel in the area's in danger
of becoming an aneurysm!
<wait>
Continue the operation... We'll just
have to treat them all!

@MSG_OPE204_LASTWAVE_SPAWN_HEMAT
<bup 1 7 5>
<vplay 7 60>
Th-This isn't good...
Hurry up and treat it!

@MSG_OPE204_HINT_HEALING_TOUCH
<bup 1 7 3>
<vplay 7 70>
Wait, what about...
...if you use the Healing Touch...

@MSG_OPE204_CAUTION_DRAIN_notUSE
<bup 1 7 5>
<vplay 7 54>
We'll have to work up close on the vessels.
Magnify the area first.

@MSG_OPE204_CAUTION_SYRINGE_notU
<bup 1 7 5>
<vplay 7 54>
We'll have to work up close on the vessels.
Magnify the area first.

@MSG_OPE204_CAUTION_HEMATOMA_EXP
<bup 1 7 3>
<vplay 7 43>
An arterial aneurysm ruptured!
This is bad! Stop the bleeding!

@MSG_OPE204_CAUTION_HEMATOMA_EXP
<bup 1 7 3>
<vplay 7 43>
An arterial aneurysm has ruptured!
Please, be careful!

@MSG_OPE204_BEFORE_LASTWAVE
<bup 1 7 1>
Good work... I think it's settled
down, for the time being.
<wait>
We should wait a moment, to be safe,
before we close him up.

@MSG_OPE204_END_FLOW_NOTHING_LES
<bup 1 7 5>
Right at the last second...
Was that the Healing Touch?
<wait>
It's incredible, but...at the same time,
it's a little frightening.
<wait>
If every doctor had that ability, what would
the medical world be like...?
<wait>
Uh--I'm sorry...
Let's close him up.

@MSG_OPE204_END_FLOW_REMAIN_LESI
<bup 1 7 5>
Right at the last second...
Was that the Healing Touch?
<wait>
It's incredible, but...at the same time,
it's a little frightening.
<wait>
If every doctor had that ability, what would
the medical world be like...?
<wait>
Uh--I'm sorry...
Let's close him up.

@MSG_OPE204_END_FLOW_NO_HT_NOTHI
<bup 1 7 5>
The patient seems stable now...
This procedure is complete.
<wait>
Let's close him up, Doctor.

@MSG_OPE204_END_FLOW_NO_HT_REMAI
<bup 1 7 5>
The patient seems stable now...
This procedure is complete.
<wait>
Finish treating the area and we
can close him up.

@MSG_OPE204_CLOSE_BODY
<bup 1 7 5>
Now, just suture the incision.

@MSG_OPE204_END_OPE
<bup 1 7 5>
<vplay 7 9>
Another operation complete...
Great work, Dr. Stiles.
<wait>
