
@MSG_OPE206_GAMEOVER
<bup 0 10 3>
You can't handle this...
Get out of my way!
<wait>
<bup_cls>

@MSG_OPE206_START_OPE
<bup 1 7 3>
<vplay 7 4>
Blood pressure and vitals are dropping fast!

@MSG_OPE206_ENTER_BODY
<bup 1 7 3>
<vplay 7 47>
Wh-What? How could something
like this happen...?
<wait>
<bup 1 10 3>
But...there aren't any external wounds...
This isn't possible!
<wait>
...No, it doesn't matter what caused it; we
need to focus on stopping that bleeding!
<wait>
<bup 1 7 5>
Understood, Doctor.
Let's begin treating her.
<wait>
The large laceration needs attention
right away. Drain the blood, first.

@MSG_OPE206_STEP_GASH_1
<bup 1 7 5>
<vplay 7 41>
Th-These are awful...trying to suture them
would be far too dangerous...
<wait>
Try using forceps to close the wounds
before you start suturing.
<wait>
Pinch one side and pull it over to form
a thin slit.

@MSG_OPE206_STEP_GASH_2
<bup 1 7 5>
Pinch the larger wound with forceps
to form one thin slit...

@MSG_OPE206_RETRY_BLOOD_REPOP
<bup 1 7 3>
<vplay 7 43>
It hemorrhaged again! This won't stop
until we treat it at the source...

@MSG_OPE206_STEP_GASH_3
<bup 1 7 5>
That's it! Now suture it up before it has
a chance to reopen!

@MSG_OPE206_RETRY_GASH_OPEN
<bup 1 7 5>
If the wound reopens, close it again
and suture it immediately.

@MSG_OPE206_STEP_GASH_END
<bup 1 7 5>
<vplay 7 29>
*sigh* The bleeding's stopped...
Now treat the other areas.

@MSG_OPE206_REMAIN_GASH
<bup 1 7 5>
<vplay 7 41>
The small lacerations are taken care of,
but she's not in the clear yet...
<wait>
We need to move on to the large
lacerations immediately.

@MSG_OPE206_REMAIN_GASH_B
<bup 1 7 5>
Doctor, you should drain the blood
so we can treat those lacerations.

@MSG_OPE206_REMAIN_SLASH
<bup 1 7 5>
<vplay 7 41>
We're done treating those, I think...
<wait>
Move on to the smaller wounds.
Don't relax just yet!

@MSG_OPE206_CAUTION_BLOOD
<bup 1 7 3>
<vplay 7 24>
Doctor! We need to drain the blood so we
can confirm the wound...

@MSG_OPE206_END_FLOW
<bup 1 7 5>
Everything's been sutured...
She's... going to make it!
<wait>
I hate to think what would have happened
if she'd arrived later...

@MSG_OPE206_CLOSE_BODY
<bup 1 7 5>
Close up the patient, Doctor.

@MSG_OPE206_END_OPE
<bup 1 7 2>
<vplay 7 9>
The operation was a success.
Good work, Dr. Stiles.
<wait>
<bup 1 10 1>
You did well, Derek.
<wait>
<bup_cls>
