
@MSG_OPE209_GAMEOVER
<bup 0 10 3>
Move, Derek!
I'll try to patch this up...
<wait>
<bup_cls>

@MSG_OPE209_START_OPE
<bup 1 7 4>
...Why now?
She said she wanted to live...!
<wait>
<bup 1 10 5>
I don't know...and these symptoms don't
add up...
<wait>
Derek, take extra care during
this operation.
<wait>
Angie, keep your eyes on the monitors.
<wait>
<bup 1 7 5>
<vplay 7 3>
...Good luck, everyone.

@MSG_OPE209_ENTER_BODY
<bup 1 10 3>
......!
<wait>
<bup 1 7 3>
But... how!?
We fixed these three days ago!
<wait>
<bup 1 10 5>
Derek, Miss Reid is still weak from
her first lobectomy...
<wait>
Use the same treatment,
but BE CAREFUL!

@MSG_OPE209_CAUTION_BLOOD
<bup 1 7 5>
Doctor! We need to drain this blood so we
can get visuals of her wounds.

@MSG_OPE209_TREATMENT_LESION_1
<bup 1 7 5>
<vplay 7 55>
Treatment is progressing well.
Please continue...

@MSG_OPE209_TREATMENT_LESION_2
<bup 1 10 5>
This is strange... We still don't have any
idea why this happened.

@MSG_OPE209_STEP_AllLESION_END
<bup 1 7 5>
...We've treated the lacerations.
What's our next step?
<wait>
<bup 1 10 5>
We need to close her up and have
a closer examination later.
<wait>
Nice job, Derek. Suture the incision
and finish--

@MSG_OPE209_WHATS_HAPPEN
<bup 1 7 9>
<vplay 7 50>
What... is that!?
<wait>
<bup 1 10 3>
What the--
What the hell's going on!?
<wait>
<bup 1 7 3>
Doctor, try using ultrasound!

@MSG_OPE209_USE_ULTRASOUND_5TIME
<bup 1 10 3>
We have to look carefully...
Just stay calm, Derek.

@MSG_OPE209_USE_ULTRASOUND_10TIM
<bup 1 7 3>
<vplay 7 77>
There has to be something...
Look carefully, Doctor.

@MSG_OPE209_STEP_KYRIAKI_FINDSHA
<bup 1 7 5>
<vplay 7 51>
Did you see that!?
It was moving...

@MSG_OPE209_CAUTION_KYRIAKI_SHAD
<bup 1 10 3>
Derek, treat it like a tumor...
Excise and remove it right away!

@MSG_OPE209_STEP_1stKYRIAKI_SCAL
<bup 1 10 3>
What the hell...!?
I've never seen anything like this!
<wait>
<bup 1 7 3>
Doctor, we have to get it out
of the patient!
<wait>
What if we tried incinerating it
with the laser?
<wait>
<bup 1 10 3>
...Good idea, Angie... Be careful, we have
to kill that thing.

@MSG_OPE209_STEP_1stKYRIAKI_LASE
<bup 1 7 3>
I think it's working!
...If we keep this up...

@MSG_OPE209_CAUTION_KYRIAKI_ATTA
<bup 1 7 3>
<vplay 7 27>
Vitals dropping due to blood loss...
Suture the lacerations!

@MSG_OPE209_STEP_1stKYRIAKI_END
<bup 1 7 5>
...It's gone...
<wait>
<bup 1 10 5>
Angie, using the laser was the right
decision. Good thinking.
<wait>
It would've been a bad idea trying to
remove that thing alive.

@MSG_OPE209_STEP_2ndKYRIAKI_SPAW
<bup 1 10 3>
It can't be!
<wait>
<bup 1 7 5>
...More of them!?
<wait>
<bup 1 10 3>
Derek, you'll have to burn them all.
That's the only way to save her!

@MSG_OPE209_STEP_2ndKYRIAKI_ULTR
<bup 1 7 3>
Just like before...drag one out with
the scalpel, then laser it...!

@MSG_OPE209_STEP_2ndKYRIAKI_1KIL
<bup 1 7 3>
<vplay 7 76>
One down...! What are these things?

@MSG_OPE209_STEP_BOSSKYRIAKI_SPA
<bup 1 10 3>
Dammit...
We have to stop these things!

@MSG_OPE209_STEP_BOSSKYRIAKI_FAD
<bup 1 10 3>
It's hiding... You'll just have to find its
shadow and then cut it out.

@MSG_OPE209_STEP_BOSSKYRIAKI_KIL
<bup 1 10 5>
That should be the last one...

@MSG_OPE209_END_FLOW_NOTHING_LES
<bup 1 7 5>
We...did it...
<wait>
<bup 1 10 1>
...Let's close her up.
Derek, Angie, you both did well.

@MSG_OPE209_END_FLOW_REMAIN_LESI
<bup 1 7 5>
We...did it...
<wait>
<bup 1 10 1>
...Let's close her up.
Derek, Angie, you both did well.

@MSG_OPE209_CLOSE_BODY
<bup 1 10 5>
(...Don't tell me that weird parasite
was the one--)
<wait>
<bup 1 7 5>
<vplay 7 74>
(Could it have been...GUILT!?)
<wait>
<bup 1 10 5>
......?
<wait>
<bup 1 1 5>
(...What's going on?
Why'd they both stop talking?)
<wait>
<bup 1 10 5>
Uh, Derek, continue...
Please suture the incision.

@MSG_OPE209_END_OPE
<bup 1 7 1>
<vplay 7 9>
Linda should finally be able to recover.
Thank you, Dr. Stiles.
<wait>
