
@MSG_OPE203_GAMEOVER

@MSG_OPE203_START_OPE
<bup 1 1 5>
Healing Touch... The power of Asclepius.
...I can do this...
<wait>
First, I'll recall the procedure...
I'm looking at the patient...
<wait>
Let's see... I think I tensed my
index finger...(Z Button)

@MSG_OPE203_KEEP_Z
<bup 1 1 5>
<vplay 1 11>
Right, what else did I do with my hands...
Tense up my other hand... (B Button)

@MSG_OPE203_CAUTION_Z_RELEASE
<bup 1 1 5>
<vplay 1 12>
No, that's not it! I'm too loose...
(Z Button)
<wait>
...I think I tensed my index finger...
(Z Button)

@MSG_OPE203_KEEP_B
<bup 1 1 5>
It's hard to concentrate when I'm so tense.
I know! Maybe if I draw a star in the air...

@MSG_OPE203_CAUTION_B_RELEASE
<bup 1 1 5>
No! Come on, Derek... Concentrate!
<wait>
Okay...so my hands were like this...
(B Button)

@MSG_OPE203_ACTIVE_HEALINGTOUCH_
<bup 1 1 3>
<vplay 1 13>
...Almost! I was so close I could feel it!
...Okay, try again.

@MSG_OPE203_ACTIVE_HEALINGTOUCH_
<bup 1 1 5>
My eyes are burning... I need to keep
at this, though...
<wait>
Okay, for real this time!
Concentrate... Concentrate...!

@MSG_OPE203_CAUTION_HEALINGTOUCH
<bup 1 1 5>
<vplay 1 12>
Dammit! I need to be quicker and
precise!

@MSG_OPE203_CAUTION_HEALINGTOUCH
<bup 1 1 5>
Dammit! I need to be quicker and
more precise!

@MSG_OPE203_ACTIVE_HEALINGTOUCH_
<bup 1 1 5>
<vplay 1 13>
Once more...! Healing Touch...
Here we go...!

@MSG_OPE203_ACTIVE_HEALINGTOUCH_
<bup 1 1 5>
<vplay 1 16>
*gasp*
...just a little more...

@MSG_OPE203_END_OPE
<bup 1 1 5>
......This is it! It's exactly like before!
<wait>
I have the Healing Touch!
<wait>
<bup 1 1 4>
Ugh...maybe I overdid it...
...gave myself a headache.
<wait>
