
@MSG_OPE201_GAMEOVER
<bup 0 10 3>
Out of the way, Derek!
...You can't handle this one!
<wait>
<bup_cls>

@MSG_OPE201_START_OPE
<bup 1 7 5>
<vplay 7 3>
These readings aren't good...
Treat the spleen right away.

@MSG_OPE201_OPEN_BODY
<bup 1 7 5>
The area has been disinfected.
Please make your incision.

@MSG_OPE201_ENTER_BODY
<bup 1 7 5>
<vplay 7 41>
The contrast medium is working well.
We've confirmed the problem area.
<wait>
The thrombi causing the vessel blockage
are originating here.
<wait>
Work carefully. Use the magnifying
tool to view the vessel area.

@MSG_OPE201_USE_MAGNIFICATION
<bup 1 7 5>
Magnification successful.
Please continue.
<wait>
<vplay 7 41>
We'll need to use ultrasound to locate
those thrombi...

@MSG_OPE201_STEP_THROMBUS_ULTRAS
<bup 1 7 5>
<vplay 7 64>
Stop the thrombus from moving.
I would recommend using forceps.

@MSG_OPE201_STEP_THROMBUS_FORCEP
<bup 1 7 5>
<vplay 7 66>
The thrombus has ceased its movement...
Make your incision there.

@MSG_OPE201_STEP_THROMBUS_SCALPE
<bup 1 7 5>
<vplay 7 67>
Drain the incised area in order to eject
the thrombus.

@MSG_OPE201_STEP_THROMBUS_DRAIN_
<bup 1 7 5>
Thrombus removal complete.
Please treat the area with gel.

@MSG_OPE201_STEP_THROMBUS_GEL_EN
<bup 1 7 5>
<vplay 7 56>
The incision has been treated.

@MSG_OPE201_FLOW_TURNING_POINT
<bup 1 7 5>
<vplay 7 55>
The thrombi seem to be diminishing,
and blood flow has improved.

@MSG_OPE201_CAUTION_THROMBUS_DAM
<bup 1 7 3>
<vplay 7 43>
...His vitals drop every time a thrombus
passes through the spleen!

@MSG_OPE201_STEP_AllTHROMBUS_END
<bup 1 7 5>
<vplay 7 43>
...!
<wait>
<bup 1 7 3>
The change in blood flow is causing
the suspended thrombi to move, too!
<wait>
Doctor, this is bad!

@MSG_OPE201_AUTOACTIVE_HEALINGTO
<bup 1 1 11>
<vplay 1 11>
Tch... Gotta' work fast...
Stay calm... Concentrate...!

@MSG_OPE201_AUTOACTIVE_HEALINGTO
<bup 1 1 11>
Everything's...slowing down...
I did it again!

@MSG_OPE201_END_FLOW_NOTHING_LES
<bup 1 7 5>
<vplay 7 69>
Doctor... What just--
<wait>
N-No thrombi detected...
Treatment is complete...

@MSG_OPE201_END_FLOW_REMAIN_LESI
<bup 1 7 5>
<vplay 7 69>
Doctor... What just--
<wait>
N-No thrombi detected...
Treatment is complete...
<wait>
Then, let's close up the patient.

@MSG_OPE201_CLOSE_BODY
<bup 1 7 5>
Suture the incision and the operation
will be complete.

@MSG_OPE201_END_OPE
<bup 1 7 5>
<vplay 7 9>
Amazing work, Dr. Stiles.
That was impressive.
<wait>
