
@MSG_OPE310_GAMEOVER
<bup 0 8 3>
Stop it, Doctor! He's not going to make it!
<wait>
<bup 0 19 1>
Our medical staff just arrived.
We'll take over from here!
<wait>
<bup_cls>

@MSG_OPE310_START_OPE
<bup 1 8 5>
<vplay 7 3>
We've never dealt with GUILT like this
before, so be careful...

@MSG_OPE310_ENTER_BODY
<bup 1 8 5>
<vplay 7 104>
What the...heck? A membrane, and...
...these look like thorns!
<wait>
<bup 1 19 1>
...What!?
Could they have known about...?
<wait>
<bup 1 8 5>
What is it, Dr. Miller?
<wait>
<bup 1 19 1>
...Stiles, I think that membrane is
responsible for the disease.
<wait>
Any organ covered by that membrane
will be slowly petrified...
<wait>
We need to detach it immediately.
Try using the forceps.

@MSG_OPE310_SELECT_SCALPEL
<bup 1 8 5>
<vplay 7 44>
Hold on... You won't be able to detach
it that way.
<wait>
Don't you see the thorns? They've
fastened the membrane to this organ.
<wait>
<bup 1 19 1>
...I think you're right.
<wait>
<bup 1 8 5>
If we can remove all three thorns on one
segment, excision may be possible.
<wait>
<bup 1 19 1>
That's quick thinking, Angie! You should
consider looking into Caduceus Europe.
<wait>
<bup 1 8 5>
...Anyway, try pulling the thorns out with
your forceps.

@MSG_OPE310_STEP_TETARTI_REMOVE_
<bup 1 8 5>
Okay, it's out...! Now, try removing thorns
from all three corners.
<wait>
That should allow us to excise a
triangular section.

@MSG_OPE310_STEP_TETARTI_REMOVE_
<bup 1 19 1>
She's right, Stiles! That would allow you
to move in with your forceps!

@MSG_OPE310_CAUTION_REVIVE_WEDGE
<bup 1 8 3>
<vplay 7 51>
...What? It re-formed!? I guess the thorns
regenerate over time.

@MSG_OPE310_CAUTION_REVIVE_WEDGE
<bup 1 8 3>
<vplay 7 51>
The thorns reappeared. You're going to have
to move more quickly, Dr. Stiles.

@MSG_OPE310_CAUTION_REVIVE_WEDGE
<bup 1 8 5>
The thorns re-formed. You need to remove
them again right away.

@MSG_OPE310_CAUTION_REMAIN_MEMBR
<bup 1 8 3>
<vplay 7 43>
The membrane is spreading again...
It will multiply if left alone!

@MSG_OPE310_CAUTION_EVAPORATE_WE
<bup 1 19 1>
What the...? Quickly, Stiles!
Drain it!

@MSG_OPE310_STEP_SMOKE_DRAIN_END
<bup 1 19 1>
No wonder the town was destroyed...
...It's highly contagious.

@MSG_OPE310_CAUTION_SMOKE_ESCAPE
<bup 1 19 1>
If we inhale that vapor, we'll all
be in danger. ...Careful, now!

@MSG_OPE310_CAUTION_SMOKE_MAKE_M
<bup 1 19 1>
If the vapor touches an organ, it begins
forming another membrane.

@MSG_OPE310_CAUTION_STARTING_OPE
<bup 1 8 5>
<vplay 7 52>
What's wrong, Doctor? We have to
remove the membrane!

@MSG_OPE310_STEP_MEMBRANE_REMOVE
<bup 1 8 3>
<vplay 7 50>
The membrane is spreading...
You can't just grab at it haphazardly.
<wait>
<bup 1 19 1>
I see... Those thorns are causing the GUILT
to spread...
<wait>
<bup 1 8 5>
Th-They are? How can you tell?
<wait>
<bup 1 19 1>
...A while ago, our country tried using similar
technology to fight cancerous tissue;
<wait>
shards which vibrate at high frequencies
to stabilize the cancer for easy removal.
<wait>
...It creates a hardened membrane exactly
like this one.
<wait>
This strain of GUILT seems to be modeled
after our treatment.
<wait>
Those thorns are releasing high frequency
waves to essentially petrify his organs.
<wait>
Dr. Stiles, we need to try removing them
all at once.
<wait>
...There has to be some pattern to it.
Keep an eye on the membrane.

@MSG_OPE310_STEP_MEMBRANE_REMOVE
<bup 1 8 3>
<vplay 7 30>
We've removed part of the membrane!
If we can keep this up...!

@MSG_OPE310_STEP_MEMBRANE_REMOVE
<bup 1 8 5>
It didn't multiply that time...
Keep it up, Dr. Stiles!

@MSG_OPE310_STEP_MEMBRANE_REMOVE
<bup 1 8 3>
<vplay 7 80>
Ugh, I don't think that's it.
The membrane multiplied again.

@MSG_OPE310_STEP_MEMBRANE_REMOVE
<bup 1 8 5>
<vplay 7 81>
Wait! I think they multiply when two
wedges are connected!

@MSG_OPE310_CAUTION_EXIST_BOSS
<bup 1 8 5>
<vplay 7 41>
That pulsing blue area is
making me uneasy...
<wait>
It's causing a serious decline
in his vitals.
<wait>
If possible, we should excise that blue
section of the membrane first.

@MSG_OPE310_STEP_MEMBRANE_REMOVE
<bup 1 8 5>
<vplay 7 55>
We're doing a good job...stay alert
until we're completely finished.

@MSG_OPE310_STEP_MEMBRANE_REMOVE
<bup 1 8 5>
I think you have it, Dr. Stiles!
Hang in there...

@MSG_OPE310_END_FLOW
<bup 1 8 5>
<vplay 7 32>
We did it! Chiral reaction is negative!
<wait>
<bup 1 19 1>
Amazing! You really can operate
successfully against GUILT!

@MSG_OPE310_CLOSE_BODY
<bup 1 8 5>
Sir... You said you were surprised
they knew about...something?
<wait>
<bup 1 19 1>
I'm afraid this GUILT...was derived from
one of my country's past sins.
<wait>
As I said earlier, we were trying to create
a treatment for cancer using
<wait>
high-frequency vibrations.
But...there were complications.
<wait>
Our treatment couldn't differentiate between
cancerous cells and healthy tissue, so it
<wait>
simply attacked them both.
<wait>
We wanted a way to help people, but we
found a way to kill them instead...
<wait>
And, apparently, Delphi found out about it.
...That's what I meant.
<wait>
Let's close up the patient.
Reuben should be fine, now.

@MSG_OPE310_MISS_MEMBRANE_DROP
<bup 1 19 1>
Don't drop the membrane, or it could
re-attach itself. Be careful!

@MSG_OPE310_END_OPE
<bup 1 8 5>
Impressive, Dr. Stiles. It seems that GUILT
is no match for you...
<wait>
I'd say you've more than earned your place
in Caduceus.
<vplay 7 9>
<wait>
