
@MSG_OPE304_GAMEOVER
<bup 0 14 1>
This is really bad! I'll take over from here,
Dr. Stiles!
<wait>
<bup 0 17 5>
Derek...
I'm not blaming you for this.
<wait>
But... I told you before.
<wait>
There are people who need doctors like me...
<wait>
...And...trying to give them hope
only increases their suffering!
<wait>
<bup_cls>

@MSG_OPE304_START_OPE
<bup 1 8 5>
<vplay 7 4>
This is really bad...
We need to hurry!

@MSG_OPE304_ENTER_BODY_1stOPE
<bup 1 8 5>
<vplay 7 41>
Those spots are tumors from the GUILT.
Burn them off with the laser.

@MSG_OPE304_TREATMENT_BIGSTAIN_H
<bup 1 8 5>
<vplay 7 55>
Continue with the tumors.
No complications yet...

@MSG_OPE304_TREATMENT_SMALLSTAIN
<bup 1 8 5>
<vplay 7 41>
That large tumor must be creating
the smaller ones! Attack it, first!

@MSG_OPE304_TREATMENT_STAIN_ALL
<bup 1 8 5>
Our data indicates the Deftera could appear
at any time...
<wait>
When the Deftera combine to form a
tumor, use the drain to remove them.
<wait>
That's the plan...
...Are you ready?
<wait>

@MSG_OPE304_STEP_DEFTERA_SPAWN
<bup 1 8 3>
<vplay 7 113>
There! Those are cells created by
this strain of GUILT--Deftera!

@MSG_OPE304_CAUTION_STAIN_MANY
<bup 1 8 3>
<vplay 7 43>
You shouldn't ignore those tumors.
Incinerate them right away.

@MSG_OPE304_CAUTION_DEFTERA_UNIT
<bup 1 8 5>
<vplay 7 43>
The Deftera have formed a tumor.
Drain the tissue quickly!

@MSG_OPE304_STEP_DEFTERA_DRAIN_1
<bup 1 8 5>
<vplay 7 30>
The Deftera's cell count is steadily
decreasing, as expected.

@MSG_OPE304_STEP_DEFTERA_DRAIN_2
<bup 1 8 5>
<vplay 7 30>
Continue the drainage...
We'll be able to excise it soon, I hope.

@MSG_OPE304_STEP_DEFTERA_DRAIN_3
<bup 1 8 5>
Chiral reaction is dropping!
It... stopped moving...?

@MSG_OPE304_STEP_DEFTERA_SCALPEL
<bup 1 8 3>
<vplay 7 72>
It's out of control! We have to remove it
as soon as possible!

@MSG_OPE304_CAUTION_DEFTERA_RAMP
<bup 1 8 3>
<vplay 7 18>
The Deftera solidified!
We should be able to excise it...

@MSG_OPE304_END_FLOW_1stOPE
<bup 1 8 5>
<vplay 7 45>
Excision complete! You've removed
the GUILT from her stomach.
<wait>
We'll move to the lungs, next.
First, finish treating these wounds.

@MSG_OPE304_END_1stOPE
<bup 1 8 2>
<vplay 7 98>
Y-You did it, Doctor!
<wait>
<bup 1 17 4>
Amy's going to be okay!
...It's a miracle...
<wait>

@MSG_OPE304_START_2ndOPE
<bup 1 8 5>
We'll move to the lungs, next.
We're counting on you, Dr. Stiles.
<wait>
<bup 1 17 4>
C'mon, Derek...!
Save my little sister!
<wait>
<bup 1 8 5>
<vplay 7 5>
Please perform a lobectomy.

@MSG_OPE304_ENTER_BODY_2ndOPE
<bup 1 8 3>
<vplay 7 113>
There are two pairs of Deftera!
Careful of those with like colors...

@MSG_OPE304_STEP_2ndDEFTERA_SCAL
<bup 1 8 3>
<vplay 7 43>
It's solidified... You should try excising it,
now.

@MSG_OPE304_STEP_2ndDEFTERA_FORC
<bup 1 8 5>
<vplay 7 31>
One set of Deftera has been removed.
...Please proceed with caution.

@MSG_OPE304_END_FLOW
<bup 1 8 5>
<vplay 7 32>
The GUILT has been eradicated!
<wait>
Chiral reaction is negative.
The operation was successful.
<wait>
<bup 1 8 2>
*sigh* Good work, Doctor. Treat the other
wounds and close her up.

@MSG_OPE304_CLOSE_BODY
<bup 1 17 4>
...Thanks, Derek...
...Thank you so much...
<wait>
You're a real doctor, dude...
...I respect that.

@MSG_OPE304_END_OPE
<bup 1 8 2>
Amy should have a smooth and painless
recovery...
<wait>
<bup 1 17 5>
Derek... I owe you, man.
...How can I ever repay you for all this?
<wait>
