
@MSG_OPE304_GAMEOVER

@MSG_OPE306_START_OPE
<bup 1 15 1>
<vplay 15 2>
Now, we can't afford to waste any time...
Let's do this!
<wait>
...I can't tell how it's been constructed
without opening the lid.
<wait>
Looks like there are 4 screws holding the lid
in place. Your scalpel should do the trick.
<wait>
Try using your scalpel to turn and remove
the screws.

@MSG_OPE306_STAGE1_SCREW_SCALPEL
<bup 1 15 1>
<vplay 15 17>
Tricky... they used counter-threaded screws
that unscrew clockwise. Keep that in mind.

@MSG_OPE306_STAGE1_SCREW_1UNSCRE
<bup 1 15 1>
<vplay 15 18>
That's one down... You know what to do.

@MSG_OPE306_STAGE1_SCREW_2UNSCRE
<bup 1 15 1>
<vplay 15 19>
Two more to go.

@MSG_OPE306_STAGE1_SCREW_3UNSCRE
<bup 1 15 1>
<vplay 15 20>
We're on the last one.

@MSG_OPE306_CLEAR_STAGE1
<bup 1 15 1>
<vplay 15 13>
So much for the screws... Help me
lift the cover. Be careful!

@MSG_OPE306_STAGE1_MISS_SCREW
<bup 1 15 3>
<vplay 15 15>
So we have a panel with blinking lights
and screws that won't turn...
<wait>
<bup 1 15 1>
Hrm... Oh, okay.
<wait>
These screws are all different--they unscrew
in different directions.
<wait>
If we try turning it in the wrong direction,
one of these lights turns on.
<wait>
I'm guessing that once all the lights are
activated, BOOM! We're history...
<wait>
Essentially, this panel is telling us how
many "misses" we're allowed.
<wait>
It looks like we only have room for
two more mistakes...
<wait>
I assume they built this in to frighten us,
so we'd be unable to defuse the bomb.
<wait>
We should prepare for the worst, but let's
concentrate on getting through this.

@MSG_OPE306_STAGE1_CAUTION_SCREW
<bup 1 15 1>
<vplay 15 16>
I think I see something in the lower right
corner, Derek...
<wait>
Can you magnify it so we can take
a closer look?

@MSG_OPE306_STAGE1_GET_SCREW_HIN
<bup 1 15 1>
<vplay 15 21>
What the...hell?
<wait>
Does this have anything to do with removing
those screws?

@MSG_OPE306_START_STAGE2
<bup 1 15 3>
<vplay 15 15>
Is this what I think it is!?
<wait>
<bup 1 2 5>
Huh? Can you recognize it?
<wait>
<bup 1 15 1>
Listen to me, Derek.
<wait>
These hexagonal panels can be destroyed
with your surgical laser.
<wait>
But, you CANNOT touch the panels
that are lit up.
<wait>
<bup 1 2 5>
But, uh... all the panels are lit up.
...aren't they?
<wait>
<bup 1 15 1>
If we can stabilize the voltage at a certain
level, it should be more clear to you.
<wait>
Luckily, I think we can do just that.
<wait>
<bup 1 2 5>
I'm impressed, Dr. Myers... You must have
learned a lot on the force.
<wait>
<bup 1 15 1>
Let's just say criminal investigators have
strange lunchroom conversations.
<wait>
If I remember correctly, it should be...
...here!

@MSG_OPE306_START_STAGE2_AFTER
<bup 1 15 1>
This is it; a voltage regulation device.
<wait>
By changing those plugs, you can adjust the
voltage. I'd suggest using your forceps.
<wait>
The line you're aiming for is right here.
<func5 364 235 270>

@MSG_OPE306_STAGE2_PLUG_GRIP
<func6 0>
<bup 1 15 1>
<vplay 15 22>
Grab a plug and pull it toward you.
It should slip right out...

@MSG_OPE306_STAGE2_PLUG_UNPLUG
<bup 1 15 1>
<vplay 15 23>
...then you just push it back in somewhere
else. It isn't complicated.

@MSG_OPE306_STAGE2_MISS_PLUG_REL
<bup 1 15 3>
<vplay 15 10>
Don't let go until the plug is pulled
all the way out!

@MSG_OPE306_STAGE2_MISS_PLUG_REL
<bup 1 15 3>
<vplay 15 11>
Don't let go of the plug until you've
pushed it all the way in!

@MSG_OPE306_STAGE2_PLUG_1TIME
<bup 1 15 1>
<vplay 15 12>
The voltage is different now.
<wait>
Let's continue swapping the plugs until we've
got it where we want it.

@MSG_OPE306_STAGE2_PLUG_3TIMES
<bup 1 15 1>
<vplay 15 24>
...This isn't going as smoothly as I'd hoped
it would.
<wait>
The change in voltage might be different
depending on where we insert the plugs.
<wait>

@MSG_OPE306_CLEAR_STAGE2
<bup 1 15 1>
<vplay 15 14>
There we go.
<wait>
Let's take another look at those panels,
now.

@MSG_OPE306_CLEAR_STAGE2_AFTER
<bup 1 15 1>
<vplay 15 26>
It's not perfect, but we should be able to
destroy those panels now.
<wait>
Are you ready?
<wait>
Use your laser to destroy the unlit panels.

@MSG_OPE306_CAUTION_LASER_SHOT_S
<bup 1 15 3>
<vplay 15 11>
What are you doing!? Do not let it touch
the panels that are still lit.

@MSG_OPE306_CAUTION_LASER_SHOT_N
<bup 1 15 3>
<vplay 15 11>
Pay attention, Derek! That panel was
already destroyed!

@MSG_OPE306_STAGE3_PANEL_DESTROY
<bup 1 15 1>
<vplay 15 12>
Whew... it worked. Now move on to the
other panels.

@MSG_OPE306_STAGE3_PANEL_DESTROY
<bup 1 15 1>
<vplay 15 14>
We're almost done--don't lose it now.

@MSG_OPE306_STAGE3_PANEL_DESTROY
<bup 1 15 1>
<vplay 15 27>
Once we destroy the panels, the regulation
core should be exposed.

@MSG_OPE306_STAGE3_PANEL_DESTROY
<bup 1 15 1>
We did it!
Here comes the regulation core.
<wait>
<bup 1 15 1>
Okay, this is basically the center
of the bomb.
<wait>
If we deactivate this,
the bomb is useless.
<wait>
Use your laser to destroy it.

@MSG_OPE306_STAGE3_CORE_DESTROY_
<bup 1 15 3>
...!?
<wait>
<vplay 15 29>
Aim for the regulation core and nothing else!
We're almost done, Derek!

@MSG_OPE306_END_OPE
<bup 1 15 1>
<vplay 15 4>
Phew... We should be safe now.
<wait>
Glad that's over... Talk about your bad
patients, huh? ...heh...
<wait>
