
@MSG_OPE302_GAMEOVER
<bup 0 13 10>
Stop the procedure! It seems your
skills were greatly exaggerated...
<wait>
<bup_cls>

@MSG_OPE302_START_OPE
<bup 1 8 5>
This is the same strain of GUILT that
Linda Reid at Hope Hospital contracted.
<wait>
<vplay 7 3>
Let's begin.

@MSG_OPE302_ENTER_BODY
<bup 1 8 5>
<vplay 7 41>
The Kyriaki are causing these lacerations...
Treat them first.

@MSG_OPE302_STEP_KYRIAKI_ULTRASO
<bup 1 8 3>
There it is!
Cut near the shadow to expose it.

@MSG_OPE302_STEP_KYRIAKI_SCALPEL
<bup 1 8 5>
Ugh... I can't stand that thing.
Use the laser!

@MSG_OPE302_TREATMENT_5LESION
<bup 1 8 5>
<vplay 7 28>
The laceration treatment is going well.
Nice work, Doctor.

@MSG_OPE302_STEP_KYRIAKI_SPAWN
<bup 1 8 3>
<vplay 7 113>
Here they come... Stay calm and use
the ultrasound.

@MSG_OPE302_CAUTION_6SLASH
<bup 1 8 3>
<vplay 7 27>
The patient's vitals are dropping!
You have to suture those wounds!

@MSG_OPE302_STEP_KYRIAKI_1KILLED
<bup 1 8 5>
<vplay 7 45>
One Kyriaki incinerated...
Keep up the good work.

@MSG_OPE302_STEP_KYRIAKI_3KILLED
<bup 1 8 3>
<vplay 7 76>
...That's the third one.
How many are there?

@MSG_OPE302_STEP_BOSSKYRIAKI_SPA
<bup 1 8 3>
<vplay 7 43>
Another laceration! It must be
the large Kyriaki, like before.

@MSG_OPE302_STEP_BOSSKYRIAKI_FAD
<bup 1 8 5>
Use the ultrasound to draw it out of hiding,
then burn it away.

@MSG_OPE302_CAUTION_ULTRASOUND
<bup 1 8 5>
<vplay 7 77>
It must be hiding... Use the ultrasound
to find it!

@MSG_OPE302_END_FLOW_NOTHING_LES
<bup 1 13 1>
Great work... It's over, Derek.
The Chiral reaction is negative.

@MSG_OPE302_END_FLOW_REMAIN_LESI
<bup 1 13 1>
Great work... It's over, Derek.
The Chiral reaction is negative.
<wait>
Let's treat those last few wounds and
close him up.

@MSG_OPE302_CLOSE_BODY
<bup 1 8 5>
...You were testing for chirality?
<wait>
<bup 1 13 1>
We were, Angie.
That's very observant of you.
<wait>
GUILT creates cells with
an unnatural chirality.
<wait>
Using the Chiron Test, we can detect
the specific wavelength they emit.
<wait>
So far, that's the only way to reliably
distinguish GUILT.
<wait>
Remind me to give you the Chiron Test
equipment, later.
<wait>
Sorry I wasted all that time, Derek.
Finish up by suturing the incision.

@MSG_OPE302_END_OPE
<bup 1 13 1>
Excellent work. I can see why my brother
recommended you.
<wait>
