
@MSG_OPE308_GAMEOVER
<bup 0 8 3>
No, close him up! We need to wait
for additional support!
<wait>
<bup_cls>

@MSG_OPE308_OPE_START
<bup 1 8 5>
Unfortunately, Doctor... There's a storm
up ahead...
<wait>
They're going to try to avoid turbulence as
much as possible...
<wait>
...but this is far from an ideal operating
environment.
<wait>
<vplay 7 3>
Try not to let the shaking of the plane
distract you, Dr. Stiles.

@MSG_OPE308_OPEN_BODY
<bup 1 8 5>
Respiratory failure is serious--we need
to finish this quickly.
<wait>
Try using the ultrasound to locate an ideal
draining area.

@MSG_OPE308_CAUTION_QUAKE_SIGN
<bup 1 8 5>
<vplay 7 78>
Ugh... It's turbulence...
I hope it settles down soon...

@MSG_OPE308_CAUTION_QUAKE_INC
<bup 1 8 3>
Eeeeeek!

@MSG_OPE308_CAUTION_QUAKE_STOP_N
<bup 1 8 5>
<vplay 7 24>
It stabilized...
<wait>
If the plane starts shaking again, it could
cause a lot of problems...
<wait>
...We might need to stop operating
temporarily until it lets up.

@MSG_OPE308_CAUTION_MAKE_SLASH
<bup 1 8 5>
<vplay 7 24>
It stabilized...
<wait>
We should probably stop operating when
the turbulence picks up...
<wait>
...Especially if you're using a scalpel...
That would be terrible.
<wait>
Make sure you suture any wounds that occur
during the turbulence.

@MSG_OPE308_CAUTION_MAKE_INFLAM
<bup 1 8 5>
<vplay 7 24>
It's settled down...
<wait>
We need to drain the area as soon as
any shaking starts...
<wait>
...See? The whole area's inflamed because
the fluids spread around.
<wait>
Treat it by injecting an anti-inflammatory.

@MSG_OPE308_CAUTION_MAKE_SLASHan
<bup 1 8 5>
I think it settled down...
<wait>
We need to drain the area as soon as any
shaking starts...
<wait>
...See? The whole area's inflamed because
the fluids spread around.
<wait>
Inject the anti-inflammatory and suture the
wounds that open up.

@MSG_OPE308_CAUTION_MAKE_INFLAM_
<bup 1 8 3>
The fluid is causing inflammations!
Inject an anti-inflammatory.

@MSG_OPE308_CAUTION_MAKE_SLASH_A
<bup 1 8 3>
<vplay 7 43>
Another wound...
You need to suture it!

@MSG_OPE308_CAUTION_MAKE_SLASHan
<bup 1 8 3>
<vplay 7 43>
This is difficult to handle. Please use
the injection and then suture it.

@MSG_OPE308_STEP_ORIFICE_ULTRASO
<bup 1 8 5>
This is a good area for drainage.
Make an incision across the shadow.

@MSG_OPE308_STEP_ORIFICE_SCALPEL
<bup 1 8 5>
<vplay 7 41>
There's a lot more fluid here than there
should be...!
<wait>
Drain it immediately, before we hit more
turbulence!

@MSG_OPE308_STEP_ORIFICE_DRAIN
<bup 1 8 5>
<vplay 7 56>
We've drained all we can from here.
Please make another incision...

@MSG_OPE308_TUNING_POINT
<bup 1 8 5>
<vplay 7 79>
Drainage is about half complete.
Please continue.

@MSG_OPE308_END_FLOW
<bup 1 8 5>
<vplay 7 114>
*sigh* Patient's breathing has stabilized.
<wait>
He should be okay, for now.
Let's finish up the treatment.

@MSG_OPE308_END_OPE
<bup 1 8 5>
*deep breath* I guess we did it.
Oh! They're applauding...
<wait>
<bup 1 8 3>
...Tch, don't let it go to your head,
Dr. Stiles.
<wait>
