
@MSG_OPE404_GAMEOVER
<bup 0 13 10>
Derek, Stop!
Dr. Clarks, take over for him!
<wait>
<bup 0 14 1>
Don't worry, Derek. I'll save him.
Just... try harder, next time.
<wait>
<bup_cls>

@MSG_OPE404_START_OPE
<bup 1 8 5>
Dr. Kasal called this your final test before
you can be proud to call yourself a doctor...
<wait>
<vplay 7 83>
...I want him to believe in you the same
way that I do.

@MSG_OPE404_OPEN_BODY
<bup 1 8 5>
<vplay 7 41>
The Tetarti has formed toxic diverticula
there, on the liver.
<wait>
When they reach maximum size,
those sacs release poison.
<wait>
You'll need to inject serum of the same
color as the diverticulum.

@MSG_OPE404_CAUTION_POISONJAR_EX
<bup 1 8 3>
<vplay 7 43>
It's releasing toxins into the body!
This is serious, Dr. Stiles!

@MSG_OPE404_CAUTION_POISON_STAY
<bup 1 8 5>
Doctor--you need to reduce the toxin
with antibiotic gel.

@MSG_OPE404_STEP_POISONJAR_SYRIN
<bup 1 8 5>
It's looking good. You should be able to
excise the diverticulum.

@MSG_OPE404_CAUTION_POISONJAR_RE
<bup 1 8 3>
<vplay 7 43>
It's active! You need to hurry!

@MSG_OPE404_MISS_SYRINGE_POISONJ
<bup 1 8 3>
<vplay 7 84>
That's the wrong serum, Doctor!
The color has to match, understand?

@MSG_OPE404_STEP_POISONJAR_SCALP
<bup 1 8 5>
Excision complete! Now you just need
to extract it.

@MSG_OPE404_STEP_POISONJAR_FORCE
<bup 1 8 5>
<vplay 7 45>
Good work, Doctor. Don't forget to treat
those wounds.

@MSG_OPE404_STEP_POISONJAR_GEL_E
<bup 1 8 5>
<vplay 7 57>
All diverticula have been removed.
<wait>
The GUILT should reveal itself in
order to reconstruct them.
<wait>
We're supposed to inject the serum
into all three of them, correct?
<wait>
You'll have to work quickly from there...
Get ready.

@MSG_OPE404_STEP_TRITI_SPAWN
<bup 1 8 5>
<vplay 7 113>
There they are! Those clusters are
the Tetarti!

@MSG_OPE404_STEP_TRITI_SYRINGE_1
<bup 1 8 5>
<vplay 7 30>
Good job. They're coming back, though.
Be careful...

@MSG_OPE404_CAUTION_PASS_TURN_1T
<bup 1 8 5>
Hmph... The GUILT only surface for short
periods of time.

@MSG_OPE404_CAUTION_PASS_TURN_2T
<bup 1 8 5>
There's not a lot of time to check which
color they are.

@MSG_OPE404_CAUTION_PASS_TURN_3T
<bup 1 8 5>
<vplay 7 43>
As soon as the GUILT surfaces,
inject the serum immediately.

@MSG_OPE404_STEP_TRITI_SYRINGE_1
<bup 1 8 5>
<vplay 7 37>
The GUILT stopped moving!
Continue with the others...

@MSG_OPE404_STEP_TRITI_SYRINGE_2
<bup 1 8 5>
<vplay 7 38>
That's two down...
...Just one left.

@MSG_OPE404_STEP_TRITI_SYRINGE_3
<bup 1 8 5>
<vplay 7 31>
It's working, Doctor! Chiral readings have
dropped considerably.

@MSG_OPE404_MISS_SYRINGE_TRITI
<bup 1 8 3>
<vplay 7 84>
Stop! Using the wrong serum will speed up
the formation of diverticula!

@MSG_OPE404_CAUTION_TIMEOUT
<bup 1 8 5>
Oh no, it escaped...

@MSG_OPE404_STEP_TRITI_RESPAWN
<bup 1 8 5>
<vplay 7 39>
They're on the move. You need to inject
all three at once.

@MSG_OPE404_STEP_TRITI_SYRINGE_2
<bup 1 8 5>
<vplay 7 46>
It's going well so far...
Continue with the injections.

@MSG_OPE404_STEP_TRITI_SYRINGE_3
<bup 1 8 5>
<vplay 7 30>
Chiral reaction is dropping steadily.
They should stop moving soon!

@MSG_OPE404_END_FLOW_NOTHING_LES
<bup 1 8 5>
<vplay 7 32>
All three Tetarti have disappeared.
We have negative Chiral reaction.
<wait>
<bup 1 8 1>
...Dr. Kasal will be proud.
Let's finish up here.

@MSG_OPE404_END_FLOW_REMAIN_LESI
<bup 1 8 5>
<vplay 7 32>
All 3 Tetarti have disappeared.
We have negative Chiral reaction.
<wait>
<bup 1 8 1>
Dr. Kasal will be proud, once
you finish treating him.

@MSG_OPE404_CLOSE_BODY
<bup 1 8 2>
I guess you finally repaid him for
everything he taught you at Hope...

@MSG_OPE404_END_OPE
<bup 1 14 1>
You've really improved, Dr. Stiles.
<wait>
The rookie surgeon who trembled before
Kyriaki is gone.
<wait>
I think Dr. Kasal will be proud to call you
his doctor.
<wait>
