
@MSG_OPE407_GAMEOVER
げーむーおーばーはないよ

@MSG_OPE407_START_OPE
<bup 1 8 1>
Use your forceps to move the pieces
so the outline is completely filled.

@MSG_OPE407_END_OPE
<bup 1 8 2>
You did it!
<wait>

@MSG_OPE407_CAUTION_PIECE_OUTofB
<bup 1 8 5>
<vplay 7 85>
You have to place the pieces inside
their bases.

@MSG_OPE407_CAUTION_PIECE_OVERLA
<bup 1 8 5>
<vplay 7 85>
No, they're not supposed to overlap.

@MSG_OPE407_TALK_AngieThompson01
<bup 1 8 9>
...You don't seem very good at puzzles.

@MSG_OPE407_TALK_TylerChase01
<bup 1 17 1>
Ready to grab some eats, Derek...?

@MSG_OPE407_TALK_TylerChase02
<bup 1 17 5>
Dude, are you still working on that?
Want me to just tell you the answer?

@MSG_OPE407_TALK_VictorNiguel01
<bup 1 16 1>
<vplay 16 24>
You can stop, I suppose.
Everyone else finished a long time ago.

@MSG_OPE407_ILLEGALCLEAR01
<bup 1 2 1>
*sigh* It's about time!
<wait>
<bup 1 8 5>
...This looks completely wrong.
<wait>
<bup 1 2 1>
Huh?
You really think so?
<wait>
<bup 1 16 1>
It's an easy puzzle, but you still have to use
your brain, Stiles.
<wait>
You have to arrange the pieces so they
match the example.

@MSG_OPE407_ILLEGALCLEAR02
<bup 1 2 1>
How's this look?
<wait>
<bup 1 8 5>
...Completely different from the example.
<wait>
<bup 1 16 1>
You can't just throw the pieces randomly
into the base.
<wait>
You have to arrange them so they at least
resemble the example!
