
@MSG_OPE409_GAMEOVER
げーむーおーばーはないよ

@MSG_OPE409_START_OPE
<bup 1 8 1>
This one's a lot bigger.
<wait>
Move the pieces with your forceps to
completely fill the base.

@MSG_OPE409_1stPUZZLE_END
<bup 1 2 1>
<vplay 1 18>
Aha! I got it.
<wait>
<bup 1 8 5>
<vplay 7 87>
There's another puzzle, Doctor.
<wait>
<bup 1 2 4>
......
<wait>
<bup 1 8 2>
Don't look so down.
Come on, let's try the next one.

@MSG_OPE409_END_OPE
<bup 1 8 1>
<vplay 7 9>
You did it, Doctor!
<wait>
...You don't look well.
Are you alright?
<wait>
<bup 1 2 2>
Ugh... I'll be okay...
<wait>

@MSG_OPE409_CAUTION_PIECE_OUTofB
<bup 1 8 5>
<vplay 7 85>
The pieces go inside the base.

@MSG_OPE409_CAUTION_PIECE_OVERLA
<bup 1 8 5>
<vplay 7 85>
You aren't supposed to overlap pieces.

@MSG_OPE409_TALK_AngieThompson01
<bup 1 8 5>
Doctor, would you like me to help?

@MSG_OPE409_TALK_AngieThompson02
<bup 1 8 2>
...Actually, that would really defeat
the purpose of this puzzle.

@MSG_OPE409_TALK_TylerChase01
<bup 1 17 1>
*laughs* You always have been bad
at these things, Stiles.

@MSG_OPE409_TALK_SidneyKasal01
<bup 1 13 1>
It looks like there are problems you can't
solve with the Healing Touch.

@MSG_OPE409_TALK_StephenClarks01
<bup 1 14 1>
Speed isn't everything, Derek.
You'll find the answer if you concentrate.

@MSG_OPE409_TALK_LeslieSears01
<bup 1 18 1>
Hm... I thought a nerdy guy like you
would like puzzles and things.

@MSG_OPE409_TALK_VictorNiguel01
<bup 1 16 1>
<vplay 16 24>
I can't believe it's taking you this long...
Very amusing.

@MSG_OPE409_ILLEGALCLEAR01
<bup 1 2 1>
I finally did it...
<wait>
<bup 1 8 5>
...This doesn't look very much like
the example.
<wait>
<bup 1 2 1>
Huh?
You're kidding.
<wait>
<bup 1 16 1>
It's not a hard puzzle, but you still need
to use your brain on it.
<wait>
Arrange the pieces so they match
the example.

@MSG_OPE409_ILLEGALCLEAR02
<bup 1 2 1>
How's this look?
<wait>
<bup 1 8 5>
That isn't what the example looks like,
Dr. Stiles.
<wait>
<bup 1 16 1>
Shoving the pieces into the base isn't
going to help me.
<wait>
I need you to make it so they match
the example, okay?
