
@MSG_OPE410_GAMEOVER
<bup 0 13 10>
Stop the procedure!
Derek, I said stop!
<wait>
<bup_cls>

@MSG_OPE410_START_OPE
<bup 1 8 5>
Remember what Dr. Kasal said--his body
won't survive much longer.
<wait>
This is our last chance...
We have to succeed.
<wait>
<bup 1 16 1>
I know you can do this, Derek.
...Don't let me down.
<wait>
<vplay 16 3>
Are you ready? We're going to crush
that bastard this time!

@MSG_OPE410_ENTER_BODY
<bup 1 16 1>
Do everything exactly like last time
until the core shows up...

@MSG_OPE410_MISS_SYRINGE
<bup 1 8 3>
<vplay 7 43>
Doctor! You need to inject it into
that hazy object, or it won't work.

@MSG_OPE410_STEP_HAZY_SYRINGE
<bup 1 16 1>
Looking good...
Continue.

@MSG_OPE410_STEP_CORE_SPAWN
<bup 1 16 1>
There! Use the new laser to destroy it!

@MSG_OPE410_STEP_CORE_LASER_END
<bup 1 16 1>
We did it!
<wait>
Ha ha ha! Take THAT you little punk!
<wait>
<bup 1 8 5>
...Something's...not right.
<wait>
If the core was destroyed, then why hasn't
the tissue receded?
<wait>
<bup 1 16 1>
...Uh oh...

@MSG_OPE410_STEP_CORE_REVIVE
<bup 1 16 1>
No! ...Not again!

@MSG_OPE410_STEP_COCORE_POP
<bup 1 16 1>
<vplay 16 15>
...It's behaving eratically.
We're in trouble, Derek!

@MSG_OPE410_STEP_COCORE_SLASH
<bup 1 16 1>
<vplay 16 32>
Quick! Use the laser to destroy
the smaller cores!

@MSG_OPE410_STEP_COCORE_SLASH_EN
<bup 1 8 5>
<vplay 7 81>
This must be an adaptable mutation...
<wait>
<bup 1 2 11>
What does that mean?
<wait>
<bup 1 16 1>
It's a mutation that lower life-forms
develop, if they're lucky...
<wait>
Some bacteria can alter their tissue
as protection against heat or cold...
<wait>
...They can adapt to pretty much any
extreme environmental condition.
<wait>
Adaptable mutation is all just theory,
though.
<wait>
...Until now, I guess.
<wait>
<bup 1 8 5>
Except this isn't a defensive mutation--it's
offensive!
<wait>
<bup 1 8 3>
Be careful, Doctor!

@MSG_OPE410_STEP_COCORE_TUMOR
<bup 1 16 1>
<vplay 16 35>
Where'd all these tumors come from!?
You have to do something, Derek!

@MSG_OPE410_STEP_COCORE_TUMOR_EN
<bup 1 16 1>
Dammit... What's going on?

@MSG_OPE410_STEP_COCORE_ROTATE
<bup 1 8 3>
<vplay 7 43>
His vitals are dropping fast...
We have to destroy those cores!

@MSG_OPE410_STEP_COCORE_ROTATE_E
<bup 1 8 5>
Wait... If the Pempti is reacting
this drastically, then...
<wait>
We must have it cornered!
<wait>
<bup 1 8 3>
The laser's working!
<wait>
<bup 1 16 1>
Keep pumping that laser into it while
defending against attack!

@MSG_OPE410_STEP_CORE_FLOAT
<bup 1 16 1>
<vplay 16 32>
...Here it comes, Derek.
Aim carefully!

@MSG_OPE410_STEP_CORE_TAKEN_DAMA
<bup 1 8 5>
<vplay 7 106>
It's working! Chiral readings are decreasing...

@MSG_OPE410_STEP_CORE_TAKEN_DAMA
<bup 1 16 1>
<vplay 16 13>
Ha ha! Take that!
...Keep it up, Derek!

@MSG_OPE410_CAUTION_TUMOR_DAMAGE
<bup 1 16 1>
<vplay 16 35>
If we ignore those tumors, they'll probably
start bleeding.

@MSG_OPE410_CAUTION_CORE_RAMPAGE
<bup 1 16 1>
Its attacks seem desperate...
So, we know it's in trouble.

@MSG_OPE410_STEP_CORE_DEAD
<bup 1 16 1>
...Is it over?

@MSG_OPE410_STEP_PASTE_LOST
<bup 1 8 5>
<vplay 7 31>
Let me check the Chiral reaction...

@MSG_OPE410_END_FLOW_NOTHING_LES
<bup 1 8 5>
<vplay 7 32>
Negative! It's completely gone.
We did it...!
<wait>
<bup 1 16 1>
<vplay 16 33>
*sigh* It's about damn time.
Let's close him up, Derek.

@MSG_OPE410_END_FLOW_REMAIN_LESI
<bup 1 8 5>
<vplay 7 32>
Negative! It's completely gone.
We did it...!
<wait>
<bup 1 16 1>
<vplay 16 33>
*sigh* It's about damn time.
Finish treating his wounds, Derek.

@MSG_OPE410_CLOSE_BODY
<bup 1 16 1>
<vplay 16 34>
How are his vitals?
<wait>
<bup 1 8 5>
...Barely within the limits, but they've
stabilized.
<wait>
<bup 1 16 1>
Hang in there, Mr. Secretary.
...We've won the war.

@MSG_OPE410_END_OPE
<bup 1 16 1>
Well... I'm going home to crash.
You guys should get some rest, too.
<wait>
You never know when the next patient
is gonna pop up.
<wait>
<bup 1 8 2>
<vplay 7 9>
We all did a great job...
<wait>
