
@MSG_OPE408_GAMEOVER
<bup 0 16 1>
Derek, leave the room! Dr. Clarks will be
relieving you.
<wait>
<bup 0 14 1>
Dr. Stiles! Go home and get some rest!
<wait>
<bup_cls>

@MSG_OPE408_START_OPE
<bup 1 16 1>
<vplay 16 2>
Perform the lobectomy.

@MSG_OPE408_ENTER_BODY
<bup 1 16 1>
<vplay 16 14>
Okay, we have the nanomachine ready
this time. Careful...
<wait>
Administer it slowly...we don't know how
the GUILT is going to react.

@MSG_OPE408_CAUTION_STARTING_OPE
<bup 1 16 1>
<vplay 16 6>
Is something wrong?
Inject the nanomachine.

@MSG_OPE408_STEP_1stSYRINGE_1TIM
<bup 1 16 1>
Okay, it's working...
Continue the injection.

@MSG_OPE408_STEP_1stSYRINGE_2TIM
<bup 1 16 1>
It looks like the Pempti is creating tumors.
Use the laser to remove 'em.

@MSG_OPE408_STEP_1stSYRINGE_3TIM
<bup 1 16 1>
<vplay 16 13>
Everything's going as planned.
We're doing well...
<wait>
Excise the Pempti at its minimum size,
along with a small sample of lung tissue.

@MSG_OPE408_STEP_CORE_SPAWN
<bup 1 16 1>
<vplay 16 30>
...What the hell!?
<wait>
Is that the Pempti core...?
Quick, use your laser!

@MSG_OPE408_STEP_CORE_LASER_END
<bup 1 16 1>
It's no longer active. Now we can excise it
without harming the--

@MSG_OPE408_STEP_CORE_REVIVEL
<bup 1 16 1>
What...!?

@MSG_OPE408_STEP_PASTE_REVIVE
<bup 1 16 1>
<vplay 16 28>
Damn!
It restored itself...
<wait>
That core Pempti has to be controlling
the rest of the cells.
<wait>
Agh... I screwed up, Derek.
I might have to apologize, later...
<wait>
But, give me one more chance.
I know I can figure this out!
<wait>
Use the nanomachine again.
Let's drag the core out...!

@MSG_OPE408_STEP_2ndSYRINGE
<bup 1 16 1>
It's looking good...

@MSG_OPE408_STEP_2ndCORE_SPAWN
<bup 1 16 1>
Doesn't this thing ever give up?
Use the laser, Derek!

@MSG_OPE408_STEP_2ndCORE_LASER_E
<bup 1 16 1>
It stopped moving...! Hurry, I think we can
remove the core!

@MSG_OPE408_STEP_PASTE_REVIVE_AG
<bup 1 16 1>
What are you waiting--? Dammit!
Now we have to start all over.

@MSG_OPE408_STEP_2ndCORE_FORCEPS
<bup 1 16 1>
<vplay 16 13>
Looking good, Derek. You're getting the hang
of this operation thing.

@MSG_OPE408_END_FLOW
<bup 1 16 1>
<vplay 16 31>
......!
<wait>
No...way...!
<wait>
Damn!
Try it again, Derek!
<wait>
<bup 1 13 10>
We have to abort the procedure.
<wait>
<bup 1 16 1>
<vplay 16 31>
No...Chief! I was almost--
<wait>
<bup 1 13 1>
His body can't handle any more!
You have to stop--this is an order.
<wait>
<bup 1 16 1>
...Damn...
Stitch him up, Derek...

@MSG_OPE408_CLOSE_BODY
<bup 1 13 1>
Please close the incision, Dr. Stiles.

@MSG_OPE408_END_OPE
<bup 1 16 1>
<vplay 16 5>
Argh... Dammit!
I can't believe this!
<wait>
