
@MSG_OPE406_GAMEOVER
<bup 0 16 1>
Tch...dammit! Get outta the way!
Where the hell is Dr. Clarks?
<wait>
<bup 0 14 1>
Let me handle this!
Dr. Stiles...go get some rest.
<wait>
<bup_cls>

@MSG_OPE406_START_OPE
<bup 1 16 1>
<vplay 16 2>
We don't have time to spare.
Perform a lobectomy.

@MSG_OPE406_CAUTION_STARTING_OPE
<bup 1 16 1>
<vplay 16 17>
Derek... You paying attention?
Hurry up with the lobectomy!

@MSG_OPE406_ENTER_BODY
<bup 1 16 1>
Surprised, Derek? Welcome to the Pempti
strain of GUILT.
<wait>
This gelatinous fluid is filling the
Secretary's left lung.
<wait>
Anyway, you're going to have to do exactly
what I tell you.
<wait>
Let's start by detaching it. Try cutting
that stuff with a scalpel.

@MSG_OPE406_CAUTION_SCALPEL_MORE
<bup 1 16 1>
<vplay 16 27>
What are you doing? Cut into it more deeply.
C'mon!

@MSG_OPE406_RETRY_SCALPEL
<bup 1 16 1>
Are you even listening?
Use the scalpel to cut it.

@MSG_OPE406_STEP_SCALPEL_END
<bup 1 16 1>
<vplay 16 19>
...So that didn't work.
On to plan B.
<wait>
How about the laser? Let's try incinerating
that bad boy.

@MSG_OPE406_CAUTION_LASER_MORE
<bup 1 16 1>
<vplay 16 26>
That's no good. Aim for one spot
and keep it there.

@MSG_OPE406_RETRY_LASER
<bup 1 16 1>
Maybe you're not getting this: use the laser
until I say stop.

@MSG_OPE406_STEP_LASER_END
<bup 1 16 1>
<vplay 16 20>
...That didn't work either?
Huh... On to plan C, I guess.
<wait>
Time for the antibiotic gel.
I tweaked the formula a bit...

@MSG_OPE406_CAUTION_GEL_MORE
<bup 1 16 1>
It'll take more than that.

@MSG_OPE406_RETRY_GEL
<bup 1 16 1>
What's wrong with you, Derek?
Use the antibiotic gel.

@MSG_OPE406_STEP_GEL_END
<bup 1 16 1>
Still no use!? ...Damn, this is starting
to annoy me.
<wait>
<vplay 16 21>
...This time we mean business.
I have one last trick up my sleeve.
<wait>
It's effective, but it's still being researched
and adjusted.
<wait>
It's not very good for the human body,
so...be extra careful.
<wait>
Start with the vial of blue liquid.
Hopefully everything goes as planned...

@MSG_OPE406_MISS_SYRINGE_1TIME
<bup 1 16 1>
<vplay 16 16>
Stop! Don't inject there!
<wait>
See that hazy object inside the fluid?
<wait>
That's the highest concentration
of Pempti cells...
<wait>
Inject the medicine there for maximum
results.

@MSG_OPE406_MISS_SYRINGE_2TIMES
<bup 1 16 1>
Aim for that hazy object!
Be careful, it's moving.

@MSG_OPE406_MISS_SYRINGE_3TIMES
<bup 1 16 1>
<vplay 16 8>
What're you doing!?
You suck at this!

@MSG_OPE406_MISS_SYRINGE_4TIMES
<bup 1 16 1>
<vplay 16 8>
Weren't you listening!?
That's poisonous to human tissue!

@MSG_OPE406_RETRY_SYRINGE_BLUE
<bup 1 16 1>
Pay attention: Inject medicine from
the blue vial.

@MSG_OPE406_STEP_SYRINGE_BLUE_EN
<bup 1 16 1>
<vplay 16 12>
Hm... It's reacting, but there's not much
of an effect.
<wait>
Try the pink medicine instead.

@MSG_OPE406_RETRY_SYRINGE_PINK
<bup 1 16 1>
The pink vial, Derek.
That'd be the light-red one.

@MSG_OPE406_STEP_SYRINGE_PINK_EN
<bup 1 16 1>
<vplay 16 12>
Hmph...still no good.
<wait>
If those didn't work, then I'm afraid
the medicine is ineffective.
<wait>
We'll just have to devote this procedure
to collecting data.
<wait>
I'm worried about Anderson's condition.
We should finish this up.
<wait>
Let's find out how it reacts to the yellow
medicine.

@MSG_OPE406_RETRY_SYRINGE_YELLOW
<bup 1 16 1>
Maybe I wasn't clear...
Inject the solution in the yellow vial.

@MSG_OPE406_STEP_SYRINGE_YELLOW_
<bup 1 16 1>
<vplay 16 30>
What the...!?
This is bad!
<wait>
The white medicine is a neutralizer!
Use it, now!

@MSG_OPE406_CAUTION_SYRINGE_WHIT
<bup 1 16 1>
Uh... I wasn't joking!
Use the white medicine!

@MSG_OPE406_CAUTION_SYRINGE_WHIT
<bup 1 16 1>
His vitals are dropping...
We need that neutralizer, fast!

@MSG_OPE406_STEP_SYRINGE_WHITE_E
<bup 1 16 1>
<vplay 16 22>
*sigh* He's okay...
Let's keep gathering data.
<wait>
Let's get his vitals back up, first.
You need to be more careful.

@MSG_OPE406_STEP_SYRINGE_WHITE_E
<bup 1 16 1>
<vplay 16 22>
*sigh* He's okay...
Let's keep gathering data.
<wait>
What if we mix an increased dosage?
Alternate between blue and yellow.

@MSG_OPE406_CAUTION_VITALRECOVER
<bup 1 16 1>
<vplay 16 9>
What are you waiting for? His vitals
aren't going to recover themselves.

@MSG_OPE406_MISS_VITALRECOVER
<bup 1 16 1>
<vplay 16 16>
You have to inject it into his body!
...We don't want to just make things worse.

@MSG_OPE406_STEP_SECRET_VITALREC
<bup 1 16 1>
<vplay 16 12>
That should do it.
<wait>
What if we mix an increased dosage?
Alternate between blue and yellow.

@MSG_OPE406_CAUTION_SYRINGE_BLUE
<bup 1 16 1>
<vplay 16 11>
Too slow! It won't have any effect unless
you inject them much faster!
<wait>

@MSG_OPE406_CAUTION_SYRINGE_BLUE
<bup 1 16 1>
You need to be faster, Derek.
This isn't reflecting well on you.
<wait>

@MSG_OPE406_RETRY_SYRINGE_BLUEan
<bup 1 16 1>
Try it again. Inject the blue and yellow
medicines alternately.

@MSG_OPE406_STEP_SYRINGE_BLUEand
<bup 1 16 1>
This is useful data... Hey, you!
Can I get some gamma readings?
<wait>
This is our last step.
<wait>
You need to alternate between the
pink medicine and the neutralizer.

@MSG_OPE406_STEP_SYRINGE_BLUEand
<bup 1 16 1>
The yellow one's next!
Inject it quickly!

@MSG_OPE406_RETRY_SYRINGE_PINKan
<bup 1 16 1>
Keep trying. Alternate between the pink
and white medicines.

@MSG_OPE406_STEP_SYRINGE_PINKand
<bup 1 16 1>
The white vial's up next!
Pick up the pace!

@MSG_OPE406_STEP_SYRINGE_PINKand
<bup 1 16 1>
<vplay 16 23>
Hm... A triple-positive HC reaction.
<wait>
...Just as I expected.
That's all the data we need for now.
<wait>
He's getting weaker, so we need to hurry.
Quick, snag a sample.
<wait>
Excise a portion of the Pempti cells
so I can research it.

@MSG_OPE406_END_FLOW_GOOD
<bup 1 16 1>
<vplay 16 13>
You weren't bad. Let's close him up
and finish the operation.

@MSG_OPE406_END_FLOW_TIMEOUT
<bup 1 16 1>
<vplay 16 20>
He's getting weaker, so we need to hurry.
Quick, snag a sample.

@MSG_OPE406_END_FLOW_BAD
<bup 1 16 1>
I think you're done.
Go switch with Dr. Clarks.
<wait>

@MSG_OPE406_MISS_OUTofINSTRUCTIO
<bup 1 16 1>
<vplay 16 9>
What're you doing!?
You do what I say, remember?
<wait>

@MSG_OPE406_MISS_OUTofINSTRUCTIO
<bup 1 16 1>
<vplay 16 9>
You're supposed to be listening to my orders.
<wait>

@MSG_OPE406_END_OPE
<bup 1 16 1>
<vplay 16 4>
You did pretty well. There might be
some truth to those rumors...
<wait>
