
@MSG_OPE506_GAMEOVER2
<bup 0 16 1>
Whoa, Derek, that's bad.
Leave this one to Dr. Clarks.
<wait>
<bup_cls>

@MSG_OPE506_START_OPE
<bup 1 8 3>
<vplay 7 4>
If anything happens to her...
Delphi will answer for this!
<wait>
Hurry, Doctor...
There's no time to lose!

@MSG_OPE506_ENTER_BODY
<bup 1 8 5>
I see lacerations, but these seem different
from the Kyriaki...
<wait>
<bup 1 16 1>
We can't ignore these wounds...
Suture them up, Derek.

@MSG_OPE506_STEP_PARASKEVI_LASER
<bup 1 8 5>
It stopped moving...
<wait>
<bup 1 16 1>
<vplay 16 18>
Hm... Looks like I was right.
Listen carefully, okay?
<wait>
This GUILT is called Paraskevi,
and it's fibrous in nature.
<wait>
So...basically, every part of its mass
functions as a muscle.
<wait>
If we just extract the thing, there is going
to be massive bleeding.
<wait>
It even burrows into organs to cause
more damage elsewhere.
<wait>
My plan of attack is primitive, and maybe
even a little rough, but...
<wait>
Just keep cutting the thing until it's
really small. Then extract it.
<wait>
If you notice any of them start burrowing,
get rid of them right away!
<wait>
That's the plan, got it?
<bup 1 8 5>
...I guess it's our only choice...
<wait>
Did you understand him, Dr. Stiles?
Slice the GUILT with your scalpel!

@MSG_OPE506_STEP_PARASKEVI_1stSC
<bup 1 16 1>
<vplay 16 35>
Dammit... Cutting it makes more?
Uh, just keep cutting them!

@MSG_OPE506_STEP_PARASKEVI_2ndSC
<bup 1 16 1>
<vplay 16 36>
Not good enough! It's still too large
to extract...

@MSG_OPE506_STEP_PARASKEVI_3rdSC
<bup 1 16 1>
<vplay 16 37>
Keep cutting! One more time should do it!

@MSG_OPE506_STEP_PARASKEVI_4thSC
<bup 1 16 1>
<vplay 16 38>
That's small enough, Derek!
Stop it from moving and pull it out!

@MSG_OPE506_MISS_FORCEPS_PARASKE
<bup 1 8 5>
Hold on, Doctor...
First you have to make it stop moving!

@MSG_OPE506_MISS_FORCEPS_PARASKE
<bup 1 16 1>
<vplay 16 8>
What the hell are you doing!?
You have to cut it first!

@MSG_OPE506_MISS_FORCEPS_PARASKE
<bup 1 16 1>
<vplay 16 26>
You have to keep cutting it...
It's still too big to extract.

@MSG_OPE506_STEP_PARASKEVI_FORCE
<bup 1 8 5>
<vplay 7 30>
Good work! Now extract all the other
pieces, too.

@MSG_OPE506_END_FLOW_NOTHING_LES
<bup 1 8 5>
<vplay 7 32>
Paraskevi extraction complete!
Great job, Dr. Stiles!
<wait>
<bup 1 8 4>
I was so worried...
I think Cybil's safe, now.

@MSG_OPE506_END_FLOW_REMAIN_LESI
<bup 1 8 5>
<vplay 7 32>
Paraskevi extraction complete!
Great job, Dr. Stiles!
<wait>
<bup 1 8 4>
I was so worried...
I think Cybil's safe, now.
<wait>
<bup 1 16 1>
You should treat the remaining wounds
and finish the operation.

@MSG_OPE506_CLOSE_BODY
<bup 1 16 1>
<vplay 16 4>
Pretty good... Looks like we still have
an anesthesiologist.
<wait>
...I'm not sure we could have found
a replacement for her, anyway.
<wait>
<bup 1 8 3>
...A replacement? How can you talk
about her that way!?
<wait>
<bup 1 16 1>
Dr. Myers is one of our
most skilled doctors.
<wait>
I don't think anyone could have taken
her place at Caduceus.
<wait>
<bup 1 8 5>
......
<wait>
<bup 1 16 1>
I'm simply relieved that my colleague
is okay.

@MSG_OPE506_CAUTION_DIVING_PARAS
<bup 1 16 1>
<vplay 16 15>
No! Don't let it get into that organ!
Laser the bastard!

@MSG_OPE506_CAUTION_DIVING_PARAS
<bup 1 8 3>
<vplay 7 43>
Doctor, use your laser to prevent that
Paraskevi from entering the organ.

@MSG_OPE506_CAUTION_LOST_PARASKE
<bup 1 8 3>
<vplay 7 43>
Doctor...this is bad.
We've lost sight of the GUILT!

@MSG_OPE506_CAUTION_LOST_PARASKE
<bup 1 8 3>
<vplay 7 43>
Where's the GUILT!?
Hurry, Dr. Stiles...

@MSG_OPE506_CAUTION_LOST_PARASKE
<bup 1 16 1>
<vplay 16 8>
This could be our last chance...
We'll have to extract it.

@MSG_OPE506_TALK_1st_2ndSTAGE
<bup 1 8 3>
<vplay 7 112>
There are Chiral readings in her stomach!
Hurry, Doctor!

@MSG_OPE506_TALK_2nd_3rdSTAGE
<bup 1 8 3>
<vplay 7 19>
It's moved to the liver...
Hurry!

@MSG_OPE506_TALK_3rd_4thSTAGE
<bup 1 8 3>
<vplay 7 107>
It's nearing her heart...!

@MSG_OPE506_CAUTION_START_PARASK
<bup 1 8 3>
<vplay 7 113>
The Paraskevi emerged!
We need to extract them!

@MSG_OPE506_CAUTION_START_PARASK
<bup 1 16 1>
<vplay 16 39>
Concentrate, Derek...
We have to stop it here.

@MSG_OPE506_CAUTION_START_PARASK
<bup 1 16 1>
<vplay 16 40>
Dammit! Use your Healing Touch
or whatever it's called!

@MSG_OPE506_CAUTION_NEXTSTAGE_RE
<bup 1 16 1>
<vplay 16 6>
What's the holdup!? Suture the wounds
so we can follow it!

@MSG_OPE506_PARASKEVI_TURNING_PO
<bup 1 8 5>
<vplay 7 101>
We've removed about half of it.
Keep going, Doctor!

@MSG_OPE506_GAMEOVER
<bup 1 16 3>
Son of a--!
<wait>

@MSG_OPE506_STEP_PARASKEVI_SPAWN
<bup 1 8 3>
<vplay 7 113>
There it is...
That's a fibrous GUILT.

@MSG_OPE506_STEP_PARASKEVI_WEAKP
<bup 1 16 1>
Try the laser, Derek! It's gotta
have a weakness somewhere!

@MSG_OPE506_END_OPE
<bup 1 8 5>
That wasn't easy...
<wait>
<bup 1 8 1>
<vplay 7 9>
We did it, Dr. Stiles...
You handled things very well.
<wait>

@MSG_OPE506_CAUTION_LOST_PARASKE
<bup 1 8 3>
<vplay 7 43>
Doctor...this is bad.
We've lost sight of the GUILT!
<wait>
<bup 1 16 1>
What's the holdup!? Suture the wounds
so we can follow it!

@MSG_OPE506_CAUTION_LOST_PARASKE
<bup 1 8 3>
<vplay 7 43>
Where's the GUILT!?
Hurry, Dr. Stiles...
<wait>
<bup 1 16 1>
What's the holdup!? Suture the wounds
so we can follow it!

@MSG_OPE506_CAUTION_LOST_PARASKE
<bup 1 16 1>
<vplay 16 8>
This could be our last chance...
We'll have to extract it.
<wait>
<bup 1 16 1>
What's the holdup!? Suture the wounds
so we can follow it!
