
@MSG_OPE503a_GAMEOVER
<bup 0 14 1>
This is too dangerous!
Dr. Stiles, let me handle it!
<wait>
<bup_cls>

@MSG_OPE503a_START_OPE
<bup 1 8 5>
Doctor, remember to drain the
vaporized thorns this time.
<wait>
If the poison escapes...
...Well, just don't let that happen.
<wait>
<vplay 7 3>
Let's begin the operation.
Good luck!

@MSG_OPE503a_ENTER_BODY
<bup 1 8 5>
We should remove the membranes exactly
like last time.

@MSG_OPE503a_CAUTION_REMAIN_MEMB
<bup 1 8 3>
<vplay 7 24>
Be careful! If a membrane is isolated,
it will multiply!

@MSG_OPE503a_CAUTION_EVAPORATE_W
<bup 1 8 3>
<vplay 7 72>
It's vaporized!
You need to drain the toxin.

@MSG_OPE503a_CAUTION_SMOKE_MAKE_
<bup 1 8 3>
Be careful... That vapor can rebuild
the membranes!

@MSG_OPE503a_TREATMENT_TETARTI_H
<bup 1 8 5>
<vplay 7 55>
Excision is proceeding nicely.
Keep it up, we're almost done.

@MSG_OPE503a_STEP_MEMBRANE_FORCE
<bup 1 8 3>
Extract the thorns carefully!
Don't let the membranes multiply.

@MSG_OPE503a_END_FLOW
<bup 1 8 1>
<vplay 7 45>
The Triti has been removed.
You're really improving, Dr. Stiles!

@MSG_OPE503a_MISS_MEMBRANE_DROP
<bup 1 8 3>
<vplay 7 27>
Don't drop it, Doctor! The membrane will
attach to whatever it touches!

@MSG_OPE503a_END_OPE
<bup 1 8 1>
If that strain had spread, it would have been
a disaster...
<wait>
<bup 1 8 2>
<vplay 7 9>
I'm glad we were able to stop it.
<wait>

@MSG_OPE503a_NEXT_OPE
<bup 0 8 3>
<vplay 7 43>
The poison gas is spreading...
<wait>
<bup 0 10 3>
Out of the way, Derek!
...Leave this one to me.
<wait>
Move on to the next infected
patient, okay? Stay calm!
<wait>
<bup 0 8 5>
Understood!
<wait>
<bup_cls>
	
