
@MSG_OPE504_GAMEOVER
<bup 0 14 1>
Stop, it's too dangerous!
Dr. Stiles, stop!
<wait>
<bup_cls>

@MSG_OPE504_START_OPE
<bup 1 8 5>
Let's begin the Tetarti eradication.
<wait>
<vplay 7 3>
This GUILT seems to be stronger than
usual... Please be careful.

@MSG_OPE504_ENTER_BODY
<bup 1 8 5>
<vplay 7 41>
Toxic diverticula confirmed...
It's just like Dr. Kasal's operation!

@MSG_OPE504_CAUTION_POISONJAR_EX
<bup 1 8 3>
<vplay 7 43>
The poison is spreading!
Use antibiotic gel to stop it!

@MSG_OPE504_STEP_AllPOISONJAR_EN
<bup 1 8 5>
<vplay 7 29>
The poisonous sacs have been excised!
The Tetarti should appear soon.

@MSG_OPE504_STEP_TRITI_SPAWN
<bup 1 8 5>
<vplay 7 113>
There's the Tetarti! Inject all three
of them with the serum at once!

@MSG_OPE504_STEP_TRITI_1stWAVE_E
<bup 1 8 5>
<vplay 7 30>
Well done!
Chiral reaction is dropping.

@MSG_OPE504_STEP_TRITI_3rdWAVE_E
<bup 1 8 5>
This doesn't seem to be effective...
Did the GUILT develop a tolerance?

@MSG_OPE504_END_FLOW_NOTHING_LES
<bup 1 8 5>
<vplay 7 32>
The Tetarti is gone!
*sigh*...That was tough.

@MSG_OPE504_END_FLOW_REMAIN_LESI
<bup 1 8 5>
<vplay 7 32>
The Tetarti is gone!
*sigh*...That was tough.
<wait>
Well, let's treat the remaining wounds
and finish up.

@MSG_OPE504_END_OPE
<bup 1 8 5>
It looks like Caduceus has the terrorist
attack under control.
<wait>
<vplay 7 9>
Great job, Dr. Stiles.
Let's return to headquarters.
<wait>
