
@MSG_OPE509_GAMEOVER
<bup 0 8 4>
D... Dad...?
What are you doing, Derek!?
<wait>
<bup_cls>

@MSG_OPE509_START_OPE
<bup 1 8 5>
Judging by the data we found, this strain
is called Savato.
<wait>
...It's most likely the final type
of GUILT.
<wait>
<vplay 7 3>
Let's get started.

@MSG_OPE509_ENTER_BODY
<bup 1 8 3>
<vplay 7 104>
This is Savato. ...How could my father
create such a thing?
<wait>
Doctor! Attack the center one--it's
causing most of these problems!

@MSG_OPE509_CAUTION_ATTACK_SAVAT
<bup 1 8 3>
<vplay 7 50>
Wh-What the...!?

@MSG_OPE509_CAUTION_ATTACK_SAVAT
<bup 1 8 3>
<vplay 7 105>
This isn't working!
It can dodge all of our attacks!

@MSG_OPE509_SELECT_SCALPEL
<bup 1 8 5>
<vplay 7 43>
...!
<wait>
We just received Dr. Niguel's analysis.
Let me read it...
<wait>
"Essentially, the Savato's 'nest' directly
nullifies the victim's heartbeat."
<wait>
"It steals that pulse to create energy for
its own purposes."
<wait>
"So, basically... Savato is a parasitic form
of death itself."
<wait>
"At the moment, I can't think of any way
to actually stop it."
<wait>
<bup 1 2 11>
...There's no way to stop it?
<wait>
<bup 1 8 5>
"But, we might have one possible
countermeasure..."
<wait>
"The GUILT depends on energy from
its nest, so if we destroy that..."
<wait>
<bup 1 8 3>
Doctor, destroy the nest!
That could be our only chance!

@MSG_OPE509_STEP_NEST_SCALPEL_1T
<bup 1 8 3>
<vplay 7 98>
Yes, it worked! ...Wait, what happened to
the scalpel you were using?
<wait>
<bup 1 2 11>
I don't know...when it touched that thread,
it started melting...
<wait>
I brought spares, though. Grab some from
our supply box.
<wait>
<bup 1 8 5>
We'll just have to deal with it, I guess.
Keep cutting, Doctor.

@MSG_OPE509_STEP_NEST_SCALPEL_2T
<bup 1 8 5>
The Savato started to move.
...What's it doing?

@MSG_OPE509_CAUTION_NEST_DAMAGE
<bup 1 8 3>
<vplay 7 22>
Vitals are dropping fast!
Don't let the web turn red!

@MSG_OPE509_STEP_NEST_REPAIR
<bup 1 8 3>
<vplay 7 51>
...The web! And, there's smaller
GUILT bodies everywhere!

@MSG_OPE509_STEP_NEST_SCALPEL_3T
<bup 1 8 5>
<vplay 7 108>
The third one has been cut. What happens
if we cut them all...?

@MSG_OPE509_NEST_RENEW_1TIME
<bup 1 8 3>
...What!? The Savato escaped!
<wait>
<bup 1 8 5>
We have to go after it!

@MSG_OPE509_NEST_RENEW_1TIME_AFT
<vplay 7 112>
Don't give up, Doctor!

@MSG_OPE509_NEST_RENEW_1TIME_REM
<bup 1 8 9>
...What!? The Savato escaped!
<wait>
We have to treat these smaller bodies
and then go after it!

@MSG_OPE509_NEST_RENEW_1TIME_REM
<bup 1 8 5>
<vplay 7 112>
We have to find the Savato!

@MSG_OPE509_NEST_RENEW_1TIME_REM
<bup 1 8 3>
Don't give up, Doctor!

@MSG_OPE509_NEST_RENEW_2TIMES
<bup 1 8 5>
Again!?
<wait>
Doctor, we have to catch it!

@MSG_OPE509_NEST_RENEW_2TIMES_AF
<bup 1 8 5>
There's a shift in the Chiral readings.
Don't stop now!

@MSG_OPE509_NEST_RENEW_2TIMES_RE
<bup 1 8 5>
Again!?
<wait>
Exterminate the smaller bodies so we
can pursue the main GUILT.

@MSG_OPE509_NEST_RENEW_2TIMES_RE
<bup 1 8 5>
It's over here, Doctor!

@MSG_OPE509_NEST_RENEW_2TIMES_RE
<bup 1 8 5>
There's a shift in the Chiral readings.
Don't stop now!

@MSG_OPE509_CLEAR_1stSTAGE_REMAI
<bup 1 8 5>
You destroyed the Savato's nest.
I think that did it...
<wait>
<vplay 7 50>
...Oh no... It's absorbing the smaller GUILT
bodies into itself!

@MSG_OPE509_CLEAR_1stSTAGE_NOTHI
<bup 1 8 5>
You destroyed the Savato's nest.
I think that did it...

@MSG_OPE509_START_2ndSTAGE
<bup 1 8 3>
<vplay 7 41>
...It's another report from Victor!
<wait>
"If the nest is destroyed, it can't continue
absorbing energy from the heart."
<wait>
"That should allow you to neutralize its
corrosive protective layer."

@MSG_OPE509_STEP_SAVATO_LASER
<bup 1 8 5>
<vplay 7 106>
I think it's working...
The coating is getting thinner!

@MSG_OPE509_CAUTION_LASER_MORE
<bup 1 8 5>
<vplay 7 43>
Doctor! You have to keep burning it
for there to be an effect!

@MSG_OPE509_STEP_SAVATO_LASER_EN
<bup 1 8 5>
<vplay 7 109>
We got through... Now's our chance to attack
Savato directly.

@MSG_OPE509_CAUTION_LASER_SAVATO
<bup 1 8 5>
<vplay 7 109>
The laser isn't working...
What could that mean?

@MSG_OPE509_CAUTION_MAKE_SLASH
<bup 1 8 3>
Suture the lacerations before they can do
any more damage!

@MSG_OPE509_1DAMEGE_SAVATO_NOTHI
<bup 1 8 5>
<vplay 7 30>
Chiral reaction is decreasing...
It's in your hands, Dr. Stiles.

@MSG_OPE509_1DAMEGE_SAVATO_NOTHI
<bup 1 8 5>
Keep going, Doctor! You have to kill it!

@MSG_OPE509_1DAMEGE_SAVATO_REMAI
<bup 1 8 5>
<vplay 7 30>
Chiral reaction is decreasing...
It's in your hands, Dr. Stiles.
<wait>
We have to finish things up here and
go after it!

@MSG_OPE509_1DAMEGE_SAVATO_REMAI
<bup 1 8 5>
Okay, we're done here!
Now searching for the GUILT's location...

@MSG_OPE509_1DAMEGE_SAVATO_REMAI
<bup 1 8 5>
There it is, Doctor!
Treat the Savato exactly like before.

@MSG_OPE509_2DAMEGE_SAVATO_NOTHI
<bup 1 16 1>
<vplay 16 41>
Looks like it's working...
Pretty good, Derek.
<wait>
<bup 1 8 3>
Victor...!? Chief?
When did you get here?
<wait>
<bup 1 16 1>
We rushed over to give you this...
<wait>
<bup 1 13 1>
It's medicine for Savato.
<wait>
The researcher you saved helped us design
a serum that should stop this thing.
<wait>
<bup 1 16 1>
He collapsed right after that, but hey,
we got what we wanted.
<wait>
I guarantee this'll work, though.
Inject it into the GUILT.
<wait>

@MSG_OPE509_2DAMEGE_SAVATO_NOTHI
<bup 1 8 5>
I'll get this ready so you can use it
as soon as you get the chance.

@MSG_OPE509_2DAMEGE_SAVATO_REMAI
<bup 1 16 1>
<vplay 16 41>
Looks like it's working...
Pretty good, Derek.
<wait>
<bup 1 8 3>
...!? Chief?
When did you get here?
<wait>
<bup 1 16 1>
We rushed over to give you this...
<wait>
<bup 1 13 1>
It's medicine for Savato.
<wait>
The researcher you saved helped us design
a serum that should stop this thing.
<wait>
<bup 1 16 1>
He collapsed right after that, but hey,
we got what we wanted.
<wait>
I guarantee this'll work, though.
Inject it into the GUILT.
<wait>
<bup 1 8 5>
We need to wrap this up so we can
figure out where the Savato went.

@MSG_OPE509_2DAMEGE_SAVATO_REMAI
<bup 1 8 5>
Chiral reaction found! It's over here!

@MSG_OPE509_2DAMEGE_SAVATO_REMAI
<bup 1 8 5>
Inject the serum into the GUILT
to defeat it... Hurry!

@MSG_OPE509_CAUTION_SAVATO_AVOID
<bup 1 16 1>
Hmph... That's no good.
Make it suffer a little more.

@MSG_OPE509_CAUTION_SAVATO_SYRIN
<bup 1 8 5>
<vplay 7 110>
Chiral reaction is low...
Finish it off with the injection!

@MSG_OPE509_SAVATO_RAMPAGE
<bup 1 8 3>
No...!

@MSG_OPE509_AUTOACTIVE_HEALINGTO
<bup 1 2 11>
<vplay 1 20>
Dammit... You're not getting away.
Professor Blackwell's going to live!

@MSG_OPE509_USE_SYRINGE_HEALINGT
<bup 1 8 3>
Even the Healing Touch isn't working...
What am I going to do!?

@MSG_OPE509_HINT_HEALINGTOUCH_DO
<bup 1 2 11>
<vplay 1 19>
(C'mon, concentrate... ...I can do this!)

@MSG_OPE509_USE_HEALINGTOUCH_DOU
<bup 1 2 11>
<vplay 1 21>
I won't let Angie down!

@MSG_OPE509_STEP_SAVATO_END
<bup 1 2 10>
<vplay 1 22>
No disease is incurable...
I'll never accept that!

@MSG_OPE509_END_FLOW
<bup 1 8 3>
<vplay 7 32>
Chiral reaction has disappeared!
<wait>
<bup 1 8 4>
D-Dad...
...We did it...
<wait>
Dr. Stiles saved you...

@MSG_OPE509_CLOSE_BODY
<bup 1 8 4>
<vplay 7 111>
Thank you, Derek...
Thank you so much...

@MSG_OPE509_END_OPE
<bup 1 13 1>
It looks like we finally won the war
against GUILT. It's over.
<wait>
<bup 1 16 1>
It took you long enough, Stiles...
But, you earned that Healing Touch.
<wait>
<bup 1 8 5>
...I'm proud to be your assistant...
<wait>
<bup 1 8 2>
<vplay 7 15>
And... I'm proud of you, Dr. Stiles.
<wait>
