
@MSG_OPE508_GAMEOVER
<bup 0 8 3>
Stop, Dr. Stiles! We'd be better off
transferring him to Caduceus!
<wait>
<bup_cls>

@MSG_OPE508_START_OPE
<bup 1 8 5>
He said something about
saving my father...
<wait>
I don't understand...
Isn't my father a terrorist?
<wait>
<vplay 7 102>
Let's begin, Doctor...
I want to find out what he meant.

@MSG_OPE508_ENTER_BODY
<bup 1 8 5>
<vplay 7 41>
Be careful, Dr. Stiles--anything
could happen...

@MSG_OPE508_1ST_WAVE_START
<bup 1 8 3>
<vplay 7 104>
What the...? It's GUILT!
Why would he be infected?

@MSG_OPE508_GUILTH_DEAD
<bup 1 8 5>
<vplay 7 106>
The laser seems to be working...
Keep incinerating them!

@MSG_OPE508_1ST_WAVE_END
<bup 1 8 5>
It isn't over...
The Chiral readings are still too high.

@MSG_OPE508_2ND_WAVE_START
<bup 1 8 3>
Ugh! It's back...
I don't feel so well.

@MSG_OPE508_3RD_WAVE_START
<bup 1 8 3>
<vplay 7 76>
How many are there!? I have a bad
feeling about this, Doctor...

@MSG_OPE508_CALL_OF_THE_CURSE
<bup 1 8 5>
They're gathering together...
What's going on?

@MSG_OPE508_CURSE_SPWAN
<bup 1 8 3>
<vplay 7 22>
His... His vitals are dropping fast!
This shouldn't be happening!
<wait>
Wha... Everything's dropping!
His condition is entirely deteriorated!
<wait>
Is that blue GUILT causing it?
Doctor, kill that one first!

@MSG_OPE508_CURSE_DEAD
<bup 1 8 5>
St-Stabilizing... Don't forget to
raise his vitals, Doctor.

@MSG_OPE508_CURSE_SPWAN_AGAIN
<bup 1 8 3>
<vplay 7 43>
What? Again!? Dr. Stiles--we have
to get rid of that blue GUILT!

@MSG_OPE508_ANGE_SELFTALK
<bup 1 8 5>
...It literally sucked the life
right out of him...

@MSG_OPE508_END_FLOW_NOTHING_LES
<bup 1 8 5>
<vplay 7 32>
Chiral reaction is negative...
He should be safe now.
<wait>

@MSG_OPE508_END_FLOW_REMAIN_LESI
<bup 1 8 5>
<vplay 7 32>
Chiral reaction is negative...
He should be safe now.
<wait>
Just treat the other wounds and
we can close him up...

@MSG_OPE508_CLOSE_BODY
<bup 1 8 5>
<vplay 7 103>
Could my father really have designed
this GUILT? ...What's he trying to do?

@MSG_OPE508_END_OPE
<bup 1 8 5>
That was a strange GUILT, but at least
we know how to handle it, now.
<wait>
The laser is effective, so treatment
is actually pretty simple.
<wait>
...It was probably still in development
when the authorities found this laboratory.
<wait>
<vplay 7 9>
...So we found it just in time.
Good work, Dr. Stiles.
<wait>
