
@MSG_OPE502_GAMEOVER
<bup 0 9 5>
You're in trouble. Leave this to me!
<wait>
<bup_cls>

@MSG_OPE502a_START_OPE
<bup 1 8 5>
<vplay 7 4>
It's a new Kyriaki strain, which gives us
about ten minutes...
<wait>
...Which means you have five patients
to treat in that amount of time.
<wait>
<vplay 7 88>
This will be tough, Doctor...
...but we have no choice!

@MSG_OPE502a_ENTER_BODY
<bup 1 8 5>
Those lacerations definitely came from
Kyriaki... Suture them quickly!

@MSG_OPE502a_STEP_KYRIAKI_2ndWAV
<bup 1 8 3>
...We have a Chiral reaction!
There are two Kyriaki bodies.

@MSG_OPE502a_STEP_AllSLASH_STITC
<bup 1 8 5>
<vplay 7 113>
See those lacerations?
It's definitely Kyriaki.

@MSG_OPE502a_STEP_KYRIAKI_3rdWAV
<bup 1 8 3>
<vplay 7 27>
There's the last one...!
Is that its origin?

@MSG_OPE502a_END_FLOW_NOTHING_LE
<bup 1 8 5>
<vplay 7 32>
Chiral reaction is negative!
We've eliminated the Kyriaki.

@MSG_OPE502a_END_FLOW_REMAIN_LES
<bup 1 8 5>
<vplay 7 32>
Okay... Treat the rest of her wounds
and move on to the next patient!

@MSG_OPE502a_CLOSE_BODY_GOOD
<bup 1 8 5>
<vplay 7 10>
Amazing! That didn't take very long at all!
...Keep it up, Doctor.

@MSG_OPE502a_CLOSE_BODY_NORMAL
<bup 1 8 5>
I think we can do this... Try to work
a little faster, though.

@MSG_OPE502a_CLOSE_BODY_BAD
<bup 1 8 5>
That took too long... If we don't hurry,
people are going to die.

@MSG_OPE502a_END_OPE
<bup 1 8 5>
<vplay 7 89>
Good work. We've finished treating
the first patient.
<wait>
<bup_cls>

@MSG_OPE502b_START_OPE
<bup 1 8 5>
<vplay 7 90>
Please begin operating on the second patient.

@MSG_OPE502b_ENTER_BODY
<bup 1 8 5>
Chiral reaction confirmed! Suture the cuts
and incinerate the GUILT!

@MSG_OPE502b_STEP_KYRIAKI_2ndWAV
<bup 1 8 3>
Chiral reaction confirmed!
It looks like three Kyriaki bodies.

@MSG_OPE502b_STEP_AllSLASH_STITC
<bup 1 8 5>
<vplay 7 113>
See those lacerations?
It's the Kyriaki!

@MSG_OPE502b_STEP_KYRIAKI_3rdWAV
<bup 1 8 3>
There! That should be the last one.

@MSG_OPE502b_END_FLOW_NOTHING_LE
<bup 1 8 5>
<vplay 7 32>
Chiral reaction is negative. We did it!

@MSG_OPE502b_END_FLOW_REMAIN_LES
<bup 1 8 5>
<vplay 7 32>
The GUILT has been eradicated.
Treat his wounds and keep moving...

@MSG_OPE502b_CLOSE_BODY_GOOD
<bup 1 8 5>
<vplay 7 11>
Great job, Dr. Stiles! At this rate,
we'll be able to save them all...!

@MSG_OPE502b_CLOSE_BODY_NORMAL
<bup 1 8 5>
We're running out of time...
Hurry, Doctor!

@MSG_OPE502b_CLOSE_BODY_BAD
<bup 1 8 5>
We don't have enough time...
I'm calling in for backup.

@MSG_OPE502b_END_OPE
<bup 1 8 5>
<vplay 7 91>
We've finished treating the second patient.
I'll bring in the next one.
<wait>

@MSG_OPE502c_START_OPE
<bup 1 8 5>
I just heard back from Director Kasal.
He's sending in backup.
<wait>
<vplay 7 92>
We need to do what we can until they arrive.
Let's continue...

@MSG_OPE502c_ENTER_BODY
<bup 1 8 5>
Chiral reaction confirmed!
We need to remove the GUILT.

@MSG_OPE502c_STEP_KYRIAKI_2ndWAV
<bup 1 8 3>
Chiral readings are increasing...
Be careful, Doctor.

@MSG_OPE502c_STEP_AllSLASH_STITC
<bup 1 8 5>
<vplay 7 113>
Those lacerations...
It's Kyriaki!

@MSG_OPE502c_STEP_KYRIAKI_3rdWAV
<bup 1 8 3>
I... I think that's the last one.
Let's take care of it!

@MSG_OPE502c_END_FLOW_NOTHING_LE
<bup 1 8 5>
<vplay 7 32>
Chiral reaction negative.
The GUILT is gone!

@MSG_OPE502c_END_FLOW_REMAIN_LES
<bup 1 8 5>
<vplay 7 32>
We did it... Treat her wounds and move on
to the next patient.

@MSG_OPE502c_CLOSE_BODY_GOOD
<bup 1 8 5>
<vplay 7 12>
Three patients in less than five minutes?
I think we'll make it!

@MSG_OPE502c_CLOSE_BODY_NORMAL
<bup 1 8 5>
Hang in there, Doctor... There are
only two patients left. Let's hurry.

@MSG_OPE502c_CLOSE_BODY_BAD
<bup 1 8 5>
Time's running out... Let's hope
the backup gets here soon!

@MSG_OPE502c_CLOSE_BODY_INC_HELP
<bup 1 8 5>
*sigh* We did it...
Let's close this patient up!

@MSG_OPE502c_TIMEUP
<bup 1 8 5>
<vplay 7 99>
Our backup arrived! *sigh*...
Let's finish treating the patient.

@MSG_OPE502c_END_OPE
<bup 1 8 5>
<vplay 7 93>
We've finished treating the third patient.
Great job, Doctor!
<wait>

@MSG_OPE502c_END_OPE_INC_HELP
<bup 1 8 5>
<vplay 7 100>
We actually did it!
Doctor... You're doing very well.
<wait>

@MSG_OPE502d_START_OPE
<bup 1 8 5>
<vplay 7 94>
Two more patients left... Let's do
what we can until backup arrives.

@MSG_OPE502d_ENTER_BODY
<bup 1 8 5>
Chiral reaction confirmed!
It's definitely GUILT, Doctor.

@MSG_OPE502d_STEP_KYRIAKI_2ndWAV
<bup 1 8 3>
Chiral reaction is rising!
...Be careful.

@MSG_OPE502d_STEP_AllSLASH_STITC
<bup 1 8 5>
<vplay 7 113>
The Kyriaki is opening lacerations!

@MSG_OPE502d_STEP_KYRIAKI_3rdWAV
<bup 1 8 3>
I think this is the last one...

@MSG_OPE502d_END_FLOW_NOTHING_LE
<bup 1 8 5>
<vplay 7 32>
Chiral reaction is negative!
Only one more patient to go!

@MSG_OPE502d_END_FLOW_REMAIN_LES
<bup 1 8 5>
<vplay 7 32>
The Kyriaki is gone... Treat his wounds
and we'll continue on.

@MSG_OPE502d_CLOSE_BODY_GOOD
<bup 1 8 5>
<vplay 7 13>
(I can't believe it...
Dr. Stiles is incredible.)

@MSG_OPE502d_CLOSE_BODY_NORMAL
<bup 1 8 5>
Just one more patient...
Come on, Doctor. Hang in there!

@MSG_OPE502d_CLOSE_BODY_BAD
<bup 1 8 5>
*sigh* He's going to be fine.
Please close the patient up.

@MSG_OPE502d_TIMEUP
<bup 1 8 5>
<vplay 7 99>
It looks like backup just arrived.
Let's close up the patient.

@MSG_OPE502d_END_OPE
<bup 1 8 5>
<vplay 7 95>
That was the fourth patient.
...We're almost done, Dr. Stiles!
<wait>

@MSG_OPE502d_END_OPE_INC_HELP
<bup 1 8 5>
<vplay 7 100>
Our backup should be able to handle
the last patient. Good work, Doctor.
<wait>

@MSG_OPE502e_START_OPE
<bup 1 8 5>
<vplay 7 96>
We saved the others, Dr. Stiles...
We can save him!

@MSG_OPE502e_ENTER_BODY
<bup 1 8 5>
Chiral reaction confirmed!
Stay focused...

@MSG_OPE502e_STEP_KYRIAKI_2ndWAV
<bup 1 8 3>
Chiral reaction is increasing.
Be careful, Dr. Stiles!

@MSG_OPE502e_STEP_AllSLASH_STITC
<bup 1 8 5>
<vplay 7 113>
The Kyriaki is creating lacerations!

@MSG_OPE502e_STEP_KYRIAKI_3rdWAV
<bup 1 8 3>
One more left...

@MSG_OPE502e_END_FLOW_NOTHING_LE
<bup 1 8 1>
<vplay 7 97>
That's the last of them!
...*sigh* We did it.

@MSG_OPE502e_END_FLOW_REMAIN_LES
<bup 1 8 1>
<vplay 7 97>
Treat the remaining wounds and finish up
the procedure.

@MSG_OPE502e_CLOSE_BODY
<bup 1 8 1>
...What a relief...
Let's close the patient up.

@MSG_OPE502e_TIMEUP
<bup 1 8 5>
<vplay 7 99>
Backup just arrived, but we might as well
finish this ourselves.

@MSG_OPE502e_END_OPE
<bup 1 8 1>
<vplay 7 14>
We actually treated five patients
in ten minutes...
<wait>
This won't mean as much now, but...
I knew you could do it.
<wait>
<bup 1 8 2>
<vplay 7 9>
Dr. Stiles...
You were really amazing!
<wait>

@MSG_OPE502e_END_OPE_INC_HELP
<bup 1 8 1>
All five Kyriaki victims have been
successfully treated...
<wait>
I'll have backup transfer them
to Caduceus.
<wait>
<bup 1 8 2>
<vplay 7 9>
I was proud to be here at your side,
Dr. Stiles.
<wait>
