
@MSG_OPE606_GAMEOVER
<bup 0 8 5>
We were too late, Dr. Stiles...
There's nothing more we can do!
<wait>
<bup 0 19 1>
Stop the procedure! We need to transfer him
to a stasis chamber immediately!
<wait>
<bup_cls>

@MSG_OPE606_START_OPE
<bup 1 8 5>
This strain may act differently than the
Pempti we dealt with the other day...
<wait>
<vplay 7 3>
We should be prepared for the worst,
just to be safe.

@MSG_OPE606_ENTER_BODY
<bup 1 8 5>
<vplay 7 113>
Inject the nanomachine to draw out
the core.

@MSG_OPE606_MISS_SYRINGE_PASTE
<bup 1 8 3>
<vplay 7 43>
Make your injection inside that cloudy
area in the fluid...

@MSG_OPE606_STEP_PASTE_SYRINGE_E
<bup 1 8 5>
The Pempti core is surfacing!
Are you standing by with the laser?

@MSG_OPE606_STEP_FAKE_PEMPTI
<bup 1 8 3>
It's the Pempti core!
<wait>
You have to destroy it with the laser!

@MSG_OPE606_STEP_REAL_PEMPTI
<bup 1 8 5>
Now the real battle starts...
Be careful.

@MSG_OPE606_CAUTION_NEOPLASM_BRO
<bup 1 8 5>
Don't let small tumors build up. Incinerate
them and heal the areas with antibiotic gel!

@MSG_OPE606_STEP_PEMPTI_LASER_1T
<bup 1 8 5>
<vplay 7 30>
Chiral reaction decreasing...
The laser is working!

@MSG_OPE606_STEP_PEMPTI_LASER_2T
<bup 1 8 5>
<vplay 7 12>
I think the core is weakening!
...Let's keep it up.

@MSG_OPE606_END_FLOW_NOTHING_LES
<bup 1 8 5>
<vplay 7 7>
We defeated the GUILT.
Good job, Dr. Stiles.

@MSG_OPE606_END_FLOW_REMAIN_LESI
<bup 1 8 5>
<vplay 7 32>
We have a negative Chiral reaction.
Don't forget to treat the smaller wounds...

@MSG_OPE606_CLOSE_BODY
<bup 1 8 5>
There are other patients that need our
attention, Doctor.
<wait>
Please suture your incision quickly.

@MSG_OPE606_END_OPE
<bup 1 8 5>
Well done, Dr. Stiles. This patient should
be just fine...
<wait>
<vplay 7 9>
But, there are still more people who need
our help. ...Let's hurry!
<wait>
