
@MSG_OPE604_GAMEOVER2
<bup 0 8 4>
No... Derek!
...Derek!
<wait>
<bup 0 19 1>
......
...Please contact Caduceus USA.
<wait>
<bup_cls>

@MSG_OPE604_START_OPE
<bup 1 8 5>
<vplay 7 6>
We're going to be working around his heart,
so be very careful, Doctor...

@MSG_OPE604_ENTER_BODY
<bup 1 8 5>
Those look like Kyriaki lacerations... You're
going to need to keep an eye on his vitals!

@MSG_OPE604_STEP_AllLESION_END
<bup 1 8 5>
<vplay 7 41>
Dr. Kimishima, I would like to confirm the
procedure before we get started...
<wait>
Don't forget that Paraskevi will stop moving
momentarily if attacked by the surgical laser.
<wait>
So, if you notice the GUILT attempting to
escape by burrowing into the affected area...
<wait>
<bup 1 8 3>
...I would strongly advice using the laser
to stop it in its tracks!
<wait>
<bup 1 8 5>
...Because...if it gets into...the patient's
heart, then there's nothing we can...do...
<wait>
<bup 1 6 1>
<vplay 4 28>
Don't worry, Angie.
...I'll take care of him.
<wait>
<bup 1 8 5>
Chiral reaction rising...
You should be able to see the GUILT!

@MSG_OPE604_CAUTION_DINING_PARAS
<bup 1 8 3>
<vplay 7 26>
Stop the Paraskevi before it burrows into
his heart!

@MSG_OPE604_END_1stSTAGE_REMAIN_
<bup 1 8 5>
<vplay 7 30>
The Chiral reaction is weakening... Don't
forget to treat the other wounds in the area!

@MSG_OPE604_END_1stSTAGE_NOTHING
<bup 1 8 5>
<vplay 7 30>
Chiral reaction decreasing.
I think we can do this...

@MSG_OPE604_ACTIVE_HEALINGTOUCH
<bup 1 8 9>
<vplay 7 49>
The patient's vitals...are recovering!
(Is this Dr. Kimishima's Healing Touch...!?)

@MSG_OPE604_CAUTION_2ndSTAGE
<bup 1 8 5>
<vplay 7 43>
Chiral reaction increasing! Careful, Doctor!

@MSG_OPE604_END_FLOW_REMAIN_LESI
<bup 1 8 5>
<vplay 7 32>
Chiral reaction is negative...
Let's treat the rest of his injuries.

@MSG_OPE604_END_FLOW_NOTHING_LES
<bup 1 8 5>
<vplay 7 32>
Chiral reaction is negative. ...We did it.

@MSG_OPE604_GAMEOVER
<bup 1 6 3>
No, dammit! This can't happen!

@MSG_OPE604_CLOSE_BODY
<bup 1 8 4>
<vplay 7 15>
Dr. Stiles...you're going to be okay...
...we did it.

@MSG_OPE604_END_OPE
<bup 1 8 2>
You were amazing, Dr. Kimishima, and--
<wait>
<bup 1 8 4>
<vplay 7 16>
...Thank you.
<wait>
