
@MSG_OPE607_GAMEOVER
<bup 0 8 3>
Close up the patient--it's too late!
We'll have to wait for Director Miller's orders.
<wait>
<bup 0 19 1>
My god... ...All personnel! Concentrate on
keeping the patients alive!
<wait>
<bup_cls>

@MSG_OPE607A_START_OPE
<bup 1 8 5>
The test results are here...
<wait>
<vplay 7 5>
It's showing up as Triti, and it seems to be
affecting the pancreas.

@MSG_OPE607A_ENTER_BODY
<bup 1 8 5>
<vplay 7 113>
As you know, those spurs need to be
extracted with your forceps.

@MSG_OPE607A_CAUTION_REMAIN_MEMB
<bup 1 8 5>
If you leave any membranes behind, they'll
hyperplasia--so be careful!

@MSG_OPE607A_CAUTION_EVAPORATE_W
<bup 1 8 3>
<vplay 7 43>
It's vaporized! You need to drain it!

@MSG_OPE607A_CAUTION_SMOKE_MAKE_
<bup 1 8 3>
Oh no... That vapor needs to be a priority,
Dr. Stiles. It's spreading the membrane!

@MSG_OPE607A_CAUTION_MAMBRANE_IN
<bup 1 8 5>
The membranes are spreading... Be more
careful while you're excising it.

@MSG_OPE607A_END_FLOW_REMAIN_LES
<bup 1 8 5>
<vplay 7 32>
Triti removal is complete... Clean the
patient up and we'll be finished.

@MSG_OPE607A_END_FLOW_NOTHING_LE
<bup 1 8 5>
<vplay 7 32>
The Chiral reaction is negative.
We've removed all of the Triti.

@MSG_OPE607A_CLOSE_BODY_GOOD
<bup 1 8 1>
<vplay 7 10>
We finished more quickly than I expected.
Suture the patient so we can move on.

@MSG_OPE607A_CLOSE_BODY_NORMAL
<bup 1 8 5>
As long as we can keep up this pace, we
should be fine. Please suture your incision.

@MSG_OPE607A_CLOSE_BODY_BAD
<bup 1 8 5>
...We need to start moving faster.
Suture the patient so we can continue.

@MSG_OPE607A_END_OPE
<bup 1 2 5>
...That went well.
<wait>
Has the next patient been anesthetized and
prepped already?
<wait>
<bup 1 8 1>
Yes. Please get ready for that procedure
while I assist Dr. Kimishima.
<wait>
We can't waste too much time between
patients.
<wait>
<bup 1 2 1>
Alright, I understand.
<wait>
Good luck, Dr. Kimishima.
<wait>

@MSG_OPE607B_START_OPE
<bup 1 6 1>
...I'm partially responsible for this, yet here
I am, fighting to stop it.
<wait>
<vplay 4 2>
But... it's a little late to start worrying
about things like that.
<wait>
<bup 1 8 5>
It looks like this patient is suffering from
Kyriaki in their left lung.

@MSG_OPE607B_ENTER_BODY
<bup 1 8 5>
Lacerations are confirmed, so get started
treating those wounds first.

@MSG_OPE607B_STEP_AllLESION_END
<bup 1 8 5>
<vplay 7 113>
We have a stronger Chiral reaction...
The Kyriaki should be visible soon.

@MSG_OPE607B_KYRIAKI_TUNING_POIN
<bup 1 8 5>
<vplay 7 30>
The Chiral readings are down 50%...
Keep attacking the Kyriaki as they appear.

@MSG_OPE607B_END_FLOW_REMAIN_LES
<bup 1 8 5>
<vplay 7 32>
The Chiral reaction is negative. Once you
clean up, we're done.

@MSG_OPE607B_END_FLOW_NOTHING_LE
<bup 1 8 5>
<vplay 7 32>
The Chiral reaction is negative.
Well done, Dr. Kimishima.

@MSG_OPE607B_CLOSE_BODY_GOOD
<bup 1 8 1>
<vplay 7 11>
You did excellent work! Now, close up the
chest area so we can complete the procedure.

@MSG_OPE607B_CLOSE_BODY_NORMAL
<bup 1 8 5>
We should still have time for the other
patients. Let's finish up here.

@MSG_OPE607B_CLOSE_BODY_BAD
<bup 1 8 5>
Hm... I had hoped we'd have more time. Close
the patient up so we can move on...

@MSG_OPE607B_END_OPE
<bup 1 8 5>
Okay, Dr. Kimishima... I'm going to go back
to assist Derek.
<wait>
Once he's finished, you'll be operating on
the final patient.
<wait>
<bup 1 6 1>
...Good, I need a minute to relax.
<wait>
Don't worry, I'll be ready to go as soon as
Stiles finishes his procedure.
<wait>

@MSG_OPE607C_START_OPE
<bup 1 8 5>
Good, the special GUILT serum just arrived.
We're all set to go.
<wait>
<bup 1 2 11>
Okay... stay calm and keep it steady,
like Dr. Kasal always says, right?
<wait>
<bup 1 8 5>
<vplay 7 3>
The Deftera is in the patient's stomach.
...Good luck, Doctor.

@MSG_OPE607C_ENTER_BODY
<bup 1 8 9>
<vplay 7 51>
What...!? They never mentioned this
hemorrhaging!
<wait>
<bup 1 8 5>
We can't start treating the GUILT until we
take care of all this!
<wait>
Quickly...start by draining the blood.

@MSG_OPE607C_STEP_BLOOD_END
<bup 1 8 3>
<vplay 7 48>
Uh...I can't seem to... I can't locate the
source of this hemorrhaging.
<wait>
<bup 1 8 5>
Does that mean it's centered
somewhere else?
<wait>
...We don't have time to search for
the source of the hemorrhaging!
<wait>
<bup 1 2 11>
Let's just worry about this for now.
<wait>
<bup 1 8 9>
What!? You're going to treat the GUILT
through all this blood?
<wait>
<bup 1 2 11>
Do you have a better idea?
<wait>
<bup 1 8 5>
I... *sigh*
<wait>
In that case, we don't have much time.
<wait>
This is an emergency, so we need to get that
GUILT out of his system--you're right.
<wait>
Drain the blood and continue with the
Deftera extraction process.
<wait>
Continue using the drain as the blood
accumulates... That's our plan.
<wait>
It won't be easy, but...

@MSG_OPE607C_RETRY_BLOOD
<bup 1 8 5>
The blood is accumulating, Doctor!
Don't forget to drain it.

@MSG_OPE607C_CAUTION_BLOOD
<bup 1 8 5>
We can't treat anything with this blood in
our way. You need to drain it, first.

@MSG_OPE607C_CAUTION_DEFTERA_UNI
<bup 1 8 5>
<vplay 7 43>
The Deftera have formed a tumor.
Drain the tissue quickly!

@MSG_OPE607C_END_FLOW_REMAIN_LES
<bup 1 8 5>
<vplay 7 32>
Deftera extraction is complete. Treat the
area and finish up.

@MSG_OPE607C_END_FLOW_NOTHING_LE
<bup 1 8 5>
The Chiral reaction is negative...
You removed the Deftera.

@MSG_OPE607C_CLOSE_BODY_GOOD
<bup 1 8 1>
<vplay 7 46>
We managed to finish fairly quickly. Suture
the incision and we'll be done.

@MSG_OPE607C_CLOSE_BODY_NORMAL
<bup 1 8 5>
Good...there's still some time left. Close the
patient up and we'll be done.

@MSG_OPE607C_CLOSE_BODY_BAD
<bup 1 8 5>
We're running out of time! Hurry, Doctor,
there's still one more patient!

@MSG_OPE607C_END_OPE
<bup 1 8 5>
I've received news on the other people who
came into contact with GUILT...
<wait>
...they're all stable for the moment, so
this will be our last emergency operation.
<wait>
<bup 1 2 5>
Ah... That's good news.
<wait>
Once Dr. Kimishima is finished, we can
finally relax.
<wait>

@MSG_OPE607D_START_OPE
<bup 1 8 3>
This is the last patient...!
<wait>
<bup 1 8 5>
The GUILT involved is...Paraskevi.
I'm afraid it's already reached the heart.
<wait>
<bup 1 6 1>
...That's all right. It hasn't progressed too
quickly--I should still have enough time.
<wait>
All I need to do is concentrate...
How hard could it be?
<wait>
<bup 1 8 5>
...I'll do everything I can to support you.
We're going to save him!
<wait>
<vplay 7 3>
...Whatever you do, keep the GUILT out of
the patient's heart!

@MSG_OPE607D_ENTER_BODY
<bup 1 8 5>
Begin by treating the lacerations.

@MSG_OPE607D_STEP_AllLESION_END
<bup 1 8 5>
Use the surgical laser to halt the Paraskevi's
progress...

@MSG_OPE607D_STEP_PARASKEVI_LASE
<bup 1 8 5>
<vplay 7 71>
The Paraskevi is stunned! Now's your chance
to cut it with your scalpel!

@MSG_OPE607D_STEP_PARASKEVI_SCAL
<bup 1 8 5>
It's starting to divide, but it's still too large
to extract.

@MSG_OPE607D_STEP_PARASKEVI_SCAL
<bup 1 8 5>
...You should be able to extract it!

@MSG_OPE607D_MISS_FORCEPS_PARASK
<bup 1 8 5>
<vplay 7 43>
Don't attempt to grab it while it's moving;
it's too dangerous!

@MSG_OPE607D_MISS_FORCEPS_PARASK
<bup 1 8 5>
<vplay 7 44>
It's still not small enough--keep cutting it!

@MSG_OPE607D_CAUTION_DIVING_PARA
<bup 1 8 3>
<vplay 7 26>
It's burrowing into the heart! You need to
laser it, now!

@MSG_OPE607D_CAUTION_DIVING_PARA
<bup 1 8 3>
<vplay 7 26>
If the Paraskevi gets into the patient's heart,
it's all over!

@MSG_OPE607D_END_FLOW_REMAIN_LES
<bup 1 8 5>
<vplay 7 32>
Paraskevi extraction complete. Remember
to treat the other problem areas.

@MSG_OPE607D_END_FLOW_NOTHING_LE
<bup 1 8 5>
<vplay 7 32>
Chiral reaction is negative... It looks like
we managed to pull it off.

@MSG_OPE607D_CLOSE_BODY_BOOD
<bup 1 8 1>
<vplay 7 14>
That was amazing! We finished with time to
spare... Let's get the patient out of surgery.

@MSG_OPE607D_CLOSE_BODY_NORMAL
<bup 1 8 5>
Perfect... Now suture your incision and
we'll be done here.

@MSG_OPE607D_CLOSE_BODY_BAD
<bup 1 8 5>
...You kind of cut it close, but now all we
need to do is close up the patient.

@MSG_OPE607D_END_OPE
<bup 1 6 1>
<vplay 4 8>
...That's the last one, right?
<wait>
<bup 1 8 5>
Yeah...we have confirmation on that.
<wait>
<bup 1 6 2>
Good... I'm glad we were able to treat all
four of them.
<wait>
...It's a relief.
<wait>
<bup 1 8 5>
Yes, but we can relax now. ...At least,
for the moment.
<wait>
<bup 1 8 2>
<vplay 7 9>
You both did an amazing job, Dr. Stiles,
Dr. Kimishima...
<wait>
