
@MSG_OPE608_GAMEOVER
<bup 0 8 4>
...Dr. Hoffman...
<wait>
<bup 0 19 1>
...Stop the operation; it's too late.
Robert...will be missed...
<wait>
<bup_cls>

@MSG_OPE608_START_OPE
<bup 1 8 5>
It's going to take both of your Healing
Touch abilities to save Dr. Hoffman...
<wait>
<vplay 7 3>
...Good luck!

@MSG_OPE608_ENTER_BODY
<bup 1 8 5>
<vplay 7 113>
First, we need to deal with that
Savato nest...

@MSG_OPE608_CAUTION_NEST_DAMAGE
<bup 1 8 3>
<vplay 7 22>
Keep an eye on the patient's vitals when
the webbing changes color!

@MSG_OPE608_NEST_RENEW_1TIME
<bup 1 2 11>
<vplay 1 24>
I've successfully removed the nest,
but Savato is moving to another location.

@MSG_OPE608_NEST_RENEW_1TIME_AFT
<bup 1 6 1>
<vplay 4 49>
Let me handle that...

@MSG_OPE608_NEST_RENEW_2TIMES
<bup 1 6 1>
<vplay 4 46>
I took care of the nest over here--he's
heading back to your side.

@MSG_OPE608_NEST_RENEW_2TIMES_AF
<bup 1 2 11>
<vplay 1 29>
Understood!

@MSG_OPE608_STEP_SAVATO_LASER_EN
<bup 1 8 5>
<vplay 7 71>
We've eliminated his protective layer...
Now! Attack it with the scalpel!

@MSG_OPE608_CAUTION_LASER_SAVATO
<bup 1 8 5>
The laser isn't working! You need to
switch to the scalpel!

@MSG_OPE608_1DAMEGE_SAVATO
<bup 1 2 11>
<vplay 1 26>
It's trying to get away again...
Are you ready?

@MSG_OPE608_1DAMEGE_SAVATO_AFTER
<bup 1 6 1>
<vplay 4 50>
Yeah, I'll take care of it.

@MSG_OPE608_2DAMEGE_SAVATO
<bup 1 6 1>
<vplay 4 47>
...Annoying bastard, isn't he?

@MSG_OPE608_2DAMEGE_SAVATO_AFTER
<bup 1 2 11>
<vplay 1 28>
This is it... Let's cut it up!

@MSG_OPE608_CAUTION_SAVATO_AVOID
<bup 1 8 5>
It's not weak enough to inject the serum yet...

@MSG_OPE608_CAUTION_SAVATO_SYRIN
<bup 1 8 3>
<vplay 7 110>
Now's your chance, Doctor!
Inject the serum!

@MSG_OPE608_AUTOACTIVE_HEALINGTO
<bup 1 2 11>
<vplay 1 20>
I won't let you take Dr. Hoffman...!

@MSG_OPE608_AUTOACTIVE_HEALINGTO
<bup 1 6 3>
<vplay 4 32>
...I've had just about enough of this
GUILT crap!

@MSG_OPE608_HINT_HEALINGTOUCH_DO
<bup 1 2 11>
<vplay 1 19>
Come on, concentrate... I have to focus!

@MSG_OPE608_END_FLOW
<bup 1 8 5>
<vplay 7 32>
Savato's disappeared...
...Chiral reaction is negative.
<wait>
You may finish the procedure, Doctor.

@MSG_OPE608_END_OPE
<bup 1 6 2>
...Whew, happy ending...
<wait>
<bup 1 2 1>
You saved us again, Dr. Kimishima.
<wait>
<bup 1 8 1>
You both made this operation a success.
<wait>
Two doctors with amazing abilities were able
to save a third...
<wait>
<bup 1 8 2>
<vplay 7 9>
...the Healing Touch will be handed down,
just as Dr. Hoffman wanted.
<wait>
