
@MSG_OPE603_GAMEOVER
<bup 0 8 3>
Derek! Just forget about it--Dr. Kimishima
can take over for you!
<wait>
<bup 0 6 1>
...I'm more than a little disappointed this is
all the great Derek Stiles has to offer.
<wait>
<bup_cls>

@MSG_OPE603_START_OPE
<bup 1 8 5>
<vplay 7 3>
Be careful, Doctor. We're not sure what
to expect during this procedure...

@MSG_OPE603_ENTER_BODY
<bup 1 8 5>
Chiral reaction is increasing...
We have visual on Tetarti.

@MSG_OPE603_STEP_TRITI_1stWAVE_E
<bup 1 8 5>
<vplay 7 46>
This strain seems identical to the Tetarti
we've treated in previous operations.

@MSG_OPE603_CAUTION_TRITI_RAMPAG
<bup 1 8 5>
The Chiral reaction is stable--it's Tetarti.

@MSG_OPE603_CAUTION_TRITI_RAMPAG
<bup 1 8 9>
<vplay 7 50>
What the--!?
I can't tell which Tetarti is which!

@MSG_OPE603_STEP_TRITI_RAMPAGE_1
<bup 1 8 5>
<vplay 7 41>
Tetarti's never reacted
that way before...
<wait>
...Doctor? Are you all right?
<wait>
<bup 1 2 11>
Yeah...
It just surprised me, is all.
<wait>
<bup 1 8 1>
We should continue, then...
<wait>
<bup 1 8 5>
Oh no! The Chiral reaction is increasing!
Here it comes...

@MSG_OPE603_CAUTION_POISON
<bup 1 8 5>
I think you can neutralize the toxic mist
with antibiotic gel.

@MSG_OPE603_HINT_TRITI_RAMPAGE
<bup 1 8 5>
<vplay 7 41>
Doctor...! I figured it out!
<wait>
<bup 1 8 5>
You can distinguish between the Tetarti by
the color of the mist they produce!

@MSG_OPE603_STEP_TRITI_RAMPAGE_2
<bup 1 2 11>
<vplay 1 14>
...*sigh*
<wait>
<bup 1 8 5>
...Are you sure you're feeling all right,
Derek?
<wait>
<bup 1 2 11>
...What? Yeah, of course...
...I'm fine...

@MSG_OPE603_CAUTION_TRITI_RAMPAG
<bup 1 8 9>
<vplay 7 50>
Ack! That could be toxic!

@MSG_OPE603_END_FLOW_NOTHING_LES
<bup 1 8 5>
<vplay 7 32>
We have a negative Chiral reaction.
Good work, Doctor.

@MSG_OPE603_END_FLOW_REMAIN_LESI
<bup 1 8 5>
<vplay 7 32>
I believe the GUILT is gone. Let's treat
those wounds and finish up.

@MSG_OPE603_CLOSE_BODY
<bup 1 8 5>
...The patient's sudden infection may have
been caused by those toxic excretions.
<wait>
We'll have to look into it further once
the patient is awake.

@MSG_OPE603_END_OPE
<bup 1 8 5>
<vplay 7 9>
Operation complete.
<wait>
