
@MSG_OPEs01_GAMEOVER
<bup 0 4 3>
None of the patient's injuries should have
been fatal...! I...
<wait>
...I screwed up.
<wait>
<bup_cls>

@MSG_OPEs01_START_OPE
<vplay 4 2>
<bup 1 4 1>
The injury is located primarily in
the patient's forearm...

@MSG_OPEs01_STEP_OPENMARKER_END
<bup 1 4 1>
Sterilization complete. I will now make
the incision.

@MSG_OPEs01_OPEN_BODY
<vplay 4 21>
<bup 1 4 1>
Incision complete. I'm opening him up...

@MSG_OPEs01_ENTER_BODY
<vplay 4 29>
<bup 1 4 1>
The hemorrhaging looks pretty bad.
I need to drain this area.

@MSG_OPEs01_STEP_BLOOD_END
<bup 1 4 1>
The bleeding is still minor enough to cure
with the antibiotic gel.

@MSG_OPEs01_STEP_SCAR_END
<vplay 4 22>
<bup 1 4 1>
That should stop the bleeding.

@MSG_OPEs01_RETRY_BLOOD_DRAIN
<vplay 4 16>
<bup 1 4 1>
If I don't treat this quickly, it's going to
hemorrhage again...

@MSG_OPEs01_STEP_AllLESION_END
<vplay 4 50>
<bup 1 4 1>
Now, I'll need to collect the fragments of
the broken bones.

@MSG_OPEs01_STEP_BONECHIP_FORCEP
<bup 1 4 1>
Now, I'll return these fragments to their
original positions in order to rebuild his arm.
<wait>
<vplay 4 27>
...It looks like his ulna is twisted
in the wrong direction.
<wait>
I'll use my forceps to move it back
into place...

@MSG_OPEs01_STEP_BONE_FORCEPS_EN
<bup 1 4 1>
With that out of the way, I should be able to
move the bone fragments where they belong.
<wait>
I might need to rotate these pieces
before they'll fit properly...

@MSG_OPEs01_STEP_BONECHIP_RETURN
<vplay 4 28>
<bup 1 4 2>
There... Solved that puzzle.

@MSG_OPEs01_MISS_BONECHIP_RETURN
<vplay 4 19>
<bup 1 4 1>
No, wait... I need to look at how these
shapes fit together more carefully.

@MSG_OPEs01_STEP_BONECHIP_END
<vplay 4 30>
<bup 1 4 1>
...Something isn't right.
<wait>
I thought I found all the fragments, but...
the radius still isn't connecting properly.
<wait>
There's probably still a fragment I haven't
found yet...
<wait>
If I use the ultrasound, I should be
able to find it.
<wait>

@MSG_OPEs01_STEP_HIDINGCHIP_ULTR
<bup 1 4 1>
Aha! Here's where you were hiding...

@MSG_OPEs01_STEP_HIDINGCHIP_SCAL
<bup 1 4 1>
Oh, here it is! Good thing I found it...

@MSG_OPEs01_STEP_HIDINGCHIP_FORC
<bup 1 4 1>
I need to treat the area before I can worry
about moving that fragment back into place.

@MSG_OPEs01_MISS_HIDINGCHIP_DROP
<bup 1 4 1>
I do need to treat the area, but... I should
locate the missing fragment, first.

@MSG_OPEs01_STEP_2ndSCAR_END
<bup 1 4 1>
Now I just need to return the bone fragment
back where it belongs...

@MSG_OPEs01_STEP_BONECHIP_RETURN
<vplay 4 21>
<bup 1 4 1>
That seems to be all of them.
<wait>
I should apply some antibiotic gel to make
sure the area is healing properly...
<wait>

@MSG_OPEs01_END_FLOW
<vplay 4 26>
<bup 1 4 1>
The radius bone has been reformed.
I anticipate a quick recovery.
<wait>

@MSG_OPEs01_CAUTION_GEL
<bup 1 4 1>
Oops... I can't risk missing a spot.

@MSG_OPEs01_CLOSE_BODY
<bup 1 4 1>
Now, I'll be suturing my incision.

@MSG_OPEs01_END_OPE
<vplay 4 7>
<bup 1 4 2>
Operation complete.
<wait>
