
@MSG_OPEs02_GAMEOVER
<bup 0 25 1>
Enough, Weaver... We'll just have to get one
of our doctors to take a look at him.
<wait>
...Doesn't look good, though. Why don't you go
wait in the other room?
<wait>
<bup_cls>

@MSG_OPEs02_START_OPE
<bup 1 5 1>
<vplay 4 4>
I'm going to get started... I'll be working in
the large intestine.

@MSG_OPEs02_STEP_OPENMARKER_END
<bup 1 5 1>
I've sterilized the area.
Now making my incision...

@MSG_OPEs02_OPEN_BODY
<bup 1 5 1>
Done. Let's have a look at this tumor.

@MSG_OPEs02_ENTER_BODY
<bup 1 5 1>
<vplay 4 29>
You weren't kidding... This isn't a normal
tumor.
<wait>
I'll need to sever the three veins supporting
this tumor before I can excise it...
<wait>
Alright... I'll begin by draining the cytoplasm.

@MSG_OPEs02_STEP_TUMOR_DRAIN_END
<bup 1 5 1>
<vplay 4 22>
Now, about those veins...

@MSG_OPEs02_STEP_TUMOR_SCALPEL_1
<bup 1 5 1>
<vplay 4 21>
I've severed the first vein.
<wait>
His vitals could be better...
<wait>
I'll need to keep an eye on his vitals as I
continue with these veins.

@MSG_OPEs02_STEP_TUMOR_SCALPEL_2
<bup 1 5 1>
<vplay 4 24>
That's the second vein.
<wait>
We have some small tumors forming, so I'm
going to use the laser to incinerate them.

@MSG_OPEs02_STEP_TUMOR_SCALPEL_3
<bup 1 5 1>
<vplay 4 22>
All three veins have been severed.
<wait>
I should be able to lift that tumor out using
the forceps, now.

@MSG_OPEs02_START_2ndWAVE
<bup 1 5 3>
<vplay 4 36>
What the hell!?
...This doesn't make sense.
<wait>
<bup 1 5 1>
I trusted an outside diagnosis and now I'm
paying the price... I hope it's not too late.

@MSG_OPEs02_STEP_TUMOR_FORCEPS_O
<bup 1 5 1>
There's only one more tumor left--I'm just
a little concerned about his vitals...

@MSG_OPEs02_STEP_TUMOR_REVIVE_1T
<bup 1 5 3>
<vplay 4 37>
What's going on!? Why does it keep
regenerating?
<wait>
I'm going to have to start over from the
beginning, by severing the veins.

@MSG_OPEs02_STEP_TUMOR_REVIVE_2T
<bup 1 5 3>
No! Why is this happening?
<wait>
<vplay 4 38>
...I probably need to get all of them out
quickly, before the others can regenerate.

@MSG_OPEs02_END_2ndWAVE
<bup 1 5 1>
There... Did that do it?

@MSG_OPEs02_START_3rdWAVE
<bup 1 5 3>
<vplay 4 30>
Four of them at once!?

@MSG_OPEs02_START_3rdWAVE_2
<bup 1 5 2>
<vplay 4 31>
I don't think I have a choice.

@MSG_OPEs02_START_3rdWAVE_3
<bup 1 5 2>
This power took away my life...

@MSG_OPEs02_START_3rdWAVE_4
<bup 1 5 2>
<vplay 4 33>
...but it's the reason I'm here.

@MSG_OPEs02_AUTOACTIVE_HEALINGTO
<bup 1 5 2>
Hopefully this is enough to get his vitals
back up where they belong...

@MSG_OPEs02_END_FLOW_NOTHING_LES
<bup 1 5 1>
<vplay 4 26>
There... I've excised the tumor.

@MSG_OPEs02_END_FLOW_REMAIN_LESI
<bup 1 5 1>
<vplay 4 26>
I've finished removing the tumor...
<wait>
Now, to patch up the rest of this mess.

@MSG_OPEs02_CLOSE_BODY
<bup 1 5 1>
...And now, to close him up.

@MSG_OPEs02_END_OPE
<bup 1 5 2>
<vplay 4 9>
I'm glad that's over.
<wait>
