
@MSG_OPEs04_GAMEOVER
<bup 0 25 1>
Abort the operation, Weaver! If you keep
going, you're only going to make things worse.
<wait>
I've already called in our doctors...
...Let them handle it, okay?
<wait>
<bup_cls>

@MSG_OPEs04_START_OPE
<bup 1 5 1>
<vplay 4 5>
I'm looking at the kidney.
<wait>
I'm going to need to remove this tumor to
make enough room for the transplant.

@MSG_OPEs04_ENTER_BODY
<bup 1 5 1>
<vplay 4 29>
This is exactly like that strange tumor
I had to deal with before.
<wait>
If I don't move quickly, they're going to
regenerate.

@MSG_OPEs04_STEP_TUMOR_FORCEPS_1
<bup 1 5 1>
<vplay 4 21>
The first tumor is out... I'm moving on to
the second one quickly.

@MSG_OPEs04_STEP_TUMOR_FORCEPS_2
<bup 1 5 1>
Tumor extraction complete! I'm going
to need that kidney soon!
<wait>
...Good. I'll be able to place this in the area
I cleared out.

@MSG_OPEs04_CAUTION_TUMOR_REVIVE
<bup 1 5 1>
<vplay 4 16>
Damn... I took too long. I need to speed up
my excisions.

@MSG_OPEs04_MISS_ORGAN_DROP
<bup 1 25 1>
<vplay 25 4>
That's the only kidney we have, y'know.
You should be more careful with it.

@MSG_OPEs04_STEP_ORGAN_END
<bup 1 5 1>
OK, it's in position.
<wait>
Now... I'm going to need to restrict blood
pressure before I can perform anastomosis.
<wait>
Meaning, the vasoconstrictor needs to be
injected into his veins.

@MSG_OPEs04_MISS_SYRINGE
<bup 1 25 1>
I thought you said that goes into his veins.

@MSG_OPEs04_STEP_VESSEL_SYRINGE_
<bup 1 25 1>
Inject the vasocon...thing into the other
one, too.
<wait>
You can only perform anastomosis once
the arteries and veins have contracted.

@MSG_OPEs04_STEP_VESSEL_SYRINGE_
<bup 1 5 1>
I need to make my incision while the
vasoconstrictor is in effect.

@MSG_OPEs04_STEP_VESSEL_SCALPEL_
<bup 1 25 1>
It looks like there will be some bleeding,
even with the vasoconstrictor...
<wait>
<bup 1 5 1>
I assure you, the bleeding would be a lot
worse without it.
<wait>
The vasoconstrictor will need to be injected
periodically to maintain this condition.
<wait>
I'm going to drain the blood and continue
with the procedure.

@MSG_OPEs04_STEP_VESSEL_DRAIN_EN
<bup 1 5 1>
<vplay 4 22>
Okay, I'll finish the anastomosis of the veins
while the vasoconstrictor is still active.
<wait>
I need to pull the veins of the kidney
together using the forceps.

@MSG_OPEs04_MISS_VESSEL_FORCEPS
<bup 1 5 1>
<vplay 4 19>
This isn't going to work if I don't pull the
veins together properly.

@MSG_OPEs04_RETRY_BLOOD_DRAIN
<bup 1 5 3>
<vplay 4 17>
Dammit... The vasoconstrictor wore off
and now we have bleeding...

@MSG_OPEs04_STEP_VESSEL_BLOOD_DR
<bup 1 5 1>
I need to use the forceps to pull
those together.

@MSG_OPEs04_STEP_VESSEL_FORCEPS_
<bup 1 5 1>
<vplay 4 21>
Anastomosis complete. Once I suture it,
I can move on to the next one.

@MSG_OPEs04_STEP_VESSEL_STITCHES
<bup 1 5 1>
<vplay 4 23>
Now I just need to do
the same thing again.

@MSG_OPEs04_CAUTION_SYRINGE
<bup 1 5 1>
<vplay 4 16>
Ugh... It wore off. I have to make another
injection.

@MSG_OPEs04_CAUTION_SYRINGE_BLOO
<bup 1 5 3>
<vplay 4 30>
Dammit! Too much bleeding... I'm going to
inject more of the vasoconstrictor.

@MSG_OPEs04_STEP_BLOOD_DRAIN_END
<bup 1 25 1>
Hey, shouldn't you inject more of that stuff
before it starts to wear off?

@MSG_OPEs04_CAUTION_RETURN_ARTER
<bup 1 5 1>
<vplay 4 30>
The vasoconstrictor is wearing off...
I'm going to need more of it.

@MSG_OPEs04_CAUTION_RETURN_VEIN
<bup 1 5 1>
<vplay 4 30>
I need to get more vasoconstrictor into
those veins before it wears off...

@MSG_OPEs04_MISS_ARTERY_NO_EFT_1
<bup 1 5 1>
<vplay 4 20>
Damn, it wore off... I need to constrict
these arteries before I can move on.

@MSG_OPEs04_MISS_ARTERY_NO_EFT_2
<bup 1 25 1>
Aren't you forgetting the vasoconstrictor?
Inject that first.

@MSG_OPEs04_MISS_VEIN_NO_EFT_1TI
<bup 1 25 1>
You can't do anything until you constrict
those arteries. You told ME that!

@MSG_OPEs04_MISS_VEIN_NO_EFT_2TI
<bup 1 5 1>
<vplay 4 30>
Tch... I can't suture anything with the blood
flowing through it like this.

@MSG_OPEs04_STEP_2VESSEL_STITCHE
<bup 1 5 1>
<vplay 4 25>
I'm on the last one.

@MSG_OPEs04_END_FLOW
<bup 1 5 1>
I've transplanted the kidney successfully.
<wait>
Once the vasoconstrictor wears off, his
blood pressure will return to normal.

@MSG_OPEs04_END_FLOW_AFTER
<bup 1 5 2>
...Everything looks good.
We're done.

@MSG_OPEs04_END_FLOW_REMAIN_LESI
I'll treat the wounds they left behind
and finish the operation.

@MSG_OPEs04_CLOSE_BODY
<bup 1 5 1>
All that's left is suturing it up.

@MSG_OPEs04_END_OPE
<bup 1 5 2>
<vplay 4 10>
The new kidney is working nicely.
I think we're done here.
<wait>
