
@MSG_OPEs03_GAMEOVER
<bup 0 25 1>
I told you it was a waste of time...
<wait>
You did what you could--we need to get
the hell out of here.
<wait>
<bup_cls>

@MSG_OPEs03_START_OPE
<bup 1 5 1>
<vplay 4 6>
Well, these are certainly less than ideal
circumstances...
<wait>
I need to confirm the patient's condition
first, but...
<wait>
...I guess I have to make do with a penlight.

@MSG_OPEs03_CAUTION_PENLIGHT
<bup 1 25 1>
No... I've confirmed it. That penlight is the
only way I'm going to see anything.

@MSG_OPEs03_SELECT_PENLIGHT
<bup 1 5 1>
<vplay 4 29>
...Let there be light.
<wait>
I need to investigate the affected area.

@MSG_OPEs03_CAUTION_PENLIGHT_MOR
<bup 1 5 1>
Hm... I need a little more light in here.

@MSG_OPEs03_USE_PENLIGHT
<bup 1 5 1>
I've confirmed the affected area.
<wait>
I'll begin by treating this laceration on
the right...

@MSG_OPEs03_CAUTION_SLASH_ONSIGH
<bup 1 5 1>
<vplay 4 39>
Um... assistant?
<wait>
<bup 1 25 1>
What do you need?
<wait>
<bup 1 5 1>
Shine this light where I tell you.
<wait>
There isn't a lot of room, but it should be
workable as long as you hold it steady.

@MSG_OPEs03_CAUTION_PENLIGHT_FIX
<bup 1 25 1>
<vplay 25 1>
...I don't see anything. Are you sure it's
shining in the right place?

@MSG_OPEs03_USE_PENLIGHT_FIX
<bup 1 5 1>
<vplay 4 39>
Just hold it steady... You let me worry about
the patient, alright?

@MSG_OPEs03_MISS_NOTHING_LIGHT_1
<bup 1 25 1>
<vplay 25 1>
Do you need me to shine the light in areas
you haven't treated yet?

@MSG_OPEs03_MISS_NOTHING_LIGHT_2
<bup 1 25 1>
<vplay 25 1>
Are you sure poking around in the dark
like that is the best idea?

@MSG_OPEs03_STEP_SLASH_END
<bup 1 5 1>
This seems to be going well.
<wait>
When I need to move on, I'm going to direct
the penlight somewhere else.

@MSG_OPEs03_END_STAGE1
<bup 1 5 1>
<vplay 4 22>
That about does it as far as the external
trauma is concerned...
<wait>
I think it went well, all things considered.
<wait>
Next, I need to find out what happened
in his abdomen.

@MSG_OPEs03_ENTER_BODY
<bup 1 5 1>
I think this is as good as it's going to get...
<wait>
Okay, just like before. Hold the light as
steady as you can.

@MSG_OPEs03_END_STAGE2
<bup 1 5 1>
...How strange. His vitals aren't stabilizing.
I'll need to take another look around...
<wait>
Here we are...
Oh. That's not good.

@MSG_OPEs03_END_STAGE2_AFTER
<bup 1 5 1>
Here we are...
Oh. That's not good.

@MSG_OPEs03_STEP_SLASH_STAGE3
<bup 1 5 3>
<vplay 4 36>
What are you doing!? I need that light!
<wait>
<bup 1 25 1>
I didn't... It wasn't me!
I think the batteries might have died.
<wait>
<bup 1 5 3>
...The batteries? Dammit!
<wait>
<bup 1 25 1>
I knew this was a bad idea--look, we
have to get lost.
<wait>
<bup 1 5 1>
<vplay 4 35>
...There has to be something we can use
around here...
<wait>
<bup 1 25 1>
Wait--what about this?
<wait>
<bup 1 5 1>
It's a camera...?
Oh! The flash!
<wait>
This poor bastard's lucky he's a reporter.

@MSG_OPEs03_SELECT_FLASH
<bup 1 5 1>
The light from the flash won't last long, so
I'll need to memorize the problem areas.

@MSG_OPEs03_USE_FLASH
<bup 1 5 1>
Now, I just need to take care of everything
before I forget where it is.

@MSG_OPEs03_CAUTION_FLASH
<bup 1 25 1>
<vplay 25 1>
Why don't you try using the flash again?

@MSG_OPEs03_MISS_ONEMORE_FLASH
<bup 1 25 1>
<vplay 25 1>
If you forgot, just use the flash again.

@MSG_OPEs03_END_FLOW
<bup 1 5 1>
<vplay 4 26>
I've finished treating his wounds.

@MSG_OPEs03_RETURN_LIGHT
<bup 1 5 1>
...Now the lights are back on.
You've gotta be kidding me.

@MSG_OPEs03_CLOSE_BODY
<bup 1 5 1>
*sigh* I'm going to close him up.

@MSG_OPEs03_END_OPE
<bup 1 5 2>
<vplay 4 10>
Well, I saved him... I hope that's the last
time I ever have to operate in the dark.
<wait>
