
@MSG_OPEs05_GAMEOVER
<bup 0 23 1>
Stop immediately, Dr. Weaver!
<wait>
I thought that you, of all people, would be
able to help us... But, you proved me wrong.
<wait>
<bup_cls>

@MSG_OPEs05_START_OPE
<bup 1 5 1>
<vplay 4 5>
Let's begin the operation.

@MSG_OPEs05_ENTER_BODY
<bup 1 5 1>
<vplay 4 34>
There's no mistaking it; these are definitely
the Kyriaki symptoms you described.

@MSG_OPEs05_START_KYRIAKI_SPAWN
<bup 1 5 1>
I've confirmed Stage 1 Kyriaki bodies.
I'm activating the laser...

@MSG_OPEs05_START_CURSE_SPAWN
<bup 1 5 1>
<vplay 4 36>
What the hell's going on!?
<wait>
<bup 1 23 1>
His vitals... All his graphs are spiking!
<wait>
<bup 1 5 3>
Professor Blackwell! What's happening
to him!?
<wait>
<bup 1 23 1>
There were some uncertainties in the
Chiral readings for this patient...
<wait>
...I believe we now know why.
<wait>
<bup 1 5 1>
So what is it!?
<wait>
<bup 1 23 1>
...If we continue the pattern, this...would
be called Savato.
<wait>
<bup 1 5 1>
Pattern...?
This is another GUILT!?
<wait>
<bup 1 23 1>
Yes... I'm afraid this complicates the
operation procedures.
<wait>
I need you to collect a sample of that
GUILT at some point during treatment.
<wait>
...Capture the GUILT, Dr. Weaver.
<wait>
<bup 1 5 1>
Capture it? How on Earth am I going
to do that?
<wait>
<bup 1 23 1>
I will prepare a drug that should restrict
the GUILT's movement for...a moment.
<wait>
I'll need some time--please continue to
treat the patient without harming the GUILT.
<wait>
<bup 1 5 1>
Don't kill it, huh? Sure, that should only
be nigh-impossible.
<wait>
<bup 1 23 1>
Without it, we have no way of developing
a proper treatment.
<wait>
I'm depending on you, Doctor. Will you be
able to handle this?
<wait>
<bup 1 5 2>
I don't have much of a choice. ...Don't
worry, I'll keep both of 'em alive.
<wait>
<bup 1 23 1>
In that case, I'll start preparing the
neutralizer.
<wait>
<bup 1 5 1>
Right, yeah... Take your time!

@MSG_OPEs05_START_CURSE_SPAWN_AF
<bup 1 5 3>
<vplay 4 30>
(This is insane...) More Kyriaki!?
At least I know how to handle them...

@MSG_OPEs05_CAUTION_CURSE_LASER_
<bup 1 25 1>
The laser seems effective on the new
GUILT as well, but...
<wait>
<bup 1 5 1>
...Blackwell told me not to kill it.

@MSG_OPEs05_CAUTION_CURSE_LASER_
<bup 1 25 1>
<vplay 25 2>
Weren't you listening to Professor
Blackwell?
<wait>
<bup 1 5 1>
I know, I know... I'm not supposed
to kill this...Savato thing.

@MSG_OPEs05_CAUTION_CURSE_KILLED
<bup 1 5 1>
<vplay 4 41>
He only needs one sample, right?
<wait>
<bup 1 25 1>
<vplay 25 4>
Probably, but...be careful not to go
overboard.

@MSG_OPEs05_CAUTION_CURSE_KILLED
<bup 1 5 3>
<vplay 4 42>
...Argh! It keeps getting in my way.
<wait>
<bup 1 25 1>
<vplay 25 5>
Doctor! We won't get another shot at this!
You have to stop killing that GUILT!

@MSG_OPEs05_STEP_KYRIAKI_END
<bup 1 23 1>
Ah, I see it's progressing...
Here is the treatment.
<wait>
<bup 1 5 1>
May I proceed, Professor?
<wait>
<bup 1 23 1>
Yes. This drug should put it in a state of
suspended animation. Temporarily, of course.
<wait>
Inject that into the Savato, then capture
the GUILT with your forceps.

@MSG_OPEs05_STEP_CURSE_CAPTURE_1
<bup 1 25 1>
<vplay 25 6>
...You did it.
Good work, Doctor.
<wait>

@MSG_OPEs05_STEP_CURSE_CAPTURE_2
<bup 1 25 1>
<vplay 25 6>
...You did it. Now just capture the other
ones and we can put this all behind us.

@MSG_OPEs05_STEP_CURSE_CAPTURE_2
<bup 1 25 1>
<vplay 25 6>
That wraps it up...
Good work, Doctor.
<wait>

@MSG_OPEs05_END_FLOW_REMAIN_LESI
<bup 1 5 1>
<vplay 4 43>
I'll treat the wounds they left behind
and finish the operation.

@MSG_OPEs05_CLOSE_BODY
<bup 1 5 1>
I can't believe how quickly that Savato
dropped the patient's vitals...

@MSG_OPEs05_END_OPE
<bup 1 5 2>
<vplay 4 11>
Operation complete... (What are they going
to have me doing next?)
<wait>
