
@MSG_OPE907_GAMEOVER
<bup 0 22 1>
Mankind strives toward death...
Only a fool could deny that.
<wait>
<bup_cls>

@MSG_OPE907_START_OPE
<bup 1 22 10>
No matter how hard you try, you cannot
overcome the power of death!

@MSG_OPE907_HT_HINT
<bup 1 6 3>
I'll have to try it the way Derek does...

@MSG_OPE907_HT_USE
<bup 1 6 2>
I must have done it well enough,
cause it worked.

@MSG_OPE907_END_OPE
<bup 1 22 10>
Your skills have given birth to many lives
which never should have been.
<wait>
As it is written in Revelation 9:6,
"During those days men will seek death, but
<wait>
will not find it--they will long to die, but
death will elude them."
<wait>
Just as the prophecy states, I have set a
plague upon mankind to torment those
<wait>
who have betrayed natural law. ...At the end
of all life, I alone will stand as an angel
<wait>
before the gaping abyss... I, who have
become the great destroyer Apollyon!
<wait>
...Your medicine is deceit, and you are
nothing but a false prophet...
<wait>
