
@MSG_EVTGOAA_001
<telop 0>
...A few days later, Derek Stiles mysteriously
disappeared without saying a word to
anyone.
<wait>

@MSG_EVTGOAA_002
<telop 0>
The burden of the patients' lives turned
out to be more than he could bear.
<wait>

@MSG_EVTGOAA_003
<telop 0>
While it might seem unfair of fate to bestow
the immense responsibility of the Healing
Touch on such a young doctor...
<wait>

@MSG_EVTGOAA_004
<telop 0>
...after his final operation, most people would
agree that Dr. Stiles had no business treating
patients in the first place.
<wait>
<telop_cls>
