
#伊東優乃

@MSG_EVT503CA_001
<bup 0 18 1>
Your next patient has been
prepped, Dr. Stiles!
<wait>

#利根川アンジュ

@MSG_EVT503CA_002
<bup 0 8 5>
We're ready in here.
Let's proceed, Doctor!
<wait>
<bup_cls>

#月森孝介

@MSG_EVT503CB_001
<bup 0 2 4>
Phew... We did it...
<wait>

#伊東優乃

@MSG_EVT503CB_002
<bup 0 18 2>
Great work, Dr. Stiles. ...Do you think
this will be over soon?
<wait>
<bup_cls>

#利根川アンジュ

@MSG_EVT503CB_003
<bup 0 8 5>
Doctor! A case of the Tetarti strain has been
confirmed nearby!
<wait>

#月森孝介

@MSG_EVT503CB_004
<bup 0 2 3>
...Well, it's not over yet.
<wait>
Tell them we're on the way!
<wait>
<bup_cls>
