
@MSG_EVT002A_001
<bup 0 20 1>
...The plane is ready, Director.
<wait>

@MSG_EVT002A_002
<bup 0 19 1>
I see.
<wait>
Dr. Stiles, Nurse Thompson...your flight home
has arrived.
<wait>

@MSG_EVT002A_003
<bup 0 2 1>
You didn't have to organize all of this
for us.
<wait>

@MSG_EVT002A_004
<bup 0 19 1>
On the contrary, I wish I could do more for
the heroes who saved us all.
<wait>
I know a lot has happened, but I do hope
you'll forgive our insolence...
<wait>

@MSG_EVT002A_005
<bup 0 8 5>
...You should apologize to the people you
treated with Adam's cells.
<wait>

@MSG_EVT002A_006
<bup 0 19 1>
That's very true.
<wait>
We've received orders from Parliament to
cease all GUILT research immediately.
<wait>
Caduceus Europe is under investigation, and
only operating on a provisional basis.
<wait>
We will probably be tried for our actions...
<wait>

@MSG_EVT002A_007
<bup 0 2 5>
GUILT was designed for the sole purpose
of wiping out mankind...
<wait>
You should have realized it couldn't be
used for anything else.
<wait>

@MSG_EVT002A_008
<bup 0 19 1>
Doctors learn from their mistakes, and we're
no different.
<wait>
...I won't let this happen again.
<wait>

@MSG_EVT002A_009
<bup 0 2 1>
You have a lot of skilled people to help you,
sir. ...Good luck, Dr. Kimishima.
<wait>

@MSG_EVT002A_010
<bup 0 6 2>
Same to you.
America's in good hands.
<wait>

@MSG_EVT002A_011
<bup 0 2 1>
Thanks.
<wait>
Hey, you should come visit us some time.
<wait>

@MSG_EVT002A_012
<bup 0 6 2>
I can't go back.
I've left America behind me.
<wait>
I bargained for amnesty in Europe, but I doubt
your country is so willing to forgive.
<wait>
...Take good care of him, Angie.
<wait>

@MSG_EVT002A_013
<bup 0 8 1>
Huh?
Oh, of course...
<wait>
My stay here was an emotional one, but
I learned a lot from you, Doctor.
<wait>
<bup 0 8 2>
Seeing you and Dr. Stiles working together
inspired me to be a better assistant. ...Thanks.
<wait>

@MSG_EVT002A_014
<bup 0 19 1>
Now that we've said our goodbyes, allow me
to accompany you both to the airstrip.
<wait>
<bup_cls>

@MSG_EVT002A_015
<bup 0 17 1>
...Now they're stuck in northern Afghanistan?
Man, I feel sorry for Derek.
<wait>
Are there any countries we haven't sent 'em
to yet?
<wait>

@MSG_EVT002A_016
<bup 0 18 1>
I hope Angie isn't too homesick.
<wait>
<bup 0 18 2>
Then again, she gets to see all those neat
places and eat exotic foods...
<wait>

@MSG_EVT002A_017
<bup 0 14 1>
Angie will be fine. I'd say Derek is the one
you need to worry about.
<wait>
...At least he has Dr. Chase here to take care
of his workload while he's away.
<wait>

@MSG_EVT002A_018
<bup 0 17 1>
Ha! Don't dump that on me.
<wait>
But seriously, those two deserve a nice
long vacation...
<wait>
All this work hasn't left them much time
to spend with each other.
<wait>

@MSG_EVT002A_019
<bup 0 18 1>
...What do you mean? They're working
together all the time.
<wait>

@MSG_EVT002A_020
<bup 0 17 1>
Oh come on...
You know what I'm talking about.
<wait>
<bup_cls>

@MSG_EVT002A_021
<bup 0 13 1>
Director Hoffman...
<wait>
The education division wanted to have a word
with you about next month's training course.
<wait>
Something about the curriculum, I believe.
...Did you need me to handle that?
<wait>

@MSG_EVT002A_022
<bup 0 9 5>
Ah, thanks for letting me know. I should be
able to take care of it myself...
<wait>
They invited a neurosurgeon from Germany
to lecture for a week or two.
<wait>
I just need to modify the course structure
accordingly.
<wait>

@MSG_EVT002A_023
<bup 0 13 1>
I see.
<wait>

@MSG_EVT002A_024
<bup 0 9 5>
This is the first educational seminar Caduceus
has offered, so there's a lot to worry about.
<wait>
But, if we're going to provide medical care to
the entire world, it's an important step to take.
<wait>
People are going to depend on our doctors;
we owe them the best training available.
<wait>

@MSG_EVT002A_025
<bup 0 13 1>
I understand.
Let me know if there's anything I can do.
<wait>

@MSG_EVT002A_026
<bup 0 9 5>
Thank you. 
<wait>
...Speaking of which, I need you to mail this
for me, addressed to one Dr. Derek Stiles.
<wait>

@MSG_EVT002A_027
<bup 0 13 1>
...What's in the package?
<wait>

@MSG_EVT002A_028
<bup 0 9 5>
Letters of gratitude we've received from his
patients all over the world.
<wait>
Stiles deserves to know he's making a
difference, don't you think?
<wait>
...I decided I should send him some reading
material for the plane ride home.
<wait>
<bup_cls>

@MSG_EVT002T_001
<telop 0>
With tragedy in Europe narrowly averted,
Caduceus International proposed a new treaty
to govern all further GUILT research.
<wait>

@MSG_EVT002T_002
<telop 0>
The treaty was ratified by most world
governments immediately, requiring that any
GUILT-related studies be approved and
disclosed to avoid further outbreaks.
<wait>

@MSG_EVT002T_003
<telop 0>
In addition, participating countries would be
granted a Caduceus-appointed Medical
Director who could act without executive
approval.
<wait>

@MSG_EVT002T_004
<telop 0>
These directors became guardians of national
health, moving toward a brighter future and
ever vigilant against new threats.
<wait>

@MSG_EVT002T_005
<telop 0>
Thus mankind banded together to share
knowledge and resources in the war against
GUILT and medical terrorism.
<wait>
<telop_cls>
