
#伊東優乃

@MSG_EVT503BA_001
<bup 0 18 1>
A patient with similar symptoms should
be arriving shortly.
<wait>

#月森孝介

@MSG_EVT503BA_002
<bup 0 2 5>
Got it!
<wait>
<bup_cls>

#月森孝介

@MSG_EVT503BB_001
<bup 0 2 4>
Phew... We did it...
<wait>

#伊東優乃

@MSG_EVT503BB_002
<bup 0 18 2>
Great work, Dr. Stiles. ...Do you think
this will be over soon?
<wait>
<bup_cls>

#利根川アンジュ

@MSG_EVT503BB_003
<bup 0 8 5>
Doctor! A case of the Tetarti strain has been
confirmed nearby!
<wait>

#月森孝介

@MSG_EVT503BB_004
<bup 0 2 3>
...Well, it's not over yet.
<wait>
Tell them we're on the way!
<wait>
<bup_cls>
