
@MSG_EVT103A_001
- Hope Hospital, Nurse's Station -
<wait>

#古村百恵

@MSG_EVT103A_002
<bup 0 11 1>
...And so, since my husband's been
relocated to a different office...
<wait>
I'll be leaving Hope Hospital,
effective immediately.
<wait>
I'm really going to miss this place and all
the friends I made here...
<wait>
but I promise to continue my work
as a nurse, wherever life takes me!
<wait>
You all taught me that nothing is more
satisfying than helping patients.
<wait>

#沓掛真一

@MSG_EVT103A_003
<bup 0 10 1>
It was a pleasure to have you
on staff, Mary.
<wait>
Good luck with the new job.
<wait>

#月森孝介

@MSG_EVT103A_004
<bup 0 1 4>
I can't believe you're leaving.
This is all so sudden...
<wait>

#沓掛真一

@MSG_EVT103A_005
<bup 0 10 2>
How are you going to get by without
her, Derek?
<wait>

#古村百恵

@MSG_EVT103A_006
<bup 0 11 1>
...Actually...
<wait>
Derek's the one reason I was a little
hesitant to leave...
<wait>
I even spoke with my husband about it.
<wait>
I told him there was a kid here who
depends on me.
<wait>
<bup 0 11 2>
He asked me how long I'd been working
in pediatrics! Ha ha!
<wait>

#月森考介

@MSG_EVT103A_007
<bup 0 1 4>
Ah c'mon...
I'm not that bad.
<wait>
<bup_cls>

#北崎威一郎

@MSG_EVT103A_008
<bup 0 9 1>
Is Nurse Fulton still here?
<wait>

#古村百恵

@MSG_EVT103A_009
<bup 0 11 1>
Oh, hello Dr. Hoffman.
<wait>

#北崎威一郎

@MSG_EVT103A_010
<bup 0 9 1>
I'm not interrupting anything, am I?
<wait>

##

@MSG_EVT103A_011
Robert Hoffman, age 62: The director
and founder of Hope Hospital.
<wait>
He used to be a renowned surgeon, but then
retired to work in management.
<wait>

#古村百恵

@MSG_EVT103A_012
<bup 0 11 1>
No, of course not.
<wait>

#北崎威一郎

@MSG_EVT103A_013
<bup 0 9 1>
I came to say goodbye, since I
won't be around tomorrow.
<wait>
Thank you for your many years of
dedicated service.
<wait>
You're a fantastic nurse...
...Probably our best.
<wait>
On behalf of our entire staff,
I'd like to say thank you.
<wait>

#古村百恵

@MSG_EVT103A_014
<bup 0 11 1>
Oh... Sir, the pleasure was all mine.
<wait>
I wish there was some way I could
thank you for this opportunity.
<wait>

#北崎威一郎

@MSG_EVT103A_015
<bup 0 9 1>
Well, you're not going to stop
nursing, are you?
<wait>
If you continue to help people,
that will be thanks enough.
<wait>

#古村百恵

@MSG_EVT103A_016
<bup 0 11 1>
Of course, sir! Helping people is my life.
<wait>
It's just...
<wait>
I wish I could stay and learn
from you a little longer.
<wait>

#北崎威一郎

@MSG_EVT103A_017
<bup 0 9 1>
Don't be modest. You already know
everything I could teach you.
<wait>
I'm afraid Dr. Kasal surpassed me
as a surgeon long ago.
<wait>

#沓掛真一

@MSG_EVT103A_018
<bup 0 10 1>
Dr. Hoffman...
<wait>

#北崎威一郎

@MSG_EVT103A_019
<bup 0 9 1>
Good luck with your new job.
Don't be a stranger, all right?
<wait>
...At any rate, I have other matters to
attend to. If you'll excuse me...
<wait>
<bup_cls>

#古村百恵

@MSG_EVT103A_020
<bup 0 11 1>
I wish I could have seen Dr. Hoffman in
action more often...
<wait>
but he hasn't performed any operations
since that incident.
<wait>

#沓掛真一

@MSG_EVT103A_021
<bup 0 10 1>
Derek, let's discuss the next patient.
<wait>

#月森考介

@MSG_EVT103A_022
<bup 0 1 1>
Yes, sir.
<wait>

#古村百恵

@MSG_EVT103A_023
<bup 0 11 1>
This will be my last procedure at Hope...
Don't let me down, Derek.
<wait>
<bup_cls>

#古村百恵

@MSG_EVT103B_001
<bup 0 11 2>
You did a great job, Derek.
It looks like I have nothing to worry about.
<wait>
You're going to make an excellent surgeon.
<wait>
Please continue using your abilities
to help the people of Angeles Bay.
<wait>
<bup_cls>
