
@MSG_EVT107A_001
<bup 0 9 1>
I understand you didn't have much
information to base a decision on...
<wait>
...and I do admit that the tumor was
difficult to see from the X-ray.
<wait>
However, the laboratory left you
several memos about the patient.
<wait>
I understand they pointed out his
extremely high readings.
<wait>
...More than that, you dumped your
responsibilities onto a nurse immediately
<wait>
following a very delicate operation.
<wait>

@MSG_EVT107A_002
<bup 0 1 4>
It wasn't...
I mean--
<wait>
<bup_cls>

@MSG_EVT107A_003
"Ms. Thompson, what are you--!?"
<wait>

@MSG_EVT107A_004
<bup 0 7 5>
Please excuse me for interrupting,
Dr. Hoffman...
<wait>
I understand this is a little rude,
but I have to say something.
<wait>

@MSG_EVT107A_005
<bup 0 9 1>
...What is it?
<wait>

@MSG_EVT107A_006
<bup 0 7 5>
It's about...the negligent attitude
Mr. Stiles has displayed thus far.
<wait>
I warned him about this patient at least
three times, but he said that there were
<wait>
important personal matters he had to
take care of.
<wait>
Then he just walked out, without
another word.
<wait>
Mr. Stiles... Maybe you didn't harm
the patient directly...
<wait>
But...
<wait>
<bup 0 7 3>
How can I work under a doctor who
doesn't even try to act like one!?
<wait>
It doesn't matter how small or
groundless a suspicion might be...
<wait>
The patients are depending on you
to take care of them!
<wait>
Why did you become a doctor?
Do you even know!?
<wait>

@MSG_EVT107A_007
<bup 0 1 4>
I--
That is, I...
<wait>

@MSG_EVT107A_008
<bup 0 7 3>
You don't deserve to be here!
<wait>
You... You're not a real doctor!
<wait>

@MSG_EVT107A_009
<bup 0 1 4>
......!
<wait>
<bup_cls>

@MSG_EVT107A_010
<bup 0 1 4>
I really screwed up...
I... ignored a patient...
<wait>
I was trying my best... I didn't
think it was anything serious...
<wait>
But, a patient almost died--and it
was all my fault...
<wait>
Being called "Dr. Stiles" doesn't
make me a good doctor...
<wait>
...What was I thinking?
<wait>
I'm no doctor... Not if I keep
making mistakes like that.
<wait>
<bup_cls>

@MSG_EVT107A_011
"Uh oh, looks like rain."
<wait>
"Hurry up, you two! We need to get
all our displays inside!"
<wait>

@MSG_EVT107A_012
<bup 0 1 4>
Rain... Maybe that'll help calm me down.
<wait>
It couldn't make things any worse...
<wait>
<bup_cls>

@MSG_EVT107A_013
"S-Sir? It looks like you're completely
soaked..."
<wait>
"Did you come from a hospital? You
might wanna head back pretty soon."
<wait>

@MSG_EVT107A_014
<bup 0 1 4>
...They don't want me there.
<wait>
I'm apparently useless as a doctor.
<wait>
<bup_cls>

@MSG_EVT107A_015
"Hey! Yeah, it's me. You're never going
to believe what I just saw..."
<wait>
"Huh? Well, you can guess if you
want...... Nope. It's even better!"
<wait>
"There was this crazy accident on Walnut
between a truck and an SUV--it was nuts!"
<wait>
"The drivers flew into the street, and...
Huh? No, it really happened!"
<wait>

@MSG_EVT107A_016
<bup 0 1 4>
...An accident on Walnut?
<wait>
They're going to be taken to our trauma ward,
but Dr. Kasal's out of town...
<wait>
<bup 0 1 3>
...and there aren't any emergency
doctors on call!
<wait>
<bup_cls>
