
@MSG_EVT108A_001
<bup 0 1 3>
...I was right. Then, there's no time to lose!
<wait>
<bup_cls>

@MSG_EVT108A_002
<bup 0 1 5>
Where are the accident victims, Angie!?
<wait>

@MSG_EVT108A_003
<bup 0 7 4>
Dr. Stiles...
<wait>
The patient... He was suffering
cardiac arrest, and... and...
<wait>
I couldn't resuscitate him!
The other nurses are busy, and...
<wait>
With Dr. Kasal gone, I can't...
...Wh-What am I supposed to do?
<wait>
The patient's going to die!
But, I can't... I can't even...
<wait>

@MSG_EVT108A_004
<bup 0 1 5>
Calm down, Angie!
...Take me to the O.R.
<wait>

@MSG_EVT108A_005
<bup 0 7 4>
O-Okay...
<wait>
<bup_cls>

@MSG_EVT108B_001
<bup 0 1 1>
(I've never felt that way before...
I think I'm starting to understand.)
<wait>
His condition's stabilized for now.
Let's keep an eye on him.
<wait>

@MSG_EVT108B_002
<bup 0 7 1>
Yes, Doctor.
<wait>

@MSG_EVT108B_003
<bup 0 1 1>
We need to contact the other
doctors, and--
<wait>

@MSG_EVT108B_004
<bup 0 7 1>
I'm way ahead of you.
<wait>
Most of the off-duty staff have agreed
to come in. I also called Dr. Kasal.
<wait>

@MSG_EVT108B_005
<bup 0 1 1>
Good work... Thank you.
<wait>

@MSG_EVT108B_006
<bup 0 7 1>
You should get some rest. We were
in surgery for a long time.
<wait>

@MSG_EVT108B_007
<bup 0 1 1>
Yeah... If it's okay with you,
I think I'll do that.
<wait>
<bup 0 1 4>
Angie...
<wait>

@MSG_EVT108B_008
<bup 0 7 1>
Yes?
<wait>

@MSG_EVT108B_009
<bup 0 1 4>
...Everything you said this morning was true.
<wait>

@MSG_EVT108B_010
<bup 0 7 5>
......
<wait>

@MSG_EVT108B_011
<bup 0 1 4>
But... I'm going to stay here as a doctor.
<wait>
I'm going to try harder... I'll become a
better surgeon, and make you proud.
<wait>

@MSG_EVT108B_012
<bup 0 7 5>
...If that's the case...
<wait>
Stop coming into work late, and don't
leave without doing your paperwork.
<wait>

@MSG_EVT108B_013
<bup 0 1 4>
...I'll do my best.
<wait>

@MSG_EVT108B_014
<bup 0 7 5>
And, there's one other thing...
<wait>

@MSG_EVT108B_015
<bup 0 1 4>
Huh?
<wait>

@MSG_EVT108B_016
<bup 0 7 1>
Please try to be more presentable.
<wait>
...I shouldn't have to worry about being
embarrassed to work with you.
<wait>

@MSG_EVT108B_017
<bup 0 1 4>
Heh...
...I'll be more careful.
<wait>
<bup 0 1 1>
*yawn* Okay, I'm taking a nap.
Wake me up if anything changes.
<wait>

@MSG_EVT108B_018
<bup 0 7 1>
I understand.
Have a good rest...
<wait>

@MSG_EVT108B_019
...Dr. Stiles.
<wait>
<bup_cls>
