
@MSG_EVT106A_001
"Thank you so much, Doctor!"
<wait>

@MSG_EVT106A_002
<bup 0 1 1>
Take care, now.
<wait>
<bup_cls>

@MSG_EVT106A_007
<bup 0 1 2>
...Well, that looks like our last walk-in
for today...
<wait>
Angie, let's start our pre-op at around
one o'clock, okay?
<wait>

@MSG_EVT106A_003
<bup 0 7 5>
Don't you think we should have
examined him more carefully?
<wait>
There were signs of cyanosis, which
could indicate asthma.
<wait>
If that's the case, he needs to see his
physician right away.
<wait>

@MSG_EVT106A_004
<bup 0 1 1>
...Really? I didn't think it looked
like anything serious.
<wait>

@MSG_EVT106A_005
<bup 0 7 5>
You need to start acting like a real doctor,
Mr. Stiles!
<wait>

@MSG_EVT106A_006
<bup 0 1 1>
You're overreacting...
I'm sure he'll be fine.
<wait>
<bup_cls>

@MSG_EVT106B_001
<bup 0 7 5>
Dr. Stiles...
<wait>

@MSG_EVT106B_002
<bup 0 1 1>
Oh, hey Angie.
Thanks for your help in there.
<wait>

@MSG_EVT106B_003
<bup 0 7 5>
I'd like to have a word with you
about that last operation.
<wait>

@MSG_EVT106B_004
<bup 0 1 1>
Hmm...? Was there something wrong
with my bedside manner?
<wait>

@MSG_EVT106B_005
<bup 0 7 5>
No, it's about the patient, actually...
<wait>
...His white blood cell and globulin counts
are rising rapidly.
<wait>
I also noticed inflammation along
the patient's peritoneum...
<wait>
We should re-examine him immediately
and consult his regular doctor.
<wait>

@MSG_EVT106B_006
<bup 0 1 1>
I agree with you... But I'm afraid it
will have to wait until tomorrow.
<wait>
I'm supposed to help with the next
symposium, so I'm meeting with some
<wait>
doctors from St. Francis to learn the
ropes and everything.
<wait>

@MSG_EVT106B_007
<bup 0 7 5>
But--
<wait>

@MSG_EVT106B_008
<bup 0 1 1>
They traveled a long way to meet with me,
and I can't just blow them off.
<wait>
We'll handle this first thing tomorrow,
I promise!
<wait>
<bup_cls>

@MSG_EVT106B_009
<bup 0 7 5>
But...!
<wait>
<bup_cls>

@MSG_EVT106B_010
<bup 0 3 2>
...Too bad I have work tomorrow. I would've
liked to talk a bit longer.
<wait>
Oh well, at least now I'm ready
for that symposium thing!
<wait>
<bup_cls>

@MSG_EVT106B_015
<bup 0 3 1>
Hm...?
Oh, my cellphone!
<wait>
<bup_cls>

@MSG_EVT106B_011
"Derek! Where are you!?"
<wait>
"The patient is in critical condition!
Get back here right now!"
<wait>

@MSG_EVT106B_012
<bup 0 3 5>
...What!?
<wait>
T-Taxi! Take me to Hope Hospital,
and step on it!
<wait>
<bup_cls>

@MSG_EVT106B_013
<bup 0 3 5>
Angie...
<wait>

@MSG_EVT106B_014
<bup 0 7 5>
A tumor metastisized behind his lungs,
which then began swelling.
<wait>
It continued to fester until 30 minutes ago,
when the tumor ruptured...
<wait>
The patient is in shock and
suffering acute peritonitis.
<wait>
...The other doctors are operating
on him as we speak.
<wait>
Follow me, Mr. Stiles...
<wait>
You need to see the consequences
of your carelessness!
<wait>
<bup_cls>
