
#古村百恵

@MSG_EVT102A_001
<bup 0 11 1>
Judging from the MRI, the tumor
is isolated in his stomach.
<wait>
It's benign, but you should
be prepared for anything.
<wait>
Any questions, Dr. Stiles?
<wait>

#月森考介

@MSG_EVT102A_002
<bup 0 1 1>
...Huh? Oh...
<wait>
Yeah, I'm fine...
Thanks anyway.
<wait>

#古村百恵

@MSG_EVT102A_003
<bup 0 11 3>
Are you even listening!?
<wait>
I know you're stressed, but this just so
happens to be your job.
<wait>
Are you getting enough sleep?
<wait>
You need at least six hours a night! I'm sure
they went over that in med school.
<wait>
These patients are depending on you!
<wait>

#沓掛真一

@MSG_EVT102A_004
<bup 0 10 1>
Derek, don't forget our follow-up appointment
with Mr. Jenkins this afternoon.
<wait>
Have you read the report?
<wait>

#月森考介

@MSG_EVT102A_005
<bup 0 1 4>
...I haven't, actually...
<wait>

#沓掛真一

@MSG_EVT102A_006
<bup 0 10 1>
You need to shape up--this is real life.
We aren't playing games.
<wait>

#古村百恵

@MSG_EVT102A_007
<bup 0 11 1>
You've been here three years, Derek.
<wait>
We shouldn't still have to babysit you.
<wait>
This might be grounds to open an
investigation...
<wait>
"The impaired medical and social
development of Dr. Derek Stiles."
<wait>

#月森考介

@MSG_EVT102A_008
<bup 0 1 4>
Harsh...
Cut me some slack, Mary.
<wait>

#沓掛真一

@MSG_EVT102A_009
<bup 0 10 1>
You're not a resident doctor anymore,
Stiles. You know that.
<wait>
By the way, Mary...
I spoke with Dr. Hoffman.
<wait>

#古村百恵

@MSG_EVT102A_010
<bup 0 11 1>
Thank you very much.
<wait>

#月森考介

@MSG_EVT102A_011
<bup 0 1 1>
Wait, you spoke with the director?
...About what?
<wait>

#古村百恵

@MSG_EVT102A_012
<bup 0 11 2>
Don't worry.
It's none of your business.
<wait>

#沓掛真一

@MSG_EVT102A_013
<bup 0 10 1>
It's a personal matter.
Forget I ever mentioned it.
<wait>

#月森考介

@MSG_EVT102A_014
<bup 0 1 1>
Are you going on vacation or something?
<wait>
...I wouldn't mind a nice, long cruise, myself.
Lounging in the sun... The sea stretching--
<wait>

#古村百恵

@MSG_EVT102A_015
<bup 0 11 1>
Okay, okay, that's enough.
We have an operation to perform.
<wait>
<bup_cls>

#沓掛真一

@MSG_EVT102B_001
<bup 0 10 1>
Nice work, Derek. You really took your
time and did things right.
<wait>
Just remember that the patient's
safety always comes first.
<wait>

#古村百恵

@MSG_EVT102B_002
<bup 0 11 1>
You're getting better every day.
Keep up the good work!
<wait>
<bup_cls>
