
@MSG_EVT105A_001
<bup 0 1 1>
Good morning.
<wait>

@MSG_EVT105A_002
<bup 0 7 5>
Hello, Dr. Stiles.
<wait>
You were supposed to be here
fifteen minutes ago.
<wait>
Your patients shouldn't have to wait
just because you're behind schedule.
<wait>

@MSG_EVT105A_003
<bup 0 1 1>
...Uh, I'm sorry?
<wait>

@MSG_EVT105A_004
<bup 0 7 5>
Anyway, I'll call in the first one.
<wait>
<bup_cls>

@MSG_EVT105A_005
<bup 0 1 1>
(Man, she's strict...)
<wait>

@MSG_EVT105A_006
<bup 0 7 5>
Please have a seat, Mr. Cox.
<wait>
<bup_cls>

@MSG_EVT105A_007
<bup 0 29 4>
Y-Yo, doc...
<wait>

@MSG_EVT105A_008
<bup 0 1 1>
During today's surgery, we'll be removing
a polyp from your throat.
<wait>
How are you feeling? It's important for us
to know about any changes to your condition.
<wait>
There could be problems if anything
unexpected happens.
<wait>

@MSG_EVT105A_009
<bup 0 29 4>
I dunno, fine I guess...?
...I really don't know...
<wait>

@MSG_EVT105A_010
<bup 0 1 1>
Huh?
<wait>

@MSG_EVT105A_011
<bup 0 29 4>
It's just not fair, y'know...? I spend years
working part-time, keeping the dream alive...
<wait>
Now, we finally land a contract with
a bigtime record producer...
<wait>
...and my throat's screwed up. So, what?
If something goes wrong, I wasted my life?
<wait>
I have to work retail 'til I die because
of this stupid polyp thing?
<wait>

@MSG_EVT105A_012
<bup 0 1 1>
J-Just try to relax...
We're hoping for the best.
<wait>

@MSG_EVT105A_013
<bup 0 29 4>
Oh, yeah, "hoping" huh?
<wait>
That's clearly all it takes, right? "Hope."
Not practice, not discipline...
<wait>
...If you could get by on hope, I woulda
had a record deal years ago!
<wait>
Maybe Dad was right... I was stupid to
think I could be a rock star.
<wait>

@MSG_EVT105A_014
<bup 0 1 1>
C'mon, try to stay positive.
You're going to be fine. Really.
<wait>

@MSG_EVT105A_015
<bup 0 29 4>
Sorry Dex, Nate, Tisha...
<wait>
...You guys fronted the money and I just
ended up letting you down...
<wait>
I don't even think I'll be able to pay it back.
<wait>

@MSG_EVT105A_016
<bup 0 7 5>
...I need to take your blood pressure,
Mr. Cox. This way, please.
<wait>

@MSG_EVT105A_017
<bup 0 29 4>
Tch... Yeah, whatever.
<wait>
<bup_cls>

@MSG_EVT105A_018
<bup 0 7 3>
Why didn't you just tell him
everything would be fine?
<wait>

@MSG_EVT105A_019
<bup 0 1 1>
...Wait, what?
<wait>

@MSG_EVT105A_020
<bup 0 7 3>
Don't you even read your own notes?
You knew he was nervous about this!
<wait>
Our job is about more than just
treating illnesses...
<wait>
Proper bedside manner is an essential
element in a patient's recovery!
<wait>
Things you say directly affect
these people's attitudes.
<wait>
Don't you get it!?
<wait>

@MSG_EVT105A_021
<bup 0 1 1>
Y-Yeah...
...I do.
<wait>

@MSG_EVT105A_022
<bup 0 7 5>
I hope you handle things more appropriately
during surgery this afternoon.
<wait>
<bup_cls>

@MSG_EVT105B_001
<bup 0 1 2>
Well, Mr. Cox, your operation
was a complete success!
<wait>

@MSG_EVT105B_002
<bup 0 29 10>
...uh......
<wait>

@MSG_EVT105B_003
<bup 0 1 2>
Don't try to speak yet--your throat needs
to rest for a few days.
<wait>
No worries, though. A week from now, you'll
be belting out power ballads, good as new.
<wait>
Speaking of which... how about a couple of
tickets to your next concert? Heh heh...
<wait>

@MSG_EVT105B_004
<bup 0 7 5>
.........
<wait>
<bup_cls>
