
@MSG_EVT104A_001
...And so, we all felt you deserved
a special gift of appreciation...
<wait>
Thank you for 18 years of dedicated
service, Mrs. Fulton.
<wait>

@MSG_EVT104A_002
<bup 0 11 1>
I don't really know what to say!
...I'm a little embarrassed.
<wait>

@MSG_EVT104A_003
<bup 0 10 1>
Mrs. Fulton was more than a great
nurse--she looked after us, as well.
<wait>
...She will be missed.
<wait>

@MSG_EVT104A_004
<bup 0 11 2>
Are you sure you're not glad
to be free of my nagging?
<wait>

@MSG_EVT104A_005
<bup 0 10 1>
What are you talking about?
<wait>
I'm just worried Derek's going to start
coming to work late again.
<wait>
You're the one who kept him in line, Mary.
<wait>

@MSG_EVT104A_006
<bup 0 1 6>
...Ah geez...
I'm standing right here, guys.
<wait>
<bup 0 1 1>
You don't need to worry. I'll be fine
without Mary's help.
<wait>
I may be young, but I'm still a doctor!
<wait>

@MSG_EVT104A_007
<bup 0 11 2>
That's good to hear...
<wait>
So, no more sobbing phone calls
from you, huh?
<wait>

@MSG_EVT104A_008
<bup 0 1 3>
Wh-What!?
I wasn't crying!
<wait>

@MSG_EVT104A_009
<bup 0 11 2>
I'm just teasing, Derek.
<wait>
<bup 0 11 1>
You've grown so much since you
joined us and I'm proud of you.
<wait>
Work hard, and you'll surpass even
Dr. Kasal, one day...
<wait>
Don't forget that I believe in you.
<wait>
<bup_cls>

@MSG_EVT104A_010
Nurse: "She isn't here yet."
<wait>

@MSG_EVT104A_011
Nurse: "She called in about some emergency,
but didn't go into detail."
<wait>

@MSG_EVT104A_012
<bup 0 1 1>
...Is something wrong?
<wait>

@MSG_EVT104A_013
<bup 0 11 1>
They must be talking about
my replacement.
<wait>
Since I'm leaving, you're going to need
a new assistant.
<wait>
I was supposed to train her
this afternoon, but...
<wait>
HR assured me she's very reliable.
...I hope everything's okay.
<wait>
<bup_cls>

@MSG_EVT104A_014
"Sorry I'm late!"
<wait>

@MSG_EVT104A_015
I'm Angie Thompson, the new nurse.
I'll be starting here tomorrow.
<wait>

@MSG_EVT104A_016
Angie Thompson, age 21: It appears she's
Hope Hospital's newest employee.
<wait>
Angie is part German, born into
a very intelligent family.
<wait>
She's young, but already earned her
International Nursing License.
<wait>

@MSG_EVT104A_017
Is... Mary Fulton here?
<wait>
I'm ready to discuss protocols and
procedures now.
<wait>

@MSG_EVT104A_018
<bup 0 11 1>
It's very nice to meet you.
<wait>

@MSG_EVT104A_019
<bup 0 1 2>
Wow, she's a nurse?
Isn't she a little too--?
<wait>

@MSG_EVT104A_020
<bup 0 7 5>
What's that, now?
<wait>

@MSG_EVT104A_021
<bup 0 1 1>
Wha-- Huh? No, nothing...
Pardon me.
<wait>

@MSG_EVT104A_022
<bup 0 7 5>
On the way here, I saw a man get hit by
a car as he was crossing the street.
<wait>
I took him to a nearby clinic and stayed until
they transferred him to St. Francis Hospital.
<wait>
Of course, the paperwork took
forever to fill out, so... yeah!
<wait>

@MSG_EVT104A_023
<bup 0 10 1>
Sounds like you had a rough morning.
<wait>

@MSG_EVT104A_024
<bup 0 11 1>
Well don't you worry about being late.
I completely understand.
<wait>
<bup_cls>

@MSG_EVT104A_025
Excuse me... Has Miss Thompson
arrived yet?
<wait>
There's someone on the line
from St. Francis Hospital...
<wait>

@MSG_EVT104A_026
<bup 0 7 1>
This must be about that patient...
Please excuse me.
<wait>
<bup_cls>

@MSG_EVT104A_027
<bup 0 10 1>
She certainly is something else...
<wait>

@MSG_EVT104A_028
<bup 0 11 1>
Looks like I'm leaving you in capable hands.
What do you think, Derek?
<wait>
<bup_cls>
