
@MSG_EVT101A_001
- Hope Hospital, Consultation Room -
<wait>

#古村百恵

@MSG_EVT101A_002
<bup 0 11 1>
The patient has been moved to
the pre-op area.
<wait>

##

@MSG_EVT101A_003
Mary Fulton, age 39: Hope Hospital's
veteran surgical assistant.
<wait>
She's kind and well-liked, so nobody
mentions she tends to ramble too much.
<wait>

#古村百恵

@MSG_EVT101A_004
The injury is located on his forearm
and he's still fully conscious.
<wait>
We should be receiving blood test
results from the lab any minute now.
<wait>

#沓掛真一

@MSG_EVT101A_005
<bup 0 10 1>
It looks worse than it is.
He's not in any real danger.
<wait>
You might say he got lucky.
<wait>

##

@MSG_EVT101A_006
Dr. Greg Kasal: The head of Hope
Hospital's surgical department.
<wait>
He's not easily rattled, but he's strict and
expects perfection from his subordinates.
<wait>

#沓掛真一

@MSG_EVT101A_007
You'll be operating, Derek.
<wait>

#月森孝介

@MSG_EVT101A_008
<bup 0 1 1>
...I will?
<wait>

##

@MSG_EVT101A_009
Derek Stiles, age 26: An inexperienced
surgeon, and the story's main character.
<wait>
He just completed his residency and
accepted a position at Hope Hospital.
<wait>

#月森孝介

@MSG_EVT101A_010
I was just about to start my rounds,
so...
<wait>

#古村百恵

@MSG_EVT101A_011
<bup 0 11 3>
Worry about that later!
You're not an intern anymore!
<wait>
Hurry up and prep for the O.R.!
<wait>

#沓掛真一

@MSG_EVT101A_012
<bup 0 10 1>
This is a simple extraction procedure.
There's nothing to worry about.
<wait>
Just take your time...
Stay calm and keep it steady.
<wait>
...You should be able to handle this
on your own by now.
<wait>
<bup_cls>

@MSG_EVT101B_001
<bup 0 11 1>
See? You're catching on quickly.
That wasn't so hard, was it?
<wait>

@MSG_EVT101B_002
<bup 0 1 1>
I couldn't have done it without
my lovely assistant.
<wait>

@MSG_EVT101B_003
<bup 0 11 2>
I can definitely see improvement,
...but flirting isn't everything.
<wait>
Seriously though, keep practicing
and you'll do just fine.
<wait>
<bup_cls>
