
@MSG_EVT202A_001
<bup 0 9 1>
...I called you here today to warn
you about something.
<wait>
Dr. Kasal tells me you may have shown
potential for the...Healing Touch.
<wait>

@MSG_EVT202A_002
<bup 0 1 5>
Healing Touch...?
<wait>

@MSG_EVT202A_003
<bup 0 9 1>
You don't know?
<wait>

@MSG_EVT202A_004
<bup 0 1 5>
...No.
<wait>

@MSG_EVT202A_005
<bup 0 9 1>
Doctors with the Healing Touch can cure
incurable diseases...
<wait>
...They can even save patients who
come within an inch of death.
<wait>
I don't know how long this gift has existed...
<wait>
But, the Greeks believed such doctors were
descendants of Asclepius.
<wait>

@MSG_EVT202A_006
<bup 0 1 5>
You mean the god of medicine...?
...Me!?
<wait>

@MSG_EVT202A_007
<bup 0 9 1>
Those with the Healing Touch have
certain special...qualities:
<wait>
...the keenest judgement, unbreakable focus,
and unmatched surgical skill.
<wait>
Haven't you noticed any changes
during your operations?
<wait>

@MSG_EVT202A_008
<bup 0 1 5>
Well...
<wait>
Sometimes it starts to feel like time is
moving much more slowly than usual.
<wait>

@MSG_EVT202A_009
<bup 0 9 1>
Hmm... That must be a result of
your extraordinary concentration.
<wait>
...It definitely marks you as
capable of the Healing Touch.
<wait>

@MSG_EVT202A_010
<bup 0 1 5>
So, I have all those powers?
<wait>

@MSG_EVT202A_011
<bup 0 9 4>
You need to forget about them.
Those things are unnecessary.
<wait>

@MSG_EVT202A_012
<bup 0 1 5>
What...?
<wait>

@MSG_EVT202A_013
<bup 0 9 1>
If you pursue this, yes, you will
become an unparalleled surgeon.
<wait>
But, are you prepared for the pain
that would bring you?
<wait>
Derek, a doctor's hands are heavy
with responsibility.
<wait>
Patients depend on us. They put their
lives in those hands of ours.
<wait>
Can you imagine how heavy that burden
would be with the Healing Touch?
<wait>
There aren't many doctors who could
endure such a weight...
<wait>
I'm only telling you this for your own good...
<wait>
Forget about that power and be a
normal doctor...
<wait>
...You'll never be happy, otherwise.
<wait>

@MSG_EVT202A_014
<bup 0 1 5>
...for my own good?
<wait>

@MSG_EVT202A_015
<bup 0 9 1>
Think of it this way: right now, you're
standing at a large door, knocking.
<wait>
If you continue to knock, that door
will eventually open.
<wait>
But, you can also turn your back on it,
and it would stay closed.
<wait>
Why not take a vacation? Get your mind
off of surgery for a while...
<wait>

@MSG_EVT202A_016
<bup 0 1 4>
...But, I--
<wait>

@MSG_EVT202A_017
<bup 0 9 1>
Trust me; it's for your own good.
<wait>

@MSG_EVT202A_018
<bup 0 1 4>
......
<wait>
<bup_cls>
