
@MSG_EVT209A_001
<bup 0 10 1>
Derek, we just received some strange
results back on Linda Reid.
<wait>

@MSG_EVT209A_002
<bup 0 1 1>
...? Do they explain the bleeding in her lungs?
<wait>

@MSG_EVT209A_003
<bup 0 10 1>
I don't think it's directly related, but they
found extremely high levels of
<wait>
syprohedrine in her blood.
<wait>

@MSG_EVT209A_004
<bup 0 1 1>
Sypro...? What's that?
<wait>

@MSG_EVT209A_005
<bup 0 7 1>
It's a new antihistamine, Doctor.
<wait>
They're usually used to treat allergies.
<wait>

@MSG_EVT209A_006
<bup 0 1 1>
...I know what antihistamines do. But, why
didn't she tell us she was on medication?
<wait>

@MSG_EVT209A_007
<bup 0 10 1>
Because she wasn't.
<wait>
Drugs involving syprohedrine are still
in clinical trial...
<wait>
Also, our tests indicated 24 times
the suggested dosage.
<wait>

@MSG_EVT209A_008
<bup 0 7 1>
Side effects from overdose include
headaches and emotional distress...
<wait>

@MSG_EVT209A_009
<bup 0 10 1>
In extreme cases, the mood swings are
serious enough to prompt suicide.
<wait>

@MSG_EVT209A_010
<bup 0 1 1>
That explains her death wish.
<wait>

@MSG_EVT209A_011
<bup 0 10 1>
It may have contributed, but I doubt
that was the primary cause.
<wait>
Still, I've never heard of syprohedrine
being synthesized within the body.
<wait>
...Whatever's causing it might be the source
of those lacerations.
<wait>
<bup_cls>

@MSG_EVT209A_012
"D-Doctor!"
<wait>

@MSG_EVT209A_013
<bup 0 10 5>
What is it!?
<wait>
<bup_cls>

@MSG_EVT209A_014
"Reid's condition is getting worse! She's
complaining about excrutiating chest pain!"
<wait>

@MSG_EVT209A_015
<bup 0 10 3>
...What!?
<wait>
<bup_cls>

@MSG_EVT209A_016
<bup 0 26 7>
...It hurts...
<wait>
<bup_cls>

@MSG_EVT209A_017
<bup 0 1 5>
Linda!
<wait>

@MSG_EVT209A_018
<bup 0 26 7>
Doctor... I want to...live.
<wait>
I want...to live, Doctor...
<wait>
Please...!
<wait>

@MSG_EVT209A_019
<bup 0 10 3>
Derek, we're operating now!
Angie, alert the staff.
<wait>
Hurry!
<wait>
<bup_cls>

@MSG_EVT209B_001
<bup 0 10 5>
...I'd like to remind everyone that
the details of this operation should
<wait>
be considered strictly confidential.
<wait>
Bring Linda Reid's medical files
to my office immediately.
<wait>
I will provide updates when appropriate.
That's all for today.
<wait>
<bup_cls>

@MSG_EVT209B_002
<bup 0 7 5>
...Doctor, could that have been GUILT?
<wait>

@MSG_EVT209B_003
<bup 0 10 5>
...How do you know about that!?
<wait>

@MSG_EVT209B_004
<bup 0 7 5>
I don't know much. ...It was mentioned
in my father's research...
<wait>

@MSG_EVT209B_005
<bup 0 10 5>
When did your father come across
something like GUILT...?
<wait>

@MSG_EVT209B_006
<bup 0 7 5>
Well, he was a researcher... Other than that,
I don't really know.
<wait>

@MSG_EVT209B_007
<bup 0 10 5>
...Give me some time to examine
the situation.
<wait>
Until then, don't mention GUILT to anyone.
Understand?
<wait>

@MSG_EVT209B_008
<bup 0 7 5>
...Yes, sir.
<wait>

@MSG_EVT209B_009
<bup 0 1 5>
(...What the hell is GUILT?)
<wait>
<bup_cls>
