
@MSG_EVT207A_001
- Hope Hospital, Room 201 -
<wait>

@MSG_EVT207A_002
<bup 0 26 1>
Get away...!
<wait>
I never asked you to save me!
Leave me alone!
<wait>

@MSG_EVT207A_003
<bup 0 1 5>
Please calm down, Miss Reid.
It's alright...
<wait>

@MSG_EVT207A_004
<bup 0 26 1>
When I passed out, I could feel it...
My chest was on fire.
<wait>
...I was finally going to be free.
<wait>
Why did you bring me back!?
I didn't want to live!
<wait>

@MSG_EVT207A_005
<bup 0 1 5>
Why would you want to die?
<wait>
You're still young...you have your whole--
<wait>

@MSG_EVT207A_006
<bup 0 26 1>
...life ahead of me? Yeah, there's something
to look forward to, huh?
<wait>
How come everyone says that? My life sucks!
I'm tired of all this pain!
<wait>
I'm not pretty enough to date the popular
guys, I'm too fat...
<wait>
My mom called me a failure yesterday
because I might not even graduate!
<wait>
Is that a life YOU'D want!?
I'm never going to be happy...
<wait>

@MSG_EVT207A_007
<bup 0 1 5>
That all depends on--
<wait>

@MSG_EVT207A_008
<bup 0 26 1>
Depends on my attitude?
<wait>
What a joke! A positive outlook won't just
magically solve all my problems!
<wait>

@MSG_EVT207A_009
<bup 0 7 3>
...Then maybe you should die.
<wait>
There are patients here who have to
fight just to breathe properly...
<wait>
Every day, someone dies after a long and
painful struggle to hold on...
<wait>
I'm sorry we saved you.
Go end your life, for all I care.
<wait>

@MSG_EVT207A_010
<bup 0 1 5>
Angie!
<wait>

@MSG_EVT207A_011
<bup 0 7 3>
I know you did your best, Doctor,
but I'm afraid it was wasted effort.
<wait>

@MSG_EVT207A_012
<bup 0 1 5>
Stop talking like that, Angie!
<wait>

@MSG_EVT207A_013
<bup 0 7 3>
I have other things...to attend to.
<wait>
<bup_cls>

@MSG_EVT207A_014
<bup 0 1 1>
......
<wait>

@MSG_EVT207A_015
<bup 0 26 1>
...I'm sorry you had to waste your
time operating on me.
<wait>

@MSG_EVT207A_016
<bup 0 1 1>
Helping someone is never a waste of time.
<wait>

@MSG_EVT207A_017
<bup 0 26 1>
...Just leave me alone.
<wait>
I don't blame that nurse for hating me...
...I hate me, too.
<wait>

@MSG_EVT207A_018
<bup 0 1 1>
I'm not going anywhere; you're still sick.
<wait>

@MSG_EVT207A_019
<bup 0 26 1>
What kind of surgeon are you, then?
I thought you fixed me.
<wait>

@MSG_EVT207A_020
<bup 0 1 1>
...It's not that kind of sickness.
<wait>
A doctor's job is about more than
just physical illnesses.
<wait>
Nurse Angie taught me that.
<wait>

@MSG_EVT207A_021
<bup 0 26 1>
......
<wait>
<bup_cls>

@MSG_EVT207A_022
<bup 0 1 1>
......
<wait>
...When I was little, I had a cat named Tama.
<wait>
We were playing one day, and he ran
out into the street...
<wait>
I wasn't fast enough to do anything...
A car hit him, and I blamed myself.
<wait>
I decided it was my fault Tama died.
I really thought I had killed my cat...
<wait>
...It was all I could think about.
<wait>
I told my mother I did a terrible thing,
and I wanted to die.
<wait>

@MSG_EVT207A_023
<bup 0 26 1>
...What happened then?
<wait>

@MSG_EVT207A_024
<bup 0 1 1>
She slapped me. ...hard.
<wait>
Mom told me Tama would be ashamed
of me, and that she was too.
<wait>
But, she also said...
<wait>
...that I was the one who should be
most ashamed of myself.
<wait>

@MSG_EVT207A_025
<bup 0 26 1>
...She said that to you?
<wait>

@MSG_EVT207A_026
<bup 0 1 1>
Who'd you grow up with, Linda?
<wait>

@MSG_EVT207A_027
<bup 0 26 1>
...Huh!?
<wait>

@MSG_EVT207A_028
<bup 0 1 1>
Do you have any siblings?
Or...what about pets?
<wait>

@MSG_EVT207A_029
<bup 0 26 1>
...Just my parents...and my friends
at school, I guess...
<wait>

@MSG_EVT207A_030
<bup 0 1 1>
Could you look those people in the eye
and tell them you wanted to die?
<wait>

@MSG_EVT207A_031
<bup 0 26 1>
No way! Of course not!
That's why I want to be left alone!
<wait>

@MSG_EVT207A_032
<bup 0 1 1>
Then, hold this.
<wait>

@MSG_EVT207A_033
<bup 0 26 1>
...A mirror?
<wait>

@MSG_EVT207A_034
<bup 0 1 1>
Look at that girl, there, and say,
"I want to die."
<wait>

@MSG_EVT207A_035
<bup 0 26 1>
......
<wait>
I...
I... want... *sob*
<wait>

@MSG_EVT207A_036
<bup 0 1 1>
I couldn't do it, either.
<wait>
Now, tell her you're sorry.
I think she deserves an apology.
<wait>

@MSG_EVT207A_037
<bup 0 26 1>
......
<wait>
...I'm... sorry...
<wait>
*sob* I'm... sorry...
I'm so sorry...!
<wait>

@MSG_EVT207A_038
<bup 0 1 1>
Stop worrying about other people,
and start making that girl happy.
<wait>
Don't work hard in school for your mom's
sake... Do it because you'll learn more,
<wait>
and become a better person.
<wait>
Don't let other people decide whether or
not you're happy.
<wait>
Find things you enjoy, and do them.
<wait>
It might not make you popular, but
you'll like yourself a lot more.
<wait>
...And you aren't too fat.
I've seen your charts, remember?
<wait>

@MSG_EVT207A_039
<bup 0 26 1>
...Your mother sounds like a smart lady.
<wait>

@MSG_EVT207A_040
<bup 0 1 1>
Really? She could be pretty weird
sometimes... But then she'd say,
<wait>
"I may be weird, but think of all the stories
you'll have to tell one day!"
<wait>

@MSG_EVT207A_041
<bup 0 26 1>
That's...interesting.
<wait>
*cough*
<wait>

@MSG_EVT207A_042
<bup 0 1 1>
Uh...sorry, I guess I got a little carried away.
<wait>
Really, though, she's great.
I should let you rest now...
<wait>

@MSG_EVT207A_043
<bup 0 26 1>
...I think I'm going to take a nap.
<wait>

@MSG_EVT207A_044
<bup 0 1 1>
That's a good idea. Sorry for talking
so much. Next time, I'll--
<wait>

@MSG_EVT207A_045
<bup 0 26 1>
Thank you...
<wait>

@MSG_EVT207A_046
<bup 0 1 1>
...?
<wait>

@MSG_EVT207A_047
<bup 0 26 2>
...You're a good doctor.
<wait>
<bup_cls>
