
@MSG_EVT211A_001
- Hope Hospital, Room 207 -
<wait>

@MSG_EVT211A_002
<bup 0 33 1>
Thank you so much, Doctor.
<wait>
It just hurt so badly... I thought I was a goner.
<wait>

@MSG_EVT211A_003
<bup 0 1 2>
Well, appendicitis is a fairly common
condition...
<wait>
But, congratulations on your recovery,
Mr. Sasano.
<wait>

@MSG_EVT211A_004
<bup 0 33 1>
If my wife gets sick, I'll make sure
you're the one operating on her!
<wait>

@MSG_EVT211A_005
<bup 0 1 1>
Heh, well, it would probably be better
if she didn't get sick at all.
<wait>

@MSG_EVT211A_006
<bup 0 33 1>
I guess that's true. Ha ha!
<wait>
<bup_cls>

@MSG_EVT211A_007
<bup 0 1 1>
(Talking with the patients is one of
my favorite parts of the job...)
<wait>
(Could I really leave that behind?)
<wait>
<bup_cls>

@MSG_EVT211A_008
<bup 0 10 1>
Derek, we'll be starting the
operation briefing soon.
<wait>

@MSG_EVT211A_009
<bup 0 1 1>
Okay.
<wait>
<bup_cls>

@MSG_EVT211B_001
<bup 0 32 4>
...Is my daughter...
Will Elisa be all right?
<wait>

@MSG_EVT211B_002
<bup 0 1 1>
The operation was a success.
<wait>
She'll need about two months to fully recover
before she can go back to school.
<wait>
But, after that, she'll be as good as new.
<wait>

@MSG_EVT211B_003
<bup 0 32 2>
That's good news...
Oh, thank you so much, Doctor!
<wait>

@MSG_EVT211B_004
<bup 0 1 1>
People are always worried about heart
surgery--especially on children.
<wait>
But, modern medicine allows us to treat such
conditions with much greater success than
<wait>
ten, even just five years ago. Young patients
like your daughter face very little risk of
<wait>
permanent physical damage.
<wait>
To be honest, I'm more worried about
the psychological stress operations
<wait>
like this might have on small children.
<wait>
Please take good care of her during
her recovery.
<wait>

@MSG_EVT211B_005
<bup 0 32 2>
Oh, of course...
<wait>
Elisa... We love you so much...
<wait>
<bup_cls>

@MSG_EVT211B_006
<bup 0 1 1>
(Modern medicine...)
<wait>
<bup_cls>

@MSG_EVT211B_007
"I'm very sorry... Modern medicine just hasn't
advanced enough to treat a disease like this."
<wait>
"You have my condolences..."
<wait>

@MSG_EVT211B_008
"Mom... Why are you crying?"
<wait>
"Dad's okay, right?"
<wait>
"He's...gonna get better, right!?"
<wait>
"B-But... Why isn't Dad getting better...?"
<wait>
"You can fix him! You just gotta!
...He's my dad!"
<wait>

@MSG_EVT211B_009
"...I'm sorry, son."
<wait>
"...No doctor in the world could
save your father from this."
<wait>

@MSG_EVT211B_010
<bup 0 1 4>
(...Things have come a long way.)
<wait>
<bup_cls>

@MSG_EVT211B_011
<bup 0 1 5>
Dr. Hoffman, I'm going to accept the offer
from Caduceus.
<wait>

@MSG_EVT211B_012
<bup 0 9 1>
So, you're willing to throw away your own
happiness for this?
<wait>

@MSG_EVT211B_013
<bup 0 1 5>
I know about what happened to you
in the past...
<wait>
I know that having superior skills will only
create more pressure to succeed...
<wait>
...That everyone will expect me to
have answers nobody else has...
<wait>
I'm sure those are valid concerns.
<wait>
And, the path I've chosen will probably
cause me a lot of pain...
<wait>
...But I became a doctor so that nobody would
have to die from an incurable disease.
<wait>
Not ever again.
<wait>

@MSG_EVT211B_014
<bup 0 9 1>
......
<wait>

@MSG_EVT211B_015
<bup 0 1 5>
Diseases are painful.
<wait>
And, losing someone to a disease
is even more painful.
<wait>
It's hard for doctors to tell people
their loved ones can't be cured.
<wait>
...I'm going to make sure they won't have to.
<wait>
Caduceus has already found ways
to save thousands of people...
<wait>
If I can somehow help them find cures for
"incurable diseases," then...
<wait>
<bup 0 1 10>
...I'll accept that responsibility.
I'm joining Caduceus!
<wait>
<bup_cls>
