
@MSG_EVT210A_001
I'm here...
<wait>

@MSG_EVT210A_002
<bup 0 9 1>
Please come in.
<wait>
<bup_cls>

@MSG_EVT210A_003
<bup 0 1 5>
Pardon me, but why was I called
to your office?
<wait>

@MSG_EVT210A_004
<bup 0 10 5>
Why don't you have a look at this
examination report, first?
<wait>

@MSG_EVT210A_005
<bup 0 1 5>
Who's this for?
<wait>

@MSG_EVT210A_006
<bup 0 10 5>
Linda Reid.
<wait>
<bup_cls>

@MSG_EVT210A_007
<bup 0 1 5>
...What do these headings mean?
<wait>
I don't recognize them...
Positive Chiral Reaction...?
<wait>
GUILT: Positive...
Spectral Analysis...G1-R...?
<wait>

@MSG_EVT210A_008
<bup 0 10 5>
Those tests are beyond our capabilities, so
we enlisted help from an outside organization.
<wait>
In the last few years, a bizarre disease
with varying symptoms has been reported
<wait>
in several isolated cases.
The two things they had in common...?
<wait>
Each victim's body turned against itself,
and they all died.
<wait>
Because of that...we believe each
subject was infected with GUILT.
<wait>
(Gangliated Utrophin Immuno Latency Toxin)
<wait>

@MSG_EVT210A_009
<bup 0 1 5>
...Then, you think Reid's illness was...
<wait>

@MSG_EVT210A_010
<bup 0 9 1>
Exactly...
Linda Reid is a GUILT victim.
<wait>
I'm surprised you were able to treat her
without the proper resources.
<wait>

@MSG_EVT210A_011
<bup 0 1 5>
It was a difficult operation, but...
I wanted to save her.
<wait>

@MSG_EVT210A_012
<bup 0 9 1>
...Well, that decision may have
changed your life.
<wait>
The organization we mentioned before
has requested that you join them.
<wait>

@MSG_EVT210A_013
<bup 0 1 5>
Wh-What...? Why me?
<wait>

@MSG_EVT210A_014
<bup 0 9 1>
Your Healing Touch ability allowed you
to successfully cure a GUILT victim.
<wait>

@MSG_EVT210A_015
<bup 0 1 5>
...What organization is this, anyway?
<wait>

@MSG_EVT210A_016
<bup 0 10 1>
They're an arm of the World Health
Organization that specializes in
<wait>
exterminating intractable diseases
that threaten mankind.
<wait>
...They're called Caduceus.
<wait>

@MSG_EVT210A_017
<bup 0 1 5>
Caduceus...?
<wait>
...I remember seeing them listed in essays
on cancer and AIDS treatments.
<wait>
Aren't they the ones who eradicated
the TFTA influenza last year!?
<wait>
...Caduceus wants me?
<wait>

@MSG_EVT210A_018
<bup 0 10 1>
What are you going to do, Derek?
<wait>
You've been offered a chance to work
at the forefront of modern medicine.
<wait>

@MSG_EVT210A_019
<bup 0 1 4>
Well... I mean, it's an honor...
<wait>
But, it's all so sudden... I'm not really sure
what to do.
<wait>
I mean...it'd change my whole life.
<wait>

@MSG_EVT210A_020
<bup 0 10 1>
You don't need to decide right away.
<wait>
Just remember that this is a choice,
not an order.
<wait>

@MSG_EVT210A_021
<bup 0 9 1>
The only reason I'm telling you this is
because an old friend asked me to.
<wait>
To be honest, I'm against you
joining Caduceus.
<wait>

@MSG_EVT210A_022
<bup 0 1 5>
Wh-What? ...Why?
<wait>

@MSG_EVT210A_023
<bup 0 9 1>
I don't think a research laboratory is
the right environment for you.
<wait>
Didn't you say you wanted to help
patients, face to face?
<wait>

@MSG_EVT210A_024
<bup 0 1 4>
(That's true.)
<wait>

@MSG_EVT210A_025
<bup 0 9 1>
...You should probably see this, as well.
<wait>

@MSG_EVT210A_026
<bup 0 1 5>
...A letter?
<wait>

@MSG_EVT210A_033
..."Kyriaki--Sunday"
<wait>
"Death is denied those who seek it,
though it be their destiny."
<wait>
"They search for it like treasure,
but the modern age conceals it."
<wait>
What's this supposed to mean?
<wait>

@MSG_EVT210A_027
<bup 0 9 1>
It arrived shortly after Linda Reid
was hospitalized.
<wait>
We don't know who sent it.
<wait>
Supposedly, these letters arrive
shortly before GUILT does...
<wait>

@MSG_EVT210A_028
<bup 0 1 5>
...Huh?
<wait>

@MSG_EVT210A_029
<bup 0 10 5>
That means GUILT doesn't occur naturally...
<wait>
...which means it could be some
kind of man-made virus.
<wait>
The World Health Organization is
considering it terrorist activity.
<wait>

@MSG_EVT210A_030
<bup 0 1 3>
Wh-What!?
<wait>

@MSG_EVT210A_031
<bup 0 10 5>
Someone is creating GUILT and
releasing it into society.
<wait>
We don't have any leads as to who, or why.
...Almost as if it's meant to confuse us.
<wait>
The U.N. even created a new term to
describe it: "Medical Terrorism."
<wait>
Caduceus is anticipating a large-scale
GUILT outbreak...
<wait>
...and they need skilled doctors
to be ready for it.
<wait>

@MSG_EVT210A_032
<bup 0 9 1>
Hopefully now you see the stakes
involved in this...
<wait>
Think it over. Don't make your decision lightly.
<wait>
<bup_cls>
