
@MSG_EVT204A_001
<bup 0 10 1>
...That concludes our meeting. Please review
the information again on your own.
<wait>
We should just move on to the surgical
conference now, to save time.
<wait>
Those doctors involved, please stick around.
<wait>
<bup_cls>

@MSG_EVT204A_002
<bup 0 1 5>
......
<wait>

@MSG_EVT204A_003
<bup 0 7 1>
...We're starting, Doctor.
<wait>

@MSG_EVT204A_004
<bup 0 1 5>
......
<wait>

@MSG_EVT204A_005
<bup 0 7 1>
Dr. Stiles!
Pay attention!
<wait>

@MSG_EVT204A_006
<bup 0 1 1>
...Huh? Wha?
Oh, sorry...
<wait>
I guess I didn't hear you.
<wait>

@MSG_EVT204A_007
<bup 0 7 1>
Is everything alright? You've been staring
at that X-ray for a long time.
<wait>

@MSG_EVT204A_008
<bup 0 1 1>
Uh... I was just going over today's
operation again in my mind.
<wait>
Anyway... Let's get the conference
started, huh?
<wait>
<bup_cls>

@MSG_EVT204A_009
<bup 0 7 1>
(...He's been spacing out a lot lately...)
<wait>
(At least he's concentrating hard
on something, I guess...)
<wait>
<bup_cls>

@MSG_EVT204B_001
<bup 0 10 1>
So, I understand you figured out
how to control the Healing Touch.
<wait>
<bup 0 10 2>
Make sure you don't rely on it too much.
You need to develop your basic skills, too.
<wait>
<bup_cls>

@MSG_EVT204B_002
<bup 0 1 4>
(Huh...? What the...)
<wait>
<bup_cls>

@MSG_EVT204B_003
<bup 0 10 2>
I know it won't be easy, but you
didn't take this job because--
<wait>
<bup_cls>

@MSG_EVT204B_004
<bup 0 1 4>
(Everything's... going black...)
<wait>

@MSG_EVT204B_005
<bup 0 10 1>
Derek, are you even listening?
<wait>
<bup_cls>

@MSG_EVT204B_006
...Derek? What's wrong!?
<wait>
