
@MSG_EVT203A_001
<bup 0 1 4>
......
<wait>

@MSG_EVT203A_002
<bup 0 10 1>
What's wrong, Derek? Shouldn't you
be checking on your patients?
<wait>

@MSG_EVT203A_003
<bup 0 1 4>
Dr. Kasal...
<wait>
Do you think I should stop trying
to improve as a doctor?
<wait>

@MSG_EVT203A_004
<bup 0 10 1>
...So you spoke with Hoffman.
<wait>
I was hoping the news about your abilities
might motivate him to start operating again.
<wait>

@MSG_EVT203A_005
<bup 0 1 4>
Huh? ...Why would it do that?
<wait>
<bup_cls>

@MSG_EVT203A_006
<bup 0 10 1>
Back when the director was still
operating on patients...
<wait>
He named that skill the Healing Touch
and accepted its... gifts.
<wait>

@MSG_EVT203A_007
<bup 0 1 1>
What...!?
He has it too?
<wait>

@MSG_EVT203A_008
<bup 0 10 1>
But then something...happened.
He hasn't operated on anyone since.
<wait>
...All because of one mistake.
<wait>
<bup_cls>

@MSG_EVT203A_009
<bup 0 9 1>
"Can you imagine how heavy that burden
would be with the Healing Touch?"
<wait>
"There aren't many doctors who could
endure such a weight..."
<wait>
<bup_cls>

@MSG_EVT203A_010
<bup 0 1 4>
...Can I really do it? Can I master
the Healing Touch?
<wait>

@MSG_EVT203A_011
<bup 0 10 1>
Well, I can't tell you what to do--I'm not
the one with your abilities.
<wait>
But, I know that if you intend to use this
power to help people...
<wait>
...You need to take command of it.
<wait>

@MSG_EVT203A_012
<bup 0 1 1>
Take...command?
<wait>

@MSG_EVT203A_013
<bup 0 10 1>
Yes. You can't be "halfway" with
something like this.
<wait>
One simple mistake changed the
director's entire life.
<wait>
He delved too far, into something
even he couldn't understand...
<wait>
I think you can learn a lot from
the director's mistake.
<wait>
If you can't control this power,
then it's going to cost you.
<wait>

@MSG_EVT203A_014
<bup 0 1 1>
So, do you...think I can do it?
<wait>

@MSG_EVT203A_015
<bup 0 10 1>
Your skill seems to involve focus,
so try to concentrate on that.
<wait>
Once you adjust, I'm sure you'll be able
to make this decision for yourself.
<wait>
...I can't fully understand the Healing Touch
because I'm not you or Dr. Hoffman.
<wait>
In the end, nobody's going to be able to
make this decision for you.
<wait>
...Good luck, Derek.
<wait>
<bup_cls>

@MSG_EVT203A_016
<bup 0 1 1>
I need to focus on concentration...
<wait>
...My dad always used to say I could
never concentrate on anything.
<wait>
He told me to imagine one shape, like a
star or a triangle, and focus on that.
<wait>
I'm pretty sure he just made that up, but it
definitely came in handy for exams.
<wait>
Maybe that could help now.
I'll imagine a star...
<wait>
I just have to relax, focus, and concentrate...!
<wait>
<bup_cls>

@MSG_EVT203B_001
<bup 0 1 5>
I think...I'm getting the hang of it!
<wait>
I might be able to handle the Healing Touch,
after all!
<wait>
<bup_cls>
