
@MSG_EVT205A_001
"Forget about that power..."
<wait>

@MSG_EVT205A_002
<bup 0 1 4>
...But, I...
<wait>
<bup_cls>

@MSG_EVT205A_003
"Are you prepared for the pain
that would bring you?"
<wait>

@MSG_EVT205A_004
<bup 0 1 4>
...I became a doctor so that I
could help people...
<wait>
<bup_cls>

@MSG_EVT205A_005
"And if it costs you your life?
You'd give up your own happiness?"
<wait>

@MSG_EVT205A_006
<bup 0 1 4>
...I don't know...but I do know
that people need my help...
<wait>
...and I want to help them.
<wait>
<bup_cls>
.........
<wait>
......
<wait>

@MSG_EVT205A_021
Wha!?
...Where am I?
<wait>

@MSG_EVT205A_022
<bup 0 1 1>
...It's the...ceiling...
What am I doing here?
<wait>

@MSG_EVT205A_007
<bup 0 7 3>
Dr. Stiles!
<wait>

@MSG_EVT205A_008
<bup 0 1 1>
Angie...?
What happened?
<wait>

@MSG_EVT205A_009
<bup 0 10 5>
After Mr. Kovac's surgery, you
just...collapsed.
<wait>
You've been asleep for three days.
<wait>

@MSG_EVT205A_010
<bup 0 1 5>
Wh-What? Three days!?
<wait>
...What about my patients?
I have operations scheduled--
<wait>

@MSG_EVT205A_011
<bup 0 10 5>
...Already taken care of, Derek.
I called in the other doctors.
<wait>
But, that's in the past. We need to discuss
how you're going to proceed from here.
<wait>

@MSG_EVT205A_012
<bup 0 1 4>
...Okay.
<wait>

@MSG_EVT205A_013
<bup 0 10 5>
Derek... I forbid you from using
the Healing Touch like that.
<wait>

@MSG_EVT205A_014
<bup 0 1 5>
But, why would you--?
<wait>

@MSG_EVT205A_015
<bup 0 10 5>
That ability puts a tremendous amount of
physical strain on your body.
<wait>
...It's too risky. What if you collapsed
in the middle of a procedure?
<wait>

@MSG_EVT205A_016
<bup 0 1 5>
But...without my Healing Touch,
Mr. Kovac might have died...
<wait>

@MSG_EVT205A_017
<bup 0 10 5>
Exactly. That is why you mustn't
abandon the Healing Touch.
<wait>
I'd advise you to use it only when
absolutely necessary...
<wait>
After all, you shouldn't be relying
solely on the Healing Touch, anyway.
<wait>
Developing your natural skills as a
surgeon is far more important.
<wait>
...We can't assume the Healing Touch
was the only reason Kovac survived.
<wait>
If you want to help people, then focus on
strengthening your natural abilities.
<wait>

@MSG_EVT205A_018
<bup 0 1 4>
...I understand.
<wait>

@MSG_EVT205A_019
<bup 0 10 1>
Take it slowly. I'm sure the power
inside you will find its way out.
<wait>
Become the best surgeon you can, and one
day you'll inherit the full heritage of Asclepius.
<wait>

@MSG_EVT205A_020
<bup 0 1 1>
Y-Yes sir!
<wait>
<bup_cls>
