
@MSG_EVT208A_001
<bup 0 1 1>
Whew... Time for a break.
<wait>

@MSG_EVT208A_002
<bup 0 7 1>
I'll go get us some coffee.
<wait>

@MSG_EVT208A_003
<bup 0 1 1>
Thanks... That's a great idea.
<wait>

@MSG_EVT208A_004
<bup 0 7 1>
I passed by Linda Reid's room
on the way here, but...
<wait>

@MSG_EVT208A_005
<bup 0 1 1>
...Is something wrong?
<wait>

@MSG_EVT208A_006
<bup 0 7 1>
Her parents were there.
<wait>
All three of them started crying
and apologizing all at once.
<wait>
It seems like a lot more was going on
than we thought...
<wait>
School, her father's job...
<wait>

@MSG_EVT208A_007
<bup 0 1 1>
Were you eavesdropping?
<wait>

@MSG_EVT208A_008
<bup 0 7 1>
...Well, I was curious...
<wait>
...I didn't hear anything worth dying over,
though.
<wait>
Everyone worries about that stuff
during high school, you know?
<wait>

@MSG_EVT208A_009
<bup 0 1 1>
I think we all handle our problems
in different ways.
<wait>
But, I'm glad her family came to visit her.
<wait>
Surgeons aren't really equipped to
heal psychological wounds.
<wait>

@MSG_EVT208A_010
<bup 0 7 1>
Don't sell yourself short...
<wait>

@MSG_EVT208A_011
<bup 0 1 3>
...Aheh... I can only try...
<wait>
<bup 0 1 1>
Anyway... If her family knows about it,
then they can help her.
<wait>

@MSG_EVT208A_012
<bup 0 7 2>
Yeah, I think she'll be fine.
<wait>
<bup 0 7 1>
That girl's lucky she was brought
to this hospital, though.
<wait>

@MSG_EVT208A_013
<bup 0 1 1>
...Huh? Why?
<wait>

@MSG_EVT208A_014
<bup 0 7 1>
Well, this is only a rumor, but...
I hear there's a death doctor.
<wait>

@MSG_EVT208A_015
<bup 0 1 1>
A what doctor!?
<wait>

@MSG_EVT208A_016
<bup 0 7 5>
...Euthanasia.
<wait>
If that doctor had been treating her when
she asked to die...
<wait>

@MSG_EVT208A_017
<bup 0 1 5>
...Death doctor, huh? I really can't understand
why anyone would want to die.
<wait>
<bup_cls>
