
@MSG_EVT201A_001
<bup 0 1 5>
(...What the heck happened during
that last operation?)
<wait>
(It almost felt like time was slowing
down... Am I losing it?)
<wait>
(I knew exactly what needed to be done,
but I'm not sure how I knew that.)
<wait>
(Ugh... Now I'm just talking in circles.
I need to sit down and figure--)
<wait>

@MSG_EVT201A_002
<bup 0 10 1>
Derek!
<wait>
<bup 0 10 3>
Pay attention!
<wait>

@MSG_EVT201A_003
<bup 0 1 5>
...Huh?
I-I mean, I was.
<wait>

@MSG_EVT201A_004
<bup 0 10 3>
Stop daydreaming and start taking
your job seriously!
<wait>

@MSG_EVT201A_005
<bup 0 1 1>
I'm sorry.
<wait>

@MSG_EVT201A_006
<bup 0 10 1>
We need to have a meeting about
Mr. Pratt's operation.
<wait>
Angie, can you handle prep for that?
<wait>

@MSG_EVT201A_007
<bup 0 7 1>
Yes, of course, Doctor.
<wait>
<bup_cls>

@MSG_EVT201B_001
<bup 0 7 1>
You might actually be a pretty
good surgeon, Dr. Stiles.
<wait>

@MSG_EVT201B_002
<bup 0 1 1>
...Huh?
<wait>

@MSG_EVT201B_003
<bup 0 7 1>
You were practically a different
person in there...
<wait>
...Just like yesterday.
<wait>

@MSG_EVT201B_004
<bup 0 1 1>
(Come to think of it, it did kind of
feel like I was someone else.)
<wait>

@MSG_EVT201B_005
<bup 0 7 1>
If you were always that focused in the O.R.,
I wouldn't have to worry as much.
<wait>

@MSG_EVT201B_006
<bup 0 1 1>
...So you worry about me?
<wait>

@MSG_EVT201B_007
<bup 0 7 2>
I definitely worry about your patients.
<wait>

@MSG_EVT201B_008
<bup 0 1 4>
*sigh*
<wait>
<bup_cls>

@MSG_EVT201B_009
<bup 0 10 1>
Angie, I'd like to review the footage
of today's operation.
<wait>

@MSG_EVT201B_010
<bup 0 7 1>
Of course, sir.
I'll bring it to you later.
<wait>

@MSG_EVT201B_011
<bup 0 10 1>
(If we're right, then we should be able
to tell from watching the tape.)
<wait>
<bup_cls>
