
@MSG_EVT206A_001
<bup 0 7 3>
Doctor! An emergency patient was
just carried in!
<wait>
Vitals at 60, CS is 300!
<wait>
She's in shock, and losing blood fast!
<wait>

@MSG_EVT206A_002
<bup 0 10 3>
...Call the rest of the staff.
We need to operate immediately!
<wait>
Angie, get the patient in the O.R.
Derek, you handle the surgery!
<wait>

@MSG_EVT206A_003
<bup 0 1 5>
I'm on it!
<wait>
<bup_cls>

@MSG_EVT206B_001
<bup 0 7 5>
Where, and what, did those injuries
come from...?
<wait>

@MSG_EVT206B_002
<bup 0 10 1>
I don't know... It'll probably take
some time to figure out.
<wait>
She'll be hospitalized for a few days,
so let's try to keep an eye on her.
<wait>

@MSG_EVT206B_003
<bup 0 7 5>
...Did you notice those cuts along
the girl's wrists?
<wait>

@MSG_EVT206B_004
<bup 0 1 5>
Yeah...
They looked recent.
<wait>
I'd say her real illness is deeper
than we thought.
<wait>
...If that's the case, I don't think we're
finished seeing complications.
<wait>
<bup_cls>
