
@MSG_EVT303A_001
<bup 0 2 1>
Hey Tyler, you around?
<wait>
...Where could he be? I didn't think
he had any patients today.
<wait>
Huh... Is this a new thesis?
<wait>
I guess he still finds time for academics,
after all.
<wait>

@MSG_EVT303A_037
Netherlands... Utrecht...
<wait>
...Euthanasia.
<wait>
Why would he keep a euthanasia thesis
in his files?
<wait>
<bup 0 2 5>
...Oh, there's a letter.
<wait>

@MSG_EVT303A_038
"Thank you, Doctor. Because of you,
my husband finally found peace."
<wait>
...What the!?
<wait>
<bup_cls>

@MSG_EVT303A_002
"We'll bring that up at the next
conference, then."
<wait>

@MSG_EVT303A_003
<bup 0 2 5>
Crap, he's coming back!
Where do I put these...?
<wait>
<bup_cls>

@MSG_EVT303A_004
<bup 0 17 1>
Hey, what's happening, Derek?
Did you need help with something?
<wait>

@MSG_EVT303A_005
<bup 0 2 6>
Uh, I...uh was just coming in to...ask you
about...something...
<wait>
It was, uh... oh, right!
Medication for the GUILT patients...!
<wait>

@MSG_EVT303A_006
<bup 0 17 1>
Post-op medication? Hmm... As far
as I know, there hasn't been any--
<wait>
<bup 0 17 5>
Hm...
<wait>
......*sigh*
<wait>

@MSG_EVT303A_007
<bup 0 2 2>
Oh, well, okay... If you don't know, then I'll just...
<wait>
Sorry to bother you!
See you later, okay?
<wait>

@MSG_EVT303A_008
<bup 0 17 5>
...Wait, Derek.
<wait>
I've been meaning to show you something.
<wait>
You would've found out about it
sooner or later, anyway.
<wait>

@MSG_EVT303A_009
<bup 0 2 5>
Wh-What!? I swear, I didn't--
<wait>

@MSG_EVT303A_010
<bup 0 17 5>
Follow me.
<wait>
<bup_cls>

@MSG_EVT303A_011
- Recovery Ward, Room 305 -
<wait>

@MSG_EVT303A_012
<bup 0 27 1>
...Hey Tyler.
<wait>

@MSG_EVT303A_013
<bup 0 17 1>
How're you doing, Amy?
<wait>

@MSG_EVT303A_014
<bup 0 27 1>
Not so good...
<wait>

@MSG_EVT303A_015
<bup 0 17 1>
Oh, that sucks...
Sorry I made you get up.
<wait>
Derek, this is my sister, Amy. She's been
hospitalized here for two years.
<wait>

@MSG_EVT303A_016
<bup 0 2 5>
You mean, she's infected with GUILT?
<wait>

@MSG_EVT303A_017
<bup 0 17 5>
Yeah...
<wait>
Amy's condition is the reason I came
here in the first place.
<wait>
<bup 0 17 1>
Amy, this is Derek Stiles.
He's an old friend of mine...
<wait>
He's going to be treating you,
so go easy on him, okay?
<wait>

@MSG_EVT303A_018
<bup 0 27 1>
...Hee, okay.
<wait>

@MSG_EVT303A_019
<bup 0 18 2>
Did you come to examine her again, Dr. Chase?
<wait>

@MSG_EVT303A_020
Leslie Sears, age 26: One of the many nurses
on staff at Caduceus.
<wait>
She currently looks after several
GUILT patients, including Amy Chase.
<wait>

@MSG_EVT303A_021
<bup 0 17 1>
Nah, I just came to see how my
little sis was holding up.
<wait>

@MSG_EVT303A_022
<bup 0 18 2>
Oh, I see.
<wait>
Amy hasn't been doing her homework lately...
<wait>
I was actually hoping you could
talk to her about that.
<wait>

@MSG_EVT303A_023
<bup 0 27 1>
...But, it's soooo boring...!
<wait>

@MSG_EVT303A_024
<bup 0 17 1>
Sis...if you slack off, then you'll end up
dumb like your big brother.
<wait>
You want people to know how smart
you are, don'tcha?
<wait>
Think about it, okay? Anyway, big bro's gotta
run, but I'll visit you again tomorrow.
<wait>
<bup_cls>

@MSG_EVT303A_025
<bup 0 2 5>
You must be going through a lot, Tyler...
<wait>

@MSG_EVT303A_026
<bup 0 17 5>
Yeah, I guess it's payback for what
I've been doing, huh?
<wait>

@MSG_EVT303A_027
<bup 0 2 5>
Huh!?
<wait>

@MSG_EVT303A_028
<bup 0 17 5>
...Look, dude, I know you saw my paper
and that letter...
<wait>
I've been practicing euthanasia ever since
I graduated.
<wait>
...That's my deep, dark secret...
<wait>

@MSG_EVT303A_029
<bup 0 2 5>
I'd heard rumors, but I never thought the
death doctor could be someone like you...
<wait>
Why would you do that!?
<wait>

@MSG_EVT303A_030
<bup 0 17 5>
...One of the professors I had
before we met died of cancer.
<wait>
It was already too late when they
found it...
<wait>
Professor Bonca told them that himself.
<wait>
All he had left to look forward to were a few
weeks of suffering and painful treatments.
<wait>
Good people shouldn't have to go through
pain like that before they die.
<wait>
...So I gave him the gift of a painless death.
<wait>

@MSG_EVT303A_031
<bup 0 2 5>
But, that's--!
<wait>

@MSG_EVT303A_032
<bup 0 17 5>
Of course people would prefer to live.
It's only natural...
<wait>
...but if everything causes pain,
and there's no chance of recovery...
<wait>
...then, are you really living?
<wait>
No, you're just sticking around so
other people don't feel bad.
<wait>

@MSG_EVT303A_033
<bup 0 2 5>
That isn't true...
<wait>

@MSG_EVT303A_034
<bup 0 17 5>
I know it's naive...
<wait>
But, I knew there might be consequences
when I started doing it.
<wait>
You probably think it's just suicide.
Or worse, murder...
<wait>
...But, things are different now.
I have to be there for Amy!
<wait>
If you're gonna turn me in, at least
wait until Amy's gone, okay?
<wait>

@MSG_EVT303A_035
<bup 0 2 5>
You aren't doing that to Amy.
I won't let you.
<wait>

@MSG_EVT303A_036
<bup 0 17 5>
......
<wait>
<bup_cls>
