
@MSG_EVT309A_001
- Remains of Rubora, Zimbabwe -
<wait>

@MSG_EVT309A_002
<bup 0 8 1>
We're finally here!
<wait>
The sky's so clear... Mmm, breathe
in that air...!
<wait>
<bup 0 8 5>
......
<wait>
...And, it's deserted.
<wait>

@MSG_EVT309A_003
<bup 0 2 5>
I think we're looking at the results
of a GUILT outbreak...
<wait>

@MSG_EVT309A_004
<bup 0 8 5>
...Ohhh, I wish we weren't so far
away from home...
<wait>

@MSG_EVT309A_005
<bup 0 2 5>
Hey, don't talk like that.
<wait>
<bup_cls>

@MSG_EVT309A_006
"Over here!"
<wait>

@MSG_EVT309A_007
<bup 0 8 1>
Who's that?
<wait>
<bup_cls>

@MSG_EVT309A_008
<bup 0 19 1>
It's nice to finally meet you, Dr. Stiles!
<wait>

@MSG_EVT309A_009
<bup 0 2 1>
Oh, Director Miller, sir!
<wait>
This is Langston Miller, from
Caduceus Europe.
<wait>

@MSG_EVT309A_010
<bup 0 8 1>
Right. He's the one who assigned you
to this mission.
<wait>

@MSG_EVT309A_011
<bup 0 19 1>
I was getting worried...
You're a little late.
<wait>
You see, one of our coordinators is sick,
and we don't know exactly where
<wait>
the research lab is...
There's been a lot to worry about.
<wait>
<bup_cls>

@MSG_EVT309A_012
<bup 0 20 1>
Sir! I have an update!
<wait>
We searched sectors B-2 through 4,
but could not locate the target.
<wait>

@MSG_EVT309A_013
<bup 0 19 1>
Hmph... In that case, expand your search
into the C areas, as well.
<wait>

@MSG_EVT309A_014
<bup 0 20 1>
Yes sir!
<wait>
<bup_cls>

@MSG_EVT309A_015
<bup 0 19 1>
The jungle makes a birds-eye search
impossible... We tried to narrow it down
<wait>
back home, but we still have a lot of ground
to cover.
<wait>

@MSG_EVT309A_016
<bup 0 2 1>
Must be frustrating...
<wait>

@MSG_EVT309A_017
<bup 0 8 1>
I have a bad feeling about this.
<wait>

@MSG_EVT309A_018
<bup 0 19 1>
You may as well join the search... Report back
if you manage to find anything.
<wait>
Here's a map of the area. We've sent
teams out here...and here...
<wait>
<bup_cls>

@MSG_EVT309A_019
<bup 0 8 1>
What kind of map is this? I can't make out
any landmarks or anything...
<wait>

@MSG_EVT309A_020
<bup 0 2 1>
Well...let's get started, I guess.
<wait>
<bup_cls>

@MSG_EVT309A_021
～ Six long hours later ～
<wait>

@MSG_EVT309A_022
<bup 0 20 1>
Are you all right, miss?
<wait>

@MSG_EVT309A_023
<bup 0 8 9>
I'm glad...we can drive...but this jeep...
sure is a...bumpy ride...
<wait>

@MSG_EVT309A_024
<bup 0 20 1>
Well there aren't any roads in this area,
but at least we're not in the jungle.
<wait>
It's been a long time--let's head back
to camp for a breather.
<wait>

@MSG_EVT309A_025
<bup 0 8 4>
I didn't mean--
<wait>
<bup 0 8 5>
...Huh? Stop the jeep!
<wait>
<bup_cls>

@MSG_EVT309A_046
<bup 0 8 3>
...There's someone in that house!
<wait>

@MSG_EVT309A_026
<bup 0 2 1>
It's a little kid... I thought they said
the area was abandoned!
<wait>
<bup_cls>

@MSG_EVT309A_027
～ One hour after that ～
<wait>

@MSG_EVT309A_028
<bup 0 19 1>
...The boy answers to Reuben... We think.
<wait>

@MSG_EVT309A_029
<bup 0 8 1>
Nice to meet you, Reuben!
<wait>

@MSG_EVT309A_030
<bup 0 28 1>
......*nod*
<wait>

@MSG_EVT309A_031
<bup 0 2 1>
What was he doing in there?
<wait>

@MSG_EVT309A_032
<bup 0 19 1>
We think he used to live there. His family
actually lives not far from here.
<wait>

@MSG_EVT309A_033
<bup 0 2 1>
Shouldn't we take him home?
<wait>

@MSG_EVT309A_034
<bup 0 19 1>
Perhaps, but...
<wait>
The boy seems to know the location
of the research lab.
<wait>
Apparently his brother worked there, and
Reuben got to tag along once or twice.
<wait>
It's more of a lead than we've found out
here thus far, don't you agree?
<wait>

@MSG_EVT309A_035
<bup 0 28 2>
......
<wait>

@MSG_EVT309A_036
<bup 0 2 1>
It's as good a plan as any.
<wait>

@MSG_EVT309A_037
<bup 0 8 2>
Thank you, Reuben!
<wait>

@MSG_EVT309A_038
<bup 0 28 2>
......!
<wait>
<bup_cls>

@MSG_EVT309A_039
- Abandoned Delphi Research Lab -
<wait>

@MSG_EVT309A_040
<bup 0 19 1>
...As we thought--it's completely vacant.
<wait>

@MSG_EVT309A_041
<bup 0 2 5>
What exactly are we looking for?
<wait>

@MSG_EVT309A_042
<bup 0 8 5>
Let me take samples from the walls
and floor, just in case...
<wait>

@MSG_EVT309A_043
<bup 0 19 1>
Thank you, young lady.
<wait>
We'll need to undergo decontamination
procedures after this, but hopefully we'll
<wait>
find something to make it worthwhile.
<wait>
...This is no place for a child, I'm afraid.
Could you wait outside?
<wait>

@MSG_EVT309A_044
<bup 0 28 1>
*nod*
<wait>

@MSG_EVT309A_045
<bup 0 19 1>
There's a good lad.
<wait>
*sigh* Cross your fingers, yes?
<wait>
<bup_cls>
