
@MSG_EVT302A_001
<bup 0 13 1>
...Several GUILT victims are currently
hospitalized here at Caduceus.
<wait>
We obviously need to treat them ASAP,
but we don't know how...
<wait>
So, at the moment, we're trying to slow
the disease's progression.
<wait>

@MSG_EVT302A_002
<bup 0 2 5>
I had a lot of trouble operating
on GUILT as well.
<wait>

@MSG_EVT302A_003
<bup 0 13 1>
Today's patient is similar to your
previous experience with GUILT.
<wait>
I watched the video footage of your
surgery at Hope, but...
<wait>
...you moved so quickly I couldn't tell
what was going on.
<wait>
I'm looking forward to seeing you
in action today.
<wait>

@MSG_EVT302A_004
<bup 0 17 1>
Let's see what you've got, buddy.
<wait>

@MSG_EVT302A_005
<bup 0 2 5>
I don't need any more pressure, thanks...
<wait>

@MSG_EVT302A_006
<bup 0 13 1>
Dr. Myers will handle the anesthesia.
<wait>

@MSG_EVT302A_007
<bup 0 15 1>
No problem.
<wait>

@MSG_EVT302A_008
<bup 0 17 1>
Myers is a tough chick, Derek.
<wait>
If you screw this up, don't expect her to
ever work with you again.
<wait>

@MSG_EVT302A_009
<bup 0 15 1>
Stop trying to scare the newbie, Chase.
<wait>
This is a difficult operation, and we don't
have room for any mistakes.
<wait>
...Just do your best, kid.
<wait>

@MSG_EVT302A_010
<bup 0 2 1>
Y-You got it...
<wait>
<bup_cls>

@MSG_EVT302B_001
<bup 0 14 1>
Unbelievable.
<wait>

@MSG_EVT302B_002
<bup 0 15 1>
He's still got a lot to learn...but that
was incredible!
<wait>

@MSG_EVT302B_003
<bup 0 13 1>
Stiles finished thirty minutes earlier
than we estimated...
<wait>
Hopefully, the patient will recover
quickly, as well.
<wait>

@MSG_EVT302B_004
<bup 0 17 1>
Heh...looks like times have changed.
<wait>
<bup_cls>
