
@MSG_EVT305A_001
<bup 0 2 1>
Excuse me, sir.
You called for me?
<wait>

@MSG_EVT305A_002
<bup 0 13 1>
...This operation is amazing.
<wait>
Your focus and concentration...
simply unbelievable.
<wait>

@MSG_EVT305A_003
<bup 0 2 1>
Is that the video of our GUILT
procedure the other day?
<wait>

@MSG_EVT305A_004
<bup 0 13 1>
I had my secretary transfer it to
an HDV media card.
<wait>
Watching this in slow motion actually reveals
quite a bit...
<wait>
Anyway, have a seat.
There's an event I'd like you to attend.
<wait>

@MSG_EVT305A_005
<bup 0 2 1>
Hm, okay.
<wait>
<bup_cls>

@MSG_EVT305A_006
<bup 0 16 1>
Hey, real fast...
<wait>
I need your signature for this.
<wait>

@MSG_EVT305A_007
<bup 0 13 1>
...Victor, we're in the middle of a meeting.
<wait>

@MSG_EVT305A_008
<bup 0 16 1>
Yeah, well this'll only take a second.
<wait>

@MSG_EVT305A_009
Victor Niguel, age 26: Head of the
Caduceus research division.
<wait>
He's responsible for a lot of the organization's
proprietary medical technology.
<wait>

@MSG_EVT305A_010
This is that proposal we went over yesterday.
There are no changes.
<wait>
...Huh? Who's the new guy?
<wait>

@MSG_EVT305A_011
<bup 0 13 1>
This is Derek Stiles, from Hope Hospital.
<wait>
...He's hardly new. You need to get
out of that laboratory more often.
<wait>

@MSG_EVT305A_012
<bup 0 16 1>
Ohhh... He's that Healing Touch guy.
<wait>
I'm Victor, from R&D. How's it going?
<wait>

@MSG_EVT305A_013
<bup 0 2 1>
It's going well...
Nice to meet you.
<wait>
<bup_cls>

@MSG_EVT305A_014
<bup 0 13 1>
How's this, Victor?
<wait>

@MSG_EVT305A_015
<bup 0 16 1>
...Looks good to me.
Okay, later.
<wait>
<bup_cls>

@MSG_EVT305A_016
<bup 0 13 1>
...Sorry. Victor doesn't concern himself with
trivial concepts like "manners."
<wait>
I apologize for the interruption.
Let's discuss your trip.
<wait>
Our International Conference will
be held in Angeles Bay this month.
<wait>
Topics will focus on the recent issue
of medical terrorism.
<wait>
Dr. Stiles, I'd like you to attend
as a representative of Caduceus USA.
<wait>
I'd also like you to speak about the strains of
GUILT you've treated, and the steps involved.
<wait>
Can you do that?
<wait>

@MSG_EVT305A_017
<bup 0 2 1>
Well, I haven't really been here that long...
<wait>
...I'm sure some of the others could
do a better job...
<wait>

@MSG_EVT305A_018
<bup 0 13 1>
We're also showing footage of your operations.
<wait>
I'd prefer that you were there to explain the
procedures, step by step.
<wait>
Dr. Myers will be going, so I'll ask her
to translate for you, as well.
<wait>
Have fun, Derek.
<wait>
<bup_cls>

@MSG_EVT305A_019
- Angeles Bay Conference Center -
<wait>

@MSG_EVT305A_020
"...Once again, that was Dr. Stiles speaking
on behalf of Caduceus USA."
<wait>

@MSG_EVT305A_021
<bup 0 2 2>
...*sigh* I'm glad that's over.
Thanks for your help, Dr. Myers.
<wait>

@MSG_EVT305A_022
<bup 0 15 1>
No problem. I think the video footage
really got their attention.
<wait>
You could've loosened up a little
out there, though.
<wait>
You're not used to speaking in front of
big groups like that, are you?
<wait>

@MSG_EVT305A_023
<bup 0 2 1>
I'm usually too busy just helping patients...
<wait>
Even if I had time for meetings,
I'd probably just fall asleep.
<wait>
So, yeah...that was my first presentation.
<wait>

@MSG_EVT305A_024
<bup 0 15 1>
Yeah, a lot of doctors are that way, but you
should still make time to attend conferences.
<wait>
It's the only way to keep up with the latest
technology, you know?
<wait>
Being a doctor is like being a
lifelong student.
<wait>

@MSG_EVT305A_025
<bup 0 2 1>
Dr. Kasal used to say the same
thing--all doctors are students.
<wait>

@MSG_EVT305A_026
<bup 0 15 1>
...Good ol' Greg, huh? Now he was
one hell of a public speaker.
<wait>
He was confident, threw in some jokes,
never had stage fright...
<wait>
...I remember staying up all night
helping him make slides...
<wait>
...Nevermind. That's all in the past now,
isn't it?
<wait>

@MSG_EVT305A_027
<bup 0 2 1>
Sounds like you guys were close.
<wait>

@MSG_EVT305A_028
<bup 0 15 1>
It...wasn't like that.
<wait>
He was a great guy, so I always
did what I could to help out.
<wait>

@MSG_EVT305A_029
<bup 0 2 1>
Really...
<wait>

@MSG_EVT305A_030
<bup 0 15 1>
...What's that supposed to mean!?
<wait>

@MSG_EVT305A_031
<bup 0 2 1>
Hear that? I think they're starting
the next presentation.
<wait>
<bup_cls>

@MSG_EVT305A_032
"...That concludes the disease treatment
workshop."
<wait>
"Next, we'll have an update on the fight
against medical terrorism."
<wait>
"Speaking on this topic is Langston Miller,
Director of Caduceus Europe."
<wait>

@MSG_EVT305A_033
<bup 0 19 1>
I received this report a few hours ago.
I hope it finds you well...
<wait>
As we all know, medical terrorism poses a
serious threat to all the world's citizens.
<wait>
Reports of GUILT have doubled in
the past year alone.
<wait>
Unfortunately, the motivation behind
this epidemic is still unknown.
<wait>
But, we have received confirmation that the
group responsible calls themselves "Delphi."
<wait>

@MSG_EVT305A_034
<bup 0 15 1>
Delphi...
The Greek oracle?
<wait>

@MSG_EVT305A_035
<bup 0 19 1>
The messages we've received from
them have been cryptic, at best.
<wait>
...Their philosophy and demands
are still a mystery.
<wait>
Are they related to other terrorist cells?
We don't have an answer.
<wait>
For all we know, they could be nothing
more than a fanatical cult.
<wait>
But, whoever they are, we know that
they're hostile and organized.
<wait>
We believe there may be additional clues hidden
in the strange letters that arrived shortly
<wait>
before each GUILT operation.
<wait>

@MSG_EVT305A_036
<bup 0 2 5>
...We received one of those at Hope Hospital.
<wait>

@MSG_EVT305A_037
<bup 0 19 1>
Medicine has advanced quickly since
the advent of genetic engineering.
<wait>
But, as GUILT has shown us, disease
can evolve just as quickly.
<wait>
The ramifications of medical terrorism
are grave, indeed.
<wait>
And, it's going to take our best minds
to devise a way to stop it...
<wait>
...though we may finally have somewhere
for them to start looking.
<wait>
We've received news of an abandoned
Delphi research facility...
<wait>
...It seems they entered a small African
village, possibly by posing as the NPO.
<wait>
...I'm afraid they were using the
townspeople to develop GUILT.
<wait>

@MSG_EVT305A_038
<bup 0 15 1>
...Bastards.
<wait>

@MSG_EVT305A_039
<bup 0 19 1>
The town was destroyed, and the facility
has been long since abandoned.
<wait>
But, I'm sure there's something there
that could lead us to Delphi.
<wait>
I propose that Caduceus send a
research team to Africa.
<wait>
Supplies and manpower will need to
be approved by each division.
<wait>
I hope to have everyone's sincere
cooperation in this matter.
<wait>
<bup_cls>
