
@MSG_EVT310A_001
<bup 0 8 5>
After all that, we still haven't learned
anything about Delphi...
<wait>

@MSG_EVT310A_002
<bup 0 2 1>
The African GUILT victims are being
transferred to Caduceus Europe, right?
<wait>
...Hopefully that will lead to something.
<wait>

@MSG_EVT310A_003
<bup 0 8 1>
*sigh* Yeah, but this was all so tiring...
<wait>
Director Miller is late. I wonder who he was
speaking with on the radio.
<wait>
<bup_cls>

@MSG_EVT310A_004
Dr. Stiles!
<wait>

@MSG_EVT310A_005
<bup 0 2 1>
What is it?
<wait>

@MSG_EVT310A_006
<bup 0 19 1>
The boy...
Reuben's been infected by GUILT!
<wait>

@MSG_EVT310A_007
<bup 0 2 3>
What? ...How!?
<wait>
<bup_cls>

@MSG_EVT310B_001
<bup 0 28 1>
......
<wait>

@MSG_EVT310B_002
<bup 0 8 1>
Try not to move, okay Reuben?
<wait>

@MSG_EVT310B_003
<bup 0 2 1>
You're going to be all right.
<wait>

@MSG_EVT310B_004
<bup 0 8 1>
Your mother's waiting just over there,
so you'll be able to see her soon, okay?
<wait>

@MSG_EVT310B_005
<bup 0 2 1>
Director Miller might be able to send him
back to England for further treatment.
<wait>
Maybe we should ask him...
<wait>

@MSG_EVT310B_006
<bup 0 8 1>
No, there's a Red Cross outpost in the
next town over...
<wait>
I think it's best to keep his treatment local
to avoid any complications.
<wait>

@MSG_EVT310B_007
<bup 0 28 1>
......
<wait>

@MSG_EVT310B_008
<bup 0 8 1>
...A gift for us?
<wait>
But...isn't this your book?
<wait>
Can we accept this, Dr. Stiles?
He... wants us to, I think.
<wait>
Huh? ...Wait, this isn't a book...
<wait>
<bup_cls>

@MSG_EVT310B_009
<bup 0 2 1>
It's a file folder...
<wait>
It's in some kind of code, but...
Yeah, read this part.
<wait>
...GUILT.
<wait>

@MSG_EVT310B_010
<bup 0 8 1>
His brother must have given it to him.
<wait>

@MSG_EVT310B_011
<bup 0 2 1>
Thank you, Reuben. This is going
to save a lot of people!
<wait>

@MSG_EVT310B_012
<bup 0 28 2>
......
<wait>
<bup_cls>

@MSG_EVT310B_013
"Dr. Stiles!"
<wait>

@MSG_EVT310B_014
<bup 0 19 1>
There you are...
<wait>

@MSG_EVT310B_015
<bup 0 2 2>
Director Miller, we have good news!
Reuben gave us this--
<wait>

@MSG_EVT310B_016
<bup 0 19 1>
That can wait. We just received an urgent
telegram from America.
<wait>

@MSG_EVT310B_017
<bup 0 2 5>
Urgent? I wonder...
<wait>
......!
<wait>
No way...
<wait>

@MSG_EVT310B_018
<bup 0 8 5>
What's wrong?
<wait>

@MSG_EVT310B_019
<bup 0 2 3>
Dr. Kasal from Hope Hospital was just
admitted to Caduceus USA...
<wait>

@MSG_EVT310B_020
<bup 0 8 9>
Caduceus?
Don't tell me he--!
<wait>

@MSG_EVT310B_021
<bup 0 2 3>
Dr. Kasal's been infected by a
new strain of GUILT!
<wait>
<bup_cls>
