
@MSG_EVT307A_001
<bup 0 13 1>
...We received a letter of thanks
from the Conference Directors.
<wait>
I was worried when I heard about the attack.
I'm glad you both made it out safely.
<wait>

@MSG_EVT307A_002
<bup 0 2 1>
It's all thanks to Dr. Myers.
<wait>

@MSG_EVT307A_003
<bup 0 13 1>
Ha ha, she's definitely the toughest
woman in medicine today.
<wait>
You should ask her about some of her
adventures on the police force, sometime!
<wait>

@MSG_EVT307A_004
<bup 0 15 1>
Ah, Chief... Derek's going to take you seriously.
<wait>

@MSG_EVT307A_005
<bup 0 13 1>
He'd have good reason to.
<wait>
...Oh, that's right, there was one other
message I received.
<wait>
Dr. Stiles, Caduceus International
has requested your presence as part
<wait>
of the research team headed to
the Delphi facility in Africa.
<wait>

@MSG_EVT307A_006
<bup 0 2 1>
They asked for me?
That seems like a mistake...
<wait>

@MSG_EVT307A_007
<bup 0 13 1>
Don't be modest. We've all seen what you're
capable of.
<wait>
You have experience treating GUILT,
and you defused a bomb...
<wait>
Langston Miller, Director of Caduceus
Europe, was very impressed.
<wait>
And, the rest of the committee voted
unanimously... You should be proud.
<wait>

@MSG_EVT307A_008
<bup 0 2 1>
Yeah, but...
I've never left the country before.
<wait>

@MSG_EVT307A_009
<bup 0 13 1>
Well, you don't have much choice;
I already accepted on your behalf.
<wait>

@MSG_EVT307A_010
<bup 0 15 1>
Give it up, Stiles. Once Sidney decides
on something, there's no arguing with him.
<wait>
Looks like you're going to Africa.
<wait>
<bup_cls>

@MSG_EVT307A_011
<bup 0 2 6>
I didn't realize he could be so stubborn.
<wait>

@MSG_EVT307A_012
<bup 0 15 1>
I guess he's always been difficult.
That's what Greg told me, anyway.
<wait>
I remember him talking about the arguments
they'd get into when they were kids.
<wait>
The only reason Sidney went to school
overseas was supposedly because
<wait>
everyone told him not to.
<wait>

@MSG_EVT307A_013
<bup 0 2 1>
Dr. Kasal could be stubborn sometimes,
but never anything like that.
<wait>

@MSG_EVT307A_014
<bup 0 15 1>
At any rate, have fun in Africa.
<wait>
...As long as your partner's reliable,
I know you'll be fine.
<wait>

@MSG_EVT307A_015
<bup 0 2 1>
Partner?
<wait>
<bup_cls>
