
@MSG_EVT306A_001
<bup 0 2 1>
Man... Talk about long speeches.
<wait>

@MSG_EVT306A_002
<bup 0 15 1>
Well, a lot happened over the last year,
so I was expecting that.
<wait>
...I will not enjoy writing the summary report,
though.
<wait>
<bup_cls>

@MSG_EVT306A_021
<bup 0 15 1>
Huh!? The lights!
<wait>
<bup_cls>

@MSG_EVT306A_003
"What happened?"
<wait>
"What's going on here!?"
<wait>

@MSG_EVT306A_004
<bup 0 2 3>
The shutters are dropping...
Is there a fire!?
<wait>
<bup_cls>

@MSG_EVT306A_005
PA Speakers: "...You doctors and your
temporary cures are worthless!"
<wait>
"If you would all just die, maybe people
could finally stop living unnatural lives."
<wait>

@MSG_EVT306A_006
<bup 0 15 1>
What the hell...?
<wait>
<bup_cls>

@MSG_EVT306A_007
"What is this thing?"
<wait>
"Don't touch it! It-It's a bomb!"
<wait>
"There's a bomb!"
<wait>

@MSG_EVT306A_022
"Aaaaahhhhh!!"
<wait>

@MSG_EVT306A_008
<bup 0 2 3>
A b-bomb!? C'mon, Cybil!
We have to get outta here!
<wait>
<bup_cls>

@MSG_EVT306A_009
"Dammit, there's no way out!"
<wait>
"We're going to die!"
"Somebody help us!"
<wait>

@MSG_EVT306A_010
<bup 0 15 1>
......
<wait>
Sounds like it's over here...
Follow me, Dr. Stiles.
<wait>

@MSG_EVT306A_011
<bup 0 2 5>
Wh-What!? But, that's where the bomb is!
<wait>

@MSG_EVT306A_012
<bup 0 15 1>
Exactly.
<wait>

@MSG_EVT306A_013
<bup 0 2 5>
What are you going to do!?
<wait>
We have to run...
There's nowhere to go, but--
<wait>

@MSG_EVT306A_014
<bup 0 15 3>
I told you to follow me!
<wait>
If we're going to die anyway, what difference
does this make? Be a man!
<wait>

@MSG_EVT306A_015
<bup 0 2 5>
...Y-Yes, ma'am!
<wait>
<bup_cls>

@MSG_EVT306A_016
<bup 0 15 1>
You're going to dismantle the bomb.
I'll assist you.
<wait>

@MSG_EVT306A_017
<bup 0 2 5>
What!? I can't do that!
<wait>

@MSG_EVT306A_018
<bup 0 15 1>
...So you'd rather do nothing?
<wait>
Are you going to sit here and cry for help
like everyone else?
<wait>
Tch... Screw that.
<wait>
If this doesn't work, at least we can say
we tried.
<wait>

@MSG_EVT306A_019
<bup 0 2 4>
I... I'm ready.
<wait>

@MSG_EVT306A_020
<bup 0 15 3>
Give us some room!
<wait>
Set up a barricade with the desks
and tables. Everyone take cover!
<wait>
...Okay, Dr. Stiles.
There's no turning back now.
<wait>
<bup_cls>

@MSG_EVT306B_001
<bup 0 2 4>
*gasp* Ugh... I'm dizzy...
I can't feel my hands...
<wait>

@MSG_EVT306B_002
<bup 0 15 1>
At least we're alive, right?
S'better than dying, any day.
<wait>
Of course...I knew we'd be fine.
It was just a bomb--no big deal.
<wait>

@MSG_EVT306B_003
<bup 0 2 4>
(The Iron Vixen, huh...? That nickname of
hers is starting to make sense.)
<wait>
<bup_cls>

@MSG_EVT306B_004
<bup 0 15 1>
The lights are coming back on...
We should tell the others it's okay.
<wait>
We stopped the bomb, everyone!
It's all clear, now!
<wait>
<bup_cls>

@MSG_EVT306B_005
"Thank God!"
<wait>
"...I thought I was going to die."
<wait>
"We're alive!"
<wait>

@MSG_EVT306B_006
<bup 0 15 1>
Great job there, Stiles.
...You definitely learned from Greg.
<wait>

@MSG_EVT306B_007
<bup 0 2 1>
Heh, same to you, Dr. Myers...
You're pretty tough.
<wait>
<bup_cls>

@MSG_EVT306B_008
"Woohoo!"
<wait>
"W-We're alive!?"
<wait>
"Let's hear it for Dr. Stiles!"
<wait>

@MSG_EVT306B_009
<bup 0 19 1>
...I believe we've found the perfect candidate
for the Africa mission.
<wait>
<bup_cls>
