
@MSG_EVT308A_001
- International Flight 326, Destination: Africa -
<wait>

@MSG_EVT308A_002
<bup 0 8 1>
Rubora's far away...
<wait>
I mean, three transfers and 33 hours
of total travel time? ...Wow.
<wait>

@MSG_EVT308A_003
<bup 0 2 4>
...At least you're used to it.
<wait>
I've never even been to Mexico...
and I don't like flying.
<wait>

@MSG_EVT308A_004
<bup 0 8 1>
Remember to drink plenty of fluids, and
get up periodically to stretch your legs.
<wait>
It wouldn't look very good for a doctor
to get sent to the hospital for blood clots.
<wait>
It'll be hot in Africa, too.
Try not to get heat stroke.
<wait>

@MSG_EVT308A_005
<bup 0 2 4>
I hope getting vaccinated for
the endemic diseases was enough...
<wait>
<bup_cls>

@MSG_EVT308A_006
"Attention please."
<wait>
"Is there a doctor on the plane?"
<wait>
"I repeat, are there any doctors on this flight?"
<wait>
"One of the passengers is sick...
We don't know how to treat him."
<wait>
"If you have any medical training,
please notify a flight attendant!"
<wait>

@MSG_EVT308A_007
<bup 0 8 5>
Doctor!
<wait>

@MSG_EVT308A_008
<bup 0 2 4>
...So much for sleeping on the plane.
<wait>
<bup_cls>

@MSG_EVT308B_001
<bup 0 2 1>
I think he'll be okay...
<wait>

@MSG_EVT308B_002
<bup 0 8 1>
I contacted a hospital near Rubora.
We can take him there once we land.
<wait>

@MSG_EVT308B_003
<bup 0 2 1>
Doctors really are on call 24/7, aren't they?
<wait>
<bup_cls>
