
@MSG_EVT301A_001
<bup 0 9 1>
Today should be Derek's first
day with Caduceus.
<wait>

@MSG_EVT301A_002
<bup 0 10 1>
Are you worried?
<wait>

@MSG_EVT301A_003
<bup 0 9 1>
I wouldn't say worried...
<wait>
We're down one doctor and one assistant.
<wait>
It won't be easy to operate with two of our
best people gone.
<wait>

@MSG_EVT301A_004
<bup 0 10 1>
Derek has potential, but he's far from perfect.
I wasn't about to send him to Caduceus
<wait>
without an assistant he's comfortable with.
<wait>
Besides, Caduceus is supposed to help us
find replacement staff.
<wait>

@MSG_EVT301A_005
<bup 0 9 1>
I see...
<wait>
Still, I didn't expect Stiles to be the selfless
humanitarian type.
<wait>

@MSG_EVT301A_006
<bup 0 10 1>
Do you think he'll be able to handle
the pressure?
<wait>

@MSG_EVT301A_007
<bup 0 9 1>
...I suppose we'll find out.
<wait>

@MSG_EVT301A_008
<bup 0 10 2>
He's going to be surprised... I didn't get a
chance to tell him about Sidney.
<wait>
<bup_cls>

@MSG_EVT301A_009
"Caduceus"
<wait>
An international organization seeking to
eradicate disease.
<wait>
"Caduceus USA" is the American branch.
<wait>
There are additional branches in Europe
and Japan.
<wait>
The US branch specializes in researching
anti-infection measures.
<wait>
It was originally established in 1980 as
a top-secret offshoot of HHS.
<wait>
(The Department of Health and
Human Services)
<wait>
Once the organization went international, the
central agency was renamed Caduceus USA.
<wait>
They are authorized to act on their own,
outside of government protocols.
<wait>

@MSG_EVT301A_010
"Derek Stiles, you may come in now."
<wait>

@MSG_EVT301A_011
<bup 0 2 1>
Hello...
<wait>
...Huh?
<wait>

@MSG_EVT301A_012
<bup 0 13 1>
Welcome to Caduceus USA, Derek.
<wait>
It's nice to meet you. I'm Sidney Kasal,
the Director of US Operations.
<wait>
My brother's told me a lot about you.
I'm glad you decided to accept our offer.
<wait>

@MSG_EVT301A_013
Sidney Kasal, age 35: Chief Director
of Caduceus. He dedicated his life
<wait>
to the study of clinical medicine after his
wife died of a tragic illness.
<wait>

@MSG_EVT301A_014
<bup 0 2 2>
Oh yeah... I think Dr. Kasal mentioned
having a brother.
<wait>
Uh, I mean--It was an honor to even be
considered for this position.
<wait>
<bup_cls>

@MSG_EVT301A_015
"Angie Thompson, would you come in
as well?"
<wait>

@MSG_EVT301A_016
<bup 0 8 1>
Yes, sir.
<wait>

@MSG_EVT301A_017
<bup 0 13 1>
Well, it's a pleasure to meet you, too.
<wait>
You're young, but I hear you're hard-working
and sharp as a tack.
<wait>
I look forward to seeing what you both
can do here at Caduceus.
<wait>

@MSG_EVT301A_018
<bup 0 8 1>
Thank you, sir. I'll do my best.
<wait>

@MSG_EVT301A_019
<bup 0 13 1>
The Secretary of Health and Human Services
should be here shortly.
<wait>
When I told him you were both coming
today, he insisted on stopping by.
<wait>
He's in charge around here, so I'm sure
you'll be seeing a lot of him.
<wait>
<bup_cls>

@MSG_EVT301A_020
"Right this way, Mr. Secretary..."
<wait>

@MSG_EVT301A_021
<bup 0 12 1>
Congratulations Derek, Angie...
I'm Richard Anderson.
<wait>
Well... Perhaps it would be more appropriate
to thank the both of you...
<wait>

@MSG_EVT301A_022
Richard Anderson: Current Secretary
of Health and Human Services.
<wait>
After a long career in politics, he became
the Executive Director of Caduceus.
<wait>

@MSG_EVT301A_023
...Thank you for accepting such a
dangerous job.
<wait>
I'm told that operating on GUILT
puts the surgeon at risk, too.
<wait>
...And we still have no idea who's
responsible for spreading it.
<wait>

@MSG_EVT301A_024
<bup 0 8 5>
......
<wait>

@MSG_EVT301A_025
<bup 0 12 1>
But, from what I hear about you two,
you're up to the task.
<wait>
Scientific advances, DNA treatments,
changing social environments...
<wait>
We live in challenging times, and it's our
responsibility to research and develop
<wait>
treatments that ensure the stability
of world health.
<wait>
...What all this means is, I'm pleased to
have you both on board.
<wait>
I hope you'll do your best, and take your
work seriously.
<wait>

@MSG_EVT301A_026
<bup 0 2 1>
...Yes sir!
<wait>
<bup_cls>

@MSG_EVT301A_027
- Caduceus USA, Conference Room -
<wait>

@MSG_EVT301A_028
<bup 0 13 1>
...and this is Dr. Clarks, our resident
surgical expert.
<wait>

@MSG_EVT301A_029
<bup 0 14 1>
Oh, I wouldn't say expert. There's always
room for improvement.
<wait>

@MSG_EVT301A_030
Stephen Clarks, age 42: Caduceus's Chief
Surgeon. He has a wife and two children.
<wait>
His kind demeanor has been a blessing
and comfort to many patients.
<wait>

@MSG_EVT301A_031
Nice to meet you.
I'm Stephen Clarks.
<wait>

@MSG_EVT301A_032
<bup 0 2 1>
Nice to meet you, Dr. Clarks.
<wait>

@MSG_EVT301A_033
<bup 0 13 1>
This is our anesthesiologist, Dr. Myers.
<wait>

@MSG_EVT301A_034
<bup 0 15 1>
The name's Cybil.
Nice to meet you.
<wait>

@MSG_EVT301A_035
Cybil Myers: A well-respected anesthesiology
specialist.
<wait>
She used to be a police officer, but left
the force to practice medicine.
<wait>
She's intelligent and very spirited. She's kept
her old nickname from the force, "Iron Vixen."
<wait>

@MSG_EVT301A_036
...You're from Hope Hospital, right?
Isn't that Greg Kasal's office?
<wait>

@MSG_EVT301A_037
<bup 0 2 1>
...Do you know him?
<wait>

@MSG_EVT301A_038
<bup 0 15 1>
We went to med school together.
He's helped me in a lot of ways...
<wait>
I'm actually the only person here who knew
Sidney was his younger brother.
<wait>
Anyway, if you have any questions,
don't be afraid to ask.
<wait>

@MSG_EVT301A_039
<bup 0 8 1>
Of course. It's nice to meet you.
<wait>

@MSG_EVT301A_040
<bup 0 13 1>
Some of our staff aren't here today,
so you'll have to meet them later...
<wait>

@MSG_EVT301A_041
<bup 0 14 1>
...Think this will lighten our workload?
<wait>

@MSG_EVT301A_042
<bup 0 15 1>
Doubt it. Have you taken a look
at the list of incoming patients?
<wait>

@MSG_EVT301A_043
<bup 0 14 1>
*sigh* Oh well...
<wait>

@MSG_EVT301A_044
<bup 0 2 1>
...Have you guys been working with a lot
of patients here?
<wait>

@MSG_EVT301A_045
<bup 0 14 1>
The public isn't aware of this yet, but we're
on the verge of an outbreak...
<wait>

@MSG_EVT301A_046
<bup 0 13 1>
Congress recently voted in favor of giving us
a budget increase, but...
<wait>
...That won't be good enough.
<wait>
At any rate, we won't need you to start
treating patients until tomorrow.
<wait>
So, for today, let's get all that paperwork
out of the way.
<wait>

@MSG_EVT301A_047
<bup 0 2 1>
Sounds good.
<wait>
<bup_cls>

@MSG_EVT301A_048
<bup 0 2 1>
Sheesh... Who knew filling out employment
forms could be so tiring?
<wait>

@MSG_EVT301A_049
<bup 0 8 1>
It's pretty late.
<wait>

@MSG_EVT301A_050
<bup 0 2 1>
Yeah...
<wait>
Hey, why'd you come to Caduceus, anyway?
<wait>

@MSG_EVT301A_051
<bup 0 8 1>
...Does it matter?
<wait>

@MSG_EVT301A_052
<bup 0 2 1>
Uh... Well, I was just curious why
you decided to join, too.
<wait>

@MSG_EVT301A_053
<bup 0 8 1>
Dr. Kasal recommended me.
<wait>

@MSG_EVT301A_054
<bup 0 2 1>
That's not what I meant--
<wait>
Before, it seemed like you knew
something about GUILT, so...
<wait>
...does it have anything to do with
your father's disappearance?
<wait>

@MSG_EVT301A_055
<bup 0 8 1>
Not really...
<wait>
Caduceus has the newest technology
and research material.
<wait>
...I wanted to be here, on the front line
of modern medicine.
<wait>
It's the same as you wanting to become
a master surgeon...
<wait>
I want to be a master assistant.
That's really all there is to it.
<wait>

@MSG_EVT301A_056
<bup 0 2 1>
I guess that makes sense...
We'll work hard, together.
<wait>
<bup_cls>

@MSG_EVT301A_057
"...the potassium chloride's ready,
so if we increase the sedative..."
<wait>

@MSG_EVT301A_058
<bup 0 2 1>
...Huh? It sounds like someone's
on the phone...
<wait>

@MSG_EVT301A_059
<bup 0 17 5>
Derek!?
<wait>
Sorry, gotta run. Yeah, I'll get back to you,
dude.
<wait>
<bup_cls>

@MSG_EVT301A_074
<bup 0 17 5>
No way...
<wait>

@MSG_EVT301A_060
<bup 0 2 1>
......Tyler?
<wait>

@MSG_EVT301A_061
<bup 0 17 1>
...No way. No way!
You seriously work here now?
<wait>

@MSG_EVT301A_062
Tyler Chase: A surgeon at Caduceus.
He went to med school with Derek.
<wait>
Tyler's very optimistic, and tries to keep
everyone in a good mood.
<wait>

@MSG_EVT301A_063
<bup 0 2 1>
Y-Yeah, I started today...
<wait>

@MSG_EVT301A_064
<bup 0 17 1>
I must say, it's very much a pleasure to
meet your gorgeous assistant...
<wait>

@MSG_EVT301A_065
<bup 0 8 1>
M-My name is Angie Thompson.
...Nice to meet you.
<wait>

@MSG_EVT301A_066
<bup 0 17 1>
Man, I heard 'em say the new guy's name
was Stiles, but... This rocks!
<wait>
I didn't think you were adventurous enough
to join Caduceus!
<wait>
...and, I mean, you weren't exactly
an A student, man...
<wait>
But, everyone here's been hyping you as
a "highly skilled surgeon."
<wait>

@MSG_EVT301A_067
<bup 0 2 1>
Wh-What? Nobody told me anything
about that...
<wait>
...I don't want people expecting too much
from me right away.
<wait>

@MSG_EVT301A_068
<bup 0 17 1>
Well, you have a pretty good track
record so far, Dr. Stiles.
<wait>
...People can change a lot in three
years, y'know?
<wait>

@MSG_EVT301A_069
<bup 0 2 1>
...What about you?
<wait>
You were probably one of the top five
in our class...
<wait>

@MSG_EVT301A_070
<bup 0 17 1>
I guess you can see for yerself, hm?
<wait>
Good luck, man. We oughtta throw you
a party or something... See ya!
<wait>
<bup_cls>

@MSG_EVT301A_071
<bup 0 2 1>
...I can't believe Tyler works here.
<wait>
Oh, sorry... Tyler's a friend of mine
from med school.
<wait>

@MSG_EVT301A_072
<bup 0 8 1>
Yeah, I kind of figured that out.
<wait>

@MSG_EVT301A_073
<bup 0 2 1>
He was the professor's favorite, so I guess I
assumed he'd still be taking classes...
<wait>
...Potassium chloride, huh? I wonder
if he's doing animal testing...
<wait>
<bup_cls>
