
@MSG_EVT304A_001
<bup 0 18 1>
Doctor! Quickly!
Amy's condition is getting worse!
<wait>
Her vitals are dropping, and
she's losing consciousness!
<wait>
<bup_cls>

@MSG_EVT304A_002
<bup 0 14 1>
What!?
<wait>
Everyone, prepare for surgery!
Angie, bring in the patient.
<wait>
I'll meet you in the O.R.
...Hurry!
<wait>

@MSG_EVT304A_003
<bup 0 8 5>
Yes sir!
<wait>
<bup_cls>

@MSG_EVT304A_004
<bup 0 2 5>
Tyler, this is an emergency!
C'mon, hurry!
<wait>

@MSG_EVT304A_005
<bup 0 17 5>
......
<wait>

@MSG_EVT304A_006
<bup 0 2 5>
What are you doing!?
Let's go!
<wait>

@MSG_EVT304A_007
<bup 0 17 5>
...You can't operate on her.
<wait>

@MSG_EVT304A_008
<bup 0 2 5>
What!? I have to!
<wait>

@MSG_EVT304A_009
<bup 0 17 5>
Haven't you seen the PET results?
The GUILT's already migrating...
<wait>
Her respiratory system's in trouble,
and her digestive tract is next.
<wait>

@MSG_EVT304A_010
<bup 0 2 3>
What are we supposed to do? Are you
just going to watch her die!?
<wait>

@MSG_EVT304A_011
<bup 0 17 5>
...Do you have any idea how many
things we've tried!?
<wait>
Dr. Clarks couldn't help, and he's
the best there is!
<wait>
...All he could do is thin out some
of the tumors...
<wait>
I just watch her get weaker, day by day...
<wait>
Amy...doesn't have a lot of time left.
<wait>
What are we supposed to do?
<wait>
I'll tell you--we're supposed to leave her
alone so she doesn't have to suffer.
<wait>
Do you really think cutting her open again
and again is gonna do anything!?
<wait>

@MSG_EVT304A_012
<bup 0 2 3>
So, what? You want us to watch
GUILT tear her apart!?
<wait>

@MSG_EVT304A_013
<bup 0 17 5>
You don't get it!
<wait>
...She doesn't need to go through
all this suffering.
<wait>
Even if this operation helps, she might
never open her eyes again.
<wait>
...She'll just be connected to some machine!
...waiting to die...
<wait>
If that's the case, then I'd rather send her
off myself...
<wait>

@MSG_EVT304A_014
<bup 0 2 3>
You call yourself a doctor!?
<wait>

@MSG_EVT304A_015
<bup 0 17 3>
I'm Amy's brother before I'm a doctor!
<wait>
You think I'm going to watch my sister
suffer just because that's my job!?
<wait>
I don't care if I lose my license...
We're talking about my sister!
<wait>
<bup_cls>

@MSG_EVT304A_016
<bup 0 8 3>
What are you still doing here!?
Hurry up!
<wait>
<bup_cls>

@MSG_EVT304A_017
<bup 0 14 1>
......
<wait>

@MSG_EVT304A_018
<bup 0 2 5>
Dr. Clarks...?
<wait>

@MSG_EVT304A_019
<bup 0 14 1>
We may not...be able to operate.
<wait>

@MSG_EVT304A_020
<bup 0 2 5>
What?
<wait>

@MSG_EVT304A_021
<bup 0 14 1>
The GUILT's in her lungs...it moved
a lot faster than we expected.
<wait>
And, I'm afraid she's not strong enough
to survive the surgery.
<wait>

@MSG_EVT304A_022
<bup 0 2 5>
What if we separate the operation
into two procedures...?
<wait>

@MSG_EVT304A_023
<bup 0 14 1>
No good...
<wait>
If we don't extract the GUILT entirely,
we'll be right back where we started.
<wait>

@MSG_EVT304A_024
<bup 0 17 5>
Now do you get it, Derek?
...This is how it always works.
<wait>
I always knew it would come down
to something like this...
<wait>

@MSG_EVT304A_025
<bup 0 2 5>
I'll operate on her.
<wait>
She'll be okay if we can extract all of it, right?
<wait>

@MSG_EVT304A_026
<bup 0 17 3>
Leave her alone, you bastard!
<wait>

@MSG_EVT304A_027
<bup 0 14 1>
...With the Healing Touch, it might
be possible...
<wait>

@MSG_EVT304A_028
<bup 0 27 7>
*gasp*...
......Tyler...
<wait>

@MSG_EVT304A_029
<bup 0 17 5>
...Amy!
<wait>

@MSG_EVT304A_030
<bup 0 27 7>
Tyler...
Please, do...the operation...
<wait>

@MSG_EVT304A_031
<bup 0 17 5>
I know you could hear us.
Aren't you... scared?
<wait>

@MSG_EVT304A_032
<bup 0 27 7>
...No... I'll be...fine...
<wait>
You worked so hard...to become
...a doctor...
<wait>
I'm going to try hard...too...
<wait>
I'm glad...that you are a good doctor...
<wait>
<bup_cls>

@MSG_EVT304A_033
<bup 0 17 4>
I thought I was doing what was
best for Amy...
<wait>
...but I was just a coward...
<wait>
I didn't even consider what she wanted...
<wait>
<bup 0 17 5>
Derek... Can you handle this operation for me?
<wait>
I don't deserve to touch her...
...not with these hands.
<wait>

@MSG_EVT304A_034
<bup 0 2 5>
I joined Caduceus so I could help people...
<wait>
What about you, Dr. Chase?
<wait>
Shouldn't we do everything we can
if it might save a person's life?
<wait>

@MSG_EVT304A_035
<bup 0 17 5>
...Yeah.
<wait>

@MSG_EVT304A_036
<bup 0 14 1>
Dr. Chase, please brief Dr. Stiles
on the Deftera strain of GUILT.
<wait>

@MSG_EVT304A_037
<bup 0 17 5>
Yeah, no problem.
...Hang in there, Sis--we'll be right back!
<wait>
<bup_cls>

@MSG_EVT304B_001
<bup 0 17 5>
Derek... It's your decision, man.
If you want to turn me in, do it.
<wait>
I'll resign, if that's what it takes.
I don't care...
<wait>
I'm just glad Amy's okay.
...Thanks, Derek.
<wait>

@MSG_EVT304B_002
<bup 0 2 5>
I want you to do me a favor.
<wait>

@MSG_EVT304B_003
<bup 0 17 5>
Huh?
<wait>

@MSG_EVT304B_004
<bup 0 2 5>
Re-edit that thesis you wrote, and offer
it to Caduceus.
<wait>

@MSG_EVT304B_005
<bup 0 17 5>
...You feeling okay, dude?
<wait>

@MSG_EVT304B_006
<bup 0 2 1>
Tyler, you've always been good at
writing detailed papers.
<wait>
Despite how you used the research,
your thesis was no exception.
<wait>
...Eliminating pain and suffering, facing death...
<wait>
Doctors and patients can both benefit
from your research.
<wait>
Find a way to use that information
to save people's lives.
<wait>
That's all I ask.
<wait>

@MSG_EVT304B_007
<bup 0 17 5>
......
<wait>
...No problem.
You got it, bro.
<wait>

@MSG_EVT304B_008
<bup 0 2 1>
......
<wait>
<bup_cls>

@MSG_EVT304B_009
<bup 0 18 2>
Oh, there you are!
<wait>
Amy's going to be awake soon.
<wait>

@MSG_EVT304B_010
<bup 0 2 1>
Let's go check on her, then.
What do you think, Big Brother?
<wait>

@MSG_EVT304B_011
<bup 0 17 5>
H-Hey! Don't call me that!
<wait>
<bup_cls>
