
@MSG_EVT404A_001
<bup 0 14 1>
Derek, you're going to be operating
on Dr. Kasal.
<wait>
<bup_cls>

@MSG_EVT404A_002
<bup 0 2 5>
Huh? But...I thought you were scheduled
for that procedure.
<wait>

@MSG_EVT404A_003
<bup 0 10 7>
I asked him to switch with you, Derek.
<wait>

@MSG_EVT404A_004
<bup 0 2 5>
...Why?
<wait>
Dr. Clarks is an experienced
surgeon--I'm just a...
<wait>

@MSG_EVT404A_005
<bup 0 10 7>
...I know that you told my brother
you couldn't operate on me.
<wait>
I'd like to know why not.
<wait>

@MSG_EVT404A_006
<bup 0 2 5>
Well... What if I did something wrong...?
I mean...you'd--
<wait>

@MSG_EVT404A_007
<bup 0 10 7>
Are you worried I won't make it?
<wait>

@MSG_EVT404A_008
<bup 0 2 5>
Of-Of course not! You're going to--
<wait>

@MSG_EVT404A_009
<bup 0 10 7>
Then make it happen.
<wait>
...It looks like I forgot to teach you a very
important lesson.
<wait>
You've developed your skills, but something's
still holding you back.
<wait>
Sometimes, a doctor needs to ignore his
personal relationships.
<wait>

@MSG_EVT404A_010
<bup 0 2 5>
...Huh?
<wait>

@MSG_EVT404A_011
<bup 0 10 7>
A friendship should have no bearing
on your surgical ability.
<wait>
Once someone is in the operating room,
they're your patient and nothing more.
<wait>
You're their doctor, so you save them.
That's all there is to it.
<wait>

@MSG_EVT404A_012
<bup 0 2 5>
But... I'm still human... I...
<wait>

@MSG_EVT404A_013
<bup 0 10 7>
This is especially important because
you have the Healing Touch.
<wait>
I won't let you end up like Robert...
<wait>

@MSG_EVT404A_014
<bup 0 2 5>
...Dr. Hoffman?
<wait>

@MSG_EVT404A_015
<bup 0 10 7>
I'll explain it when the time comes.
But...for now...
<wait>
You just need to focus, Dr. Stiles.
I know you can do this.
<wait>
Think of it as a trial...
<wait>
...The final test before you can call
yourself a doctor and really mean it.
<wait>

@MSG_EVT404A_016
<bup 0 2 5>
Dr. Kasal...
<wait>

@MSG_EVT404A_017
<bup 0 10 7>
Well, Doctor...
Can I be cured?
<wait>

@MSG_EVT404A_018
<bup 0 2 5>
Yes, I anticipate a full recovery
after the procedure.
<wait>

@MSG_EVT404A_019
<bup 0 10 7>
Who's going to be operating?
<wait>

@MSG_EVT404A_020
<bup 0 2 5>
I... I will.
<wait>

@MSG_EVT404A_021
<bup 0 10 7>
You don't sound very confident.
<wait>

@MSG_EVT404A_022
<bup 0 2 3>
...You can trust me.
You're in good hands, Mr. Kasal.
<wait>

@MSG_EVT404A_023
<bup 0 10 7>
...That's the spirit, Derek.
Remember, I believe in you.
<wait>

@MSG_EVT404A_024
<bup 0 2 5>
Yes sir.
<wait>
<bup_cls>

@MSG_EVT404B_001
<bup 0 15 1>
...Is he all right?
<wait>

@MSG_EVT404B_002
<bup 0 2 1>
I removed all traces of GUILT tissue...
<wait>
Now we just have to wait, and hope
that serum takes care of the toxin.
<wait>

@MSG_EVT404B_003
<bup 0 8 1>
I can try telling Dr. Kasal he needs rest,
but...
<wait>
Knowing him, he'll want to return
to Hope Hospital immediately.
<wait>

@MSG_EVT404B_004
<bup 0 15 1>
He needs to recover first!
<wait>

@MSG_EVT404B_005
<bup 0 2 1>
GUILT is just about the only thing
that could bring Dr. Kasal down.
<wait>
I'm sure he'll be back to normal in no time.
<wait>

@MSG_EVT404B_006
<bup 0 8 1>
...Dr. Myers.
<wait>
It looks like they're a little understaffed.
Maybe you could help with Dr. Kasal for a bit?
<wait>

@MSG_EVT404B_007
<bup 0 15 1>
Me...?
<wait>
Y-Yes, of course.
...I'd be glad to.
<wait>

@MSG_EVT404B_008
<bup 0 8 2>
Come with me, then.
<wait>
<bup_cls>
