
@MSG_EVT401A_001
<bup 0 13 1>
...Good, you're back.
<wait>

@MSG_EVT401A_002
<bup 0 2 5>
What's Dr. Kasal's condition!?
<wait>

@MSG_EVT401A_003
<bup 0 13 1>
Stable...for now. He's gotten a lot
weaker, though.
<wait>
I don't think he has the strength to survive
an operation...
<wait>
...Well, go see for yourself.
<wait>
<bup_cls>

@MSG_EVT401A_004
- Surgical Ward, Room 202 -
<wait>

@MSG_EVT401A_005
<bup 0 10 7>
...Good to see you, Derek.
<wait>

@MSG_EVT401A_006
<bup 0 18 1>
Dr. Kasal! You shouldn't get up...!
<wait>

@MSG_EVT401A_007
<bup 0 2 5>
Don't strain yourself, sir...
<wait>

@MSG_EVT401A_008
<bup 0 10 7>
...I should've been suspicious when I couldn't
diagnose my own condition...
<wait>
It spread so fast...
I didn't think...it was GUILT.
<wait>

@MSG_EVT401A_009
<bup 0 8 5>
Have they identified the strain?
<wait>

@MSG_EVT401A_010
<bup 0 10 7>
...I heard Sidney say it was an unidentified
type, so...be careful.
<wait>
<bup_cls>

@MSG_EVT401A_011
<bup 0 13 1>
Greg, we've received detailed
information on this GUILT.
<wait>

@MSG_EVT401A_012
<bup 0 10 7>
What...? From where?
<wait>

@MSG_EVT401A_013
<bup 0 13 1>
These two just got back from Africa...and
an old Delphi research facility.
<wait>

@MSG_EVT401A_014
<bup 0 8 5>
The file Reuben gave us...!
<wait>

@MSG_EVT401A_015
<bup 0 13 1>
We're analyzing the data. We think it might
help us devise a treatment.
<wait>
...Don't give up, Greg.
<wait>

@MSG_EVT401A_016
<bup 0 10 7>
I believe in you...and in Caduceus...
<wait>
That's why I wanted Derek to join you.
<wait>

@MSG_EVT401A_017
<bup 0 2 5>
...Dr. Kasal.
<wait>

@MSG_EVT401A_018
<bup 0 10 7>
Keep working hard, Derek.
<wait>
<bup_cls>

@MSG_EVT401A_019
<bup 0 13 1>
Results arrived from the lab.
They've settled on a theoretical cure.
<wait>
Victor's report says they can create
a serum to eliminate the GUILT.
<wait>

@MSG_EVT401A_020
<bup 0 8 5>
...There's hope, then?
<wait>

@MSG_EVT401A_021
<bup 0 13 1>
It's...possible. But, we don't have enough
antigen samples to finish the serum.
<wait>

@MSG_EVT401A_022
<bup 0 2 5>
Antigen samples...?
<wait>

@MSG_EVT401A_023
<bup 0 13 1>
While you were in Africa, there was
a highly toxic GUILT outbreak.
<wait>
My brother was infected while treating one
of the victims...
<wait>
In theory, we can extract samples from
the untreated GUILT patients.
<wait>
As long as their infections haven't progressed
to full term, we can just remove the GUILT.
<wait>
We've compiled a list of patients with
symptoms matching Greg's.
<wait>
Derek... I need you to operate on them
in order to obtain the necessary samples.
<wait>

@MSG_EVT401A_024
<bup 0 2 5>
So I'll be traveling to hospitals where
the victims are being observed?
<wait>

@MSG_EVT401A_025
<bup 0 13 1>
Yes, exactly.
...Good luck.
<wait>
Once we have enough antigen,
we can engineer the serum.
<wait>

@MSG_EVT401A_026
<bup 0 2 5>
I understand, sir.
<wait>

@MSG_EVT401A_027
<bup 0 13 1>
Derek...
<wait>

@MSG_EVT401A_028
<bup 0 2 5>
...?
<wait>

@MSG_EVT401A_029
<bup 0 13 10>
Greg is my brother.
...Please remember that.
<wait>

@MSG_EVT401A_030
<bup 0 2 5>
Of course, Dr. Kasal.
Let's go, Angie!
<wait>
<bup_cls>
