
@MSG_EVT407A_001
<bup 0 16 1>
...Let's start with the good news.
The Pempti strain has a weakness.
<wait>
There's a section of its DNA that can be
easily altered. By injecting a nanomachine,
<wait>
we can basically reprogram it--convince
it to self-destruct.
<wait>
But, there's a part of the nanomachine
I just can't nail down...
<wait>
One of the programming strings is... complex.
<wait>
Therefore, I need your help.
<wait>

@MSG_EVT407A_002
<bup 0 2 5>
What do I need to do?
<wait>
<bup_cls>

@MSG_EVT407B_001
<bup 0 16 1>
Hmm... I see... That kind of makes sense.
...In a way.
<wait>
In that case, I just need to think backwards!
<wait>
Thank you, Dr. Stiles.
<wait>
I think I can use a simple program
that shouldn't take long to code.
<wait>
(Dammit! I guess a group of idiots
really could outwit a genius...)
<wait>
Let's get started right away!
No sleep tonight, guys!
<wait>
<bup_cls>

@MSG_EVT407B_002
"Ahhh, man..."
<wait>
