
@MSG_EVT403A_001
<bup 0 15 3>
Chief... How is he?
<wait>

@MSG_EVT403A_002
<bup 0 13 1>
We're using the samples Derek collected
to create a serum.
<wait>

@MSG_EVT403A_003
<bup 0 15 3>
But, will it be done in time!?
<wait>

@MSG_EVT403A_004
<bup 0 13 1>
I don't know... We just have to put our faith
in Victor.
<wait>

@MSG_EVT403A_005
<bup 0 15 3>
...I can help! There has to be something
I can do!
<wait>

@MSG_EVT403A_006
<bup 0 2 5>
Try to stay calm, Dr. Myers...
I'm sure Victor can handle it.
<wait>

@MSG_EVT403A_007
<bup 0 15 3>
Stay calm? How the hell can you say that
when your mentor is dying in there!?
<wait>
If... If you hadn't been gone--!
<wait>

@MSG_EVT403A_008
<bup 0 13 1>
Stop it, Cybil.
This isn't his fault.
<wait>

@MSG_EVT403A_009
<bup 0 15 4>
......I-I'm sorry.
<wait>
......
<wait>
I'm very sorry.
...I need to go lie down.
<wait>
<bup_cls>

@MSG_EVT403A_010
<bup 0 17 5>
...Wow. I've never seen Dr. Myers freak out
like that.
<wait>

@MSG_EVT403A_011
<bup 0 13 1>
Cybil and my brother have some history...
I can understand why she's so emotional.
<wait>
Don't hold it against her, Derek.
<wait>

@MSG_EVT403A_012
<bup 0 2 5>
Of course not.
<wait>
<bup_cls>

@MSG_EVT403A_013
<bup 0 2 4>
......
<wait>
(This must be how patients' families feel.)
<wait>
(...It's hard entrusting the life of a loved-one
into someone else's hands.)
<wait>

@MSG_EVT403A_014
<bup 0 15 4>
Who knew waiting could be this painful...?
<wait>

@MSG_EVT403A_015
<bup 0 13 10>
......
<wait>
<bup_cls>

@MSG_EVT403A_016
<bup 0 16 1>
Excuse me.
<wait>
It's ready, Chief.
<wait>
We're administering the serum via IV.
He should start to recover soon.
<wait>

@MSG_EVT403A_017
<bup 0 13 1>
I see... That's good news.
<wait>

@MSG_EVT403A_018
<bup 0 16 1>
But, the GUILT's still inside him.
You plan on removing it, right?
<wait>

@MSG_EVT403A_019
<bup 0 13 1>
...We should do it right away.
<wait>
Dr. Clarks, can you operate?
I'd like Derek to assist you, as well.
<wait>

@MSG_EVT403A_020
<bup 0 14 1>
I'll do my best, sir.
<wait>

@MSG_EVT403A_021
<bup 0 2 5>
...Understood.
<wait>
<bup_cls>
