
@MSG_EVT410A_001
<bup 0 13 1>
Listen up, everyone...
<wait>
Secretary Anderson is getting weaker
every day. It seems hopeless.
<wait>
But, I don't think he'll die. I've never seen
anyone fight so hard to stay alive...
<wait>
So, all we can really do is destroy the GUILT
that's killing him from the inside.
<wait>
Don't think about anything but the operation
at hand. This is serious.
<wait>
Victor, please explain our plan of attack.
<wait>

@MSG_EVT410A_002
<bup 0 16 1>
Okay, pay attention...
<wait>
<bup_cls>

@MSG_EVT410B_001
<bup 0 13 1>
Good work, everyone.
<wait>

@MSG_EVT410B_002
<bup 0 16 1>
Secretary Anderson was doing all the work.
I'm surprised he held out for so long.
<wait>

@MSG_EVT410B_003
<bup 0 13 1>
Victor!
<wait>

@MSG_EVT410B_004
<bup 0 16 1>
...What?
I was just being honest.
<wait>

@MSG_EVT410B_005
<bup 0 13 1>
Well...we all fought hard, Secretary Anderson
included.
<wait>

@MSG_EVT410B_006
<bup 0 16 1>
I'm taking off...
My work here is done.
<wait>
<bup_cls>

@MSG_EVT410B_007
<bup 0 13 10>
......
<wait>
<bup_cls>

@MSG_EVT410B_008
<bup 0 8 5>
How's he doing...?
<wait>

@MSG_EVT410B_009
<bup 0 9 1>
I don't know.
<wait>
It's a miracle in itself that his body
could withstand three operations.
<wait>
Apparently, the Pempti strain focuses its
attack on the nervous system first.
<wait>
Can you imagine what kind of pain
Richard must have been in?
<wait>

@MSG_EVT410B_010
<bup 0 8 5>
......
<wait>

@MSG_EVT410B_011
<bup 0 9 1>
But, pain killers would have interfered
with our test results...
<wait>
...so he hid the pain.
He fought against GUILT all by himself.
<wait>

@MSG_EVT410B_012
<bup 0 8 5>
Is he going to wake up...?
<wait>

@MSG_EVT410B_013
<bup 0 9 1>
God only knows...
The only thing we can do now is pray.
<wait>
<bup_cls>
