
@MSG_EVT402A_001
<bup 0 2 5>
I think it's around here...
<wait>

@MSG_EVT402A_002
<bup 0 8 5>
I just contacted the hospital. They'll have
the patient ready for us when we arrive.
<wait>

@MSG_EVT402A_003
<bup 0 2 5>
This vehicle is specially designed
as a sterile environment.
<wait>
We can't risk a secondary infection,
so we'll have to operate in here.
<wait>
This strain may be spread by physical
contact. Wear your protective gear.
<wait>
<bup_cls>

@MSG_EVT402B_001
<bup 0 2 5>
Did I...do it correctly?
<wait>

@MSG_EVT402B_002
<bup 0 8 5>
I think so...
<wait>
According to what Kasal told us,
we need three types of antigen.
<wait>
There are P, V, and H-types; he wants
one sample of each.
<wait>
I'll send a composition of this sample back
to Caduceus.
<wait>

@MSG_EVT402B_003
<bup 0 2 5>
Hm... I wonder what type it is.
<wait>
<bup_cls>

@MSG_EVT402B_004
<bup 0 8 5>
There's our answer! It looks like
this is the V-type antigen.
<wait>
Let's move on to the next patient.
We still need the other two types!
<wait>

@MSG_EVT402B_005
<bup 0 2 5>
Yeah--let's go!
<wait>
<bup_cls>
