
@MSG_EVT408A_001
<bup 0 8 5>
Let's begin the briefing on
the Pempti treatment.
<wait>

@MSG_EVT408A_002
<bup 0 16 1>
I have a few theories about this Pempti thing,
and I've prepared appropriate countermeasures.
<wait>
I'll explain those now.
<wait>
<bup_cls>

@MSG_EVT408B_001
<bup 0 16 3>
...Gah! It has a contingency plan!
<wait>
How could I be so stupid? They have
an obvious flaw in their DNA...
<wait>
...so of COURSE they have a system
to reinforce it! Dammit!
<wait>

@MSG_EVT408B_004
Stupid... I can't believe I made such
an idiotic mistake!
<wait>

@MSG_EVT408B_002
<bup 0 13 1>
When are you going to grow up?
We all make mistakes, Victor.
<wait>
At least Derek was able to retrieve
a sample of the GUILT for us.
<wait>
Couldn't you use that to create a
more effective treatment?
<wait>

@MSG_EVT408B_003
<bup 0 16 3>
Of course I can!
<wait>
Grrr... That virus is gonna pay
for making a fool out of me!
<wait>
<bup_cls>
