
@MSG_EVT411A_001
Three days later...
<wait>

@MSG_EVT411A_002
<bup 0 8 5>
Chief! Secretary Anderson has
regained consciousness!
<wait>

@MSG_EVT411A_003
<bup 0 13 1>
What!?
...I'll be right there!
<wait>
<bup_cls>

@MSG_EVT411A_004
<bup 0 12 2>
It feels like I've been asleep
...for a very long time.
<wait>

@MSG_EVT411A_005
<bup 0 13 1>
...We were worried, Mr. Secretary.
<wait>
There was a chance you would never
regain consciousness...
<wait>

@MSG_EVT411A_006
<bup 0 12 2>
I'm sorry that I caused you all
so much trouble...
<wait>
...Sidney, please do me a favor.
Could you call Robert Hoffman in?
<wait>
...There's one last thing I needed to discuss
with him before he returns to Hope...
<wait>

@MSG_EVT411A_007
<bup 0 8 9>
...Mr. Secretary?
What are you saying...?
<wait>

@MSG_EVT411A_008
<bup 0 13 1>
Angie, contact Dr. Hoffman.
Also, please assemble the GUILT team.
<wait>
<bup_cls>

@MSG_EVT411A_009
<bup 0 8 5>
Chief...what's going on?
<wait>

@MSG_EVT411A_010
<bup 0 13 1>
With your experience and knowledge,
Angie, you should already know.
<wait>
That last operation took quite a toll on
the Secretary's body...
<wait>

@MSG_EVT411A_011
<bup 0 8 4>
But...we found a treatment!
<wait>
It's not fair!
<wait>
<bup_cls>

@MSG_EVT411A_012
<bup 0 9 1>
Richard...
Are you all right?
<wait>

@MSG_EVT411A_013
<bup 0 12 2>
I'd almost forgotten to ask you about
that request of mine...
<wait>

@MSG_EVT411A_014
<bup 0 9 1>
That's right. I remember you mentioning it.
<wait>

@MSG_EVT411A_015
<bup 0 12 2>
I'm...leaving Caduceus in your hands.
<wait>

@MSG_EVT411A_016
<bup 0 9 1>
What are you talking about!?
<wait>

@MSG_EVT411A_017
<bup 0 12 2>
Is that okay with you, Sidney?
<wait>

@MSG_EVT411A_018
<bup 0 13 1>
Dr. Hoffman was a very skilled
surgeon...but--
<wait>

@MSG_EVT411A_019
<bup 0 9 1>
Exactly--that's all in the past. I haven't
performed an operation in years!
<wait>
I couldn't...keep taking responsibility.
<wait>
What good is a useless doctor like
me to Caduceus?
<wait>

@MSG_EVT411A_020
<bup 0 12 2>
Why did you...stop operating...?
<wait>

@MSG_EVT411A_021
<bup 0 9 1>
......
<wait>

@MSG_EVT411A_022
<bup 0 12 2>
You told me that your greatest joy
was being able to help patients...
<wait>
You're the last person I would expect to
turn his back on patients in need...
<wait>

@MSG_EVT411A_023
<bup 0 9 1>
......
<wait>
My hands...
They've grown too heavy.
<wait>
I can heal people. There's no doubt about that;
the Healing Touch let me save patients that
<wait>
nobody else could...
<wait>
...But, it's impossible to save every
single patient.
<wait>
That burden is too great.
...I can't bear it.
<wait>

@MSG_EVT411A_024
<bup 0 12 2>
Still trying to do everything alone...
You haven't changed at all.
<wait>
Can't you see all the doctors and nurses here,
ready to support you?
<wait>
...Doctors like Derek and Greg...
You don't have to fight alone.
<wait>

@MSG_EVT411A_025
<bup 0 9 1>
That may be, but I...
<wait>

@MSG_EVT411A_026
<bup 0 12 2>
Have you forgotten already?
Your patients are fighting, too.
<wait>

@MSG_EVT411A_027
<bup 0 9 1>
......!
<wait>

@MSG_EVT411A_028
<bup 0 12 2>
The patients you operated on asked you to
fight by their side as an ally in that battle.
<wait>
...Even if they ended up as casualties.
<wait>
Nobody understands that more than
I do, now...
<wait>
Some people may be disappointed that you
couldn't save their loved ones...
<wait>
But, nobody is pleased that you stopped
trying.
<wait>

@MSG_EVT411A_029
<bup 0 9 1>
Richard...
<wait>

@MSG_EVT411A_030
<bup 0 12 2>
I remember something you told me back
in our college days...
<wait>
You said that people should never have to hear
that their condition is "incurable."
<wait>
...There are doctors here, like Derek Stiles,
who feel the same way.
<wait>
But, perhaps you have changed.
<wait>

@MSG_EVT411A_031
<bup 0 9 1>
I...
<wait>

@MSG_EVT411A_032
<bup 0 12 2>
Tell me, then...
<wait>
If that isn't what you believe anymore,
I understand...
<wait>
But... if you still want to save the unsaveable...
<wait>
I want you to...lead Caduceus in my place...
<wait>
Treat the injured, and save the weak.
<wait>

@MSG_EVT411A_033
<bup 0 9 4>
Richard...!
<wait>

@MSG_EVT411A_034
<bup 0 12 2>
Caduceus is a group of people...
<wait>
who refuse to accept that some diseases
cannot be cured.
<wait>

@MSG_EVT411A_035
<bup 0 9 4>
Stop it!
<wait>
We should discuss this after you've
recovered and left the hospital.
<wait>

@MSG_EVT411A_036
<bup 0 12 2>
I...won't be leaving.
My place is here...with Caduceus.
<wait>
I hope you'll stay, as well...
<wait>
...even if I'm...sleeping...
*cough*
<wait>
I will... still...
<wait>

@MSG_EVT411A_040
...Ah...
<wait>
...The sunset is beautiful here...
<wait>
<bup_cls>

@MSG_EVT411A_037
<bup 0 9 4>
...I never forgot what I told you...
<wait>
I remember everything, and I still
believe what I said...
<wait>
Nothing's changed.
<wait>
...What have I been doing all these years?
<wait>

@MSG_EVT411A_038
<bup 0 12 2>
I'm glad to hear it.
<wait>
I knew you hadn't changed, Robert...
<wait>
That's why you...recommended Derek.
<wait>
...You knew that he...
could help Caduceus...
<wait>
......
<wait>
Robert...
<wait>
...Please...
<wait>
take care... of Caduceus...
<wait>
<bup_cls>
.........
<wait>

@MSG_EVT411A_039
<bup 0 9 4>
......
<wait>
My friend...
<wait>
I promise... I'll work hard to bring
our dream to life.
<wait>
<bup 0 9 5>
...Count on it.
<wait>
<bup_cls>
