
@MSG_EVT405A_001
- Angeles Bay, City Hall -
<wait>

@MSG_EVT405A_002
<bup 0 12 1>
...And that's why a substantial medical grant
would...*ahem*
<wait>
<bup 0 12 10>
...everyone's... Ugh...
<wait>
<bup_cls>

@MSG_EVT405A_003
"Mr. Secretary, what's wrong?"
<wait>

@MSG_EVT405A_004
<bup 0 12 10>
Ugh... It's my...
My chest...
<wait>
Ugh...
<wait>
<bup_cls>

@MSG_EVT405A_005
"Mr. Secretary!?"
<wait>
"We need help here!
Somebody call an ambulance!"
<wait>

@MSG_EVT405A_006
<bup 0 13 1>
Hmm...
<wait>

@MSG_EVT405A_014
"...But who will take record of
the sins of our modern age?"
<wait>
Is this some kind of prank?
<wait>
Wait... Could this be a--?
<wait>
<bup_cls>

@MSG_EVT405A_007
<bup 0 8 3>
Chief!
<wait>

@MSG_EVT405A_008
<bup 0 13 1>
What is it?
<wait>

@MSG_EVT405A_009
<bup 0 8 3>
It's Richard Anderson...!
<wait>

@MSG_EVT405A_010
<bup 0 13 1>
Then, this...
<wait>

@MSG_EVT405A_015
"Pempti--Thursday"
<wait>
"As each death is sacrificed, man
furnishes his dwelling in hell."
<wait>
"...But who will take record of
the sins of our modern age?"
<wait>
D-Does this mean...
<wait>
...What is the Secretary's condition!?
<wait>

@MSG_EVT405A_011
<bup 0 8 5>
We haven't gotten test results back yet, but...
It's most likely GUILT.
<wait>

@MSG_EVT405A_012
<bup 0 13 10>
How could this happen...? How did they get
close enough to infect Secretary Anderson!?
<wait>
<bup 0 13 1>
We need to formulate a plan with Victor.
Call in our entire staff.
<wait>
I hate interrupting his day off,
but we need Derek here as well.
<wait>

@MSG_EVT405A_013
<bup 0 8 5>
Yes sir!
<wait>
<bup_cls>
