
@MSG_EVT406A_001
<bup 0 2 5>
I came as soon as I heard...
What's the Secretary's condition!?
<wait>

@MSG_EVT406A_002
<bup 0 13 1>
...It's another new strain of GUILT.
<wait>
We've tried a number of treatments,
but nothing works.
<wait>
Dr. Clarks has been with Anderson
since he arrived.
<wait>
You'll be taking his place.
<wait>

@MSG_EVT406A_003
<bup 0 2 5>
I understand.
<wait>

@MSG_EVT406A_004
<bup 0 13 1>
Victor, we need instructions.
<wait>

@MSG_EVT406A_005
<bup 0 16 1>
Okay... We'll be working together
on this one, Stiles.
<wait>
<bup_cls>

@MSG_EVT406A_006
<bup 0 12 3>
I still can't believe they got to me, too...
<wait>
I should have been more careful...
I'm sorry about all this.
<wait>

@MSG_EVT406A_007
<bup 0 13 1>
Don't strain yourself, Mr. Secretary.
<wait>

@MSG_EVT406A_008
<bup 0 12 3>
What are my chances, Victor?
<wait>

@MSG_EVT406A_009
<bup 0 16 1>
......
<wait>

@MSG_EVT406A_010
<bup 0 12 3>
Tell me the truth. ...I can take it.
<wait>

@MSG_EVT406A_011
<bup 0 16 1>
I'd say around 25%, but even that's being
generous.
<wait>

@MSG_EVT406A_012
<bup 0 13 1>
Victor!
<wait>

@MSG_EVT406A_013
<bup 0 12 3>
It's alright, Sidney. I want to know all
the facts about my condition.
<wait>
...Otherwise, how can I make informed
decisions?
<wait>
No matter what condition I'm in, I'm still
Secretary of Health and *cough*
<wait>
...Victor, will you be able to figure out
some way to treat this?
<wait>

@MSG_EVT406A_014
<bup 0 16 1>
I can't make any guarantees, but I'm trying.
<wait>
After all, you're the first victim
of this particular strain.
<wait>

@MSG_EVT406A_015
<bup 0 12 3>
I see... So I'm the first one.
<wait>
...Then, my treatment is even more crucial.
<wait>
Sidney, use me as a guinea pig.
Find a way to stop this GUILT!
<wait>
I give Caduceus full discretion
over my treatment.
<wait>

@MSG_EVT406A_016
<bup 0 13 10>
But, Richard, that's--!
<wait>

@MSG_EVT406A_017
<bup 0 16 1>
...Are you sure? I can't promise any of
the treatments will actually work.
<wait>

@MSG_EVT406A_018
<bup 0 12 3>
Yes, I understand.
<wait>
Worst case, you can use my results to find
a cure for others... Can you do that?
<wait>

@MSG_EVT406A_019
<bup 0 16 1>
......
<wait>

@MSG_EVT406A_020
<bup 0 13 10>
......
<wait>

@MSG_EVT406A_021
<bup 0 16 1>
...I accept your challenge, Mr. Secretary.
<wait>
I've decided that I will save you...
But, it might sting a little.
<wait>

@MSG_EVT406A_022
<bup 0 12 3>
Heh...
Do what you must.
<wait>

@MSG_EVT406A_023
<bup 0 16 1>
...As long as you're prepared for the worst,
then I'm going to find a cure.
<wait>
I'm too smart not to!
<wait>
<bup_cls>

@MSG_EVT406B_001
<bup 0 13 1>
Now, all we can do is wait for his analysis
to come in...
<wait>
We're depending on you, Victor...
<wait>
<bup_cls>
