
@MSG_EVT409A_001
<bup 0 12 2>
...It's good to see you, Robert,
but shouldn't you be back at Hope?
<wait>

@MSG_EVT409A_002
<bup 0 9 1>
Actually, I've found that, as Director,
I have a little too much time on my hands.
<wait>

@MSG_EVT409A_003
<bup 0 12 2>
I'd think a doctor of your ability
wouldn't have time to spare...
<wait>
...Oh, are you here to visit your
favorite student?
<wait>
<bup_cls>

@MSG_EVT409A_004
<bup 0 2 1>
How are you feeling, Secretary Anders--!?
<wait>
Dr. Hoffman!
When did you get here?
<wait>

@MSG_EVT409A_005
<bup 0 9 1>
Derek wasn't my student, Richard.
I didn't teach him anything.
<wait>
...I've known the Secretary for
a long time, and came to see him.
<wait>

@MSG_EVT409A_006
<bup 0 12 2>
I'm sorry that our visit had to be under
such unfortunate circumstances.
<wait>

@MSG_EVT409A_007
<bup 0 9 1>
It isn't your fault--this is no ordinary disease.
<wait>

@MSG_EVT409A_008
<bup 0 18 1>
I need to see your right hand, Mr. Secretary...
<wait>

@MSG_EVT409A_009
<bup 0 9 1>
Sorry, am I in the way?
<wait>

@MSG_EVT409A_010
<bup 0 18 1>
Oh, it's fine. Don't worry.
<wait>

@MSG_EVT409A_011
<bup 0 9 1>
Pretend I'm not here. I want you
to be able to do your job.
<wait>
Richard, I'll be honest...
<wait>
You're not going to be happy, but I took
a look at your charts.
<wait>
I'm going to be taking part in the briefing
as well. Is that all right?
<wait>

@MSG_EVT409A_012
<bup 0 12 2>
So you've started practicing again?
<wait>

@MSG_EVT409A_013
<bup 0 9 1>
Don't jump to conclusions--I'm only acting
as an advisor, and only until you're discharged.
<wait>
I hope you can forgive my selfishness...
<wait>
Besides, Caduceus owes me, after taking
one of Hope's best surgeons.
<wait>

@MSG_EVT409A_014
<bup 0 12 2>
Well... I had a request for you, as well...
<wait>
Even if I said no, it wouldn't stop you.
Do what you think is best.
<wait>

@MSG_EVT409A_015
<bup 0 9 1>
...Okay.
<wait>
Is Director Kasal here?
<wait>

@MSG_EVT409A_016
<bup 0 18 1>
He should be in his office...
<wait>

@MSG_EVT409A_017
<bup 0 9 1>
I'll go speak with him, then.
Get some rest, Richard.
<wait>
<bup_cls>

@MSG_EVT409A_018
<bup 0 16 1>
Hey, Derek. I need your help again, okay?
<wait>

@MSG_EVT409A_019
<bup 0 2 1>
Is this another puzzle?
I hate those stupid things...
<wait>

@MSG_EVT409A_020
<bup 0 17 1>
Yeah, he might look smart, but Derek
used to copy off my tests--
<wait>

@MSG_EVT409A_021
<bup 0 2 3>
That was a long time ago!
<wait>

@MSG_EVT409A_022
<bup 0 16 1>
Seriously, it'll only take a few minutes.
<wait>

@MSG_EVT409A_023
<bup 0 2 1>
...Whatever. But, I still don't understand
how these things make any difference.
<wait>
<bup_cls>

@MSG_EVT409B_001
<bup 0 16 1>
Aha! Good job...
This should do nicely.
<wait>

@MSG_EVT409B_002
<bup 0 2 1>
(Wow, that was almost a compliment.)
<wait>

@MSG_EVT409B_003
<bup 0 16 1>
Overall, you only contributed about 1%...
But still, thanks a lot.
<wait>

@MSG_EVT409B_004
<bup 0 2 4>
*sigh*...
<wait>

@MSG_EVT409B_005
<bup 0 16 1>
I had all of Caduceus help out this time.
<wait>
That gave me more than enough data.
I should be finished in no time.
<wait>

@MSG_EVT409B_006
<bup 0 17 5>
...So can you really do it?
<wait>

@MSG_EVT409B_007
<bup 0 16 1>
What are you, stupid?
That's the reason I'm here.
<wait>
<bup_cls>

@MSG_EVT409B_008
<bup 0 8 5>
...How are you feeling, sir?
<wait>

@MSG_EVT409B_009
<bup 0 12 3>
When I was younger, I was in much
better shape. I never got sick...
<wait>
Now I understand...
Having a disease is so painful...
<wait>
If Delphi is capable of creating something
like this...they need to be stopped at any cost.
<wait>

@MSG_EVT409B_010
<bup 0 8 5>
Of course, sir.
<wait>

@MSG_EVT409B_011
<bup 0 12 2>
But...I'm glad.
<wait>

@MSG_EVT409B_012
<bup 0 8 5>
Huh?
<wait>

@MSG_EVT409B_013
<bup 0 12 2>
I don't know how to operate on patients
or how to research treatments.
<wait>
So, if the only way I can help fight GUILT
is to be your test patient...then so be it.
<wait>
<bup 0 12 3>
I'll gladly fulfill my obligation to Caduceus.
<wait>
Don't worry... I won't give up until
you find some kind of treatment...
<wait>
<bup_cls>
