
@MSG_EVT508A_001
"We've just received some breaking news...!"
<wait>
"Local police have cordoned off a research
facility owned by Eidoth Pharmaceuticals."
<wait>
"This investigation may be linked to recent
bio-terrorist activities."
<wait>
"Investigators are now entering the building,
and we'll return with more details as soon
<wait>
as they become available!
Stay tuned to channel--"
<wait>

#北崎威一郎

@MSG_EVT508A_002
<bup 0 9 5>
...So it begins. I wish we could have sent
more than one doctor, but we have patients
<wait>
here that still need help...
<wait>

#沓掛宗二

@MSG_EVT508A_003
<bup 0 13 1>
Good luck, Derek.
<wait>
<bup_cls>

##

@MSG_EVT508A_004
- Eidoth Pharmaceutical Research -
<wait>

@MSG_EVT508A_005
"We have a biohazard here, guys."
<wait>
"If you don't have protective gear, you'll need
to get the hell out of this area!"
<wait>

#月森孝介

@MSG_EVT508A_006
<bup 0 2 5>
I can't believe this...
<wait>
<bup_cls>

#デルフ研究員

@MSG_EVT508A_007
<bup 0 24 7>
*gasp*... *gasp*...
<wait>

#利根川アンジュ

@MSG_EVT508A_008
<bup 0 8 5>
That researcher...
He's infected with GUILT!
<wait>

#月森孝介

@MSG_EVT508A_009
<bup 0 2 5>
Get the anesthesia ready...
We'll need to operate immediately!
<wait>

#利根川アンジュ

@MSG_EVT508A_010
<bup 0 8 5>
Yes, Doctor!
<wait>

#月森孝介

@MSG_EVT508A_011
<bup 0 2 5>
I'm - a - doctor... Do you understand?
I'm - here - to - help.
<wait>

#デルフ研究員

@MSG_EVT508A_012
<bup 0 24 7>
Forget about me... I'm already dead.
<wait>
Those bastards...they... betrayed us!
<wait>
But, th-the...professor...
<wait>

#月森孝介

@MSG_EVT508A_013
<bup 0 2 5>
Calm down.
Try to conserve your strength!
<wait>

#デルフ研究員

@MSG_EVT508A_014
<bup 0 24 7>
Help Professor Blackwell...
<wait>
He...doesn't deserve to die...like th--!
<wait>

#利根川アンジュ

@MSG_EVT508A_015
<bup 0 8 5>
His vitals are dropping fast!
What should we do?
<wait>

#月森孝介

@MSG_EVT508A_016
<bup 0 2 5>
If we don't operate right now, he's going to die.
<wait>
I'm going to administer painkillers.
...Hang in there!
<wait>

#デルフ研究員

@MSG_EVT508A_017
<bup 0 24 7>
No... Save the professor...!
<wait>

#月森孝介

@MSG_EVT508A_018
<bup 0 2 5>
...Don't worry.
We'll take care of him.
<wait>

#デルフ研究員

@MSG_EVT508A_019
<bup 0 24 7>
*gasp*...
<wait>
<bup_cls>

#月森孝介

@MSG_EVT508A_020
<bup 0 2 5>
The anesthesia is working--get a table ready!
<wait>

#利根川アンジュ

@MSG_EVT508A_021
<bup 0 8 5>
Right away!
<wait>
<bup_cls>

#利根川アンジュ

@MSG_EVT508B_001
<bup 0 8 5>
The police are moving him to Caduceus.
<wait>

#月森孝介

@MSG_EVT508B_002
<bup 0 2 5>
Good.
<wait>
......
<wait>
He kept asking us to save Professor
Blackwell...
<wait>

#利根川アンジュ

@MSG_EVT508B_003
<bup 0 8 5>
...Then, my father really is here.
<wait>

#月森孝介

@MSG_EVT508B_004
<bup 0 2 5>
He must be further inside.
Let's go, Angie!
<wait>

#利根川アンジュ

@MSG_EVT508B_005
<bup 0 8 5>
...Okay.
<wait>
<bup_cls>
