
#利根川アンジュ

@MSG_EVT504A_001
<bup 0 8 5>
The patient is being transported
from a nearby hospital.
<wait>
<bup_cls>

#宝生卓而

@MSG_EVT504A_002
<bup 0 14 1>
The Tetarti case is here... Derek's operating?
That's a relief...
<wait>
This strain is too contagious to treat
in a normal operating room.
<wait>
I'm moving on to the next hospital.
Good luck, you two!
<wait>
<bup_cls>

#北崎威一郎

@MSG_EVT504B_001
<bup 0 9 5>
...How widespread should we expect
this outbreak to be?
<wait>

#沓掛宗二

@MSG_EVT504B_002
<bup 0 13 1>
We're receiving updated reports from
Caduceus International.
<wait>
...They've confirmed GUILT victims in
at least four California cities...
<wait>

#北崎威一郎

@MSG_EVT504B_003
<bup 0 9 5>
How did you respond?
<wait>

#沓掛宗二

@MSG_EVT504B_004
<bup 0 13 1>
I've sent medication and treatment
instructions to hospitals in those locations.
<wait>
Hopefully the local doctors can
take it from there.
<wait>
<bup_cls>

@MSG_EVT504B_040
<bup 0 13 1>
...A phone call?
<wait>

@MSG_EVT504B_041
Hello, this is Director Kasal.
<wait>
<bup_cls>

##

@MSG_EVT504B_005
Secretary of Health: "Sidney, we're
concerned about some of the decisions
<wait>
you've made today."
<wait>

#沓掛宗二

@MSG_EVT504B_006
<bup 0 13 1>
...We're in high alert, sir. I would ask that
you please make this brief.
<wait>
<bup_cls>

##

@MSG_EVT504B_007
"I certainly appreciate your circumstances,
but I'm calling in regard to the medication
<wait>
you've issued to a number of hospitals."
<wait>
"I'm afraid you're going to have to
abort those shipments."
<wait>

#沓掛宗二

@MSG_EVT504B_008
<bup 0 13 1>
...I beg your pardon, sir?
<wait>
<bup_cls>

##

@MSG_EVT504B_009
"You don't have the proper clearance to issue
those treatments to public facilities."
<wait>
"Most of them haven't even started
the FDA approval process."
<wait>
"If those drugs reach the public sector,
the pharmeceutical industry won't be happy..."
<wait>
"If you insist on using those treatments,
you're going to have to administer them
<wait>
yourself, at Caduceus."
<wait>

#沓掛宗二

@MSG_EVT504B_010
<bup 0 13 10>
What the hell are you talking about!?
You've seen what GUILT does!
<wait>
The patients would die before they even
got here!
<wait>
We're cutting things too close as it is...
I won't listen to this!
<wait>
<bup_cls>

##

@MSG_EVT504B_011
"I heard you were a difficult man, but you
might want to think this through carefully."
<wait>
"You've read the reports. We both know
your funding is in jeopardy..."
<wait>

#沓掛宗二

@MSG_EVT504B_012
<bup 0 13 1>
...I've had enough of this crap.
<wait>
Excuse me... There are important matters
which demand my attention.
<wait>
<bup_cls>

@MSG_EVT504B_042
<bup 0 13 10>
...Those bastards!
<wait>

#北崎威一郎

@MSG_EVT504B_013
<bup 0 9 5>
Hmph... The politicians seem restless.
<wait>
I assume Richard had been holding
them back while he was in office.
<wait>
...Now that he's gone, there's nothing
standing in their way.
<wait>

#沓掛宗二

@MSG_EVT504B_014
<bup 0 13 10>
They don't even understand what
Caduceus stands for...
<wait>
Our entire purpose is to do what other
medical organizations can't!
<wait>
...I need to speak to Victor.
<wait>
<bup_cls>

#新垣修也

@MSG_EVT504B_015
<bup 0 16 1>
What's going on, Chief?
...Kinda busy here...
<wait>
<bup_cls>

##

@MSG_EVT504B_016
Sidney: "I need you to take care of
something for me right away."
<wait>
"Please send complete copies of our GUILT
reports to all major US hospitals."
<wait>

#新垣修也

@MSG_EVT504B_017
<bup 0 16 1>
...You sure that's okay?
I mean, that's a pretty big deal.
<wait>
<bup_cls>

##

@MSG_EVT504B_018
"Don't worry, Victor. I'll take full responsibility."
<wait>

#新垣修也

@MSG_EVT504B_019
<bup 0 16 1>
Heh... I was actually expecting you to do
something crazy like this...
<wait>
I already have the files ready.
<wait>
<bup_cls>

##

@MSG_EVT504B_020
"Then send them, Victor."
<wait>

#北崎威一郎

@MSG_EVT504B_021
<bup 0 9 5>
You're even more serious than your brother.
<wait>

#沓掛宗二

@MSG_EVT504B_022
<bup 0 13 1>
...I've never lost a fight.
<wait>
<bup_cls>

##

@MSG_EVT504B_023
- Flight to San Francisco -
<wait>

@MSG_EVT504B_024
"Are you all right, sir?
You don't look well."
<wait>

@MSG_EVT504B_025
<bup 0 31 1>
Y-Yeah, I'm fine...
<wait>
<bup_cls>

@MSG_EVT504B_026
"......"
<wait>

@MSG_EVT504B_027
<bup 0 31 1>
I have to deliver this as soon as possible...
<wait>
People's lives are at stake.
<wait>
<bup_cls>

@MSG_EVT504B_028
"Ah... I understand."
<wait>
"I've seen that mark on your bag before,
actually."
<wait>

@MSG_EVT504B_029
<bup 0 31 1>
......?
<wait>
<bup_cls>

@MSG_EVT504B_030
Pilot: "May I have your attention, please."
<wait>
"Our expected time of arrival has changed.
It is no longer 3:25 PM."
<wait>
"Because of a... strong tailwind, we should
be arriving early, at approximately 2:45."
<wait>

@MSG_EVT504B_031
<bup 0 31 1>
Th-Thank you so much...
<wait>
<bup_cls>

@MSG_EVT504B_032
- Community Hospital, San Diego -
<wait>

#古村百恵

@MSG_EVT504B_033
<bup 0 11 1>
Hm...? The technique in this video almost
looks like...
<wait>
*chuckle* ...It's good to know Derek
is still working hard.
<wait>

@MSG_EVT504B_034
<bup 0 30 1>
Mrs. Fulton! The vaccine and serum
just arrived!
<wait>

#古村百恵

@MSG_EVT504B_035
<bup 0 11 1>
Alright, I'll get things ready.
You should change your clothes.
<wait>
We also need to contact any doctors
who are off duty.
<wait>
<bup_cls>

##

@MSG_EVT504B_036
"It's going to be a long day, Nurse Fulton!"
<wait>

#古村百恵

@MSG_EVT504B_037
<bup 0 11 1>
...He's here earlier than usual.
<wait>

##

@MSG_EVT504B_038
<bup 0 30 1>
Yeah... Dr. Jaeger's never here on time.
What's going on?
<wait>
This must really be serious...
<wait>

#古村百恵

@MSG_EVT504B_039
<bup 0 11 1>
*chuckle*
Doctors always come when they're needed.
<wait>
Let's get started, shall we?
I can't let my own pupil show me up!
<wait>
<bup_cls>
