
#佐倉東吾

@MSG_EVT505A_001
<bup 0 17 1>
...So'd we get it under control?
<wait>

#明神さやか

@MSG_EVT505A_002
<bup 0 15 1>
I think so. We managed to contain the GUILT
before it could spread...
<wait>
It's all over the news, though. If Delphi expects
to catch us off guard again, it's going to take
<wait>
a lot more work...
<wait>

#利根川アンジュ

@MSG_EVT505A_003
<bup 0 8 5>
What about Director Kasal?
<wait>

#明神さやか

@MSG_EVT505A_004
<bup 0 15 1>
You mean because he sent that medicine?
I'm sure he'll be fine.
<wait>
He did what had to be done and averted
a major catastrophe.
<wait>
And, I guess someone tipped off the press
about what really happened...
<wait>
They can't fire him now--he's a hero,
politically.
<wait>

#佐倉東吾

@MSG_EVT505A_005
<bup 0 17 1>
I wonder who tipped 'em off...
What do you think, Victor?
<wait>

#新垣修也

@MSG_EVT505A_006
<bup 0 16 1>
...I find it intriguing.
<wait>

#月森孝介

@MSG_EVT505A_007
<bup 0 2 5>
I hear even the Counter Terrorism Unit
is getting involved...
<wait>

#佐倉東吾

@MSG_EVT505A_008
<bup 0 17 5>
S'about time, huh?
<wait>
The President's going to be here next week,
supposedly...
<wait>
...Hope nobody wanted a vacation
any time soon!
<wait>

#伊東優乃

@MSG_EVT505A_009
<bup 0 18 1>
I had to cancel mine...
<wait>
...I could be scuba diving right now...
<wait>

#佐倉東吾

@MSG_EVT505A_010
<bup 0 17 1>
Don't hold back on our account, Leslie.
How do you really feel?
<wait>
<bup_cls>

##

@MSG_EVT505A_011
"Emergency Warning! Unidentified persons
have been seen on the premises."
<wait>
"All staff return to your stations immediately
to await further instruction."
<wait>

#月森孝介

@MSG_EVT505A_012
<bup 0 2 5>
Do you think it's someone from Delphi?
<wait>
<bup_cls>

#沓掛宗二

@MSG_EVT505A_013
<bup 0 13 1>
There were several intruders...
Some already escaped.
<wait>
We've contacted security, but...
<wait>

#佐倉東吾

@MSG_EVT505A_014
<bup 0 17 5>
We can't just let 'em get away!
<wait>
Chief, we should be looking for
these punks ourselves!
<wait>

#明神さやか

@MSG_EVT505A_015
<bup 0 15 1>
...We're defenseless, and we don't even know
whether or not they're armed.
<wait>

#佐倉東吾

@MSG_EVT505A_016
<bup 0 17 5>
Well we don't have any leads on Delphi's
location, do we?
<wait>
...Letting them walk outta here would be like
letting hundreds of people die!
<wait>

#沓掛宗二

@MSG_EVT505A_017
<bup 0 13 1>
Dr. Chase has a point... It's dangerous,
but we need to find them.
<wait>
Those of us who can defend ourselves
should pair-off and start looking.
<wait>

#佐倉東吾

@MSG_EVT505A_018
<bup 0 17 1>
That's what I'm talking about!
<wait>
The ladies should stay back here
where it's safe...
<wait>

#明神さやか

@MSG_EVT505A_019
<bup 0 15 1>
Slow down there, Tarzan--I used to be
a cop, remember?
<wait>

#利根川アンジュ

@MSG_EVT505A_020
<bup 0 8 5>
I have studied Aikido.
<wait>

#月森孝介

@MSG_EVT505A_021
<bup 0 2 5>
...You have!?
<wait>

#利根川アンジュ

@MSG_EVT505A_022
<bup 0 8 5>
What? We live in dangerous times.
...Let's begin the search.
<wait>
<bup_cls>

#月森孝介

@MSG_EVT505A_023
<bup 0 2 5>
......
<wait>

#利根川アンジュ

@MSG_EVT505A_024
<bup 0 8 5>
They don't seem to be hiding anywhere
in this building...
<wait>
All the rooms are locked, and this hall ends
up ahead.
<wait>

#月森孝介

@MSG_EVT505A_025
<bup 0 2 5>
That's a relief...
We should probably head back--
<wait>
<bup_cls>

##

@MSG_EVT505A_026
**CRASH**
<wait>

#明神さやか

@MSG_EVT505A_027
<bup 0 15 3>
Stop right there!
<wait>

#月森孝介

@MSG_EVT505A_028
<bup 0 2 5>
Huh!?
<wait>

#利根川アンジュ

@MSG_EVT505A_029
<bup 0 8 5>
It's one of the Delphi--!
<wait>
<bup_cls>

##

@MSG_EVT505A_030
<bup 0 23 10>
...!
<wait>

#利根川アンジュ

@MSG_EVT505A_031
<bup 0 8 5>
But...how?
<wait>
<bup_cls>

#月森孝介

@MSG_EVT505A_032
<bup 0 2 5>
There's nowhere to run!
<wait>
...What's wrong, Angie?
We almost had him!
<wait>

#利根川アンジュ

@MSG_EVT505A_033
<bup 0 8 9>
...No... It couldn't be...
<wait>
<bup_cls>

#明神さやか

@MSG_EVT505A_034
<bup 0 15 4>
*gasp*...
I think...he got away...!
<wait>

#月森孝介

@MSG_EVT505A_035
<bup 0 2 4>
I'm sorry, I...
<wait>

#明神さやか

@MSG_EVT505A_036
<bup 0 15 1>
Oh well...
<wait>
He had a gun, so it's probably for the best
I didn't catch up with him...
<wait>
Let's head back. We need someone
to examine this evidence.
<wait>

#月森孝介

@MSG_EVT505A_037
<bup 0 2 5>
Evidence?
<wait>

#明神さやか

@MSG_EVT505A_038
<bup 0 15 1>
It was pretty dark, but I tried anyway...
See?
<wait>

#月森孝介

@MSG_EVT505A_039
<bup 0 2 5>
A camera!? ...You managed to take
his picture that fast?
<wait>

#明神さやか

@MSG_EVT505A_040
<bup 0 15 7>
Ugh...
<wait>

#月森孝介

@MSG_EVT505A_041
<bup 0 2 5>
...What's wrong?
<wait>

#明神さやか

@MSG_EVT505A_042
<bup 0 15 7>
Ahhh no... Don't tell me...
<wait>
<bup_cls>

##

@MSG_EVT505A_043
*faint*
<wait>

#月森孝介

@MSG_EVT505A_044
<bup 0 2 3>
Th-This is bad! Quick, someone!
We need help over here!
<wait>
<bup_cls>
