
@MSG_EVT509A_001
- Eidoth Research Facility -
<wait>

#月森孝介

@MSG_EVT509A_002
<bup 0 2 5>
...Professor?
<wait>

#利根川アンジュ

@MSG_EVT509A_003
<bup 0 8 5>
......
<wait>

#天羽恭司

@MSG_EVT509A_004
<bup 0 23 7>
Who...are you...?
<wait>

#月森孝介

@MSG_EVT509A_005
<bup 0 2 5>
I'm a doctor from Caduceus.
...You're going to be okay, sir.
<wait>
We need to operate immediately...
Please don't resist.
<wait>

#天羽恭司

@MSG_EVT509A_006
<bup 0 23 7>
Heh... I think you're confused...
But, no matter... It's too late.
<wait>

#月森孝介

@MSG_EVT509A_007
<bup 0 2 5>
That isn't true. We saved your colleagues,
and we can save you.
<wait>

#天羽恭司

@MSG_EVT509A_008
<bup 0 23 7>
...Yes, I was disappointed by how
quickly you stopped my GUILT...
<wait>
You found ways to treat all six strains...
<wait>
You've definitely proven your surgical ability.
<wait>
But, the GUILT inside me is unlike
anything you've seen thus far...
<wait>
Now that the Savato is completed,
this facility means nothing to them...
<wait>
...So, I'm ending it all... before Delphi can...
<wait>
Go...! A pathetic sinner like me isn't...
...worth saving...
<wait>

#月森孝介

@MSG_EVT509A_009
<bup 0 2 5>
I'm a doctor.
<wait>
Helping people fight off disease is my job.
<wait>
You can worry about your sins after
I save your life.
<wait>

#天羽恭司

@MSG_EVT509A_010
<bup 0 23 7>
None of us are allowed to die...
...It's exactly as he preached.
<wait>
But...that doesn't matter...
...I've made my choice.
<wait>

#利根川アンジュ

@MSG_EVT509A_011
<bup 0 8 5>
Why did you create GUILT!?
<wait>

#天羽恭司

@MSG_EVT509A_012
<bup 0 23 7>
......?
<wait>

#利根川アンジュ

@MSG_EVT509A_013
<bup 0 8 5>
You threw away your reputation, your life...
...even your family!
<wait>
<bup 0 8 4>
...Why, Father!?
<wait>

#天羽恭司

@MSG_EVT509A_014
<bup 0 23 7>
...!
<wait>
Angie... I was afraid that was you.
<wait>
I wanted to die...so you'd never find out...
about this.
<wait>

#利根川アンジュ

@MSG_EVT509A_015
<bup 0 8 4>
Just tell me why!
<wait>

#天羽恭司

@MSG_EVT509A_016
<bup 0 23 7>
Angela Blackwell's father died...
13 years ago.
<wait>
I'm just a ghost...
<wait>
Please...
Let me pass on.
<wait>

#利根川アンジュ

@MSG_EVT509A_017
<bup 0 8 4>
You can't do this!
<wait>

#天羽恭司

@MSG_EVT509A_018
<bup 0 23 7>
...Is this the kind of father you WANT!?
<wait>

#利根川アンジュ

@MSG_EVT509A_019
<bup 0 8 5>
It's my job to help people...
...and I'm proud of that fact.
<wait>
I refuse to watch you die.
<wait>

#天羽恭司

@MSG_EVT509A_020
<bup 0 23 7>
...As you wish...
<wait>
But, you cannot defeat Death.
...It is not of this world.
<wait>

#月森孝介

@MSG_EVT509A_021
<bup 0 2 5>
......
<wait>
Begin the anesthesia.
<wait>

#天羽恭司

@MSG_EVT509A_022
<bup 0 23 7>
...Ugh...
<wait>

#月森孝介

@MSG_EVT509A_023
<bup 0 2 5>
We'll start operating as soon as it
takes effect. Get ready, Angie.
<wait>
<bup_cls>

#利根川アンジュ

@MSG_EVT509B_001
<bup 0 8 4>
......
<wait>
...I didn't cry.
<wait>
Yesterday, you said I was much
stronger than you.
<wait>
...So, I forced myself not to cry.
<wait>
I'm your assistant, Dr. Stiles.
<wait>
And, an assistant has to support her doctor...
<wait>
Thank you for allowing me to see my
father again...
<wait>

#月森孝介

@MSG_EVT509B_002
<bup 0 2 1>
...I'm proud of you, Angie.
<wait>

#利根川アンジュ

@MSG_EVT509B_003
<bup 0 8 4>
Doctor...
<wait>

#月森孝介

@MSG_EVT509B_004
<bup 0 2 1>
We still need to carry him out...
<wait>
Then it's finally over.
<wait>
<bup_cls>
