
#北崎威一郎

@MSG_EVT501A_001
<bup 0 9 5>
My name is Dr. Robert Hoffman, and I'm the
new Executive Director of Caduceus.
<wait>
I'd like to say a few words...
<wait>
The late Richard Anderson was a
truly extraordinary man.
<wait>
Though he was a politician, his true passion
was the medical field.
<wait>
Which, of course, led to the formation
of Caduceus.
<wait>

#沓掛宗二

@MSG_EVT501A_002
<bup 0 13 1>
...Secretary Anderson was a man
of incredible vision.
<wait>

#北崎威一郎

@MSG_EVT501A_003
<bup 0 9 5>
Yes, and without his organization, the world
would be powerless against medical terrorism.
<wait>
We would all be cowering in fear of GUILT.
<wait>
I plan to continue his work, and
fight back against that menace.
<wait>

#月森孝介

@MSG_EVT501A_004
<bup 0 2 5>
......
<wait>

#北崎威一郎

@MSG_EVT501A_005
<bup 0 9 5>
That has always been the mission of
Caduceus, and it will not change.
<wait>
I hope that I have your support in striving
toward the future together.
<wait>

#利根川アンジュ

@MSG_EVT501A_006
<bup 0 8 5>
So, Caduceus will continue in honor
of Secretary Anderson...
<wait>

#宝生卓而

@MSG_EVT501A_007
<bup 0 14 1>
I finished compiling all of our GUILT
treatment data, but...
<wait>

#沓掛宗二

@MSG_EVT501A_008
<bup 0 13 1>
Delphi's actions seem to be more
and more deliberate...
<wait>
...And, we don't have any idea how far
they're willing to go.
<wait>
We'll need to construct full-scale
countermeasure scenarios...
<wait>
<bup_cls>

##

@MSG_EVT501A_009
"Attention all staff."
<wait>
"We've received a number of reports
indicating possible GUILT victims."
<wait>
"There is risk of an outbreak.
All emergency teams must respond!"
<wait>

#佐倉東吾

@MSG_EVT501A_010
<bup 0 17 5>
Well, well... Speak of the devil.
<wait>

#沓掛宗二

@MSG_EVT501A_011
<bup 0 13 10>
Everyone! Gather your supplies,
and get out there immediately!
<wait>

#月森孝介

@MSG_EVT501A_012
<bup 0 2 5>
Yes sir!
<wait>
<bup_cls>

#利根川アンジュ

@MSG_EVT501A_013
<bup 0 8 9>
People have started collapsing...
<wait>

#沓掛宗二

@MSG_EVT501A_014
<bup 0 13 1>
I want three teams! Start treating
the most advanced symptoms first!
<wait>
Dr. Clarks, find out which hospitals have
received GUILT victims...
<wait>
Cooperate with those doctors and
instruct them on proper treatment.
<wait>

#宝生卓而

@MSG_EVT501A_015
<bup 0 14 1>
Understood.
<wait>

#沓掛宗二

@MSG_EVT501A_016
<bup 0 13 1>
Dr. Stiles, Dr. Chase--get ready to operate!
<wait>
Dr. Myers, assign two teams to
handle anesthesia!
<wait>

#月森孝介

@MSG_EVT501A_017
<bup 0 2 5>
Yes sir!
<wait>

#佐倉東吾

@MSG_EVT501A_018
<bup 0 17 5>
Here we go...
<wait>

#明神さやか

@MSG_EVT501A_019
<bup 0 15 1>
Understood, Chief.
<wait>

#北崎威一郎

@MSG_EVT501A_020
<bup 0 9 5>
...How can I help?
<wait>

#月森孝介

@MSG_EVT501A_021
<bup 0 2 5>
Dr. Hoffman!
<wait>

#北崎威一郎

@MSG_EVT501A_022
<bup 0 9 5>
My medical license has been an
ornament for far too long...
<wait>
It's time I made good on the Hippocratic Oath.
<wait>

#沓掛宗二

@MSG_EVT501A_023
<bup 0 13 1>
If you're sure you can operate,
we'd welcome your support.
<wait>
As far as treating the GUILT--
<wait>

#北崎威一郎

@MSG_EVT501A_024
<bup 0 9 5>
I've memorized the surgery footage.
...I know what to do.
<wait>

#沓掛宗二

@MSG_EVT501A_025
<bup 0 13 1>
Then... Good luck, sir.
<wait>

#北崎威一郎

@MSG_EVT501A_026
<bup 0 9 5>
My surgical skills haven't rusted over yet...
<wait>
<bup_cls>
