
#明神さやか

@MSG_EVT503A_001
<bup 0 15 3>
We have a problem! People are starting to
collapse outside of our quarantine perimeter.
<wait>

#月森孝介

@MSG_EVT503A_002
<bup 0 2 5>
...From GUILT!?
<wait>

#明神さやか

@MSG_EVT503A_003
<bup 0 15 3>
The tests haven't come back yet, but judging
by their symptoms...
<wait>
Anyway, you need to help them
immediately--Chief's orders!
<wait>

#月森孝介

@MSG_EVT503A_004
<bup 0 2 5>
We're on our way!
<wait>
<bup_cls>

#佐倉東吾

@MSG_EVT503A_005
<bup 0 17 1>
Good to see you, dude...
<wait>

#月森孝介

@MSG_EVT503A_006
<bup 0 2 5>
What's the situation?
<wait>

#佐倉東吾

@MSG_EVT503A_007
<bup 0 17 5>
...The tests came back positive.
It's definitely GUILT.
<wait>
But, these symptoms don't match...
Could be an all new strain.
<wait>
And, if you want my opinion, I think
this one's airborne.
<wait>

#月森孝介

@MSG_EVT503A_008
<bup 0 2 5>
Airborne!?
<wait>

#佐倉東吾

@MSG_EVT503A_009
<bup 0 17 5>
We need to collect GUILT samples
while treating these patients.
<wait>
If this strain manages to spread,
it'll be a total disaster.
<wait>
<bup_cls>

#伊東優乃

@MSG_EVT503A_010
<bup 0 18 1>
...I informed the police, and they're
expanding the safety perimeter.
<wait>

#佐倉東吾

@MSG_EVT503A_011
<bup 0 17 1>
Good call, Leslie. We have to minimize
damage wherever possible.
<wait>
It's in your court, Derek. I don't have
the skills to handle this one.
<wait>
I'll take care of the old school GUILT patients.
Good luck, man!
<wait>

#月森孝介

@MSG_EVT503A_012
<bup 0 2 5>
Yeah... Good luck on your patients, too!
<wait>

#佐倉東吾

@MSG_EVT503A_013
<bup 0 17 1>
No sweat!
<wait>
<bup_cls>

#月森孝介

@MSG_EVT503AB_001
<bup 0 2 4>
Phew... We did it...
<wait>

#伊東優乃

@MSG_EVT503AB_002
<bup 0 18 2>
Great work, Dr. Stiles. ...Do you think
this will be over soon?
<wait>
<bup_cls>

#利根川アンジュ

@MSG_EVT503AB_003
<bup 0 8 5>
Doctor! A case of the Tetarti strain has been
confirmed nearby!
<wait>

#月森孝介

@MSG_EVT503AB_004
<bup 0 2 3>
...Well, it's not over yet.
<wait>
Tell them we're on the way!
<wait>
<bup_cls>
