
#北崎威一郎

@MSG_EVT507A_001
<bup 0 9 5>
...What I'm about to tell you does not
leave this room.
<wait>
We've found Professor Blackwell.
...He's up north, in Santa Balboa.
<wait>

#月森孝介

@MSG_EVT507A_002
<bup 0 2 5>
What's he doing up there?
<wait>

#北崎威一郎

@MSG_EVT507A_003
<bup 0 9 5>
He's apparently hiding at the
Eidoth Pharmeceuticals research lab.
<wait>
The FBI's been watching him since
late yesterday.
<wait>

#沓掛宗二

@MSG_EVT507A_004
<bup 0 13 1>
Do you think Eidoth is sheltering
Blackwell, then?
<wait>

#北崎威一郎

@MSG_EVT507A_005
<bup 0 9 5>
The question is whether or not they know
they're sheltering him.
<wait>
I doubt the regular employees have any idea
he's there...
<wait>
...or what kind of research he could be doing.
<wait>

#月森孝介

@MSG_EVT507A_006
<bup 0 2 5>
They're going to raid the lab?
<wait>

#北崎威一郎

@MSG_EVT507A_007
<bup 0 9 5>
Yes, tomorrow.
<wait>
To reduce the risk of another GUILT outbreak,
they want us to be there as well.
<wait>

#沓掛宗二

@MSG_EVT507A_008
<bup 0 13 1>
...Then, we're sending Derek in with them?
<wait>

#北崎威一郎

@MSG_EVT507A_009
<bup 0 9 5>
That's really our only option.
Can you accept the risk, Derek?
<wait>

#月森孝介

@MSG_EVT507A_010
<bup 0 2 5>
Of course.
<wait>
But... There might be one problem.
<wait>

#沓掛宗二

@MSG_EVT507A_011
<bup 0 13 1>
What's that?
<wait>

#北崎威一郎

@MSG_EVT507A_012
<bup 0 9 5>
...I think he's referring to Angie.
<wait>
...She has as much experience with
GUILT as Derek does...
<wait>
But, all things considered, taking her
might not be a good idea.
<wait>
Don't worry, I'll arrange for someone
else to assist you.
<wait>

#月森孝介

@MSG_EVT507A_013
<bup 0 2 4>
...I understand, sir.
<wait>
But...
<wait>

#北崎威一郎

@MSG_EVT507A_014
<bup 0 9 5>
Is there something else?
<wait>

#月森孝介

@MSG_EVT507A_015
<bup 0 2 4>
I don't think Angie's going to like that much.
<wait>

#沓掛宗二

@MSG_EVT507A_016
<bup 0 13 10>
......
<wait>

#月森孝介

@MSG_EVT507A_017
<bup 0 2 4>
I mean... They're going in after her father...
<wait>
If I were in Angie's place, I'd want
to see the truth for myself.
<wait>

#沓掛宗二

@MSG_EVT507A_018
<bup 0 13 10>
It's a conflict of interest that could
compromise the mission.
<wait>

#月森孝介

@MSG_EVT507A_019
<bup 0 2 4>
...It might be painful for her, but still--
<wait>
<bup_cls>

#利根川アンジュ

@MSG_EVT507A_020
<bup 0 8 5>
...Excuse me.
<wait>

#沓掛宗二

@MSG_EVT507A_021
<bup 0 13 1>
Angie? You heard us...?
<wait>

#北崎威一郎

@MSG_EVT507A_022
<bup 0 9 4>
You shouldn't be eavesdropping.
<wait>

#利根川アンジュ

@MSG_EVT507A_023
<bup 0 8 5>
I'm sorry...
<wait>
But, I can make my own decisions.
<wait>
Did you stop to consider how I might
feel about this...?
<wait>
I'm not a child...
I deserve a choice, at the very least.
<wait>

#北崎威一郎

@MSG_EVT507A_024
<bup 0 9 5>
You could watch them arrest your father?
<wait>

#利根川アンジュ

@MSG_EVT507A_025
<bup 0 8 5>
...Derek was right. I want to see the truth
with my own eyes...
<wait>

#北崎威一郎

@MSG_EVT507A_026
<bup 0 9 5>
......
<wait>

#月森孝介

@MSG_EVT507A_027
<bup 0 2 5>
Let her go.
<wait>
Angie may just be my assistant, but she's
a lot stronger than I am.
<wait>
I don't think I could have completed
all those operations without her.
<wait>

#北崎威一郎

@MSG_EVT507A_028
<bup 0 9 5>
......
<wait>

#沓掛宗二

@MSG_EVT507A_029
<bup 0 13 1>
What should we do, sir?
<wait>

#北崎威一郎

@MSG_EVT507A_030
<bup 0 9 5>
...Let her go.
<wait>
I doubt we could even find a suitable
replacement.
<wait>
...And sending Stiles in without an assistant
would be foolish.
<wait>

#月森孝介

@MSG_EVT507A_031
<bup 0 8 5>
Thank you.
<wait>
<bup_cls>

#月森孝介

@MSG_EVT507A_032
<bup 0 2 4>
I heard what you said back there, but...
Are you going to be okay?
<wait>

#利根川アンジュ

@MSG_EVT507A_033
<bup 0 8 5>
Thank you for supporting me, Dr. Stiles.
<wait>
...I'll be alright.
<wait>
But, so much has happened over
the past few days...
<wait>
...More than anything, I just want to know
the truth. I need to find out for myself...
<wait>
I'm going to ask my father why he joined
Delphi!
<wait>

#月森孝介

@MSG_EVT507A_034
<bup 0 2 5>
......
<wait>

#利根川アンジュ

@MSG_EVT507A_035
<bup 0 8 5>
My father disappeared right before
I entered elementary school.
<wait>
He simply vanished--nobody had any
idea what happened to him.
<wait>
There were times I hated my father.
I'd ask Mom why he left us...
<wait>
...But, she never had an answer.
<wait>
Even after all that, I found it hard
not to respect him.
<wait>
...Nobody ever had anything bad to say
about my father.
<wait>
He's the reason I started studying medicine
in the first place.
<wait>

#月森孝介

@MSG_EVT507A_036
<bup 0 2 5>
...I'm sorry about this, Angie.
<wait>

#利根川アンジュ

@MSG_EVT507A_037
<bup 0 8 4>
I...
<wait>
I never thought my father could be
involved in something like this...
<wait>
...Was all my hard work for nothing?
<wait>
I'm sorry, Derek...
I'll be fine tomorrow.
<wait>
But, for right now...
I can't help it.
<wait>
...I'm so sorry...
<wait>
*sob*
<wait>

#月森孝介

@MSG_EVT507A_038
<bup 0 2 5>
Angie...
<wait>
<bup_cls>
