
#北崎威一郎

@MSG_EVT502A_001
<bup 0 9 5>
*sigh*... I think he's stable.
<wait>

#沓掛宗二

@MSG_EVT502A_002
<bup 0 13 1>
Well done, Dr. Hoffman.
<wait>

#佐倉東吾

@MSG_EVT502A_003
<bup 0 17 5>
There's no way... How'd the old man
move so fast!?
<wait>

#月森孝介

@MSG_EVT502A_004
<bup 0 2 5>
Amazing...! That must be what it's
like to watch the Healing Touch.
<wait>
...Do I look like that, too?
<wait>

#利根川アンジュ

@MSG_EVT502A_005
<bup 0 8 5>
Dr. Stiles! We're ready for the procedure.
<wait>

#月森孝介

@MSG_EVT502A_006
<bup 0 2 5>
Yeah... I'll be right there!
<wait>
<bup_cls>

#北崎威一郎

@MSG_EVT502B_001
<bup 0 9 5>
Hm... Dr. Stiles has come a long way, himself.
<wait>

#沓掛宗二

@MSG_EVT502B_002
<bup 0 13 1>
I know it's tough, Derek, but prepare
for the next patient.
<wait>

#月森孝介

@MSG_EVT502B_003
<bup 0 2 3>
Understood!
<wait>
<bup_cls>
