
#月森孝介

@MSG_EVT506A_001
<bup 0 2 3>
How's Dr. Myers doing!?
<wait>

#沓掛宗二

@MSG_EVT506A_002
<bup 0 13 1>
It's GUILT, Derek...
You'll need to operate immediately.
<wait>
We found a needle in her leg--they
must have injected it, somehow.
<wait>

#月森孝介

@MSG_EVT506A_003
<bup 0 2 5>
Which strain is it?
<wait>

#沓掛宗二

@MSG_EVT506A_004
<bup 0 13 1>
...We don't know.
It could be a new one.
<wait>

#月森孝介

@MSG_EVT506A_005
<bup 0 2 5>
Another one!?
<wait>

#沓掛宗二

@MSG_EVT506A_006
<bup 0 13 1>
Victor's analyzing it as we speak.
We'll start when he gets back to us.
<wait>

#月森孝介

@MSG_EVT506A_007
<bup 0 2 5>
Understood.
<wait>

#利根川アンジュ

@MSG_EVT506A_008
<bup 0 8 5>
......
<wait>

#月森孝介

@MSG_EVT506A_009
<bup 0 2 5>
Tell me what's going on, Angie.
<wait>

#利根川アンジュ

@MSG_EVT506A_010
<bup 0 8 5>
Huh? I-I'm sorry...
It's nothing. Don't worry.
<wait>
We should prep for the operation, Doctor.
<wait>

#月森孝介

@MSG_EVT506A_011
<bup 0 2 5>
......
<wait>
<bup_cls>

#沓掛宗二

@MSG_EVT506B_001
<bup 0 13 10>
You did well, Derek.
<wait>

#月森孝介

@MSG_EVT506B_002
<bup 0 2 1>
I had to save her...
<wait>

#沓掛宗二

@MSG_EVT506B_003
<bup 0 13 1>
We couldn't let anything happen to
one of our best doctors...
<wait>
...And, I couldn't let my brother down, either.
<wait>

#佐倉東吾

@MSG_EVT506B_004
<bup 0 17 4>
So, was that picture worth Cybil
risking her life?
<wait>

#月森孝介

@MSG_EVT506B_005
<bup 0 2 5>
Oh! I totally forgot about that!
<wait>

#利根川アンジュ

@MSG_EVT506B_006
<bup 0 8 5>
......
<wait>

#宝生卓而

@MSG_EVT506B_007
<bup 0 14 1>
Let's see...
<wait>

#伊東優乃

@MSG_EVT506B_008
<bup 0 18 2>
Well... He's very handsome.
<wait>

#沓掛宗二

@MSG_EVT506B_009
<bup 0 13 1>
...Huh?
<wait>

#宝生卓而

@MSG_EVT506B_010
<bup 0 14 1>
I remember that face...
I've seen him before.
<wait>
Hmm...
<wait>
Blackwell!
That's Professor Blackwell!
<wait>
He went missing about ten years ago.
<wait>

#沓掛宗二

@MSG_EVT506B_011
<bup 0 13 1>
...Are you sure!?
<wait>

#宝生卓而

@MSG_EVT506B_012
<bup 0 14 1>
Yes. He was studying immunology.
<wait>
Before his disappearance, he was
a big-name scientist.
<wait>
But, could he really be involved with Delphi?
<wait>

#利根川アンジュ

@MSG_EVT506B_013
<bup 0 8 5>
There's no doubt about it...
That man is Kenneth Blackwell.
<wait>

#月森孝介

@MSG_EVT506B_014
<bup 0 2 5>
Angie...?
<wait>

#利根川アンジュ

@MSG_EVT506B_015
<bup 0 8 5>
Blackwell disappeared 13 years ago,
leaving his wife and daughter behind.
<wait>
He's my father.
<wait>

#月森孝介

@MSG_EVT506B_016
<bup 0 2 5>
...!
<wait>
<bup_cls>
