
@MSG_EVT603A_001
<bup 0 21 1>
...32 hours have passed since the patient was
infected.
<wait>
His vitals are relatively stable, but we have no
indication how long that will last.
<wait>
The Chiral reaction indicates Tetarti, and we
know it's in his liver. However, the tests--
<wait>
...Exercise every precaution. This strain seems
unusually contagious.
<wait>

@MSG_EVT603A_002
<bup 0 8 1>
I've updated his chart...
<wait>
We have a lot of experience treating this
GUILT, and will proceed as normal.
<wait>

@MSG_EVT603A_003
<bup 0 19 1>
Yes...if you require any additional tools, don't
hesitate to let me know.
<wait>
I believe you'll find our facilities to be state of
the art. I'm expecting a flawless performance!
<wait>

@MSG_EVT603A_004
<bup 0 2 1>
We'll do our best.
<wait>

@MSG_EVT603A_005
<bup 0 6 1>
...I'm going to be observing this one from the
monitoring station.
<wait>
I'm interested to see what your
Healing Touch is like, Stiles.
<wait>
<bup_cls>

@MSG_EVT603B_007
- Caduceus Europe, Operating Room -
<wait>

@MSG_EVT603B_001
<bup 0 2 7>
What the...*cough*
...What's wrong with--
<wait>

@MSG_EVT603B_002
<bup 0 8 5>
Dr. Stiles... Is there something wrong
with the patient!?
<wait>

@MSG_EVT603B_003
<bup 0 2 7>
No... This is--*cough*
Ugh...
<wait>
<bup_cls>

@MSG_EVT603B_004
<bup 0 8 9>
Derek! What happened!?
<wait>

@MSG_EVT603B_005
<bup 0 6 3>
His symptoms...!
<wait>

@MSG_EVT603B_006
<bup 0 19 1>
This is bad! Order a Chiral test immediately!
<wait>
He...may have been infected...
<wait>
<bup_cls>
