
@MSG_EVT606A_001
- Caduceus Europe, Conference Hall -
<wait>

@MSG_EVT606A_002
<bup 0 21 1>
...patients who lost organ, bone, and
muscle cells...
<wait>
Near-complete recoveries were reported in
every one of these cases.
<wait>
I hope this demonstrates the effectiveness of
the neo-cells, or Z-Cells, as we call them.
<wait>
However, I'd like to convince you further by
bringing up one of our Z-Cell patients...
<wait>
...Thank you again, Mr. Heigl, for your
willingness to take part in this demonstration.
<wait>
There will be a short break as we set up
for the next segment of the conference.
<wait>
<bup_cls>

@MSG_EVT606A_003
<bup 0 9 5>
...It seems Great Britain has put some thought
into this.
<wait>

@MSG_EVT606A_004
<bup 0 19 1>
I understand your sarcasm...
<wait>
However, I went to a lot of trouble convincing
the military to allow us to reveal even this.
<wait>
...If we continued to conceal research, we
would have lost our international support.
<wait>

@MSG_EVT606A_005
<bup 0 9 5>
Regardless of my opinion, the results
are impressive.
<wait>
I'd like America to research similar methods,
if only to keep a closer eye on them.
<wait>

@MSG_EVT606A_006
<bup 0 19 1>
Our country was generous to supply funding
for our research, since they found it useful.
<wait>
On the other hand, it was given on the grounds
that we would be treating wounded soldiers.
<wait>

@MSG_EVT606A_007
<bup 0 9 5>
Soldiers...?
<wait>
What happens to them once the treatment
is finished?
<wait>

@MSG_EVT606A_008
<bup 0 19 1>
...They can't return to duty.
I assume they become civilians.
<wait>

@MSG_EVT606A_009
<bup 0 9 5>
Meaning your treatment takes all the risk
out of sending men off to war...
<wait>

@MSG_EVT606A_010
<bup 0 19 1>
......
<wait>

@MSG_EVT606A_011
<bup 0 21 1>
...We're ready to begin, if you'll kindly return
to your seats.
<wait>
I would like you to take a look at the screen...
<wait>

@MSG_EVT606A_035
This was Mr. Heigl's condition before he
arrived for treatment...
<wait>
As you can see, his abdomen was severely
damaged by a bullet wound.
<wait>
...Dialysis was the only thing keeping him alive.
<wait>
But, once we implanted the Z-Cells...
...Please come out, Mr. Heigl.
<wait>
<bup_cls>

@MSG_EVT606A_036
<bup 0 21 1>
You can see that he's doing...quite a bit
better now.
<wait>
Although he still has scars from several
surgeries, internally, he's fully recovered!
<wait>
...If we pull up a diagnostic image of his
body's interior...
<wait>

@MSG_EVT606A_038
...you can clearly see that it's been completely
restored to its natural condition, pre-injury.
<wait>
Followup treatment is simple and unintrusive:
we simply administer a serum semi-annually.
<wait>
This aids in the formation of tissue and helps
to stabilize it.
<wait>
If Mr. Heigl will excuse me... I can demonstrate
this treatment for you, as well.
<wait>

@MSG_EVT606A_012
<bup 0 2 5>
...His tissue completely regenerated.
That's amazing!
<wait>

@MSG_EVT606A_013
<bup 0 6 1>
Even though, for all intents and purposes,
it's just the eighth GUILT?
<wait>

@MSG_EVT606A_014
<bup 0 8 5>
You're against it then, Dr. Kimishima?
<wait>

@MSG_EVT606A_015
<bup 0 6 1>
Your father told me there was no way to
control that monster.
<wait>
He studied it for years... Created it...
Even he was afraid of GUILT.
<wait>

@MSG_EVT606A_016
<bup 0 8 5>
......
<wait>

@MSG_EVT606A_017
<bup 0 6 1>
I don't care how much research they've done
with these Z-Cells...
<wait>
If GUILT is involved, it's going to backfire.
I just hope I'm not there when it happens.
<wait>

@MSG_EVT606A_018
<bup 0 21 1>
...!? Mr. Heigl!
<wait>
<bup_cls>

@MSG_EVT606A_019
What's-- I don't...
<wait>
*cough*
<wait>
...Ugh... AaaaRGH!
<wait>

@MSG_EVT606A_037
<func7>

@MSG_EVT606A_020
<bup 0 2 3>
What's going on?
<wait>

@MSG_EVT606A_021
<bup 0 6 3>
...It's GUILT. This strain must be airborne--it's
being released from his blood!
<wait>
<bup_cls>

@MSG_EVT606A_022
Help me!
<wait>
Something's wrong, I...
...What is this!?
<wait>
<func8>

@MSG_EVT606A_023
<bup 0 19 1>
No...this can't happen! Not in front of
all these people!
<wait>

@MSG_EVT606A_024
<bup 0 9 5>
We have to evacuate the attendees before
everyone is infected!
<wait>
But, how can we...
<wait>

@MSG_EVT606A_025
<bup 0 19 1>
But, how can we...
<wait>
*/

@MSG_EVT606A_026
<bup 0 6 1>
...It seems a little rude to say I told you so.
Think you can handle this, Stiles?
<wait>

@MSG_EVT606A_027
<bup 0 2 5>
I-I'll do my best, but...what about you?
<wait>

@MSG_EVT606A_028
<bup 0 6 1>
GUILT survivors develop antibodies to protect
against further infection.
<wait>
Didn't they show you the research?
<wait>

@MSG_EVT606A_029
<bup 0 2 5>
...!?
<wait>

@MSG_EVT606A_030
<bup 0 6 1>
In these conditions, anyone who operates on
those people is going to get infected.
<wait>
...Except that you're immune.
Looks like you need to get ready.
<wait>

@MSG_EVT606A_031
<bup 0 2 5>
I understand! Angie, will you be all right
assisting me?
<wait>

@MSG_EVT606A_032
<bup 0 8 5>
...I'll be fine. We need to move the infected
attendees to an operating area, stat!
<wait>
<bup_cls>

@MSG_EVT606A_033
<bup 0 19 1>
...How could we let this happen?
<wait>

@MSG_EVT606A_034
<bup 0 21 1>
......
<wait>
<bup_cls>
