
@MSG_EVT600A_001
<telop 0>
With Delphi exposed, it didn't take long for
sleeper cells to be found and eliminated.
The end of medical terrorism seemed to
be within reach.
<wait>

@MSG_EVT600A_002
<telop 0>
Professor Blackwell pledged his full
cooperation with Caduceus in the ongoing
investigation.
<wait>

@MSG_EVT600A_003
<telop 0>
Although it was his daughter's kidnapping
that forced Blackwell to cooperate, he
maintained that Delphi's actions would have
been impossible without his research.
<wait>

@MSG_EVT600A_004
<telop 0>
When offered a formal pardon, Blackwell
insisted that he serve out his term in prison.
He thanked Derek and Angie for giving him
a second  chance to atone for his mistakes.
<wait>

@MSG_EVT600A_005
<telop 1>
The professor's testimony provided a clearer
picture of the international terrorist
organization known as Delphi, and shed light
on their intentions.
<wait>

@MSG_EVT600A_006
<telop 1>
Delphi held to a dangerous ideology
preached by their leader, a mysterious man
who called himself Adam.
<wait>

@MSG_EVT600A_007
<telop 1>
Their financial backing came primarily from
holdings they absorbed from a number of
international pharmeceutical conglomerates
such as the Eidoth Corporation.
<wait>

@MSG_EVT600A_008
<telop 2>
The major world powers combined resources
in a massive search for Delphi's headquarters.
It wasn't long before they located it:
a fortified vessel in the Atlantic Ocean.
<wait>

@MSG_EVT600A_009
<telop 2>
Dr. Stiles and Nurse Angie were asked to
accompany the British Navy in a raid on
Delphi's aquatic facility.
<wait>

@MSG_EVT600A_010
<telop 2>
A horrifying discovery awaited them inside
the vessel; one which demonstrated the cruel
lengths to which Delphi had gone to develop
their GUILT...
<wait>

@MSG_EVT600A_011
<telop 3>
They had kidnapped children from all over
the world to serve as hosts for the original
subspecies of GUILT.
<wait>

@MSG_EVT600A_012
<telop 3>
Dr. Stiles and Angie operated on these victims,
who were taken into protective custody once
they were free of the virus.
<wait>

@MSG_EVT600A_013
<telop 4>
And, in the hidden depths of the vessel, Derek
came face to face with Adam--the
mastermind behind medical terrorism, and the
main objective of the raid.
<wait>

@MSG_EVT600A_014
<telop 4>
...Although, having absorbed GUILT into his own
body, Adam had become scarcely more than
a corpse.
<wait>

@MSG_EVT600A_015
<telop 4>
The vapors present in Adam's chamber were
enough to momentarily incapacitate Derek,
though British forces soon located and
revived him. At last, the mission was complete.
<wait>

@MSG_EVT600A_016
<telop 4>
Adam's GUILT-infested remains were
confiscated by the British Navy, and their
current whereabouts are unknown.
<wait>

@MSG_EVT600A_017
<telop 4>
For all intents and purposes, Delphi has
been destroyed.
<wait>

@MSG_EVT600A_018
<telop 0>
Several months have passed since that time.
<wait>

@MSG_EVT600A_019
<telop 0>
Caduceus USA has continued its ongoing
battle against intractable diseases.
<wait>

@MSG_EVT600A_020
<telop 0>
They have seen many members come and go,
but their mission to research new treatments
has continued, with Dr. Derek Stiles at the
forefront.
<wait>

@MSG_EVT600A_021
<telop 0>
Thanks to the vigilant efforts of Caduceus
USA, memories of the plague known as
GUILT have finally started to vanish.
<wait>

@MSG_EVT600A_022
<telop 0>
However...
<wait>
<telop_cls>

@MSG_EVT601A_001
<bup 0 17 1>
...This new medication is sweet. The patients
have been responding really well.
<wait>

@MSG_EVT601A_002
<bup 0 16 1>
Well, I'm not usually one to brag...
<wait>
Let's just say I expected nothing less
than perfection.
<wait>

@MSG_EVT601A_003
<bup 0 17 1>
Shouldn't you give some credit to Blackwell
since he, you know, thought of it?
<wait>

@MSG_EVT601A_004
<bup 0 16 1>
There is a fine line between theory and
creation.
<wait>
I question your abilities as a doctor if you
don't appreciate that difference.
<wait>

@MSG_EVT601A_005
<bup 0 14 1>
All right, Victor... Blackwell thought up a
method of treatment, and you made it work.
<wait>
Can we drop it now?
<wait>

@MSG_EVT601A_006
<bup 0 16 1>
Whatever...
I still made it work.
<wait>

@MSG_EVT601A_007
<bup 0 17 5>
It kinda sucks we're the only ones who will
ever know Blackwell had anything to do with it.
<wait>

@MSG_EVT601A_008
<bup 0 14 1>
We're fortunate he agreed to help us while
paying his debt to society.
<wait>
The world needs Professor Blackwell's
research more than anyone will ever know.
<wait>
<bup_cls>

@MSG_EVT601A_009
<bup 0 18 2>
...Welcome back, Dr. Stiles! You too, Angie!
Thanks for the souvenirs.
<wait>
That Pochy was delicious…
I'm such a slave to Japanese treats.
<wait>

@MSG_EVT601A_010
<bup 0 8 2>
Glad you liked it.
<wait>
We didn't have much time to appreciate Tokyo,
though, since most of our time was spent on
<wait>
conferences and hospital visitations.
<wait>

@MSG_EVT601A_011
<bup 0 2 4>
I think I'm still a little jet-lagged...
<wait>

@MSG_EVT601A_012
<bup 0 18 2>
*sigh* Can't you at least try to act like you're
a world-renowned super doctor?
<wait>

@MSG_EVT601A_013
<bup 0 8 1>
Have you heard back from Dr. Myers? I'd like
to know how she's adjusting to Hope Hospital.
<wait>

@MSG_EVT601A_014
<bup 0 18 2>
...Oh, I forgot! The Director wanted to see
you two as soon as you got back.
<wait>
It must be tough being so popular, huh?
You'd better head up to his office.
<wait>

@MSG_EVT601A_015
<bup 0 8 1>
Well, thanks for letting us know.
<wait>

@MSG_EVT601A_016
<bup 0 2 1>
Think there's any chance he's going to give
us a vacation?
<wait>

@MSG_EVT601A_017
<bup 0 18 2>
Hmm...?
I seriously doubt it.
<wait>
<bup_cls>

@MSG_EVT601A_018
<bup 0 2 1>
...A long-term assignment in Great Britain?
<wait>

@MSG_EVT601A_019
<bup 0 8 1>
Will I be going as well?
<wait>

@MSG_EVT601A_020
<bup 0 13 1>
Yes. They asked for both of you specifically.
<wait>
They're in the final stages of some project and
asked that our most skilled doctors participate.
<wait>

@MSG_EVT601A_021
<bup 0 9 5>
We were hesitant about their proposition...
<wait>
But, considering they finally decided to ask for
our help after months of silence, we agreed.
<wait>

@MSG_EVT601A_022
<bup 0 13 1>
Caduceus Europe will also be holding a
conference there, in about a month.
<wait>
We'd like you to attend that as well, and
Director Hoffman will be joining you.
<wait>
Like he said, the British have been quiet
about their research since the raid.
<wait>
...Now, all of a sudden, they're asking outside
organizations for help with some project.
<wait>

@MSG_EVT601A_023
<bup 0 9 5>
They must be extremely confident if they're
willing to break their silence on the issue...
<wait>
...considering they were unwilling to share any
information on Delphi only months ago.
<wait>
We would like you to keep us posted on
their activities while you're there.
<wait>

@MSG_EVT601A_024
<bup 0 2 1>
So, they're sharing their data? I thought you
said they just wanted skilled surgeons.
<wait>

@MSG_EVT601A_025
<bup 0 13 1>
They made sure we understood none of their
research was to be made public...
<wait>

@MSG_EVT601A_026
<bup 0 9 5>
Director Miller is a good man, but I worry
about all this secrecy...
<wait>
I can only assume the government wanted to
have others involved as a safety measure.
<wait>

@MSG_EVT601A_027
<bup 0 13 1>
Are you willing to accept, knowing that there's
more to this than meets the eye?
<wait>

@MSG_EVT601A_028
<bup 0 2 1>
...I understand the situation. But, if they need
our help, I'm willing to go.
<wait>

@MSG_EVT601A_029
<bup 0 8 1>
We accept.
<wait>

@MSG_EVT601A_030
<bup 0 13 1>
We've made preparations for you to leave in
five days. You'll be on duty as usual until then.
<wait>

@MSG_EVT601A_031
<bup 0 9 5>
I'll see you both in a month.
<wait>
<bup_cls>
