
@MSG_EVT607A_001
<bup 0 20 1>
Sir! I have an update on the situation!
<wait>
Dr. Ashton has been confirmed infected.
Mr. Alex Yang is also infected.
<wait>
Professor Ritz has been infected.
We've confirmed Dr. Maffouse, as well.
<wait>
There are 22 others who are confirmed to be
infected, 7 of whom show full Chiral reactions.
<wait>
<bup_cls>

@MSG_EVT607A_002
<bup 0 19 1>
This is a disaster... GUILT is going to destroy
modern medicine in one fell swoop!
<wait>

@MSG_EVT607A_003
<bup 0 9 5>
Panicking isn't going to save those people,
Langston.
<wait>
We're going to stop this if at all possible.
I'll be helping with the operations...
<wait>

@MSG_EVT607A_004
<bup 0 19 1>
...Thank you, Robert.
<wait>
...Dr. Stiles, Dr. Kimishima...
<wait>
I need you to operate on the four patients
the sergeant just mentioned.
<wait>

@MSG_EVT607A_005
<bup 0 2 5>
Understood.
<wait>

@MSG_EVT607A_006
<bup 0 6 1>
We need to get started.
<wait>

@MSG_EVT607A_007
<bup 0 19 1>
I understand this is a dire situation, but
I sincerely appreciate your help...
<wait>
...Where is Dr. Owen?
<wait>
<bup_cls>

@MSG_EVT607A_008
<bup 0 20 1>
Sir! There has been no sign of Dr. Owen
for at least thirty minutes!
<wait>

@MSG_EVT607A_009
<bup 0 19 1>
...What!?
Unacceptable!
<wait>
He shouldn't be abandoning his duties
at a time like this!
<wait>

@MSG_EVT607A_010
<bup 0 9 5>
How does this affect the situation?
<wait>

@MSG_EVT607A_011
<bup 0 19 1>
We extracted samples from Adam in order
to create a serum to combat GUILT...
<wait>
Dr. Owen is the only person who has
access to them!
<wait>

@MSG_EVT607A_012
<bup 0 9 5>
...Mind if I try to get more?
<wait>

@MSG_EVT607A_013
<bup 0 19 1>
Hmm... True, you might be able to...
<wait>
This is the only guaranteed cure, but you know
there are certain risks when handling GUILT...
<wait>
I'll explain the procedure, but you must
be careful at all times.
<wait>
Please follow me, Dr. Hoffman...
<wait>
We'll send the serum as soon as we can,
Dr. Stiles! Do your best until then!
<wait>

@MSG_EVT607A_014
<bup 0 2 5>
Understood!
<wait>

@MSG_EVT607A_015
<bup 0 8 5>
I have a plan.
<wait>
Dr. Stiles, Dr. Kimishima...you will both
alternate treating these four patients.
<wait>
In other words, you'll each perform two
procedures. The patients are being brought in...
<wait>

@MSG_EVT607A_016
<bup 0 2 5>
Let's get to the Operating Room, then.
There isn't any time to waste!
<wait>
<bup_cls>

@MSG_EVT607B_001
ＢＧ０００　北崎病院診療室
<wait>

@MSG_EVT607B_002
ＢＧ００１　北崎病院ナースステーション
<wait>

@MSG_EVT607B_003
ＢＧ００２　北崎病院病室
<wait>

@MSG_EVT607B_004
ＢＧ００３　北崎病院手術室
<wait>

@MSG_EVT607B_005
ＢＧ００４　北崎病院外観
<wait>

@MSG_EVT607B_006
ＢＧ２０４　北崎病院外観（夜）
<wait>

@MSG_EVT607B_007
ＢＧ００５　北崎病院院長室
<wait>

@MSG_EVT607B_008
ＢＧ０１０　カドゥケウス沓掛オフィス
<wait>

@MSG_EVT607B_009
ＢＧ０１１　カドゥケウス手術室
<wait>

@MSG_EVT607B_010
ＢＧ０１２　カドゥケウス病室
<wait>

@MSG_EVT607B_011
ＢＧ０１３　カドゥケウス医師控え室
<wait>

@MSG_EVT607B_012
ＢＧ０１４　カドゥケウス廊下（昼）
<wait>

@MSG_EVT607B_013
ＢＧ２１４　カドゥケウス廊下（夜）
<wait>

@MSG_EVT607B_014
ＢＧ０１５　カドゥケウス理事長室
<wait>

@MSG_EVT607B_015
ＢＧ０１６　カドゥケウス外観
<wait>

@MSG_EVT607B_016
ＢＧ０２０　飛行機の中
<wait>

@MSG_EVT607B_017
ＢＧ０２１　学会会場
<wait>

@MSG_EVT607B_018
ＢＧ２２１　学会会場（停電）
<wait>

@MSG_EVT607B_019
ＢＧ０２２　アフリカの村
<wait>

@MSG_EVT607B_020
ＢＧ０２３　デルフォイ研究所跡
<wait>

@MSG_EVT607B_021
ＢＧ０３０　デルフォイ研究室
<wait>

@MSG_EVT607B_022
ＢＧ０３１　デルフォイ最深部研究室
<wait>

@MSG_EVT607B_023
ＢＧ０３２　デルフォイ創始者室
<wait>

@MSG_EVT607B_024
ＢＧ０３３　デルフォイ医院
<wait>

@MSG_EVT607B_025
ＢＧ０４２　日本オフィス街
<wait>

@MSG_EVT607B_026
ＢＧ０４３　日本繁華街
<wait>

@MSG_EVT607B_027
ＢＧ２４３　日本繁華街（夜）
<wait>

@MSG_EVT607B_028
ＢＧ０４４　日本住宅街
<wait>

@MSG_EVT607B_029
ＢＧ０４５　山道（トンネル）
<wait>

@MSG_EVT607B_042
ＢＧ０４６　トンネルの中
<wait>

@MSG_EVT607B_030
ＢＧ０５０　米カドゥケウスオフィス
<wait>

@MSG_EVT607B_031
ＢＧ０５１　米カドゥケウス手術室
<wait>

@MSG_EVT607B_032
ＢＧ０５２　米カドゥケウス病室
<wait>

@MSG_EVT607B_033
ＢＧ０５３　米カドゥケウス研究室兼標本室
<wait>

@MSG_EVT607B_034
ＢＧ０５４　米カドゥケウス会議室
<wait>

@MSG_EVT607B_035
ＢＧ０６０　新病院医師控え室
<wait>

@MSG_EVT607B_036
ＢＧ０６１　新病院医師手術室
<wait>

@MSG_EVT607B_037
ＭＡＰ００　千羽市
<wait>

@MSG_EVT607B_038
ＭＡＰ０１　千羽市（夜）
<wait>

@MSG_EVT607B_039
ＭＡＰ０２　アフリカ
<wait>

@MSG_EVT607B_040
ＭＡＰ０３　北富市
<wait>

@MSG_EVT607B_041
ＭＡＰ０４　アメリカ（ヨーロッパ）
<wait>
