
@MSG_EVT604A_001
- Caduceus Europe, Emergency Ward -
<wait>

@MSG_EVT604A_002
<bup 0 21 1>
...Tests are positive.
He's been infected with GUILT.
<wait>
I knew there was something odd about that
last patient!
<wait>

@MSG_EVT604A_003
<bup 0 19 1>
...There's no precedent for this--if it's reached
his heart, he shouldn't even be conscious!
<wait>

@MSG_EVT604A_004
<bup 0 2 4>
...I guess I was careless...
I didn't think--Hng!
<wait>

@MSG_EVT604A_005
<bup 0 19 1>
We've wasted enough time talking about it...
If we don't operate immediately, he'll die.
<wait>
I wish we had more information to go on, but
we've run out of options.
<wait>
Dr. Kimishima, you're the only person qualified
to handle this operation.
<wait>

@MSG_EVT604A_006
<bup 0 6 1>
...Of course, Director.
<wait>

@MSG_EVT604A_007
<bup 0 19 1>
I've contacted Caduceus USA and received
their consent to proceed.
<wait>
I don't need to tell any of you how crucial this
surgery will be...
<wait>
But, Dr. Stiles is no ordinary patient. He's
the medical field's national treasure.
<wait>
Nurse Thompson, I would like you to provide
full support to Dr. Kimishima.
<wait>

@MSG_EVT604A_008
<bup 0 8 4>
...Yes. I'll do...my best.
<wait>

@MSG_EVT604A_009
<bup 0 6 1>
......
<wait>
Director, may I speak to Dr. Stiles--
<wait>
...I'd like to speak with the patient, alone.
<wait>

@MSG_EVT604A_010
<bup 0 19 1>
If you must.
<wait>
...We'll be right outside. Let us know as soon
as you're ready to proceed.
<wait>
<bup_cls>

@MSG_EVT604A_011
<bup 0 6 2>
...I'm worried that Nurse Thompson's feelings
for you will prevent her from doing her job.
<wait>
Are you sure she can handle this?
<wait>

@MSG_EVT604A_012
<bup 0 2 4>
...Don't worry about Angie.
She's the best there is.
<wait>

@MSG_EVT604A_013
<bup 0 6 1>
She's Professor Blackwell's daughter, right?
...I hope she's as tough as her old man.
<wait>

@MSG_EVT604A_014
<bup 0 2 5>
...Huh?
<wait>

@MSG_EVT604A_015
<bup 0 6 1>
...I took a few jobs for Delphi back in America,
under an assumed name.
<wait>
I can't stop time or anything, but my Healing
Touch was enough for them to pay top dollar.
<wait>
They needed me to keep GUILT subjects alive
long enough to complete their research...
<wait>
In a way, that GUILT inside you wouldn't exist
without me.
<wait>

@MSG_EVT604A_016
<bup 0 2 5>
Wh-Why are you... *cough*
<wait>

@MSG_EVT604A_017
<bup 0 6 1>
After you raided Delphi's American Eidoth
facility, I cut a deal with Caduceus Europe...
<wait>
I gave them a GUILT sample and my Healing
Touch in exchange for full immunity.
<wait>
This is how I've chosen to atone for my sins.
<wait>

@MSG_EVT604A_018
<bup 0 2 5>
No... *cough*
...Why are you telling me this?
<wait>

@MSG_EVT604A_019
<bup 0 6 2>
Trust is a crucial component of the
doctor/patient relationship.
<wait>

@MSG_EVT604A_020
<bup 0 2 6>
...Yeah, but it's usually *cough* the other
way around...
<wait>

@MSG_EVT604A_021
<bup 0 6 2>
*chuckle* You might have a point.
<wait>
I had my reservations, of course. Doubts...
about whether I deserved to keep operating.
<wait>
Look at us... You've saved countless lives, and
you'll die if I can't save yours...
<wait>
But, I've realized something... As long as I'm
still needed, I can be a doctor.
<wait>
...I want my life back, just as much as you
want to live.
<wait>
We both need to keep fighting.
<wait>

@MSG_EVT604A_022
<bup 0 2 1>
...I believe in you, Kimishima...
<wait>
*cough*
I can trust you...with my life.
<wait>

@MSG_EVT604A_023
<bup 0 6 1>
...See you on the other side.
<wait>
<bup_cls>

@MSG_EVT604B_001
<bup 0 19 1>
A miracle... I don't believe it!
We're fortunate the operation went so well.
<wait>
Caduceus Europe would be ruined if Dr. Stiles
had died on our watch.
<wait>

@MSG_EVT604B_002
<bup 0 21 1>
...You are truly a blessing, Dr. Kimishima.
<wait>

@MSG_EVT604B_003
<bup 0 8 4>
...Thank you...Naomi.
<wait>
I'm sure Derek will get well...soon...
<wait>

@MSG_EVT604B_004
<bup 0 6 2>
I was just doing my job;
no need to thank me.
<wait>
...But, why would you want to hide
your tears from him?
<wait>
You think he doesn't already know?
The man deserves to see how you feel.
<wait>
<bup_cls>
