
@MSG_EVT605A_001
<bup 0 19 1>
...It's good to see you're doing well, Dr. Stiles.
<wait>

@MSG_EVT605A_002
<bup 0 2 1>
...Some doctor, right? Heh... I don't think I
could even lift a scalpel right now.
<wait>
...Did you need anything, Director Miller?
<wait>

@MSG_EVT605A_003
<bup 0 19 1>
No, you can rest. There was just something
I thought I should tell you...
<wait>

@MSG_EVT605A_004
<bup 0 2 1>
Oh, about Dr. Kimishima?
<wait>
...You don't need to worry, I already know.
She told me all about her past.
<wait>

@MSG_EVT605A_005
<bup 0 19 1>
Yes, well...I trust you understand. She's
become a valuable member of our team here.
<wait>
...But, that isn't what I wanted to speak with
you about. This is something you do not know.
<wait>
Are you okay to walk...?
Please, follow me.
<wait>

@MSG_EVT605A_006
<bup 0 2 1>
...Sure, okay.
<wait>
<bup_cls>

@MSG_EVT605A_007
<bup 0 19 1>
...Here. You're looking at our big secret.
<wait>

@MSG_EVT605A_008
<bup 0 2 3>
This is...!?
<wait>
<bup_cls>

@MSG_EVT605A_009
<bup 0 22 1>
......
<wait>

@MSG_EVT605A_010
<bup 0 19 1>
The source of GUILT's evil is sleeping right
there, in that capsule...
<wait>
He no longer breathes, and blood has ceased
to flow in his veins.
<wait>

@MSG_EVT605A_011
<bup 0 2 5>
He's dead.
<wait>

@MSG_EVT605A_012
<bup 0 19 1>
Well, he isn't alive. So, technically, yes.
<wait>
We're preserving him at very low temperatures.
Don't worry, he cannot be revived.
<wait>
...The strange thing is, his body shows
no signs of putrefaction.
<wait>

@MSG_EVT605A_013
<bup 0 22 1>
......
<wait>

@MSG_EVT605A_014
<bup 0 19 1>
We've been researching GUILT and Adam
since the raid on Delphi's ocean fortress.
<wait>
Those studies were the basis of the
regenerative treatments we showed you.
<wait>
We felt the risk was justified, if it meant
saving more lives.
<wait>
...But, there are times I wonder...
<wait>
...Are we continuing along Delphi's path?
<wait>

@MSG_EVT605A_015
<bup 0 2 5>
Why did you show this to me?
<wait>

@MSG_EVT605A_016
<bup 0 19 1>
I'm not exactly sure... I just felt you had
the right to know.
<wait>

@MSG_EVT605A_017
<bup 0 2 5>
...How did you expect me to feel?
All the work I've done...and now this!
<wait>

@MSG_EVT605A_018
<bup 0 19 1>
If it motivated you in the fight against GUILT,
then I wouldn't regret a thing.
<wait>
The neo-cells our treatment is based on
came directly from Adam's body.
<wait>
His bodily fluids are being used in a unique
new serum we're developing...
<wait>
We risked our lives on that ship, battling
the evils Delphi had unleashed...
<wait>
...but we also found great treasure onboard.
We've earned that bounty.
<wait>
...I'll be going into further detail during the
upcoming conference. I'd like to hear your
<wait>
opinions on the subject then, since you're
such a valuable figure in the field of medicine.
<wait>

@MSG_EVT605A_019
<bup 0 2 5>
......
<wait>
<bup_cls>
