
@MSG_EVT608A_001
"...He's in here! Stop him!"
<wait>

@MSG_EVT608A_002
<bup 0 20 1>
Dr. Owen has been taken into military custody.
<wait>
We found him in the underground parking
structure, attempting to escape.
<wait>

@MSG_EVT608A_003
<bup 0 21 10>
...You should have accepted death.
<wait>

@MSG_EVT608A_004
<bup 0 19 1>
...?
Why were you trying to run, Owen?
<wait>

@MSG_EVT608A_005
<bup 0 21 10>
Unlike the rest of you fools... I know the future
of medicine will not be a happy one.
<wait>

@MSG_EVT608A_006
<bup 0 19 1>
...!?
<wait>

@MSG_EVT608A_007
<bup 0 21 10>
Who provided for me when I had nothing?
...Who made me a medical researcher?
<wait>
It wasn't your government! No... the man who
created me is sleeping in your prison!
<wait>

@MSG_EVT608A_008
<bup 0 19 1>
Then, you're one of Delphi's--!
<wait>

@MSG_EVT608A_009
<bup 0 21 10>
Struggle against fate as much as you like...
<wait>
With an army of 7 billion, mankind will only
defeat itself!
<wait>

@MSG_EVT608A_010
<bup 0 19 1>
Shut up, Owen. After what you did in there,
you expect us to listen to this nonsense?
<wait>
Humanity will continue to thrive, well into
the future. We're making that possible.
<wait>
Strip him of his rank and take him away!
<wait>
<bup_cls>

@MSG_EVT608A_011
<bup 0 20 1>
Sir! There seems to have been an incident
in the laboratory...!
<wait>

@MSG_EVT608A_012
<bup 0 19 1>
...The laboratory!?
<wait>

@MSG_EVT608A_013
<bup 0 20 1>
...Adam's chamber, Sir.
<wait>

@MSG_EVT608A_014
<bup 0 19 1>
Oh no... Robert!
<wait>
<bup_cls>

@MSG_EVT608A_015
<bup 0 8 4>
Hang in there, Dr. Hoffman!
<wait>

@MSG_EVT608A_016
<bup 0 2 5>
Then, they were actually taking the serum
directly out of Adam's body!?
<wait>

@MSG_EVT608A_017
<bup 0 6 3>
This GUILT is going to be a pain...it can
genetically mutate at the drop of a hat.
<wait>
...At least, according to the data we've been
given. It might be even worse.
<wait>

@MSG_EVT608A_018
<bup 0 9 7>
...The professors...are they safe?
<wait>

@MSG_EVT608A_019
<bup 0 19 1>
Yes, thanks to Dr. Stiles and Dr. Kimishima...
<wait>
They're going to save you as well,
Dr. Hoffman.
<wait>

@MSG_EVT608A_020
<bup 0 9 7>
...So this is how...you find out if you were
a good surgeon...
<wait>
...No matter how many lives you save...
<wait>
...It's impossible to save your own.
<wait>

@MSG_EVT608A_021
<bup 0 2 5>
Don't strain yourself, Dr. Hoffman.
<wait>

@MSG_EVT608A_022
<bup 0 9 7>
Listen to me, Derek! ...These may be
my last words...
<wait>
No doctor can operate on himself...I suppose
that is our fatal flaw...
<wait>
...It's a test...when you're dying.
*cough*
<wait>
I have to depend on...the ones I trained...
On you, Derek...
<wait>
...It's the only way *cough* to know...
...was I a good doctor?
<wait>

@MSG_EVT608A_023
<bup 0 8 5>
You're a good man, Dr. Hoffman--and an
excellent surgeon!
<wait>
You passed on a lot more than your skills,
like your passion, and your kindness...
<wait>
...Dr. Stiles should be all the proof you need.
You're a great doctor!
<wait>

@MSG_EVT608A_024
<bup 0 2 5>
...We can continue this conversation once
you're recovering.
<wait>

@MSG_EVT608A_025
<bup 0 9 7>
Yes...we will...
<wait>

@MSG_EVT608A_026
<bup 0 19 1>
Then, let's get Dr. Hoffman to the operating
room and begin administering anesthesia.
<wait>
<bup_cls>

@MSG_EVT608A_032
<bup 0 19 1>
Stiles... Kimishima...
<wait>
I don't want to take any risks. I'd like you both
to operate on Dr. Hoffman together.
<wait>

@MSG_EVT608A_027
<bup 0 2 5>
...!?
<wait>

@MSG_EVT608A_028
<bup 0 6 2>
...I see.
<wait>

@MSG_EVT608A_029
<bup 0 19 1>
I'm sure you're exhausted...
<wait>
...but the Healing Touch may be the only
hope that Dr. Hoffman has at this point.
<wait>

@MSG_EVT608A_030
<bup 0 2 5>
...Of course. Losing Dr. Hoffman isn't an
option. I'll do whatever it takes.
<wait>
Let's work together, Dr. Kimishima...
<wait>

@MSG_EVT608A_031
<bup 0 6 1>
I won't let you down.
<wait>
<bup_cls>
