
@MSG_EVT602A_001
- Caduceus Europe, Director's Office -
<wait>

@MSG_EVT602A_002
<bup 0 19 1>
...Thank you for coming all this way.
I'm sure you're both quite tired.
<wait>
I don't believe we've spoken since the Delphi
raid! It feels good to see old friends again.
<wait>

@MSG_EVT602A_003
<bup 0 2 1>
It was a difficult mission... But, I'm glad
everything turned out for the best.
<wait>
It's an honor to be invited here.
<wait>

@MSG_EVT602A_004
<bup 0 19 1>
Ms. Thompson, please let me know if there's
anything we can do to make your stay easier.
<wait>
After all, I'm sure Dr. Stiles owes much of his
success to having you at his side.
<wait>

@MSG_EVT602A_005
<bup 0 8 1>
Thank you, Director...
<wait>
I'm positive Dr. Stiles and I will both learn
quite a bit during our stay.
<wait>

@MSG_EVT602A_006
<bup 0 19 1>
...Allow me to introduce you both to Dr. Owen,
our Research Executive.
<wait>
He will be supervising all the research you take
part in while you're with us here.
<wait>

@MSG_EVT602A_007
<bup 0 21 1>
It's an honor to meet you both, Dr. Stiles,
Nurse Thompson...
<wait>
Your work on our project will be quite pivotal,
I'm certain.
<wait>

@MSG_EVT602A_008
<bup 0 2 1>
Nice to meet you.
<wait>

@MSG_EVT602A_009
<bup 0 19 1>
Dr. Owen was actually the first person to
recommend your involvement.
<wait>
He believed that only doctors of your talent
would be able to complete these final stages.
<wait>

@MSG_EVT602A_010
<bup 0 21 1>
*chuckle* ...You might think I'm being selfish,
but this is something only you two can handle.
<wait>

@MSG_EVT602A_011
<bup 0 2 1>
Hopefully we won't embarrass ourselves
too badly.
<wait>

@MSG_EVT602A_012
<bup 0 19 1>
Well then, if you'll follow me, I can fill you in
on the details of our research...
<wait>
<bup_cls>

@MSG_EVT602A_013
- Caduceus Europe, Research Laboratory -
<wait>

@MSG_EVT602A_014
<bup 0 21 1>
...the results of our "regenerative treatments"
have been far beyond expectation.
<wait>
If I might be so bold, I would say we're about
to turn medical science on its head.
<wait>
As you can see, we transplant these neo-cells
in hopes that they regenerate the lost tissue.
<wait>
...What's surprising is how quickly it occurs
and the low rate of autoimmune difficulties.
<wait>

@MSG_EVT602A_015
<bup 0 19 1>
This is only possible because of our advanced
facilities and brilliant researchers.
<wait>
If we were as limited as the other branches
of Caduceus...
<wait>
...I doubt our research would have advanced
even half as quickly.
<wait>

@MSG_EVT602A_016
<bup 0 2 5>
Hey, I'm impressed. I didn't realize you guys
were working on something like this.
<wait>
But...what does any of this have to do
with GUILT research?
<wait>

@MSG_EVT602A_017
<bup 0 21 1>
Most of the theories we've put into practice
are based on what we learned fighting GUILT.
<wait>
...I'm afraid I can't say more than that--we're
saving the finer details for our conference.
<wait>

@MSG_EVT602A_018
<bup 0 8 1>
...You said you've already treated hundreds of
patients with regenerative technology?
<wait>

@MSG_EVT602A_019
<bup 0 19 1>
We'll be visiting those patients tomorrow...
<wait>
It will be easier to understand if you can see
their recoveries for yourself.
<wait>
<bup_cls>

@MSG_EVT602A_032
<bup 0 19 1>
...Ah, Dr. Kimishima! Have you finished your
rounds for the day?
<wait>

@MSG_EVT602A_020
<bup 0 6 1>
Yes, Director. I assume these are the doctors
from America?
<wait>

@MSG_EVT602A_021
<bup 0 19 1>
Your timing couldn't be better...
Allow me to introduce you.
<wait>
Dr. Stiles, this is Dr. Naomi Kimishima...
<wait>
She's been working with us for some time.
Like you, she specializes in miracle surgeries.
<wait>

@MSG_EVT602A_022
<bup 0 6 2>
A pleasure to meet you...
<wait>
Anata ga yuumei na Stiles-sensei ne.
*chuckle*
<wait>

@MSG_EVT602A_023
<bup 0 2 1>
...It's uh... n-nice to meet you...
<wait>
I'm afraid I don't understand what you just
said, Dr. uh...Kimishima...
<wait>

@MSG_EVT602A_024
<bup 0 6 2>
Oh, my mistake...I was under the impression
you had recently traveled to Japan.
<wait>

@MSG_EVT602A_025
<bup 0 19 1>
She actually hails from Japan, originally.
That, however, is not important...
<wait>
She's been supporting our research in a
number of ways with her unique talents.
<wait>
In a perfect world, she'd be able to work in your
place, however...there's been a problem.
<wait>

@MSG_EVT602A_026
<bup 0 2 5>
...A problem?
<wait>

@MSG_EVT602A_027
<bup 0 19 1>
There have been isolated reports of GUILT
throughout Europe, even after Delphi's defeat.
<wait>
Unfortunately, we have no idea what could
be causing them.
<wait>
There has been speculation that these
outbreaks are occurring naturally...
<wait>
...but splinters of Delphi are far more likely.
The FBI has been investigating this as well.
<wait>
Dr. Kimishima has her hands full treating the
GUILT victims as they're brought in.
<wait>
That is why we cannot have her working
on research full-time.
<wait>

@MSG_EVT602A_028
<bup 0 21 1>
We may also need you to assist her
occasionally, Dr. Stiles.
<wait>
I hope that you understand.
<wait>

@MSG_EVT602A_029
<bup 0 2 1>
Of course. I'd be glad to help...
<wait>

@MSG_EVT602A_030
<bup 0 8 5>
...I didn't realize there were still GUILT
outbreaks.
<wait>

@MSG_EVT602A_031
<bup 0 6 1>
It would appear Delphi's power runs deeper
than anyone thought possible...
<wait>
<bup_cls>
