
@MSG_EVT703A_001
- Mountain Pass -
<wait>

@MSG_EVT703A_002
<bup 0 25 1>
...He's still following us. I thought we'd be able
to lose him on this mountain road.
<wait>

@MSG_EVT703A_003
<bup 0 5 1>
He did come all the way from Japan.
Would you want to leave empty-handed?
<wait>

@MSG_EVT703A_004
<bup 0 25 1>
Damn reporters'll do anything for a scoop.
<wait>
He probably wants to build his career on
the remains of the "devil doctor."
<wait>
It isn't often the Japanese Medical Board
expels a doctor for having magical powers.
<wait>
...Or maybe he wants to get under that labcoat
of yours and start some rumors of his own.
<wait>

@MSG_EVT703A_005
<bup 0 5 2>
You're disgusting.
<wait>
What makes you think it's me he's after,
anyway?
<wait>
<bup 0 5 1>
Maybe he stumbled on your organization;
they have a presence in Japan, don't they?
<wait>
Considering all your activity lately--
<wait>

@MSG_EVT703A_006
<bup 0 25 1>
If anybody had found out about us, I'd know.
<wait>
If it's all right with you, I believe this situation
calls for a little more speed...
<wait>
<bup_cls>

@MSG_EVT703A_007
<bup 0 5 1>
...Are we sure he's a reporter? He could be
working for the government.
<wait>

@MSG_EVT703A_008
<bup 0 25 1>
The FBI wouldn't be so obvious. It's clear he
has no idea what he's doing.
<wait>
I've had training, but he's going to get himself
killed if he keeps driving like that.
<wait>

@MSG_EVT703A_009
<bup 0 5 3>
Look out!
<wait>
There's a curve ahead!
<wait>

@MSG_EVT703A_010
<bup 0 25 1>
I know that!
<wait>
<bup_cls>

@MSG_EVT703A_016
<bup 0 25 1>
...Dammit!
<wait>
<bup_cls>

@MSG_EVT703A_011
<bup 0 25 1>
That idiot ran right into the wall!
<wait>

@MSG_EVT703A_012
<bup 0 5 1>
...Go back.
<wait>

@MSG_EVT703A_013
<bup 0 25 1>
You don't think you're going to save him,
do you!? It's his own fault this happened.
<wait>
Besides, pulling him out of that wreck
would be a pain in the ass.
<wait>

@MSG_EVT703A_014
<bup 0 5 1>
And, how do you think his newspaper will
treat this story if he dies?
<wait>
I'm already in enough trouble as it is.
<wait>

@MSG_EVT703A_015
<bup 0 25 1>
Tch, doctors... This would be a lot easier if
you didn't have a conscience.
<wait>
We're getting the hell out of here if he's
already black-tagged, understand?
<wait>
<bup_cls>

@MSG_EVT703B_001
<bup 0 5 1>
He's stable enough...
Call for a rescue team.
<wait>
Hey... You weren't half bad as an assistant.
<wait>

@MSG_EVT703B_002
<bup 0 25 1>
Yeah, well I don't intend to make a habit of it.
<wait>
Let's get out of here. The last thing we need
to do right now is play twenty questions.
<wait>

@MSG_EVT703B_003
<bup 0 5 2>
...Let me drive.
That put me in a good mood.
<wait>
<bup_cls>
