
@MSG_EVT702A_001
- Old Brooks St. Hospital, O.R. -
<wait>

@MSG_EVT702A_002
<bup 0 25 1>
...This one has a tumor on his large intestine,
so we need you to remove it.
<wait>
I should warn you that this particular tumor
is very...delicate.
<wait>
Be careful when you take it out.
<wait>
He contracted it during an early research
stage, so I'm afraid it's rather advanced now.
<wait>
They don't think he has much chance
of survival.
<wait>
Of course, it would be better not to lose him.
This is why they wanted you to try.
<wait>

@MSG_EVT702A_003
<bup 0 5 1>
I'd ask what all this research was for, but
I know I wouldn't get a real answer.
<wait>
Four cases in the past month... Is it just me,
or are you guys having some trouble lately?
<wait>

@MSG_EVT702A_004
<bup 0 25 1>
These people aren't afraid to die.
<wait>
There's no need to waste your sympathy
on the choices they made.
<wait>

@MSG_EVT702A_005
<bup 0 5 1>
Don't worry about me. Sympathy isn't an
emotion I feel much anymore.
<wait>
The patients exist so that I can save them;
it's as simple as that.
<wait>

@MSG_EVT702A_006
<bup 0 25 1>
Think you'll need to use the Healing Touch
on this case?
<wait>

@MSG_EVT702A_007
<bup 0 5 2>
Would you have even called me if it wasn't
that serious?
<wait>
Without patients like this, I'd never be able
to practice my true medical talents...
<wait>
<bup 0 5 1>
...Let's get this over with.
Bring him in.
<wait>
<bup_cls>

@MSG_EVT702B_001
<bup 0 25 1>
Amazing, as always. You can expect another
glowing report.
<wait>
It's a shame someone with your...skills can't
practice them out in the open.
<wait>
Medical society just isn't ready for someone
who can manipulate energy the way you do.
<wait>
Then again, how many people could there
possibly be with special powers like that?
<wait>

@MSG_EVT702B_002
<bup 0 5 1>
...You don't usually talk this much afterward.
<wait>

@MSG_EVT702B_003
<bup 0 25 1>
Pardon me. I didn't mean anything by it.
<wait>

@MSG_EVT702B_004
<bup 0 5 1>
Oh, it's fine. I'm just used to you being
all business. That's what I meant.
<wait>
Let me know when you've transferred the
payment to my account.
<wait>

@MSG_EVT702B_005
<bup 0 25 1>
Double checking, huh?
You're as pragmatic as always.
<wait>

@MSG_EVT702B_006
<bup 0 5 2>
A girl has to make a living, doesn't she?
<wait>
Money's about the only thing that ability of
mine is worth these days, depressing as it is.
<wait>

@MSG_EVT702B_007
<bup 0 25 1>
I understand. You'll be contacted as soon as
the transaction is complete, but don't forget...
<wait>
We're the ones who transferred you to an
American hospital when you lost your license.
<wait>
Without us, you wouldn't have a new name, and
you wouldn't have a new life...Dr. Kimishima.
<wait>

@MSG_EVT702B_008
<bup 0 5 1>
...Trust me--nobody understands my position
better than I do.
<wait>
You fixed my broken wings, and I'm willing to
repay that favor, no matter what it costs.
<wait>
I know who my friends are.
<wait>

@MSG_EVT702B_009
<bup 0 25 1>
Glad to hear it.
<wait>
Well then, come with me.
I'll be escorting you home, as always.
<wait>
<bup_cls>
