
@MSG_EVT701A_001
- St. Francis Hospital, Conference Room -
<wait>

@MSG_EVT701A_002
...The patient, Alan Chambers, is suffering a
comminuted fracture in his right forearm.
<wait>
He was rushed here as soon as the injury
occurred, thanks to a nurse who witnessed it.
<wait>
Judging by the X-ray, this one could give
us some trouble...
<wait>
But, I'm sure Dr. Weaver will be able to
fix him up, good as new.
<wait>

@MSG_EVT701A_003
<bup 0 4 1>
I appreciate the confidence, but you know
this is no big deal.
<wait>
I haven't let a patient down yet, have I?
<wait>

@MSG_EVT701A_004
Nozomi Weaver, age 29: a Japanese surgeon
who came to America on an exchange program.
<wait>
Since transferring from her original hospital in
Okinawa, she's gained quite a reputation.
<wait>
<bup_cls>

@MSG_EVT701A_005
Alan Chambers... Isn't he a famous
screenwriter? Think it's the same guy?
<wait>
It would certainly explain the media circus
gathering outside...
<wait>
Hey, maybe they'll want to interview us!
<wait>
...or Dr. Weaver, anyway. She's probably
the most photogenic doctor here.
<wait>

@MSG_EVT701A_006
<bup 0 4 2>
I definitely don't need that kind of attention.
<wait>
If they're looking for a press conference, the
head surgeon is welcome to take my place.
<wait>
<bup_cls>

@MSG_EVT701A_007
You're too modest, Dr. Weaver.
<wait>
She's really put our hospital on the map,
though. We have patients coming from all over.
<wait>
I'd say that exchange program was the best
thing to happen to St. Francis.
<wait>
I'm surprised your hospital was willing to
let you go, Doctor!
<wait>

@MSG_EVT701A_008
<bup 0 4 2>
You're giving me too much credit...
I haven't even been here for a full year.
<wait>
<bup_cls>

@MSG_EVT701A_009
...We're getting a little sidetracked, I think.
Let's proceed with the operation.
<wait>
Good luck, Dr. Weaver.
<wait>
<bup_cls>

@MSG_EVT701A_010
<bup 0 4 1>
(...Now I just need to avoid unnecessary
media attention.)
<wait>
(I still can't believe they want me operating
out in the open like this...)
<wait>
(Didn't they learn their lesson in Okinawa?)
<wait>
<bup_cls>

@MSG_EVT701B_001
- St. Francis Hospital, Conference Room -
<wait>

@MSG_EVT701B_002
...Another amazing operation, Dr. Weaver!
I think we all learned a thing or two. *chuckle*
<wait>
Well then, if you'll excuse me...
<wait>

@MSG_EVT701B_003
<bup 0 4 1>
See you tomorrow.
<wait>
<bup_cls>

@MSG_EVT701B_006
<bup 0 4 1>
(Interesting...)
<wait>
(I always thought American doctors were more
concerned about golf than their patients...)
<wait>
(But, everyone here is so kind. They accepted
me as one of their own immediately...)
<wait>
<bup 0 4 2>
(...Only because they don't know the truth.)
<wait>
<bup_cls>

@MSG_EVT701B_004
<bup 0 4 1>
(Hm? A phone call...?
Oh, it's them.)
<wait>

@MSG_EVT701B_005
This is Weaver.
<wait>
...A procedure on Sunday?
It's kind of sudden, don't you think?
<wait>
*sigh* Not that I can refuse or anything.
Yeah, I'll be there.
<wait>
<bup_cls>
