
@MSG_EVT704A_001
- Old Brooks St. Hospital, O.R. -
<wait>

@MSG_EVT704A_002
<bup 0 25 1>
...The kidney is on its way. ETA is one hour.
<wait>
Plan out your operation with that in mind.
<wait>

@MSG_EVT704A_003
<bup 0 5 1>
I'm more concerned about that tumor,
to be honest.
<wait>

@MSG_EVT704A_004
<bup 0 23 10>
You'll need to excise the tumor before you
can perform the kidney transplant.
<wait>
Otherwise, those veins are going to bleed
out, and you'll have serious complications.
<wait>

@MSG_EVT704A_005
<bup 0 5 1>
You aren't concerned at all that his body
may reject the new kidney?
<wait>

@MSG_EVT704A_006
<bup 0 23 10>
We already know that this GUILT severely
inhibits the body's autoimmune response.
<wait>
As you can imagine, that all but eliminates
any such risk.
<wait>
We're confident the kidney won't be rejected.
<wait>

@MSG_EVT704A_007
<bup 0 5 1>
Alright, Professor...
<wait>
But, this had better not be a sacrificial
operation. I already told them--
<wait>

@MSG_EVT704A_008
<bup 0 25 1>
Yes, we're quite familiar with your contract,
Dr. Weaver.
<wait>
I assure you, all your patients are people
we expect to see back at work.
<wait>

@MSG_EVT704A_009
<bup 0 23 10>
...Well then, Dr. Weaver. Please begin the
operation.
<wait>
<bup_cls>

@MSG_EVT704B_001
<bup 0 25 1>
...I've come to expect miracles from you,
Dr. Weaver.
<wait>
His prognosis is still in question, but that's
something for our doctors to worry about.
<wait>

@MSG_EVT704B_002
<bup 0 5 1>
I don't understand what Delphi is hoping
to do here...
<wait>
Are you trying to save mankind or wipe it out?
<wait>

@MSG_EVT704B_003
<bup 0 23 10>
The path humanity has been on since the
dawn of civilization will soon come to an end.
<wait>
Our planet cannot support 7 billion people,
all living out long, meaningless lives.
<wait>
We're here to ensure that human beings are
changed before it's too late.
<wait>
That is the meaning of our GUILT research.
<wait>
GUILT will free mankind from the sins that
bind it to a history of destruction.
<wait>

@MSG_EVT704B_004
<bup 0 5 1>
...This is something you believe, Professor?
<wait>

@MSG_EVT704B_005
<bup 0 23 10>
Our leader, Adam, has promised us salvation
for the good work we do here.
<wait>
This is the only way to absolve our own sin;
by paving the way for a new future.
<wait>
Freedom from the shadow of medicine...
It's as simple as that.
<wait>

@MSG_EVT704B_006
<bup 0 5 1>
I don't understand how a man like you could
believe a word of that, Professor.
<wait>

@MSG_EVT704B_007
<bup 0 25 1>
Dr. Weaver, I would advise that you only
speak about things pertinent to your job here.
<wait>
Doing otherwise could be considered
...a breach of contract.
<wait>

@MSG_EVT704B_008
<bup 0 23 10>
Don't worry, Doctor. I'm sure you'll come
to understand, sooner or later.
<wait>
<bup_cls>
