
@MSG_EVT705A_001
- Eidoth Pharmaceutical Laboratory -
<wait>

@MSG_EVT705A_002
Attention all personnel! The laboratory has
been contaminated. The GUILT is unstable.
<wait>
Seal all but the main entrance! Stand by for
further instructions. I repeat...
<wait>
All personnel! The laboratory has been
contaminated. The GUILT is unstable.
<wait>

@MSG_EVT705A_003
<bup 0 5 1>
...So, it all comes down to this, huh?
<wait>
I assume this facility is finished, considering
how many people know about GUILT, now.
<wait>

@MSG_EVT705A_004
<bup 0 25 1>
The Inner Circle is discussing how to proceed.
However, you still have work to do.
<wait>

@MSG_EVT705A_005
<bup 0 5 1>
You want me to take care of the GUILT
responsible for this mess, I assume?
<wait>

@MSG_EVT705A_006
<bup 0 25 1>
The researcher you're responsible for seems
to have a GUILT isolated in his small intestine.
<wait>
His symptoms point to the GUILT strain called
Kyriaki, but...we're still waiting on lab results.
<wait>
Professor Blackwell printed up some
information that might help you prepare...
<wait>

@MSG_EVT705A_007
<bup 0 5 1>
Understood. So...the Kyriaki strain causes
multiple lacerations... hm...
<wait>
(This is insane. How can I treat a body they've
turned against itself!?)
<wait>
Looks like I have my work cut out for me.
<wait>
Still, I've never lost a patient--I'm not about
to start now.
<wait>
<bup_cls>

@MSG_EVT705B_001
<bup 0 5 1>
Did Blackwell leave already? I wanted to ask
him something about that last operation...
<wait>

@MSG_EVT705B_002
<bup 0 25 1>
He's otherwise...occupied. Also, they've issued
orders for you to evacuate immediately.
<wait>

@MSG_EVT705B_003
<bup 0 5 1>
...What?
<wait>

@MSG_EVT705B_004
<bup 0 25 1>
That's how they've chosen to handle the
situation. I'm supposed to evacuate, too.
<wait>

@MSG_EVT705B_005
<bup 0 5 3>
What about the other researchers?
Who's going to operate on them!?
<wait>

@MSG_EVT705B_006
<bup 0 25 1>
...I guess that's part of their plan, as well.
<wait>
They've already dispatched a cleanup crew.
There's nothing more we can do here.
<wait>

@MSG_EVT705B_007
<bup 0 5 1>
...A "cleanup crew," huh?
<wait>
You guys really are fanatics! You don't even
care about people's lives!
<wait>

@MSG_EVT705B_008
<bup 0 25 1>
Everyone here understands the risks involved
in what they're doing.
<wait>
...They all know that sins have consequences
and mercy is not easily earned.
<wait>
But, sacrifices must be made if we're to be
freed from the shackles of medical science.
<wait>

@MSG_EVT705B_009
<bup 0 5 1>
......
<wait>
I suppose I don't have a choice.
<wait>
I'll agree to evacuate.
This is no place for a doctor, anyway.
<wait>

@MSG_EVT705B_010
<bup 0 25 1>
Understood.
We will not meet again.
<wait>

@MSG_EVT705B_011
<bup 0 5 1>
Good bye...and good luck.
<wait>
<bup_cls>

@MSG_EVT705B_012
<bup 0 5 2>
(I should probably be thankful they let me go,
no questions asked.
<wait>
But, it's only a matter of time before the
past catches up to me...)
<wait>
<bup 0 5 1>
......
<wait>
(It's a shame they forgot to ask me for
that GUILT sample I extracted...)
<wait>
......
<wait>
(...Maybe the path of GUILT does lead to
salvation, after all.
<wait>
Now that I have all the cards...
it's time to ante up.)
<wait>
<bup 0 5 2>
I hear Europe is nice this time of year...
<wait>
<bup_cls>
